### ISSUE TITLE
ERROR when installing Linux/Windows (CUDA) dependencies

### ISSUE THREAD

**Issue by wither735** [carson-katri/dream-textures#111]
I always get an Error when I try to install the Linux/Windows (CUDA) dependencies. I ran Blender as an Administrator.
Here is an image of the Error I always get 
![Desktop Screenshot 2022 09 24 - 11 06 12 39](https://user-images.githubusercontent.com/89296018/192089911-3e27f695-49c4-45c5-bb56-a9b2a8d6a870.png)
![Desktop Screenshot 2022 09 24 - 11 05 59 12](https://user-images.githubusercontent.com/89296018/192089912-59d56ee7-a291-4d25-b9d3-e0df8ed9a96a.png)

**Comment by miaumori** [comment]
install git first and only after it install depencies

**Comment by wither735** [comment]
Yeah I also relised that XD how can I delete this issue
