### ISSUE TITLE
Unable to install dependencies, python setup.py egg_info did not run successfully.

### ISSUE THREAD

**Issue by AmiTunami** [carson-katri/dream-textures#112]
I ran blender as administrator, installed Git, and the download went well, but during the installation I always got an error while preparing metadata.
I tried solutions I could find online, but these don't seem to work.
![1](https://user-images.githubusercontent.com/114287110/192092342-9bce5246-ef78-4828-880a-43449e636f2d.png)
It would be great helpful if you could fix this problem, thanks.

**Comment by denis-roy** [comment]
This could be a path limit issue @AmiTunami . Try this procedure (taken from the project's README & mentionned in the addon preference's troubleshooting section)


> Note for Windows users - If you get an error when installing dependencies that looks similar to the one described https://github.com/carson-katri/dream-textures/issues/13, your dependency file paths might be too long (can't be longer than 256 characters). You can solve it by telling Windows to allow long file paths in the registry:
> 
> - Open up the Window registry (Start > Run > `regedit`)
> - Navigate to `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem`
> - Set `LongPathsEnabled` to `1`

**Comment by NOSALIS** [comment]
> This could be a path limit issue @AmiTunami . Try this procedure (taken from the project's README & mentionned in the addon preference's troubleshooting section)
> 
> > Note for Windows users - If you get an error when installing dependencies that looks similar to the one described #13, your dependency file paths might be too long (can't be longer than 256 characters). You can solve it by telling Windows to allow long file paths in the registry:
> > 
> > * Open up the Window registry (Start > Run > `regedit`)
> > * Navigate to `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem`
> > * Set `LongPathsEnabled` to `1`

That worked for me - but then I got:

Collecting torch==1.11.0
  Downloading https://download.pytorch.org/whl/cu113/torch-1.11.0%2Bcu113-cp310-cp310-win_amd64.whl (2186.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 1.5/2.2 GB 29.7 MB/s eta 0:00:25
ERROR: Wheel 'torch' located at C:\Users\My Name\AppData\Local\Temp\pip-unpack-ibtcmvlp\torch-1.11.0+cu113-cp310-cp310-win_amd64.whl is invalid.

**Comment by denis-roy** [comment]
@NOSALIS  You might want to try again as it looks like the 2.2GB file download was unable to finish properly

**Comment by AmiTunami** [comment]
> This could be a path limit issue @AmiTunami . Try this procedure (taken from the project's README & mentionned in the addon preference's troubleshooting section)
> 
> > Note for Windows users - If you get an error when installing dependencies that looks similar to the one described #13, your dependency file paths might be too long (can't be longer than 256 characters). You can solve it by telling Windows to allow long file paths in the registry:
> > 
> > * Open up the Window registry (Start > Run > `regedit`)
> > * Navigate to `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem`
> > * Set `LongPathsEnabled` to `1`

It solve my problem, thanks!

**Comment by NOSALIS** [comment]
> @NOSALIS You might want to try again as it looks like the 2.2GB file download was unable to finish properly

Finally got it to work (had some network issue on my end that took a week to resolve).
