### ISSUE TITLE
Problem installing dependencies, MacOS 12.3, Blender 3.3, Python 3.10.

### ISSUE THREAD

**Issue by Gussisaurio** [carson-katri/dream-textures#118]
Hi there.
I am trying to install dream-textures on Mac OS 12.3, with Blender 3.3 and Python 3.10.
When installing dependencies, I get the following (log and then the) **error**:

pip 21.2.4 from /Applications/Blender 3.3.app/Contents/Resources/3.3/python/lib/python3.10/site-packages/pip (python 3.10)
adding trusted host: 'https://download.pytorch.org' (from line 4 of /Users/user/Library/Application Support/Blender/3.3/scripts/addons/dream_textures/stable_diffusion/requirements-mac-MPS-CPU.txt)
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/nightly/cpu
Collecting clip
  Cloning https://github.com/openai/CLIP.git (to revision main) to /private/var/folders/vt/xzhtgl0j0hg630_86cb647x80000gq/T/pip-install-1631_hia/clip_fe110a6dd2d14b44864be0317600cd44
  Running command git clone -q https://github.com/openai/CLIP.git /private/var/folders/vt/xzhtgl0j0hg630_86cb647x80000gq/T/pip-install-1631_hia/clip_fe110a6dd2d14b44864be0317600cd44
  xcrun: **error**: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
**WARNING**: Discarding git+https://github.com/openai/CLIP.git@main#egg=clip. Command errored out with exit status 1: git clone -q https://github.com/openai/CLIP.git /private/var/folders/vt/xzhtgl0j0hg630_86cb647x80000gq/T/pip-install-1631_hia/clip_fe110a6dd2d14b44864be0317600cd44 Check the logs for full command output.
Collecting k-diffusion
  Cloning https://github.com/Birch-san/k-diffusion.git (to revision mps) to /private/var/folders/vt/xzhtgl0j0hg630_86cb647x80000gq/T/pip-install-1631_hia/k-diffusion_33c5e6d03a4e405f8f6e6c5285a65386
  Running command git clone -q https://github.com/Birch-san/k-diffusion.git /private/var/folders/vt/xzhtgl0j0hg630_86cb647x80000gq/T/pip-install-1631_hia/k-diffusion_33c5e6d03a4e405f8f6e6c5285a65386
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
WARNING: Discarding git+https://github.com/Birch-san/k-diffusion.git@mps#egg=k-diffusion. Command errored out with exit status 1: git clone -q https://github.com/Birch-san/k-diffusion.git /private/var/folders/vt/xzhtgl0j0hg630_86cb647x80000gq/T/pip-install-1631_hia/k-diffusion_33c5e6d03a4e405f8f6e6c5285a65386 Check the logs for full command output.
Collecting gfpgan
  Cloning https://github.com/lstein/GFPGAN (to revision fix-dark-cast-images) to /private/var/folders/vt/xzhtgl0j0hg630_86cb647x80000gq/T/pip-install-1631_hia/gfpgan_ef4f1159e7804e9cac0d90585624dcae
  Running command git clone -q https://github.com/lstein/GFPGAN /private/var/folders/vt/xzhtgl0j0hg630_86cb647x80000gq/T/pip-install-1631_hia/gfpgan_ef4f1159e7804e9cac0d90585624dcae
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
WARNING: Discarding git+https://github.com/lstein/GFPGAN@fix-dark-cast-images#egg=gfpgan. Command errored out with exit status 1: git clone -q https://github.com/lstein/GFPGAN /private/var/folders/vt/xzhtgl0j0hg630_86cb647x80000gq/T/pip-install-1631_hia/gfpgan_ef4f1159e7804e9cac0d90585624dcae Check the logs for full command output.
Obtaining file:///Users/user/Library/Application%20Support/Blender/3.3/scripts/addons/dream_textures/stable_diffusion (from -r /Users/user/Library/Application Support/Blender/3.3/scripts/addons/dream_textures/stable_diffusion/requirements-mac-MPS-CPU.txt (line 9))
Collecting albumentations
  Downloading albumentations-1.3.0-py3-none-any.whl (123 kB)
     |████████████████████████████████| 123 kB 1.0 MB/s 
Collecting einops
  Downloading einops-0.4.1-py3-none-any.whl (28 kB)
Collecting huggingface-hub
  Downloading huggingface_hub-0.9.1-py3-none-any.whl (120 kB)
     |████████████████████████████████| 120 kB 3.7 MB/s 
Collecting imageio-ffmpeg
  Downloading imageio-ffmpeg-0.4.7.tar.gz (16 kB)
Collecting imageio
  Downloading imageio-2.22.0-py3-none-any.whl (3.4 MB)
     |████████████████████████████████| 3.4 MB 3.8 MB/s 
Collecting kornia
  Downloading kornia-0.6.7-py2.py3-none-any.whl (565 kB)
     |████████████████████████████████| 565 kB 3.7 MB/s 
Requirement already satisfied: numpy in /Applications/Blender 3.3.app/Contents/Resources/3.3/python/lib/python3.10/site-packages (from -r /Users/user/Library/Application Support/Blender/3.3/scripts/addons/dream_textures/stable_diffusion/requirements.txt (line 10)) (1.22.0)
Collecting omegaconf
  Downloading omegaconf-2.3.0.dev0-py3-none-any.whl (79 kB)
     |████████████████████████████████| 79 kB 4.4 MB/s 
Collecting opencv-python
  Downloading opencv_python-4.6.0.66-cp37-abi3-macosx_11_0_arm64.whl (30.0 MB)
     |████████████████████████████████| 30.0 MB 3.8 MB/s 
Collecting pillow
  Downloading Pillow-9.2.0-cp310-cp310-macosx_11_0_arm64.whl (2.8 MB)
     |████████████████████████████████| 2.8 MB 3.6 MB/s 
Collecting pip>=22
  Downloading pip-22.2.2-py3-none-any.whl (2.0 MB)
     |████████████████████████████████| 2.0 MB 3.8 MB/s 
Collecting pudb
  Downloading pudb-2014.1-py2.py3-none-any.whl (49 kB)
     |████████████████████████████████| 49 kB 4.5 MB/s 
Collecting pytorch-lightning
  Downloading pytorch_lightning-1.7.7-py3-none-any.whl (708 kB)
     |████████████████████████████████| 708 kB 3.0 MB/s 
Collecting streamlit
  Downloading streamlit-1.13.0-py2.py3-none-any.whl (9.2 MB)
     |████████████████████████████████| 9.2 MB 3.6 MB/s 
Collecting taming-transformers-rom1504
  Downloading taming_transformers_rom1504-0.0.6-py3-none-any.whl (51 kB)
     |████████████████████████████████| 51 kB 2.9 MB/s 
Collecting test-tube
  Downloading test_tube-0.7.5.tar.gz (21 kB)
Collecting torch-fidelity
  Downloading torch_fidelity-0.3.0-py3-none-any.whl (37 kB)
Collecting torchmetrics
  Downloading torchmetrics-0.10.0rc0-py3-none-any.whl (524 kB)
     |████████████████████████████████| 524 kB 3.9 MB/s 
Collecting transformers
  Downloading transformers-4.22.1-py3-none-any.whl (4.9 MB)
     |████████████████████████████████| 4.9 MB 3.7 MB/s 
Collecting flask==2.1.3
  Downloading Flask-2.1.3-py3-none-any.whl (95 kB)
     |████████████████████████████████| 95 kB 4.3 MB/s 
Collecting flask_socketio==5.3.0
  Downloading Flask_SocketIO-5.3.0-py3-none-any.whl (17 kB)
Collecting flask_cors==3.0.10
  Downloading Flask_Cors-3.0.10-py2.py3-none-any.whl (14 kB)
Collecting dependency_injector==4.40.0
  Downloading dependency-injector-4.40.0.tar.gz (912 kB)
     |████████████████████████████████| 912 kB 3.5 MB/s 
Collecting eventlet
  Downloading eventlet-0.33.1-py2.py3-none-any.whl (226 kB)
     |████████████████████████████████| 226 kB 4.5 MB/s 
**ERROR: Could not find a version that satisfies the requirement clip (unavailable) (from versions: 0.0.1, 0.1.0, 0.2.0)
ERROR: No matching distribution found for clip (unavailable)**

Any clues on how to solve it?

Thanks in advance.

**Comment by Rav1oliRav1oli** [comment]
I too have this problem. I thought it might be because I'm on the Ventura beta but you are on Monterrey so that can't be it. I'm on a Mac mini with M1 chip.

**Comment by SorryNotCyborg** [comment]
> I too have this problem. I thought it might be because I'm on the Ventura beta but you are on Monterrey so that can't be it. I'm on a Mac mini with M1 chip.

I resolved this issue on my end, here's what I had to do to install the dependencies:
- Update pip from the blender/python path
- Have Xcode installed 
- Agree to Xcode terms and conditions
- Install Command-line tools
- Restart Mac
- Open blender from the terminal command '/Applications/Blender.app/Contents/MacOS/Blender'
- try install the dependencies again

**Comment by keo17** [comment]
I have the same problem. Maybe it is not made for MacOS!

**Comment by carson-katri** [comment]
Please try the release of v0.0.6 `dream_textures-darwin-arm64.zip`, which does not require dependencies to be installed.
