### ISSUE TITLE
Running on Mac M1 8GB is Really Slow?

### ISSUE THREAD

**Issue by enzyme69** [carson-katri/dream-textures#12]
I wonder if it's my iMac M1 8GB machine that is too slow to run this stable diffusion or that the addon is not optimized or maybe I have option that's not turned on, but producing even a small size artwork is really slow.

So far I use the preset photograph, but kept only getting abstract result, this one takes 5-10 minutes for 64 x 64 pixels:
<img width="404" alt="Screenshot 2022-09-18 at 11 21 53 am" src="https://user-images.githubusercontent.com/3952687/190881643-9a9d81d8-b3b6-4f75-83f6-25994e6939de.png">

**Comment by enzyme69** [comment]
<img width="353" alt="Screenshot 2022-09-18 at 11 36 19 am" src="https://user-images.githubusercontent.com/3952687/190881900-b7603795-1a43-4105-afff-3ebcbf0eed4d.png">

"Photograph of monkey sleeping" prompt after 50 steps gives me another abstract result. I wonder why... and this took me a long time too.

Is there a possibility to also add estimate time for completion?

**Comment by enzyme69** [comment]
Also another question: does this addon requires fast Internet access while processing?

**Comment by enzyme69** [comment]
I kept getting just a random images, I wonder why and running super slow, the returned message:

```
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
>> Using slower but more accurate full-precision math (--full_precision)
>> Model loaded in 66.36s
>> Setting Sampler to k_lms
2022-09-18 11:59:45,513 [WARNING] py.warnings: /Users/jimmygunawan/Library/Application Support/Blender/3.4/scripts/addons/dream_textures/stable_diffusion/ldm/modules/embedding_manager.py:155: UserWarning: The operator 'aten::nonzero' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/mps/MPSFallback.mm:11.)
  placeholder_idx = torch.where(

```

**Comment by enzyme69** [comment]
![2935619316](https://user-images.githubusercontent.com/3952687/190882783-cea1a6c1-f204-4979-b203-b2349fa5aaea.png)
1000 seconds, 25 steps produces this on prompt "beautiful monkey goddess". When it's producing up to 24, it was looking nice and realistic, but step 25 really problematic and the monkey face is broken / glitching.

**Comment by carson-katri** [comment]
If you disable "Show Steps" it will speed up. On my M1 Max it usually takes around 20-25 seconds per image.

**Comment by carson-katri** [comment]
Also, no internet connection is required to run the addon after installation is completed.

**Comment by enzyme69** [comment]
Okey, noted. I think my 8 GB M1 is ... yes will be slow. 15 - 45 mins / 25-50 samples. I will try turning off step. The last 40-50 samples are showing nice preview of the final result.
