### ISSUE TITLE
File "setup.py" or "setup.cfg" not found

### ISSUE THREAD

**Issue by ortizgab** [carson-katri/dream-textures#121]
ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode: C:\Users\go_gr\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream-textures-main\stable_diffusion

Any ideas?

**Comment by ortizgab** [comment]
also:

WARNING: You are using pip version 21.2.4; however, version 22.2.2 is available.
You should consider upgrading via the 'C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\bin\python.EXE -m pip install --upgrade pip' command.

**Comment by Voyager137** [comment]
You have to download the addon from the releases tab:
https://github.com/carson-katri/dream-textures/tags

**Comment by ortizgab** [comment]
I'm getting these errors when installing dependencies...

**Comment by carson-katri** [comment]
Closing as a duplicate of #47
