### ISSUE TITLE
Error when reinstalling dependencies

### ISSUE THREAD

**Issue by worthis5612** [carson-katri/dream-textures#124]
![image](https://user-images.githubusercontent.com/114337958/192139172-a5b0d2ed-d7e1-4f4c-9c1a-ecb04e0eeb2f.png)

I get this error every time i try to reinstall dependencies, i tried to clear temp folder /reinstall the addon / restart pc but it still occurs ,tried aswell the regedit tip 

gpu:Gtx 1660ti mobile

**Comment by carson-katri** [comment]
Try removing the folders `huggingface` and `torch` in `C:\Users\yourname\.cache`
