### ISSUE TITLE
Dream-Texture.zip Name Error 'async_loop' is not defined

### ISSUE THREAD

**Issue by lukaspacalon** [carson-katri/dream-textures#125]
![Async_Loop_error](https://user-images.githubusercontent.com/11665146/192142283-f218a986-ec08-4a58-a9bb-703a980ce881.png)

Hi, I am actually struggling to install dream-texture.zip addon.
I downloaded the file "Dream-Texture.zip" and try to install it in blender using preferences menu but then this error occured. Can someone help with this message ? I didn't see it in the issues requests. Thanks a lot ! cheers and have a nice day ;)

**Comment by carson-katri** [comment]
Version 0.0.6 removed async_loop.py. Please also upgrade to Blender 3.3.
