### ISSUE TITLE
Headless AI generation and rendering

### ISSUE THREAD

**Issue by Smuzzies** [carson-katri/dream-textures#126]
Running the generator all via command line. Looking for some ideas on how to get the generation to start before the render begins. The addon is loading successfully with addon_utils.enable, it appears to make it through the subject/genre/seed but then starts to render the plane the image is applied to before it actually generates the new image. Have tried a time.sleep to no avail. Was able to get a modal time to work but put it into an endless generation loop. Looking for smart brains if anyone has had success in doing this all from command line with -b -P -f -o switches. Thanks in advance.

`#search string for AI - subject (WORKING)
bpy.context.scene.dream_textures_prompt.prompt_structure_token_subject = "skateboarder"

#search string for AI - genre (WORKING)
bpy.context.scene.dream_textures_prompt.prompt_structure_token_genre = "urban"

#seed set to 1 for material apply (WORKING)
bpy.context.scene.dream_textures_prompt.seed = 1

#load the image to apply the AI to (WORKING)
image = bpy.data.images.load("image.jpg")
image.name = "ai_image"
bpy.context.scene.init_img = image

#run AI script with delay to start (RENDER STARTS TOO SOON)
#--------------------------------------------------------
#does not run or does not complete before render starts
#some luck with a modal timer but endless looped
#--------------------------------------------------------
bpy.ops.shade.dream_texture()`
time.sleep(30)

**Comment by Smuzzies** [comment]
Decided to move the whole env over to windows to see if the issue persists. Same thing here although more info from debug. Seems like the async_loop error does appear but the new image generates just fine. It does take longer to go throught the error spam than it does to generate the new image.

![image](https://user-images.githubusercontent.com/110495122/192159851-846512cf-9891-447b-94b3-4a5d77caec90.png)

**Comment by Smuzzies** [comment]
Looks like it might be skipping the render bpy command due to the model file not being quite loaded yet or there's another bpy command to load it that I cannot find. Either way, if it will just process " bpy.ops.shade.dream_texture() " before render takes place....

![image](https://user-images.githubusercontent.com/110495122/192168428-f69d9acf-61d6-4b13-be6b-cf0b031d2255.png)
![image](https://user-images.githubusercontent.com/110495122/192168432-b5471fec-34ad-43dd-ae4b-90a60698e828.png)

**Comment by NullSenseStudio** [comment]
It might be more suitable for you to run your python script and directly access image generating, save images to disk, then run blender with another script to load those images in.

**Comment by NullSenseStudio** [comment]
So I did some digging and found some issues with trying to run the addon headlessly. Main issue boils down to that the addon does not block Blender's main thread while generating (won't freeze Blender while it does its thing), so it'll continue on to the render phase before generating even begins. Also if you tried running Blender without its render arguments it will close soon after because it assumes all work is done due to the main thread running out of things to do. It could potentially work if you continuously call the modal method until generation is complete, but that's only accessible if your script is run as part of the addon.

I've made a script that will allow you to bypass the addon (but still needs to be installed) and use stable diffusion directly, which doesn't have the issue mentioned above. You can also run it directly in Blender instead of externally so disregard my previous comment.

One issue to note with this script is it will keep its VRAM usage after generating, so Blender may have issues attempting to render. Try reducing your generated image resolution if it does run into trouble with that.

Another potential issue is that this script was made with the next release in mind, it should still work with previous releases but I never bothered to test that.

```python
import bpy
import numpy as np
import sys
import os
import site
import pkg_resources
PATH_TO_ADDON = r'C:\Users\ACCOUNT_NAME\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream-textures' # wherever the addon gets installed to on your system

os.environ["PYTORCH_ENABLE_MPS_FALLBACK"] = "1"
sys.path.append(PATH_TO_ADDON)
sys.path.append(os.path.join(PATH_TO_ADDON,"stable_diffusion/"))
sys.path.append(os.path.join(PATH_TO_ADDON,"stable_diffusion/src/clip"))
sys.path.append(os.path.join(PATH_TO_ADDON,"stable_diffusion/src/k-diffusion"))
sys.path.append(os.path.join(PATH_TO_ADDON,"stable_diffusion/src/taming-transformers"))

site.addsitedir(os.path.join(PATH_TO_ADDON,".python_dependencies"))
pkg_resources._initialize_master_working_set()

from stable_diffusion.ldm.generate import Generate
from omegaconf import OmegaConf
from PIL import ImageOps

models_config  = os.path.join(PATH_TO_ADDON,'stable_diffusion/configs/models.yaml')
model   = 'stable-diffusion-1.4'

models  = OmegaConf.load(models_config)
config  = os.path.join(PATH_TO_ADDON,'stable_diffusion/' + models[model].config)
weights = os.path.join(PATH_TO_ADDON,'stable_diffusion/' + models[model].weights)

generator = Generate(
	conf=models_config,
	model=model,
	weights=weights,
	config=config,
	full_precision=False
)

# only need one generator, you may call generator.prompt2image for as many images as you need
(img, seed) = generator.prompt2image(
	prompt = 'brick texture',
	steps = 25,
	seed = None, # None for random
	cfg_scale = 7.5,
	width = 512,
	height = 512,
	sampler_name = 'k_lms', # 'ddim', 'k_dpm_2_a', 'k_dpm_2', 'k_euler_a', 'k_euler', 'k_heun', 'k_lms', 'plms'
	seamless = True,
	
	init_img = None, # path to file
	strength = 0.75,
	fit = True
)[0]

image = bpy.data.images.new("name", width=img.width, height=img.height)
image.pixels[:] = (np.asarray(ImageOps.flip(img).convert('RGBA'),dtype=np.float32) * (1.0 / 255.0)).ravel()
image.pack()

bpy.data.materials["Material"].node_tree.nodes["Image Texture"].image = image # place the image wherever you see fit

```

**Comment by ACMOIDRE** [comment]
I don't think your script work for me.
even 128x128 :(

**Comment by NullSenseStudio** [comment]
Some error information from the console would help. Also did you make sure the PATH_TO_ADDON variable was set correctly for your installation?

**Comment by ACMOIDRE** [comment]
Sorry, Not posting error before:

Python: Traceback (most recent call last):
  File "C:\Users\99026\Blender\Addons\New Folder\DreamTextureRepair.blend\Text", line 19, in <module>
ModuleNotFoundError: No module named 'stable_diffusion'

thanks responding quickly.

**Comment by ACMOIDRE** [comment]
does quick pip install work bcoz its install np, matpl , other module which I already install for python3

**Comment by NullSenseStudio** [comment]
All pip modules would already be installed when you followed the steps in the addon's preferences window. As long as the addon will generate images they're all ready.

Since it can't find the stable_diffusion module I don't think the PATH_TO_ADDON is set correctly. Can you double check where the addon is installed to?

**Comment by Seeders** [comment]
@ACMOIDRE , To get @NullSenseStudio s script to work, I had to update the PATH_TO_ADDON path, not only my username but also the last part should be "dream_textures" instead of "dream-textures"

**Comment by Seeders** [comment]
@NullSenseStudio any idea how to release the VRAM or re-use an existing generator?  

The script works until it eats all my ram and then i have to restart blender.

**Comment by NullSenseStudio** [comment]
You're talking about the generator in the script right? It should have no issue being reused as it is. Just keep calling `generator.prompt2image(...` for as many images as you need.

**Comment by Seeders** [comment]
@NullSenseStudio yea, the problem is i like to iterate after seeing a result, but then i have to hit play again which creates another generator.

**Comment by NullSenseStudio** [comment]
The script was intended to be used headlessly by launching Blender in background mode through command line with the script only needing run once. Since you're running with full UI isn't the addon menu fine for your use?

**Comment by ACMOIDRE** [comment]
@NullSenseStudio Code look like this.
I'm running on blender script tab should need run script command line of windows ?

import bpy
import numpy as np
import sys
import os
import site
import pkg_resources
PATH_TO_ADDON = r'C:\Users\99026\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\stable_diffusion\models\ldm\stable-diffusion-v1' # wherever the addon gets installed to on your system

os.environ["PYTORCH_ENABLE_MPS_FALLBACK"] = "1"
sys.path.append(PATH_TO_ADDON)
sys.path.append(os.path.join(PATH_TO_ADDON,"stable_diffusion/"))
sys.path.append(os.path.join(PATH_TO_ADDON,"stable_diffusion/src/clip"))
sys.path.append(os.path.join(PATH_TO_ADDON,"stable_diffusion/src/k-diffusion"))
sys.path.append(os.path.join(PATH_TO_ADDON,"stable_diffusion/src/taming-transformers"))

site.addsitedir(os.path.join(PATH_TO_ADDON,".python_dependencies"))
pkg_resources._initialize_master_working_set()

from stable_diffusion.ldm.generate import Generate
from omegaconf import OmegaConf
from PIL import ImageOps

models_config  = os.path.join(PATH_TO_ADDON,'stable_diffusion/configs/models.yaml')
model   = 'stable-diffusion-1.4'

models  = OmegaConf.load(models_config)
config  = os.path.join(PATH_TO_ADDON,'stable_diffusion/' + models[model].config)
weights = os.path.join(PATH_TO_ADDON,'stable_diffusion/' + models[model].weights)

generator = Generate(
    conf=models_config,
    model=model,
    weights=weights,
    config=config,
    full_precision=False
)

# only need one generator, you may call generator.prompt2image for as many images as you need
(img, seed) = generator.prompt2image(
    prompt = 'brick texture',
    steps = 25,
    seed = None, # None for random
    cfg_scale = 7.5,
    width = 512,
    height = 512,
    sampler_name = 'k_lms', # 'ddim', 'k_dpm_2_a', 'k_dpm_2', 'k_euler_a', 'k_euler', 'k_heun', 'k_lms', 'plms'
    seamless = True,
    
    init_img = None, # path to file
    strength = 0.75,
    fit = True
)[0]

image = bpy.data.images.new("name", width=img.width, height=img.height)
image.pixels[:] = (np.asarray(ImageOps.flip(img).convert('RGBA'),dtype=np.float32) * (1.0 / 255.0)).ravel()
image.pack()

bpy.data.materials["Material"].node_tree.nodes["Image Texture"].image = image # place the image wherever you see fit

**Comment by Seeders** [comment]
@NullSenseStudio ok makes sense, i've started using it this way as well.

I modified it a bit so it saves files to a directory, in a subdirectory named after the path, and filename based on the seed.  

`    
import bpy
import numpy as np
import sys
import os
import site
import pkg_resources
PATH_TO_ADDON = r'C:\Users\Jared\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures' # wherever the addon gets installed to on your system
SAVE_PATH = r'D:\projects\DreamTextures\\' # wherever the addon gets installed to on your system
os.environ["PYTORCH_ENABLE_MPS_FALLBACK"] = "1"
sys.path.append(PATH_TO_ADDON)
sys.path.append(os.path.join(PATH_TO_ADDON,"stable_diffusion/"))
sys.path.append(os.path.join(PATH_TO_ADDON,"stable_diffusion/src/clip"))
sys.path.append(os.path.join(PATH_TO_ADDON,"stable_diffusion/src/k-diffusion"))
sys.path.append(os.path.join(PATH_TO_ADDON,"stable_diffusion/src/taming-transformers"))

site.addsitedir(os.path.join(PATH_TO_ADDON,".python_dependencies"))
pkg_resources._initialize_master_working_set()

from stable_diffusion.ldm.generate import Generate
from omegaconf import OmegaConf
from PIL import ImageOps

models_config  = os.path.join(PATH_TO_ADDON,'stable_diffusion/configs/models.yaml')
model   = 'stable-diffusion-1.4'

models  = OmegaConf.load(models_config)
config  = os.path.join(PATH_TO_ADDON,'stable_diffusion/' + models[model].config)
weights = os.path.join(PATH_TO_ADDON,'stable_diffusion/' + models[model].weights)

generator = Generate(
    conf=models_config,
    model=model,
    weights=weights,
    config=config,
    full_precision=False
)



for bpy_data_iter in bpy.data.images:
    bpy.data.images.remove(bpy_data_iter)

argv = sys.argv
argv = argv[argv.index("--") + 1:]
prompt = argv[0]
num = argv[1]
baseSeed = argv[2]
for seed in range(int(num)):
    # only need one generator, you may call generator.prompt2image for as many images as you need
    (img, seed) = generator.prompt2image(
        prompt = prompt,
        steps = 25,
        seed = seed + int(baseSeed), # None for random
        cfg_scale = 17.5,
        width = 512,
        height = 512,
        sampler_name = 'ddim', # 'ddim', 'k_dpm_2_a', 'k_dpm_2', 'k_euler_a', 'k_euler', 'k_heun', 'k_lms', 'plms'
        seamless = False,
        
        init_img = None, # path to file
        strength = 0.75,
        fit = True
    )[0]
    image_name = prompt + "_" + str(seed)
    image = bpy.data.images.new(image_name, width=img.width, height=img.height)
    image.pixels[:] = (np.asarray(ImageOps.flip(img).convert('RGBA'),dtype=np.float32) * (1.0 / 255.0)).ravel()
    image.pack()
    
    image.alpha_mode = 'STRAIGHT'
    image.filepath_raw = SAVE_PATH + prompt + '\\' + str(seed) + ".png"
    image.file_format = 'PNG'
    image.save()

    print(SAVE_PATH + prompt + '\\' + str(seed) + ".png - saved")`

**Comment by ACMOIDRE** [comment]
@Seeders 
check first line 
` import bpy

**Comment by ACMOIDRE** [comment]
How put code inside block ?
is '' code ''

**Comment by Seeders** [comment]
@ACMOIDRE your path should be

PATH_TO_ADDON = r'C:\Users\99026\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures'

**Comment by Seeders** [comment]
> How put code inside block ?


Select all the code then click the 'insert code' button.

**Comment by ACMOIDRE** [comment]
Ok, i will try

**Comment by ACMOIDRE** [comment]
error:
Python: Traceback (most recent call last):
  File "C:\Users\99026\Blender\Addons\New Folder\DreamTextureRepairScript.blend\Text.py", line 19, in <module>
ModuleNotFoundError: No module named 'stable_diffusion'

**Comment by Seeders** [comment]
@ACMOIDRE if you go here https://github.com/carson-katri/dream-textures and follow instructions, then click verify install, does it work?

**Comment by ACMOIDRE** [comment]
[Does](https://github.com/carson-katri/dream-textures/releases/tag/0.0.6)
Does above version latest version.
i'm try this one now

**Comment by ACMOIDRE** [comment]
![ADF](https://user-images.githubusercontent.com/26376925/192666089-8afa8925-68e2-4e71-96c0-bb091d5fe2f0.jpg)

does this help

**Comment by ACMOIDRE** [comment]
it showing install validation succeded

**Comment by Smuzzies** [comment]
> So I did some digging and found some issues with trying to run the addon headlessly. Main issue boils down to that the addon does not block Blender's main thread while generating (won't freeze Blender while it does its thing), so it'll continue on to the render phase before generating even begins. Also if you tried running Blender without its render arguments it will close soon after because it assumes all work is done due to the main thread running out of things to do. It could potentially work if you continuously call the modal method until generation is complete, but that's only accessible if your script is run as part of the addon.
> 
> I've made a script that will allow you to bypass the addon (but still needs to be installed) and use stable diffusion directly, which doesn't have the issue mentioned above. You can also run it directly in Blender instead of externally so disregard my previous comment.
> 
> One issue to note with this script is it will keep its VRAM usage after generating, so Blender may have issues attempting to render. Try reducing your generated image resolution if it does run into trouble with that.
> 
> Another potential issue is that this script was made with the next release in mind, it should still work with previous releases but I never bothered to test that.
> 
> ```python
> import bpy
> import numpy as np
> import sys
> import os
> import site
> import pkg_resources
> PATH_TO_ADDON = r'C:\Users\ACCOUNT_NAME\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream-textures' # wherever the addon gets installed to on your system
> 
> os.environ["PYTORCH_ENABLE_MPS_FALLBACK"] = "1"
> sys.path.append(PATH_TO_ADDON)
> sys.path.append(os.path.join(PATH_TO_ADDON,"stable_diffusion/"))
> sys.path.append(os.path.join(PATH_TO_ADDON,"stable_diffusion/src/clip"))
> sys.path.append(os.path.join(PATH_TO_ADDON,"stable_diffusion/src/k-diffusion"))
> sys.path.append(os.path.join(PATH_TO_ADDON,"stable_diffusion/src/taming-transformers"))
> 
> site.addsitedir(os.path.join(PATH_TO_ADDON,".python_dependencies"))
> pkg_resources._initialize_master_working_set()
> 
> from stable_diffusion.ldm.generate import Generate
> from omegaconf import OmegaConf
> from PIL import ImageOps
> 
> models_config  = os.path.join(PATH_TO_ADDON,'stable_diffusion/configs/models.yaml')
> model   = 'stable-diffusion-1.4'
> 
> models  = OmegaConf.load(models_config)
> config  = os.path.join(PATH_TO_ADDON,'stable_diffusion/' + models[model].config)
> weights = os.path.join(PATH_TO_ADDON,'stable_diffusion/' + models[model].weights)
> 
> generator = Generate(
> 	conf=models_config,
> 	model=model,
> 	weights=weights,
> 	config=config,
> 	full_precision=False
> )
> 
> # only need one generator, you may call generator.prompt2image for as many images as you need
> (img, seed) = generator.prompt2image(
> 	prompt = 'brick texture',
> 	steps = 25,
> 	seed = None, # None for random
> 	cfg_scale = 7.5,
> 	width = 512,
> 	height = 512,
> 	sampler_name = 'k_lms', # 'ddim', 'k_dpm_2_a', 'k_dpm_2', 'k_euler_a', 'k_euler', 'k_heun', 'k_lms', 'plms'
> 	seamless = True,
> 	
> 	init_img = None, # path to file
> 	strength = 0.75,
> 	fit = True
> )[0]
> 
> image = bpy.data.images.new("name", width=img.width, height=img.height)
> image.pixels[:] = (np.asarray(ImageOps.flip(img).convert('RGBA'),dtype=np.float32) * (1.0 / 255.0)).ravel()
> image.pack()
> 
> bpy.data.materials["Material"].node_tree.nodes["Image Texture"].image = image # place the image wherever you see fit
> ```

Fantastic script! Attempting to work it this morning. Got the py setup and configured PATH to the addon and changed the material/node selection. The script runs and the only error I'm seeing in console is:
![image](https://user-images.githubusercontent.com/110495122/192832267-cbd55006-ffc0-4416-b857-5c4d57d26c2e.png)
It seems like it's running, takes 15-20 seconds to complete. Then spits out the result in the tmp folder.
![image](https://user-images.githubusercontent.com/110495122/192832436-f353af9f-3511-426b-9cc4-e834ab78e385.png)
However, the newly created 0001.jpg is blank (pink missing image).
![image](https://user-images.githubusercontent.com/110495122/192832586-2b878052-a55f-4439-906e-5f6b2aeb3a2a.png)

So close! And great thinking sir. Further thoughts would be mucho appreciated!

**Comment by Smuzzies** [comment]
Nevermind. Forgot the --python-use-system-env. =) Working! 

NullSense and Carson, you two are amazing! I hope your Wednesday is stellar!

**Comment by Smuzzies** [comment]
Would there be a way to translate the subject/genre/and concept artist? Digging through code now.

**Comment by NullSenseStudio** [comment]
If you'd like to request translation it should be posted as a new issue.

**Comment by Smuzzies** [comment]
Looking forward to future updates. Appreciate all the support thus far.

**Comment by Penanito** [comment]
Has anyone gotten this script working in a newer version of dream textures? There is no folder named stable_diffusion in the addon directory anymore... anyone know how I would replace those file paths?
