### ISSUE TITLE
Blender won't unfreeze 

### ISSUE THREAD

**Issue by wither735** [carson-katri/dream-textures#127]
Every time I start generating a Texture Blender start to freeze and never unfreeze, I already waited over 31 Minutes

**Comment by carson-katri** [comment]
What hardware do you have

**Comment by wither735** [comment]
GTX 1650 OC 4GB
16 GB Ram
I tried to set the size of the image from 521 to 1 so it has to calculate far far less but still same rusulte

**Comment by carson-katri** [comment]
The 1650 need the full precision option to be enabled. Please try with that checked and the size reduced to 256x256 and work up from there.

**Comment by wither735** [comment]
How can i enable that?

**Comment by carson-katri** [comment]
Advanced Configuration > Full Precision

**Comment by wither735** [comment]
In Blender or Navidia Programm ( sorry for that stupid questions)

**Comment by carson-katri** [comment]
In the Dream Textures popup window.

**Comment by wither735** [comment]
I tried it and its still not working. I opend Task Manager and there i saw that only 13-30% of my GPU where used i dont know if thats normal. Oh and i saw i just have 8GB Ram because the other 8GB are broken it happend a few days ago. And my Ram was at 95-100%

**Comment by ACMOIDRE** [comment]
I'm having similiar issue as @wither735 on  multiple system gtx 1665  and 8gb ram

**Comment by ACMOIDRE** [comment]
I tried 256*256 and 128*128 still didn't work :(
