### ISSUE TITLE
random seed generator is incompatible with the custom seed input fields

### ISSUE THREAD

**Issue by djpiercy** [carson-katri/dream-textures#129]
The random seeds getting generated by the AI are in the range between 0 to 4294967295, but blender's input fields (or at least the ones used by the addon) work in a range from -2147483648 to +2147483647. This means that **_half_** of all random seeds generated cannot be repeated. While not a huge addon-breaking issue, it becomes very annoying when you finally find a perfect texture seed, only to be unable to repeat it at a higher sample count, and it seems like it could be a rather simple fix. 

(on a semi-related note, any negative value in the seed field will result in a random seed)

**Comment by carson-katri** [comment]
#69 has fixed this, and will be included in the next release.
