### ISSUE TITLE
open_weights_directory()

### ISSUE THREAD

**Issue by HatmanStack** [carson-katri/dream-textures#130]
Having a little trouble getting blender pointed to the correct model directory.  I guessed at the target directory opened in the preference window 

Non-admin account: AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\stable_diffusion\stable-diffusion-v1

not sure if it's right but my install of blender is on a seperate drive along with the addons.  I'm in a non-admin account.  I've tried to create the folder manually for both drives on the D:\ using the blender install...neither working.  Am I missing something simple?

**Comment by carson-katri** [comment]
So it tries to open a folder that doesn’t exist? When you install a Blender addon it should always go into AppData, so I’m not sure how it could end up on separate drive? Unless the whole user is somehow on the other drive.

**Comment by HatmanStack** [comment]
When installing Blender I chose to install it on D:\\ so I guess that's where all of the add-ons live?  Corrected my folder locations from absolute_path.py to reflect that string...stable_diffusion/models/ldm/stable-diffusion-v1/model.ckpt  created that path in the blender_foundation location in C:\\app data and for the blender install on D:\\...  The preference window opens the folder correctly without error on C:\\ and the model.ckpt but I'm not getting a validation button.

**Comment by HatmanStack** [comment]
Needed to access admin account and move model weights...to Admin Blender Account Path in               AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\stable_diffusion\models\ldm\stable-diffusion-v1

**Comment by carson-katri** [comment]
Is it working then?

**Comment by HatmanStack** [comment]
I think it would be if my GPU had higher VRAM, and at this point, I feel like a little girl with red hair and ponytails crying about how hard her life is.  The tech is just so good and the fault isn't your add-on. 

I installed stable diffusion from their git to use from the cmd line.  Used the diffuser library first and was greeted with "RuntimeError: CUDA out of memory."  Then I installed it from the original which took a little bit of refactoring of some .py's but got there and was rewarded with a 'RuntimeError: CUDA out of memory.'  Ran it with both 32 and 16 factors of Cuda with arguments height & width to 256, 128, 64; n_samples = 1; precision="full" & "autocast", removed the safety_checker; watermark and still get "RuntimeError: CUDA out of memory."

Some Cat over [here](https://github.com/CompVis/stable-diffusion/issues/69) got it working with  8 Gb ram, 4Gb 1650 GPU on a  lappie...not sure how, something to do with sacrificing his firstborn.  For now I'm using a colab to generate texutres:

https://colab.research.google.com/github/huggingface/notebooks/blob/main/diffusers/stable_diffusion.ipynb

And some others to extend functionality till I upgrade:

https://colab.research.google.com/github/patil-suraj/Notebooks/blob/master/image_2_image_using_diffusers.ipynb
https://colab.research.google.com/github/patil-suraj/Notebooks/blob/master/in_painting_with_stable_diffusion_using_diffusers.ipynb
https://colab.research.google.com/github/huggingface/notebooks/blob/main/diffusers/training_example.ipynb

Cool add-on man gives me a reason to trash this dated card.  All the Best!

16 Gb ram
Nvidia 1650 GPU
