### ISSUE TITLE
Encountered error while generating package metadata 

### ISSUE THREAD

**Issue by vediovis81** [carson-katri/dream-textures#131]
Install dependecies never get installed im getting the following error msg at the end of installation

 File "C:\Blender 3.3\3.3\python\lib\site-packages\setuptools\wheel.py", line 103, in _install_as_egg
          self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
        File "C:\Blender 3.3\3.3\python\lib\site-packages\setuptools\wheel.py", line 125, in _convert_metadata
          zf.extractall(destination_eggdir)
        File "C:\Blender 3.3\3.3\python\lib\zipfile.py", line 1634, in extractall
          self._extract_member(zipinfo, path, pwd)
        File "C:\Blender 3.3\3.3\python\lib\zipfile.py", line 1688, in _extract_member
          open(targetpath, "wb") as target:
      FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\fafou\\AppData\\Local\\Temp\\pip-install-o6tfe_hw\\basicsr_dffee4a0ae2041eb9aa75144004c05b5\\.eggs\\torch-1.12.1-py3.10-win-amd64.egg\\caffe2\\python\\serialized_test\\data\\operator_test\\learning_rate_adaption_op_test.test_learning_rate_adaption_op_normalization.zip'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
[https://imgur.com/Vz17tXF](url)

**System (please complete the following information):**
- OS
  - [x] Windows
  - [ ] macOS
  - [ ] Other
- GPU
  - [x] NVIDIA 
  - [ ] NVIDIA 16*XX*
  - [ ] Apple Silicon
  - [ ] AMD
- Addon Version
  - Latest

pip version 22.2.2

any ideas ?? Thanks a lot

**Comment by denis-roy** [comment]
Please make sure:

1. You have set `LongPathsEnabled` to `1` in your registry under `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem` as per indicated in the README
2. You are running Blender as Administrator

and try again. 

Don't forget to have a look at the other issues (especially the closed ones) to see if anyone is experiencing a problem similar to yours and how they resolved it if they did. 

Good luck :)

**Comment by vediovis81** [comment]
solved ! thanks a lot 👍
