### ISSUE TITLE
Renders are distorted

### ISSUE THREAD

**Issue by bobwareinc** [carson-katri/dream-textures#133]
Hello! For some reason, when I increase the image size to 1024x1024, the image starts deforming in an abomination! For example, when trying to render a chihuahua, the chihuahua will be morphing into many more chihuahua's. Any ideas?
![Dream Texture Panel](https://user-images.githubusercontent.com/91074643/192165063-91f538bd-10c9-482d-af00-e789c98f0fe9.png)
![Abomination Chihuahua](https://user-images.githubusercontent.com/91074643/192165070-2aa86d99-0158-453a-a887-83a7d9cf5b77.png)
![Chihuahua Human](https://user-images.githubusercontent.com/91074643/192165075-0bf7129d-9a8c-4415-8c34-8c36dc5cbc7c.png)
![Horror Chihuahua](https://user-images.githubusercontent.com/91074643/192165081-9a39bf02-0824-4349-b9bf-f46950709a57.png)

**Comment by carson-katri** [comment]
Stable diffusion was trained on 512x512 images, so when you generate images of a different size, it can tend to repeat itself a few times. Two heads are a common problem with portraits, for example. I am not aware of any way around this as of now, except to generate at 512x512 then upscale to 1024x1024.

**Comment by bobwareinc** [comment]
> Stable diffusion was trained on 512x512 images, so when you generate images of a different size, it can tend to repeat itself a few times. Two heads are a common problem with portraits, for example. I am not aware of any way around this as of now, except to generate at 512x512 then upscale to 1024x1024.

AH, okay I understand! Thanks for the info!
