### ISSUE TITLE
Windows Dependencies Version Error

### ISSUE THREAD

**Issue by AgainsTurb** [carson-katri/dream-textures#135]
When I try to install windows dependencies, it pops up:
ERROR: Could not find a version that satisfies the requirement clip (unavailable) (from versions: 0.0.1, 0.1.0, 0.2.0)
ERROR: No matching distribution found for clip (unavailable)

Could anyone please help me out?
 Thx a lot:)

**Comment by dschiller** [comment]
Which Python Version do you use ?
- Open a shell ( Windows key + R, type `cmd`, press enter )
- Type `python --version`, press enter

**Comment by carson-katri** [comment]
There is no need to install dependencies in 0.0.6.
