### ISSUE TITLE
It's not working for me. Ii just keeps saying "please complete setup in the preferences window".

### ISSUE THREAD

**Issue by Mechaghostman2** [carson-katri/dream-textures#14]
It's not working for me. It just keeps saying "please complete setup in the preferences window".

I did, 20 times. I installed the add-on, installed the dependencies, and moved the file to be renamed to "model.cpkt" into the addons folder, all while in administrative mode.

I'm using an Nvidia 3060ti and I'm on Blender 3.3.

You may need clearer install instructions or something. I can't get it to work.

All I get is "C:\Program Files\Blender Foundation\3.3\python\lib\site-packages\accelerate\state.py:16: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives from distutils.util import strtobool"

What does that even mean?

**Comment by Jeffan207** [comment]
That error is only shown when your weights are not installed: https://github.com/carson-katri/dream-textures/blob/main/operators/dream_texture.py#L40-L41. From your description, I think you typo'd the name of the weights file when moving it. It should be `model.ckpt` not `model.cpkt`. I made a similar mistake on my first install.
