### ISSUE TITLE
Installed everything but still have error... wont generate anything... please help

### ISSUE THREAD

**Issue by eqluna** [carson-katri/dream-textures#140]
**Describe the bug**
0.05
It would not do a thing, even after Installed Dependencies, Model Weights. Restarted Blender, Validation succeeded; even reinstalled Blender 3.3 and redo this whole process... nothing appears...

**To Reproduce**

**Screenshots**
https://gyazo.com/452ada847772747384a75b6a1356c96c
https://gyazo.com/a3c16ae05c486bf86769b26f188733dc
another try:
https://gyazo.com/42d02d45793a8e9dbf701398309cf512
yet another try:
https://gyazo.com/6b3ec0246a7d0d689b03533bd0bc6582

I look thru the files and there are nothing called DreamPrompt.cfgscale  which is the property not found

**System (please complete the following information):**
- OS
  - [x] Windows
  - [ ] macOS
  - [ ] Other
- GPU
  - [x] NVIDIA
  - [ ] NVIDIA 16*XX*
  - [ ] Apple Silicon
  - [ ] AMD
- Addon Version
  - Latest

**Additional context**

**Comment by noc2art** [comment]
Same here... Installation gets validated, but no image gets generated after half a minute of hanging.

![image](https://user-images.githubusercontent.com/32395664/192339629-4f937d7b-d90b-4634-8008-207c84d20ef0.png)


[DreamT_Blender_Console.txt](https://github.com/carson-katri/dream-textures/files/9648334/DreamT_Blender_Console.txt)

**Comment by eqluna** [comment]
> Same here... Installation gets validated, but no image gets generated after half a minute of hanging.
> 
> ![image](https://user-images.githubusercontent.com/32395664/192339629-4f937d7b-d90b-4634-8008-207c84d20ef0.png)
> 
> [DreamT_Blender_Console.txt](https://github.com/carson-katri/dream-textures/files/9648334/DreamT_Blender_Console.txt)

If you look at the console window, it has TONS of error, especially it cannot find properties that do not exist anywhere, I have looked EVERY FILE.

**Comment by nikolatesla20** [comment]
Those event_loop "error" I believe are normal, I see those and my Dream Texture installation is working

**Comment by ACMOIDRE** [comment]
I'm having similiar issue as @wither735 on  multiple system gtx 1660 Ti  and 8gb ram

**Comment by eqluna** [comment]
> Those event_loop "error" I believe are normal, I see those and my Dream Texture installation is working

Are you using Mac or PC?  It was reported that Mac Works, but PC users encountered fleet of issues.

**Comment by noc2art** [comment]
I'm on a PC, Win 10 Pro, Blender 3.3.

**Comment by ACMOIDRE** [comment]
Window 10 not pro

**Comment by Husan544** [comment]
I'm having similiar issue as @wither735 on multiple system gtx 1660 Ti and 16gb ram

**Comment by eqluna** [comment]
> I'm on a PC, Win 10 Pro, Blender 3.3.

Can you please teach us? exactly what is the process to install?  did you do anything extra?

**Comment by carson-katri** [comment]
v0.0.6 no longer requires dependencies to be installed. NVIDIA 1650/60 require Full Precision to be enabled under Advanced Configuration.

**Comment by nikolatesla20** [comment]
Instead of just closing the issue, could there have been a way of detecting video cards and setting full on if it's required? Would have helped those users that didn't realize that and ease confusion

**Comment by carson-katri** [comment]
Yes, the next version will likely provide more fine control over precision that just a checkbox, and also automatically set it correctly for the detected card.

**Comment by eqluna** [comment]
> Yes, the next version will likely provide more fine control over precision than just a checkbox, and also automatically set it correctly for the detected card.

0.06 failed instantly after installation when clicking the little check box
https://gyazo.com/64615e4f0811a8b2a469aa0d7bc63902
Please kindly help and thanks

**Comment by eqluna** [comment]
> > Yes, the next version will likely provide more fine control over precision than just a checkbox, and also automatically set it correctly for the detected card.
> 
> 0.06 failed instantly after installation when clicking the little check box https://gyazo.com/64615e4f0811a8b2a469aa0d7bc63902 Please kindly help and thanks

found out why, need to install this as Admin. thank you
