### ISSUE TITLE
Cant install dependencies

### ISSUE THREAD

**Issue by NaughtDZ** [carson-katri/dream-textures#143]
I have been installed Git and there is python 3.8 already install in my pc.I know,Blender have it own python.
And i do both update 2 python pip already.....

pip 22.2.2 from F:\Games\steam\steamapps\common\Blender\3.3\python\lib\site-packages\pip (python 3.10)
Starting new HTTPS connection (1): www.python.org:443
https://www.python.org:443 "GET /ftp/python/3.10.2/Python-3.10.2.tgz HTTP/1.1" 200 25067363
adding trusted host: 'https://download.pytorch.org' (from line 29 of C:\Users\Naught\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\requirements-win-torch-1-11-0.txt)
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple, https://download.pytorch.org/whl/cu113
Collecting clip
  Cloning https://github.com/openai/CLIP.git (to revision main) to c:\users\naught\appdata\local\temp\pip-install-6c9g_mn8\clip_936f8868545745aba26004351f09f39a
  Running command git clone --filter=blob:none --quiet https://github.com/openai/CLIP.git 'C:\Users\Naught\AppData\Local\Temp\pip-install-6c9g_mn8\clip_936f8868545745aba26004351f09f39a'
  Resolved https://github.com/openai/CLIP.git to commit d50d76daa670286dd6cacf3bcd80b5e4823fc8e1
  Preparing metadata (setup.py) ... done
Collecting k-diffusion
  Cloning https://github.com/lstein/k-diffusion.git (to revision master) to c:\users\naught\appdata\local\temp\pip-install-6c9g_mn8\k-diffusion_9f7a5488a4d147d9b7665abfb562edc2
  Running command git clone --filter=blob:none --quiet https://github.com/lstein/k-diffusion.git 'C:\Users\Naught\AppData\Local\Temp\pip-install-6c9g_mn8\k-diffusion_9f7a5488a4d147d9b7665abfb562edc2'
  Resolved https://github.com/lstein/k-diffusion.git to commit ef1bf07627c9a10ba9137e68a0206b844544a7d9
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting gfpgan
  Cloning https://github.com/lstein/GFPGAN (to revision fix-dark-cast-images) to c:\users\naught\appdata\local\temp\pip-install-6c9g_mn8\gfpgan_d3f803f0a85b4f988ec5c849658308ee
  Running command git clone --filter=blob:none --quiet https://github.com/lstein/GFPGAN 'C:\Users\Naught\AppData\Local\Temp\pip-install-6c9g_mn8\gfpgan_d3f803f0a85b4f988ec5c849658308ee'
  fatal: unable to access 'https://github.com/lstein/GFPGAN/': OpenSSL SSL_read: Connection was reset, errno 10054
  fatal: unable to access 'https://github.com/lstein/GFPGAN/': Failed to connect to github.com port 443 after 21084 ms: Timed out
  error: unable to read sha1 file of .github/workflows/no-response.yml (fa702eeacff13fe8475b0e102a8b8c37602f3963)
  Auto packing the repository in background for optimum performance.
  See "git help gc" for manual housekeeping.
  fatal: unable to checkout working tree
  warning: Clone succeeded, but checkout failed.
  You can inspect what was checked out with 'git status'
  and retry with 'git restore --source=HEAD :/'

  error: subprocess-exited-with-error

  × git clone --filter=blob:none --quiet https://github.com/lstein/GFPGAN 'C:\Users\Naught\AppData\Local\Temp\pip-install-6c9g_mn8\gfpgan_d3f803f0a85b4f988ec5c849658308ee' did not run successfully.
  │ exit code: 128
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/lstein/GFPGAN 'C:\Users\Naught\AppData\Local\Temp\pip-install-6c9g_mn8\gfpgan_d3f803f0a85b4f988ec5c849658308ee' did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by carson-katri** [comment]
Please take a look at [v0.0.6](https://github.com/carson-katri/dream-textures/releases/tag/0.0.6), which removes the need to install dependencies.
