### ISSUE TITLE
installation failure, unknown cause

### ISSUE THREAD

**Issue by Cutinup99** [carson-katri/dream-textures#144]
**Is this a known issue?**
This does not appear to be a known issue, however, I could have missed it.

**Describe the bug**
This appears to be multiple errors from different places, one was during initial downloading of the CLIP module (which now refuses to download at all), and one was after trying to run the addon despite that. all the visual elements of the addon function correctly, its simply that no image is generated and it spits out **alot** of the same error for ~10 seconds before giving up

**To Reproduce**
Genuinely wish I knew how it happened in the first place, if I found out how to reproduce it, I will update with a comment

**Expected behavior**
I expected the addon to install normally, and function normally after applying the registry fix.

**System:**
- OS
  - [x] Windows
  - [ ] macOS
  - [ ] Other
- GPU
  - [x] NVIDIA (GTX 1060 3GB)
  - [ ] NVIDIA 16*XX*
  - [ ] Apple Silicon
  - [ ] AMD
- Addon Version
  - Latest

**Additional context**
all `<USER>` in the following error log snippets were replacing just the windows username. nothing else has been modified in the logs
I can provide aditional information if required
[Generation failure.txt](https://github.com/carson-katri/dream-textures/files/9646442/Generation.failure.txt)
[Download failure.txt](https://github.com/carson-katri/dream-textures/files/9646443/Download.failure.txt)

**Comment by Harvester62** [comment]
Hi @Cutinup99 after your initial report, have you tried to install the latest v0.0.9, and in the affirmative are you having the same problems with this version too?

**Comment by Cutinup99** [comment]
I totally forgot to update this issue, I apologize. i fixed the issue after going to the discord and talking there, turns out all I had to do was delete the downloads folder, because the download got corrupted. the folder in specific was `C:\Users\(username)\.cache\huggingface`
after I deleted that, it started working just fine on that version, and all subsequent versions.
