### ISSUE TITLE
Can't Reimagine a Concept Art using its Seed value

### ISSUE THREAD

**Issue by SolusGod** [carson-katri/dream-textures#154]
**Is this a known issue?**
I don't think so.

**Describe the bug**
I like to generate a low resolution of a concept art and if I find the one I like I try to reimagine it in a higher resolution using the same seed value but the AI gives a completely new Concept Art even though it's the exact seed value... what gives! 

**To Reproduce**
1. Generate a random Concept Art
2. Try to use the same seed value and reimagine it with more steps
3. Compare Output

**Expected behavior**
As I understand it, if you have the seed value of an art concept you basically have the path to it and can reimagine or add to it, but it seems the AI is getting lost somewhere along the way! Or maybe I am an idiot!

**Screenshots**
Couldn't provide screenshots because the Seed Value keeps resetting to -2147483648 every time I input my Seed which is 4262555810. This bug is an off and on kind of thing, sometimes a seed value gets accepted, other times not. (I know this is related to another bug that is being worked on)

**System (please complete the following information):**
- OS
  - [x] Windows
  - [ ] macOS
  - [ ] Other
- GPU
  - [x] NVIDIA
  - [ ] NVIDIA 16*XX*
  - [ ] Apple Silicon
  - [ ] AMD
- Addon Version
  - Latest

**Comment by carson-katri** [comment]
All parameters need to be the same to get the exact same image with a given seed, including the size. Although i would expect the images to at least be similar with the same seed and slightly different settings otherwise.
