### ISSUE TITLE
depencies

### ISSUE THREAD

**Issue by kayeegrow** [carson-katri/dream-textures#155]
**Is this a known issue?**
Check the troubleshooting section of the addon before reporting a new issue. Also [search for the error](https://github.com/carson-katri/dream-textures/issues?q=is%3Aissue) first.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
- OS
  - [x] Windows
  - [ ] macOS
  - [ ] Other
- GPU
  - [x] NVIDIA
  - [ ] NVIDIA 16*XX*
  - [ ] Apple Silicon
  - [ ] AMD
- Addon Version
  - Latest

**Additional context**

**Comment by carson-katri** [comment]
I am unsure what this is reporting. No information was given.
