### ISSUE TITLE
Failing to install the Dependencies

### ISSUE THREAD

**Issue by Sainte-croix** [carson-katri/dream-textures#157]
**Describe the bug**
When I try to install the dependencies, the message "ERROR: Failed building wheel for opencv-python-headless" is shown.
I'm very new to coding so it might be a simple problem that i just don't know how to solve...

**Screenshots**
Here is a screenshot of what the terminal on Mac says :

<img width="1065" alt="Capture d’écran 2022-09-27 à 16 30 16" src="https://user-images.githubusercontent.com/114500323/192555211-2c3943ab-d2ab-4989-9ff2-bd5be9c4d3ee.png">

**System (please complete the following information):**
- OS
  - [X] macOS
- GPU
  - [x] Apple Silicon
- Addon Version
  - Latest

**Comment by carson-katri** [comment]
Please take a look at [v0.0.6](https://github.com/carson-katri/dream-textures/releases/tag/0.0.6), which removes the need to install dependencies.
