### ISSUE TITLE
Problems with installing newest release

### ISSUE THREAD

**Issue by SolusGod** [carson-katri/dream-textures#159]
**Is this a known issue?**
No.

**Describe the bug**
Installing the 0.5 version was a bit tricky but I made it work, and I was highly anticipating the release of 0.6 which happened today thanks to your hard work! But when installing the new version It gives me a traceback error (Images Provided) and the Plugin can't be enabled anymore. 
Note that I didn't delete previous plugin's dependencies, It may or may not be worth mentioning.

**To Reproduce**
1. Install latest plugin
2. Try to enable it
3. Scream in agony

**Expected behavior**
In a perfect world all the Plugins should install without any errors.

**Screenshots**
![image_2022-09-27_150826573](https://user-images.githubusercontent.com/114396538/192614475-8946bc85-ab83-4029-b7b0-1d7be72586eb.png)

**System (please complete the following information):**
- OS
  - [x] Windows
  - [ ] macOS
  - [ ] Other
- GPU
  - [x] NVIDIA
  - [ ] NVIDIA 16*XX*
  - [ ] Apple Silicon
  - [ ] AMD
- Addon Version
  - Latest

**Comment by SolusGod** [comment]
I did. I even removed the old dependencies which I thought may be the problem. But it seems the issue from what I can decode from the error is just a missing/corrupt import of 'kill.generator'. I reinstalled the addon 3 times with no avail. 

I used the dream_textures-win32-cuda.7z

**Comment by carson-katri** [comment]
I would suggest either redownloading the 7z or re-extracting the 7z. It seems like that file went missing somewhere down the line.

**Comment by SolusGod** [comment]
Apologies, I forgot to run Blender using Admin Rights. That seemed to have solved it. Thanks a lot Carson!

**Comment by carson-katri** [comment]
You needed to run Blender as admin to delete the old one, or to install the new one?

**Comment by SolusGod** [comment]
I installed the new addon without Admin rights. but I couldn't enable it because it would give me the error above. But closing Blender and reopening it using Admin Rights somehow makes it possible for me to enable the Plugin. 

As clarification, I didn't need to install the plugin with Admin Rights, but I needed to run Blender after Plugin Installation with Admin Rights to Enable it.

**Comment by carson-katri** [comment]
Interesting ok. I may need to note that in the instructions.
