### ISSUE TITLE
Request: Dream Textures Batch output?

### ISSUE THREAD

**Issue by enzyme69** [carson-katri/dream-textures#16]
On my M1 Mac, it runs 1000-3000 seconds at least to generate something from a prompt (25-50 samples). I am thinking to run this overnight like maybe if possible output a batch, so I can get a nice 20-30 AI Art per night. I wonder if there is a plan to support batch "dreams"?

Thanks!

**Comment by carson-katri** [comment]
There is an 'Iterations' option but it is currently disabled until I can properly support it.

Try disabling 'Show Steps' to speed it up.

**Comment by Smuzzies** [comment]
Having it generate the image and change the image link on an already existing image texture node would be awesome! Thanks for the tool and great work!
