### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by Sainte-croix** [carson-katri/dream-textures#163]
**Describe the bug**
When I press on Target Directory, it shows the Error as in the screenshot. It looks like it tries to connect with a file that doesn't exist.
I don't have any /Library in my user file /esteban
Mine is directly in /Mac DD/Library/Application Support
But even in the file Application Support I don't have a blender file.

In the beginning, i thought it was a Blender problem, so i reinstalled it. But it didn't change anything.

I don't really know if it's a problem from my computer or anything else i dont know.

**Screenshots**
<img width="1076" alt="Capture d’écran 2022-09-27 à 23 49 39" src="https://user-images.githubusercontent.com/114500323/192642560-47b4c2e6-7e3a-46ce-beff-8fc5d7890bc3.png">

**System (please complete the following information):**
- OS
  - [x] macOS
- GPU
  - [X] Apple Silicon
- Addon Version
  - Latest 0.0.6

Thanks again a lot!

**Comment by carson-katri** [comment]
Did you download the file `dream_textures-darwin-arm64.zip` from the 0.0.6 release? If not, please follow the macOS installation instructions here: https://github.com/carson-katri/dream-textures/releases/tag/0.0.6

**Comment by Sainte-croix** [comment]
yes perfect that was it
