### ISSUE TITLE
"LayerNormKernelImpl" not implemented for 'Half'

### ISSUE THREAD

**Issue by alexandis** [carson-katri/dream-textures#166]
It is what I got on new version 0.0.6 trying to generate 512x512 texture "brick wall" (all settings - default).
The notebook is HP EliteBook 8540w, videocard NVidia Quadro FX 880M:

[render_issue.txt](https://github.com/carson-katri/dream-textures/files/9664067/render_issue.txt)

**Comment by carson-katri** [comment]
Can you try enabling full precision under advanced configuration?

**Comment by alexandis** [comment]
I did. And now I have finally received this short error:

> C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\torch\cuda\__init__.py:82: UserWarning: CUDA initialization: CUDA driver initialization failed, you might not have a CUDA gpu. (Triggered internally at  ..\c10\cuda\CUDAFunctions.cpp:112.)
>   return torch._C._cuda_getDeviceCount() > 0

which does not seem true:

![image](https://user-images.githubusercontent.com/6149843/192789170-32b2cfc4-4cfa-4759-acce-bc18988e6dfc.png)

Anyway, I do realize that my card is old. But is there any way to get this texture generated?

**Comment by alexandis** [comment]
> With 1GB of VRAM that is impossible. Minimum requirement is 4GB and even then it still often has issues.

Too bad... No chance to make it runnable on CPU emulation? I'm asking before the rendering itself can use CPU even if there is no GPU unit available.

**Comment by NullSenseStudio** [comment]
We could look into a way to force CPU generating. Though that runs much slower, and with how old your laptop model is I doubt it can run on CPU either.

**Comment by alexandis** [comment]
> We could look into a way to force CPU generating. Though that runs much slower, and with how old your laptop model is I doubt it can run on CPU either.

Probably texture generation is a very time-consuming. But I do use this old notebook for Blender rendering and it's ok for me. I'm not a pro, of course, I'm an amateur. So if you manage to make a CPU-driven texture generation, I'll give it a try.
