### ISSUE TITLE
OSerror(22, 'Cannot find specified module.; , none, 126 

### ISSUE THREAD

**Issue by yungappa** [carson-katri/dream-textures#169]
After installing the v0.0.6, adding it in administrator mode and downloading the needed assets multiple times (redownloaded and installed the add-on 3 times already) I keep getting the same message. The message is in dutch for some reason, but translated it says 
"cannot find the specified module"

![image](https://user-images.githubusercontent.com/114586299/192778775-93504707-02dd-44cf-9785-f0b28f292635.png)

1. Installed dream_textures-win32-cuda.7z
2. downloaded 7-Zip, then extracted it with Extract Here
3. Opened blender as administrator and installed the add-on
4. Downloaded sd-v1-4.ckpt weights and renamed it to model.ckpt
5. Add-on fully installed (see screenshot)
![image](https://user-images.githubusercontent.com/114586299/192779513-1b5d91e4-473b-4b1d-b5cd-753fc9d43f9a.png)
6. type in a prompt, in this case 'grass' 
7. Get the error
8. Retry the installation multiple times with restarting Blender, same problem

**System (please complete the following information):**
- OS
  - [x] Windows
  - [ ] macOS
  - [ ] Other
- GPU
  - [x] NVIDIA
  - [ ] NVIDIA 16*XX*
  - [ ] Apple Silicon
  - [ ] AMD
- Addon Version
  - Latest

**Comment by carson-katri** [comment]
Can you try to delete the folders `huggingface` and `torch` in `%HOMEPATH%\.cache\`

**Comment by ESPPIRAL** [comment]
Same error here, but I can't locate the aforementioned foders to delete.
![image](https://user-images.githubusercontent.com/29869781/193105703-d1196b18-b431-4135-9bd2-f59ab9dc2f1f.png)

**Comment by Bigfellas** [comment]
I am getting the same error. Tride deleting the huggingface cache but didn't have the torch cache.

Windows 11 and Nvidia

**Comment by Ysaare** [comment]
Same here. Clicking "Generate", "Initializing process"... about a second later, boom.
![image](https://user-images.githubusercontent.com/81472874/193681201-02d7e9a9-82fd-495e-8a24-74884a13ed7d.png)

.cache folder contained none of the folders (checked hidden)
I tried changing the sampler.
What might be of interest: I followed a YT tutorial on this topic, and the OP has "Node: Dream Textures" in the add-ons. I have "Paint: Dream textures" following the exact same steps. Not sure if this matters.
v0.0.6

**Comment by SSA4** [comment]
I have the same problem. I get a new  empty PC with only Blender and this Addon installed and if I try to click "Generate" I get the "OSerror(22, 'Cannot find specified module.; , none, 126" error.
I tried this Addon on Blender 3.2 and 3.3 and I get the the same Error. With my old PC it worked without any problems but this Addon wont work on my new PC. I can't locate the hugginface and torch folder too. I using Windows 10 with NVIDIA RTX 3090 TI.

**Comment by neoOpus** [comment]
> I have the same problem. I get a new empty PC with only Blender and this Addon installed and if I try to click "Generate" I get the "OSerror(22, 'Cannot find specified module.; , none, 126" error. I tried this Addon on Blender 3.2 and 3.3 and I get the the same Error. With my old PC it worked without any problems but this Addon wont work on my new PC. I can't locate the hugginface and torch folder too. I using Windows 10 with NVIDIA RTX 3090 TI.

try version 0.0.7 pre-release

**Comment by SSA4** [comment]
I already used the 0.07 pre-release version. This is the more detailed error I get from the console.
![error](https://user-images.githubusercontent.com/34798862/194565145-8c0c8f1b-ac9f-4ec0-b380-8a5062cae66a.png)
The german sentece means: "Cannot find the specified module"

**Comment by NullSenseStudio** [comment]
Looks like `asmjit.dll` requires the Microsoft visual C++ redistributable to be installed.

https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

Most of you will likely need the x64 architecture version installed, x86 if you are somehow still running 32-bit Windows. You may also have to restart your computer after installing.

**Comment by Ysaare** [comment]
After updating to 0.0.7 and installing MS visual C++ redist the error message is gone (in fact it's a different this time, but probably unrelated) so thanks!

**Comment by Anax7** [comment]
Hi! I get the same error too. Installed addon as admin. Installed MS visual C++ redist. Do I have to install any CUDA kit?

My system specs:
Blender version 3.0.0
Python version 3.9.7
Windows 10 x64
Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz   3.60 GHz
8 GB RAM
GeForce GTX 980 4 GB RAM
