### ISSUE TITLE
Concept Artist option is missing in the new 0.0.6 release

### ISSUE THREAD

**Issue by etherealxx** [carson-katri/dream-textures#171]
when choosing Concept Art preset in 0.0.5, there is an option to choose which concept artist you want.
![2022-09-28 21_40_41-2022-09-24 00_57_15-Blender_  E__Blender Stuff_Project_stablediffusion blend jp](https://user-images.githubusercontent.com/64251396/192810958-9515da41-9dd0-4f80-a684-6444e1cd63cb.jpg)
![2022-09-26 06_07_31-Blender_  E__Blender Stuff_Project_stablediffusion blend](https://user-images.githubusercontent.com/64251396/192812042-aa33f144-3533-4776-be77-7c6ba2a2fd30.jpg)
With the recent UI changes in 0.0.6, the feature seems to be missing.
![2022-09-28 13_25_19-Blender_  C__Users_Ethereal_Documents_Real-ESRGAN_stablediffusion blend](https://user-images.githubusercontent.com/64251396/192813251-e756435d-e140-47fe-ae50-2b484730d133.jpg)
Do i miss something? Is it moved to somewhere else?
If it's intentional, is there any reasoning behind the removal of the feature?

**Comment by carson-katri** [comment]
This option was intentionally removed to not disrespect any living artists. You can manually add to your prompt a style you would like, however.
