### ISSUE TITLE
Install Dependencies Error Non-Zero Exit Status 1

### ISSUE THREAD

**Issue by fatboymonster** [carson-katri/dream-textures#178]
Command '['/Applications/Blender.app/Contents/Resources/3.3/python/bin/python3.10', '-m', 'pip', 'install', '-r', '/Users/********/Library/Application Support/Blender/3.3/scripts/addons/dream_textures/stable_diffusion/requirements-mac-MPS-CPU.txt', '--no-cache-dir']' returned non-zero exit status 1.

Apologies if this has been posted and resolved but I don't know how to fix this

**Comment by carson-katri** [comment]
You should not need to install dependencies with v0.0.6
