### ISSUE TITLE
Process closed unexpectedly

### ISSUE THREAD

**Issue by worthis5612** [carson-katri/dream-textures#179]
After downloading v0.0.6 and installing it , i tried to run the addon but after it loaded a few things an error popped up saying 'process closed unexpectedly' .
![image](https://user-images.githubusercontent.com/114337958/192882759-71c148fa-b243-431e-b483-7be0e10e4b05.png)

I've tried reinstalling blender 3.3 as well as the addon but it still does that no matter what i search.
Windows 10, Gtx 1660 ti mobile

**Comment by carson-katri** [comment]
Try deleting the `huggingface` and `torch` folders in `C:\Users\yourusername\.cache`

**Comment by worthis5612** [comment]
Thanks, that seems to do the trick
