### ISSUE TITLE
Getting Error installing dependencies.

### ISSUE THREAD

**Issue by BioMechAlex** [carson-katri/dream-textures#18]
Trying to install dependencies I'm getting this error

ERROR: Could not find a version that satisfies the requirement basicsr>=1.4.2 (from gfpgan) (from versions: 1.3.1, 1.3.2, 1.3.3, 1.3.3.1, 1.3.3.3, 1.3.3.4, 1.3.3.5, 1.3.3.6, 1.3.3.7, 1.3.3.8, 1.3.3.9, 1.3.3.10, 1.3.3.11, 1.3.4.0, 1.3.4.1, 1.3.4.2, 1.3.4.3, 1.3.4.4, 1.3.4.6, 1.3.4.7, 1.3.4.8, 1.3.4.9, 1.3.5, 1.4.0, 1.4.1, 1.4.2)
ERROR: No matching distribution found for basicsr>=1.4.2

This comes up after, (if it hepls)

INFO: pip is looking at multiple versions of transformers to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of torchmetrics to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of torch-fidelity to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of taming-transformers-rom1504 to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of streamlit to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pytorch-lightning to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pudb to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pillow to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of opencv-python to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of omegaconf to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of kornia to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of imageio to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of imageio-ffmpeg to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of huggingface-hub to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of einops to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of albumentations to determine which version is compatible with other requirements. This could take a while.

**Comment by HowTheHellDoIdoThis** [comment]
i got the same thing, this fixed it:
https://github.com/carson-katri/dream-textures/pull/15

**Comment by BioMechAlex** [comment]
That worked, thank you.
