### ISSUE TITLE
Windows + rx570 4gb

### ISSUE THREAD

**Issue by wennerlas** [carson-katri/dream-textures#180]
I can't generate textures on windows with my rx570 4gb. Probably because it doesn't have cuda support. Has anyone managed to use windows with amd cards of the same range?

**Comment by Ecl1pseGST** [comment]
No, but you can run Full Precision and use your CPU instead. To use your GPU you need to use an SD fork that supports onnx, hopefully they add support to this soon, as having it inside Blender is super handy.
