### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by worthis5612** [carson-katri/dream-textures#181]
After pressing the generate button and waiting a bit , after the 'loading model' and 'starting' messages , i get this error 
![image](https://user-images.githubusercontent.com/114337958/192891009-4d6cb52f-5303-4be4-8575-7a3b888b7c8c.png)
 
 tried restarting blender with admin rights and without ,nothing changed
 gtx 1660 ti mobile,windows 10

**Comment by carson-katri** [comment]
Enable “Full Precision” under advanced configuration for your graphics card.
