### ISSUE TITLE
'python setup.py egg_info' failure when installing dependencies

### ISSUE THREAD

**Issue by CosmicDTaco** [carson-katri/dream-textures#182]
**Describe the bug**
When Installing the dependencies for Dream Textures, There is an error at the end that includes "python setup.py egg_info did not run successfully",  "WARNING: The wheel package is not available", and "error: metadata-generation-failed. During which, the console window cannot be closed out of with the top bar and forcing it to close shuts the blender project down.

**To Reproduce**
1. Download the latest version of Dream Textures,
2. Install the zip onto blender 3.2.2,
3. Install dependencies in Linux/Windows CUDA option

**Expected behavior**
The dependencies are installed without errors

**Screenshots**
![image](https://user-images.githubusercontent.com/75339772/192895703-41f55fef-9819-4546-9659-fa5b8b68e081.png)

**System (please complete the following information):**
- OS
  - [x] Windows
  - [ ] macOS
  - [ ] Other
- GPU
  - [x] NVIDIA
  - [ ] NVIDIA 16*XX*
  - [ ] Apple Silicon
  - [ ] AMD
- Addon Version
  - Latest

**Additional context**
I'm not very savvy with this kind of stuff but if it matters I have the latest version of pip installed in the path environment, and I have Git installed.

**Comment by carson-katri** [comment]
Version 0.0.6 does not require installing dependencies. Please try the latest release from the releases tab and follow the instructions there for Windows installation.
