### ISSUE TITLE
Customizing in Headless Mode

### ISSUE THREAD

**Issue by Smuzzies** [carson-katri/dream-textures#189]
Looking for a way to translate the subject/type/genre/and concept artist within the script itself to be passed into the generation before render. Would be great if an image render from both GUI and headless matched up for easy testing between different desired results. Prompt works great for simplistic results.
> 
> ![image](https://user-images.githubusercontent.com/110495122/192930374-486a70cb-bd06-499a-bcc7-dc17af1caab4.png)

**Comment by NullSenseStudio** [comment]
I think I misunderstood what you were asking for the last time. You can get the full prompt from the UI with `bpy.context.scene.dream_textures_prompt.generate_prompt()` to see how it pieces things together.

![image](https://user-images.githubusercontent.com/47096043/193078721-f03d04f4-94d8-4060-9cab-063258a741e9.png)

**Comment by Smuzzies** [comment]
All good friend. 
I have all the prompts from the gui via the script panel:

- bpy.context.scene.dream_textures_prompt.prompt_structure = 'concept_art'
- bpy.context.scene.dream_textures_prompt.prompt_structure_token_subject = "demon lizard baby"
- bpy.context.scene.dream_textures_prompt.prompt_structure_token_subject_type_enum = 'character'
- bpy.context.scene.dream_textures_prompt.prompt_structure_token_genre = "horror"
- bpy.context.scene.dream_textures_prompt.prompt_structure_token_concept_artist_enum = 'grimmer'
- bpy.context.scene.dream_textures_prompt.strength = 0.63

These work fine from the UI. Translating them over to the headless script, not so much. Very different results using same seed and init_img value. Just wondering if the variable names are different the way you have this script setup since it's accessing SD directly.

```
(img, seed) = generator.prompt2image(
   prompt = 'concept_art',
   subject = "demon lizard baby",
   type_enum = 'character',
   genre = "horror",
   concept_artist_enum = 'grimmer',
   strength = 0.63,
```

**Comment by NullSenseStudio** [comment]
Everything in the prompt section of the UI get concatenated and put as the prompt argument. Having it as separate arguments is causing the rest to not be used by the generator.

**Comment by Smuzzies** [comment]
OH! Roger that, I get what you're saying now I think. Gonna give it a go.

**Comment by Smuzzies** [comment]
Worked perfectly. Much obliged.
