### ISSUE TITLE
Dream textures - no install dependencies button

### ISSUE THREAD

**Issue by TheTruelycon** [carson-katri/dream-textures#197]
Dream textures - no install dependencies button
Very weird behavior, not sure what happens here, but I cannot make the add on to work at all
**To Reproduce**
1. download "cuda" zip file from https://github.com/carson-katri/dream-textures/releases/tag/0.0.6
2. unpack zip file
3. Select and install zip. file in the unpacked folder
4. GO to edit>pref>addons> Dream textures
5. See that there is no install dependencies button and add on does not work at all

**Screenshots**
[screen](https://cdn.discordapp.com/attachments/1025080459681595392/1025084940901154936/unknown.png)

**System (please complete the following information):**
- OS
  - Win 10
  
- GPU
  -3080 10GB
- Addon Version
  - Latest

Note:
For some reason before I cleared whole installation I was able to select main zip file without unpacking, which actually gave me install dependencies button nad all seemed ok, however add on still did not work, now I cannot do it anymore

**Comment by carson-katri** [comment]
Version 0.0.6 does not require you to install dependencies.

**Comment by TheTruelycon** [comment]
Ok, I am dumb, got too attached to video guides for previous versions
