### ISSUE TITLE
Install dependencies fail.

### ISSUE THREAD

**Issue by Paull1996** [carson-katri/dream-textures#198]
**Describe the bug**
Traceback (most recent call last):
  File "C:\Users\cheng\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\stable_diffusion\scripts\preload_models.py", line 6, in <module>
    from transformers import CLIPTokenizer, CLIPTextModel
ModuleNotFoundError: No module named 'transformers'
Traceback (most recent call last):
  File "C:\Users\cheng\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\operators\install_dependencies.py", line 80, in execute
    subprocess.run([sys.executable, absolute_path("stable_diffusion/scripts/preload_models.py")], check=True, cwd=absolute_path("stable_diffusion/"))
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Program Files\\Blender Foundation\\Blender 3.3\\3.3\\python\\bin\\python.EXE', 'C:\\Users\\cheng\\AppData\\Roaming\\Blender Foundation\\Blender\\3.3\\scripts\\addons\\dream_textures\\stable_diffusion/scripts/preload_models.py']' returned non-zero exit status 1.
Error: Python: Traceback (most recent call last):
  File "C:\Users\cheng\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\operators\install_dependencies.py", line 80, in execute
    subprocess.run([sys.executable, absolute_path("stable_diffusion/scripts/preload_models.py")], check=True, cwd=absolute_path("stable_diffusion/"))
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Program Files\\Blender Foundation\\Blender 3.3\\3.3\\python\\bin\\python.EXE', 'C:\\Users\\cheng\\AppData\\Roaming\\Blender Foundation\\Blender\\3.3\\scripts\\addons\\dream_textures\\stable_diffusion/scripts/preload_models.py']' returned non-zero exit status 1.

and huge warning.

**To Reproduce**
In the last step, I'm install dependencies, but it fail.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/73776027/193100541-c641428f-8b53-4388-859c-4de14d288627.png)
![image](https://user-images.githubusercontent.com/73776027/193100577-5f5e1046-7a30-4d2a-96c3-bde0d9745476.png)
![image](https://user-images.githubusercontent.com/73776027/193100603-667df708-5df4-461f-990f-e7aaa502e6d8.png)

**System (please complete the following information):**
- OS
  - [x] Windows
  - [ ] macOS
  - [ ] Other
- GPU
  - [x] NVIDIA
  - [x]  NVIDIA 1060
  - [ ] Apple Silicon
  - [ ] AMD
- Addon Version
  - Latest

**Additional context**

**Comment by carson-katri** [comment]
v0.0.6 does not require installing dependencies, please update and try that version.

**Comment by Paull1996** [comment]
> 
v0.0.6 does not require installing dependencies, but version is v0.0.6
It's no need to install, but I don't have see any dream texture button in image editor.

**Comment by carson-katri** [comment]
It move to the side panel, click N to open and select the dream tab

**Comment by Paull1996** [comment]
I see it!!
Thank You so much, you fix for my problem.
