### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by sebas6691** [carson-katri/dream-textures#20]
I've installed dreamtextures as per the instructions.
After installing the dependencies (which was marked as success) I pressed the validate install and got this error:
```
ModuleNotFoundError: No module named 'antlr4'
```
So I restarted Blender in admin mode and reinstalled the dependencies, again a success. But the validation failed again with the same module.

How to solve this issue?

**Comment by PaintOnBrush** [comment]
you might try to open "cmd" as admin

try something like this

```
cd C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\

.\python\python.exe -m ensurepip

Scripts\pip install antlr4-python3-runtime

pip install antlr4-python3-runtime
```

**Comment by sebas6691** [comment]
Thanks for your reply!

Executed the command in Windows CMD as admin and got this as a result:
```
C:\Program Files\Blender Foundation\Blender 3.3\3.3\python>Scripts\pip install antlr4-python3-runtime
Requirement already satisfied: antlr4-python3-runtime in c:\program files\blender foundation\blender 3.3\3.3\python\lib\site-packages (4.8)
```
Still get the error in Blender.
But if I go with explorer to the folder C:\program files\blender foundation\blender 3.3\3.3\python\lib\site-packages (4.8). It doesn't exist, but this folder does:
C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\antlr4_python3_runtime-4.8-py3.10.egg-info

Any other solution?

**Comment by carson-katri** [comment]
I don’t except uninstalling Blender and deleting the files it leaves in `C:\Program Files\Blender Foundation` and `C:\Users\yourname\AppData\Roaming\Blender Foundation` then reinstalling.

**Comment by sebas6691** [comment]
That's a bit of a bummer..
Thanks for the help!

**Comment by sebas6691** [comment]
Awesome!
Will give it another shot!
