### ISSUE TITLE
Loading Model

### ISSUE THREAD

**Issue by wither735** [carson-katri/dream-textures#200]
Blender Freeze when the Model is loading after pressing Generate and not only Ble dee my whole pc freeze even with 64x64 Resolution and 5 Steps. Evem after 50 Minutes no result

1. Go to "Dream" Panel
2. Click on Generate
4. Stuck in Loading Model

- OS
  - [x] Windows
  - [ ] macOS
  - [ ] Other
- GPU 
  - [x] NVIDIA GTX 1650 OS 4 GB VRAM 
  - [ ] NVIDIA 16*XX*
  - [ ] Apple Silicon
  - [ ] AMD
8GB Ram
- Addon Version: 0.6

**Comment by wennerlas** [comment]
Same problem here. I thought it was because my amd gpu doesn't support cuda but if your nvidia has that too then maybe there is hope for me.

**Comment by carson-katri** [comment]
For the 1650 you will need to enable full precision under “Advanced Configuration”.

**Comment by wither735** [comment]
I already did but its still not working

**Comment by RazorWolvendom** [comment]
yeah same, idk why it just loads instantly as it should from the youtuber that presentated this addon so yeah idk
