### ISSUE TITLE
sorry to say but 0.06 for PC is even worse than last release... here is why

### ISSUE THREAD

**Issue by eqluna** [carson-katri/dream-textures#203]
**Describe the bug**
Last version, 0.05, at least I could install everything after hours of jumping thru the hoops and NOT working...
this time, installed and when I try to click the box to enable it, error at once.
https://gyazo.com/64615e4f0811a8b2a469aa0d7bc63902

At least I did not need to spend hours on it this time and not working. please help and thanks

**Comment by NullSenseStudio** [comment]
Try installing as admin or go to where the addon is saved to and manually copy everything in the zip file to there.

**Comment by SolusGod** [comment]
I had the same Bug, and I've seen a lot of people complaining about this. You just need to run Blender as Admin and then you can enable the plugin with no errors! Maybe this tip should be added to the troubleshoot somewhere.
