### ISSUE TITLE
Init Image [Attribute Error]

### ISSUE THREAD

**Issue by nyu777** [carson-katri/dream-textures#205]
When I try to create an image from my own image with "init image", the process starts but I get an "Attribute Error".

windows10
Blender3.3LTS
v0.0.6
GPU Geforce3080
![SnapCrab_NoName_2022-9-30_16-53-22_No-00](https://user-images.githubusercontent.com/114099714/193222015-c7d6d9b4-242f-4920-b3fb-742e7a7d13ce.png)
![SnapCrab_NoName_2022-9-30_16-57-54_No-00](https://user-images.githubusercontent.com/114099714/193222038-d97c5502-a9f4-4ecd-9f55-a0d9b3171530.png)

**Comment by ahoagmedia** [comment]
Same issue here, and also have an identical error when trying to use inpainting.  

Also on W10, Blender 3.3 LTS, v.0.0.6 with a 3080.

**Comment by Smuzzies** [comment]
Just fixed it on mine, by removing a local copy of Python i was using for unrelated projects and then removing the folder - c:\user\name\appdata\python which contained an outdated version of PIL (pillow 9.0)
