### ISSUE TITLE
Always weird colored images are generated

### ISSUE THREAD

**Issue by YAFU** [carson-katri/dream-textures#208]
Hi.
Using Linux (Ubuntu 20.04) and dream textures with CUDA (GTX 960 4GB)

Whatever configuration I use I get weird colored images as a result, even though I specify words like "real" "realistic" or "photo" in the prompt field:
https://postimg.cc/MX1KmNSV

https://postimg.cc/bDNWSGpm

Currently testing 0.0.6 version, but the problem had started with 0.0.5 as well. Due to low vRAM of my card, I am using custom size of 256x256 (I can't test with default 512x512)

**Comment by carson-katri** [comment]
You will probably need to increase steps under “advanced configuration” to work with smaller sizes.

**Comment by YAFU** [comment]
Hi.
No, increasing steps doesn't seem to help.
Apparently it is all related to size. The closer to 512x512 the better result I get. But I can't go beyond 400x400 due to my 4GB vRAM GPU
