### ISSUE TITLE
[v0.0.6] MacOS troubles with MS Windows paths

### ISSUE THREAD

**Issue by wwarlock** [carson-katri/dream-textures#213]
After plugin installation and weights relocation to plugin folder, Blender must install dependencies.
But it failed cause windows paths hard-coded inside MacOS plugin.

Cannot select and copy text from dialogue, so please check screenshot.
<img width="1512" alt="Screen Shot 2022-09-30 at 23 40 56" src="https://user-images.githubusercontent.com/478413/193353786-d8d6b948-17da-463f-9f74-a5404f8fd493.png">

**Comment by carson-katri** [comment]
No dependencies need to be installed in v0.0.6. If you got the models weights in you’re done.

**Comment by wwarlock** [comment]
Oh, I see. I was so scared, what event didn't try to launch generator.
So, the generator is started and I see the repeatable "Downloading Clip" message and nothing more
<img width="1512" alt="Screen Shot 2022-10-01 at 18 34 39" src="https://user-images.githubusercontent.com/478413/193416965-88b9ce05-97fe-43e6-a0b9-7dcc36f965cc.png">

**Comment by wwarlock** [comment]
finally, it rendered.
I appreciate your help
