### ISSUE TITLE
Unable to load weights from pytorch checkpoint file

### ISSUE THREAD

**Issue by amrelsayed0321** [carson-katri/dream-textures#214]
hello

all the installs are ok but when I click generate nothing happens I tried all the troubleshoot solutions but it doesn't work 
this is a screenshot from the console

![Screenshot_1](https://user-images.githubusercontent.com/114792158/193389318-b1dcdeed-b904-41d3-81c1-44083be99c61.png)

**Comment by amrelsayed0321** [comment]
also, this message shows when I am trying to install dependencies
![Screenshot_2](https://user-images.githubusercontent.com/114792158/193391369-dc8ae7f7-dfd9-4c3e-b8c0-f389c0e27e86.png)

**Comment by carson-katri** [comment]
Please install 0.0.6, it does not require any dependencies to be installed

**Comment by amrelsayed0321** [comment]
> Please install 0.0.6, it does not require any dependencies to be installed

thank you it worked

**Comment by adityapandeyz** [comment]
Facing same issue in 2.0.0
