### ISSUE TITLE
[Suggestion] adding a render queue with auto saving the textures

### ISSUE THREAD

**Issue by Goldk4t** [carson-katri/dream-textures#216]
Hello,

first things first. Thank you so much for this awesome tool!

Since it takes a while for an image to render, I thought a render queue would be a nice feature. Then u can start rendering some images and going to work or what ever ;)

Sorry, dont know how to add a "Suggestion" label, im new to github.

**Comment by rexorp** [comment]
This is just an FYI but I have accidentally hit the Generate button twice and both renders completed and were in the image list that is already created in the Image Viewer.
