### ISSUE TITLE
ModuleNotFoundError -> stable-diffusion.ldm

### ISSUE THREAD

**Issue by Half-and-Xat** [carson-katri/dream-textures#217]
Generating images stops instantly with following Error:
_ModuleNotFoundError("No module named 'stable_diffusion.ldm'")_

I installed everything as expected, but had to create folders /models/ldm/stable-diffusion-v1 by myself into the folder .../stable_diffusion, else it wouldn't found model.ckpt (not sure if this has any relation to this bug). After everything seems to work I tried to generate my first texture, but nothing happened except that error. I started Blender as Admin.

OS: Windows 10
Version of Dream Textures: 0.0.6

**Comment by carson-katri** [comment]
You need to download the packaged addon from the release tab, not the source code.

**Comment by JollySquid** [comment]
After doing that I'm getting another error message.

ImportError('Failed to load PyTorch C extensions:
    It appears that PyTorch has loaded the `torch/_C` folder
    of the PyTorch repository rather than the C extensions which
    are expected in the `torch._C` namespace. This can occur when
    using the `install` workflow. e.g.
        $ python setup.py install && python -c "import torch"

    This error can generally be solved using the `develop` workflow
        $ python setup.py develop && python -c "import torch"  # This should succeed
    or by running Python from a different directory.')

When navigating to the stable diffusion folder and running the second python command it tells me I don't have access to write to the directory it's trying to install torch into.

**Comment by carson-katri** [comment]
Is your blender installed with the MSI on blender.org?

**Comment by Half-and-Xat** [comment]
Problem solved for me, thanks a lot. Generating works as expected right now.
