### ISSUE TITLE
can't inpaint on generated textures

### ISSUE THREAD

**Issue by rvorias** [carson-katri/dream-textures#22]
It seems that the inpaint brush's alpha is not applied on the active image. This means that the second expression will not be true and the inpaint menu will not be visible.

https://github.com/carson-katri/dream-textures/blob/3ef841866be3808838c994273f680c705e6ee48f/operators/dream_texture.py#L72

A workaround is to save the inpainted image as RGBA and then run the inpainting.

updates:

This is from a freshly generated picture in the Image Editor:
![image](https://user-images.githubusercontent.com/21060408/190898400-1c526ff1-c487-4777-885f-7baacb28b469.png)
In the blender data API, everything checks out though. (the image is 24bits deep)

This happens when you apply the alpha in the editor:
![image](https://user-images.githubusercontent.com/21060408/190898506-41263e17-91ed-4dc2-beeb-65bc11be4d6b.png)

**Comment by rvorias** [comment]
This is from a freshly generated picture in the Image Editor:
![image](https://user-images.githubusercontent.com/21060408/190898400-1c526ff1-c487-4777-885f-7baacb28b469.png)
In the blender data API, everything checks out though. (the image is 24bits deep)

**Comment by carson-katri** [comment]
This should be possible in the latest version.
