### ISSUE TITLE
Cannot generate - OSError('openai/clip-vit-large-patch14 does not appear to have a file named pytorch_model.bin

### ISSUE THREAD

**Issue by tomaslamacz** [carson-katri/dream-textures#220]
Installed version 0.06, MacOS, M1. Blender 3.3.

Cannot generate anything, it creates this error:

OSError('openai/clip-vit-large-patch14 does not appear to have a file named pytorch_model.bin but there is a file for TensorFlow weights. Use `from_tf=True` to load this model from those weights.')

**Comment by NadiaVish** [comment]
I have the same issue when trying to generate a picture for the 1st time. It says "Loading" and then stops and shows the error. 
I also have M1, Blender 3.3 and 0.06 version.

**Comment by carson-katri** [comment]
Try deleting the folders `huggingface` and `torch` in `/Users/youruser/.cache`

**Comment by tomaslamacz** [comment]
I only had folder hugginface there. I deleted it and tried again. Now there is a different error:
**Process closed unexpectedly**

**Comment by tomaslamacz** [comment]
Restarted Blender again and it works now.
