### ISSUE TITLE
Issue on Mac OS when trying to generate image for the 1st time

### ISSUE THREAD

**Issue by NadiaVish** [carson-katri/dream-textures#222]
I see this error every time I try to generate an image:

OSError('dlopen(/Users/nadia/Library/Application Support/Blender/3.3/scripts/addons/dream_textures/.python_dependencies/torch/lib/libtorch_global_deps.dylib, 10): **no suitable image found.** 
Did find:\n\t/Users/nadia/Library/Application Support/Blender/3.3/scripts/addons/dream_texturesTpython_dependencies/torch/lib/libtorch_global_deps.dylib: mach-o, but **wrong architecture**\n\t/Users/nadia/Library/ 

I use:
Blender 3.3
Dream Textures v0.0.6
OS Catalina 10.15.7
AMD Radeon Pro 5300 4 GB

**Comment by carson-katri** [comment]
The addon only supports Apple Silicon macs and NVIDIA GPUs.
