### ISSUE TITLE
Feature request: allow connecting to an existing WebUI instance

### ISSUE THREAD

**Issue by InconsolableCellist** [carson-katri/dream-textures#225]
This addon currently assumes that you don't already have SD running and want to install it on the same system that you're using Blender on, but I think that's not the case for many people, and isn't for me. I already have a computer running SD with WebUI and use Krita remotely with a plugin; it'd be nice if Blender can do that too.

Thus can you add support for making queries to WebUI? The best way is probably to make the server/client architecture work that way locally as well, so it doesn't matter where the server install is.

**Comment by carson-katri** [comment]
The addon is built on the InvokeAI fork of SD. Is there a particular fork you are referring to? The main issue I see is that every fork is going to have a different API surface, so making a unified system would likely mean catering to certain forks and not others.

**Comment by InconsolableCellist** [comment]
I was thinking: https://github.com/sd-webui/stable-diffusion-webui

Is that not the main one? I'm not familiar with InvokeAI

**Comment by carson-katri** [comment]
A couple other popular ones are Automatic1111’s fork and basujindal’s fork

**Comment by InconsolableCellist** [comment]
I mean, as it is now yours is using InvokeAI's SD fork, so if one of those WebUI forks added special features you'd have to merge it into this one as well. I'd be surprised if they changed their APIs to be incompatible with one another though.

https://github.com/invoke-ai/InvokeAI/tree/61f46cac31b53f3f043819358382102f1d1d0e78 says that they have a WebUI, so you could keep it, but make it have a client/server architecture that lets you run it on a remote machine.

**Comment by carson-katri** [comment]
The blender addon does not interface with a web ui or server at the moment, it directly runs the model.

**Comment by InconsolableCellist** [comment]
The feature request is that it runs it as a client/server, which that fork supports, but it would mean implementing the WebUI API

**Comment by carson-katri** [comment]
Dream Textures does not use InvokeAI as of #405

**Comment by micahscopes** [comment]
> Dream Textures does not use InvokeAI as of #405 

Here are some more details about the upcoming InvokeAI  API: https://github.com/invoke-ai/InvokeAI/issues/2205#issuecomment-1411078906

It looks quite similar to the internal execution system you're using, though I'm not sure if they're relying exclusively on huggingface pipelines.

Either way it'd be great if there was some self hostable way to execute these things remotely, InvokeAI or otherwise.

I suppose another option could be to implement something in this project that can run in a headless blender instance and execute remote requests.
