### ISSUE TITLE
Some installation Errors

### ISSUE THREAD

**Issue by muchasty** [carson-katri/dream-textures#227]
Add-on enabling error in:
addon_utils.py line 333 in enable mod = __import__(module_name):
No module named 'dream-textures-releases-0'

**Comment by carson-katri** [comment]
Did you download the `dream_textures-win32-cuda.7z` file from the releases tab? If not, please follow the instructions there for installation.

**Comment by muchasty** [comment]
Oh. .. I did not. Thanks. I will try right now
