### ISSUE TITLE
Suggestion: Outpainting

### ISSUE THREAD

**Issue by RazorWolvendom** [carson-katri/dream-textures#232]
i would love to have like a kind of function that could procedurally set a alignment to specific spaces of another generated image to "extend" / continue it instead of having a image all in one, so you could also make bigger images as final Art

example: generating the Middle of the final image of 512x512 and then next to the Left of it generating another image with the same resolution to continue that prompted Art with seamless border of the first image.

![ScreenShot_20221003022427](https://user-images.githubusercontent.com/44827474/193483414-db1c06b4-a62f-4cd9-9f43-40c601851820.png)
![ScreenShot_20221003022829](https://user-images.githubusercontent.com/44827474/193483422-21837d9a-ca7f-4742-a0f8-a7427a85065c.png)

idk how hard would it be to implement something like that but the creativity would be much more defined to the actual limitation of the resolution we can only generate at once.

i would love to hear your opinion about this :)

**Comment by carson-katri** [comment]
This is very possible and I would like to include it. FYI, it’s called “outpainting”.

**Comment by RazorWolvendom** [comment]
> This is very possible and I would like to include it. FYI, it’s called “outpainting”.

oh i see, welp everyone got a other defination ofc hehe
