### ISSUE TITLE
Addon's Troubleshooting Confusion

### ISSUE THREAD

**Issue by neoOpus** [carson-katri/dream-textures#234]
I just want to report that the design of the addon troubleshooting is very confusing since it took me a moment to understand that I don't have an issue with my installation and the displayed information there aren't errors that I have to fix... I did several installs and some readings here to find out that I don't have an issue with Python dependencies...

**Comment by dionyroxys** [comment]
...why is this labeled a bug? this is more of an enhancement request as the system worked as intended, you didnt. understanding basic terminology is important. 

i.e. troubleshooting is what you do when youve confirmed you have a problem, not when the information appears in the first place.

**Comment by carson-katri** [comment]
@dionyroxys Issues made with the bug report template are automatically given this label.

**Comment by dionyroxys** [comment]
> @dionyroxys Issues made with the bug report template are automatically given this label.

ah, i totally forgot autolabeling was a thing.

**Comment by neoOpus** [comment]
Right now I am unable to have it working I still have issue with dependencies not being installed and I am unable to figure out how to solve this myself...

**Comment by carson-katri** [comment]
@neoOpus There is no need to install dependencies. If you have the model weights setup you’re done

**Comment by neoOpus** [comment]
Then I guess my GPU is the problem I have MX450 with 2GB VRAM... I don't see the Dream tab in N-Panel, but the Paint Brush in T-Panel shows up, of course it doesn't work, I thought that it can be supported by tweaking the settings

**Comment by carson-katri** [comment]
Troubleshooting section was removed in #240

**Comment by carson-katri** [comment]
4GB is the absolute minimum
