### ISSUE TITLE
no dependencies - missing software?

### ISSUE THREAD

**Issue by IXarl** [carson-katri/dream-textures#235]
Hey everyone, 

I installed and reinstalled blender as well as the zip file (download from the release tab 👍) multiple times. 

However at the preference tab of blender i've never got the dependency section and therefore i've never got any button to install the dependencies. (see below, red)
I followed the steps from the youtube-Video and from the read-me file. Same issue. 
I ran dream texture and got this error code (yellow)
I dont have any knowledge of software and writing so i've got no clue what it means. : ) 

I guess i'm missing some software i need and noone mentioned. 
Do i need to install python or anything alike?
By the way i'm using Windows and an AMD Ryzen 7

Thanks for 
![fehler](https://user-images.githubusercontent.com/114912073/193544752-1ed5246d-9aa6-454a-ad31-5acace309793.png)

**Comment by neoOpus** [comment]
same here

**Comment by constasmile** [comment]
same thing

**Comment by NullSenseStudio** [comment]
Version 0.0.6 doesn't require extra dependencies to be installed, they now come packaged with the addon. Once you've got the model.ckpt file placed setup is done.

The `RuntimeError: expected scalar type Half but found Float` error means your system needs you to enable the Advanced Configuration > Full Precision checkbox above the Generate button.

**Comment by IXarl** [comment]
ok, i enabled the full precision checkbox. 
Now i've got this error: : D 

![Unbenannt](https://user-images.githubusercontent.com/114912073/193766509-ffafc690-d351-4f96-9d6d-075b000dfd9e.png)

**Comment by NullSenseStudio** [comment]
Looks like you don't have enough VRAM. I'm guessing you have a GTX 1650, it's a pretty common issue with them. You might have better luck when version 0.0.7 is out.

**Comment by IXarl** [comment]
Yeah, that's it. 

Thanks a lot
