### ISSUE TITLE
Suggestion: Cached Models / Locally stored Downloads

### ISSUE THREAD

**Issue by RazorWolvendom** [carson-katri/dream-textures#236]
wouldnt it be better if all those models and Downloaded "CLIP"s be stored in your blender directory to improve the loading times further? aslong it doesnt needs too much additional RAM, besides add a option to Cache those data to load it all faster if desired.

i hope that would also improve the rendering times since "Show steps" disabled runs also much faster that it would be when enabled ofc.

Sincerily, Razor

**Comment by NullSenseStudio** [comment]
It already does cache those. As long as when it shows `Downloading ... (0%)` and doesn't go over 0% then they're being loaded from file.

**Comment by RazorWolvendom** [comment]
> It already does cache those. As long as when it shows `Downloading ... (0%)` and doesn't go over 0% then they're being loaded from file.

oh i see, thank you for the information
