### ISSUE TITLE
Displaying the prompt settings as a watermark

### ISSUE THREAD

**Issue by 1435thunder** [carson-katri/dream-textures#238]
wtb a checkbox to activate displaying the prompt settings as a watermark on the output image?
The purpose is to share the settings and or signed by the artist?

I've found the settings are easily lost, making reproduction impossible

**Comment by RazorWolvendom** [comment]
> 1435thunder

not quiet, the history stores your prompt, Resolution, steps and Sampler.

just not the CFG Scale yet, which should he add tbh
