### ISSUE TITLE
512 limit

### ISSUE THREAD

**Issue by marcrhoule** [carson-katri/dream-textures#24]
Apologies if the answer is obvious, but anytime i try anything above 512X512, nothing happens.
1024 hangs (left overnight to be sure), 512 is immediate. 

My VRAM goes up to 8gb so something is happening......Windows

thank you !

**Comment by carson-katri** [comment]
You probably just don't have enough VRAM to generate larger images. 1024x1024 takes around 20-25GB of VRAM in my testing on an M1 Max.

**Comment by marcrhoule** [comment]
oh wow ok - i guess ill wait for the 5080
thanks!
