### ISSUE TITLE
Error displayed on Console when I try to generate image. No error is shown in the UI part

### ISSUE THREAD

**Issue by Ishan5hrestha** [carson-katri/dream-textures#241]
![image](https://user-images.githubusercontent.com/45944370/193809273-4066ecd5-10e5-4ed1-b303-b7d32fd51f0c.png)
This error appears on console when I try to generate image. Blender's Addon tab also Validates successfully.

**Comment by carson-katri** [comment]
Enable full precision under advanced configuration.
