### ISSUE TITLE
Please bring back the drop-down list of concept artists

### ISSUE THREAD

**Issue by realstevewarner** [carson-katri/dream-textures#242]
In 0.0.5 we had the ability to choose from a list of popular concept artists.  This allowed us to easily test out different art styles.  In 0.06, this feature was removed.  Please bring this feature back!

Taking out the list of popular artists is no different than taking away the "Seamless" checkbox in the textures section.  You're removing functionality and making it more difficult to do things.  

In version 0.6 I have to manually type "by Greg Rutkowski" to get the same results that I could easily get with a drop-down menu in 0.5.  You haven't eliminated my ability to match the Rutkowski style.  You've simply made it more difficult to do so.  Same as the "Seamless" checkbox.  If you took this out, I could still manually type that in.  But having it in the UI simply makes it faster and easier, and isn't that the point?

Half of the battle with a tool like Stable Diffusion is mastering the prompts to get good results.  Having the drop-down lists for Photography, Concept Art, etc. is what makes Dream Textures so fantastic.  You didn't have to guess.  Now you're making it so people have to guess.

I understand that there is some controversy over the inclusion of known artists.  But this functionality still exists in the tool.  Hiding it from the user doesn't fix the ethics issues.  It only makes working with the tool more frustrating.

Please work to expose the list of known artists and add to it with others we might want (e.g. Picasso, Rembrandt, etc.).  

Thank you!

**Comment by carson-katri** [comment]
It is not exactly like the seamless checkbox, because the seamless mode actually changes the way the model works, it doesn’t simply add the word “seamless” to your prompt. Perhaps adding a blank field to the tab to type a style in would be a good replacement, but I do not plan on adding the drop-down back
