### ISSUE TITLE
Suggestion:  Allow users to automatically generate a number of images via an input field

### ISSUE THREAD

**Issue by realstevewarner** [carson-katri/dream-textures#244]
In the Stable Diffusion GUI, multiple images can be created automatically by putting the same prompt on a new line.  There's no way to do that in Dream Textures (that I'm aware of).  It would be nice to have a drop down or user-input field next to the Generate button that allows users to generate multiple versions without having to wait, then hit generate, then wait, then hit generate.  This would allow us to generate 10 or 20 variations on a prompt, walk away, then review the results when done.

Thanks for your consideration!

**Comment by RazorWolvendom** [comment]
yeah i would like that too

**Comment by cholushkin** [comment]
Also I would like to see options of of what to variate. For example:  
* iteration range
* seed range
* list of samplers to choose from
* Cfg scale range
* some color scheme options

**Comment by GottfriedHofmann** [comment]
Isnt' this fixed in [0.0.8 ](https://github.com/carson-katri/dream-textures/releases/tag/0.0.8) by the iterations field and the option to batch process promts from a text datablock?
