### ISSUE TITLE
Dream Texture - RuntimeError: expected scalar but found half float

### ISSUE THREAD

**Issue by avishaked** [carson-katri/dream-textures#253]
Hello,
I’ve downloaded from GitHub the “Dream Textures” 0.0.6 add-on for Blender 3D
software and installed it.
While generating an image, there is a RuntimeError: expected scalar but found half float.

![Dream Texture - RuntimeError](https://user-images.githubusercontent.com/63899055/194218289-3a10ecbf-e008-4044-8e21-4b6c0f16468d.png)
Attached the screenshot of the error.
I need help to solve this problem, please.
Environment
OS - Windows 11, Python 3.10 (64 bit), NVIDIA GeForce GTX 1660 SUPER. CUDA Cores 1408 
Regards
Avi

**Comment by A-thief** [comment]
Had the same issue, enabling "Full Precision" under Advanced Configuration has fixed it for me

**Comment by avishaked** [comment]
Thanks A-thief,
I didn’t find at my Nvidia Control Panel the Advanced Configuration, so I
can’t enable the Full Precision.
Could you please guide me?
Regards
Avi

בתאריך יום ו׳, 7 באוק׳ 2022 ב-0:50 מאת A-thief ***@***.***>:

**Comment by A-thief** [comment]
Advance Configuration is in the Dream-Texture tab in Blender, it's above the "Generate" button

**Comment by avishaked** [comment]
Thanks

בתאריך יום ו׳, 7 באוק׳ 2022 ב-2:02 מאת A-thief ***@***.***>:
