### ISSUE TITLE
When clicking Generate this error occurs

### ISSUE THREAD

**Issue by Abhishekrazy** [carson-katri/dream-textures#259]
CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 4.00 GiB total capacity; 3.39 GiB already allocated; 0 bytes free; 3.45 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by nikolatesla20** [comment]
What is your configuration? we need details. What GPU. Also, try setting "Precision" to "Full precision" to see if that changes anything

**Comment by HenRi-Mergenthaler** [comment]
Same issue. My Gpu is GTX 1660 super 6gb, have tested "Fullprecision". 16gb RAM

**Comment by Shrimpey** [comment]
Same problem, run it on laptop with GTX 1650, 16GB RAM.

`RuntimeError('CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 4.00 GiB total capacity; 3.41 GiB already allocated; 0 bytes free; 3.46 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF')
`

It seems to top the RAM usage all the way to 16GB (during loading model step) and then it crashes. Changing to Fullprecision doesn't change the outcome.

**Comment by Dylan-Ewok** [comment]
I also have the same problem as @Shrimpey and cannot get any prompts to work when I use half precision, and it won't even render if it is at any other setting.  I have the GTX 1650 with 16gb of ram, is there any setting in blender or in windows that will allow it to work?

**Comment by MegaGlodon** [comment]
Same problem, will only run on half precision and all I get regardless of options is a green square. GTX 1650 win 11.

**Comment by Dylan-Ewok** [comment]
Hmmmmmm....... I tried allocating more ram to python (which was very heavily used when trying to generate), and doing it for blender shouldn't really matter since it is never at full usage for it when generating.  Maybe this is simply just a bug in the code, hopefully a new version will be released soon and it will work then.

**Comment by Alexandrull** [comment]
So, we have no solution for this? I needed this add-on for a project, and I can't use it.. 
I have a Nvidia GTX 1650 Ti and 16GB RAM.
![image](https://user-images.githubusercontent.com/116813409/198287957-ae7e4887-d8ab-43df-8858-cf768c5760e3.png)

**Comment by carson-katri** [comment]
This is a hardware limitation of 16 series cards, and not a defect in the addon. 16 series cards do not support mixed precision math.

**Comment by Niko-La** [comment]
@carson-katri is this the case with a gtx 1050 also? I am not getting anything when I click on project after the progress bar.  I switched to the non cuda (dreamstudio) and I am able to generate uv image.  I assume the dreamstudio version of the plugin does not nave the texture feature yet?

**Comment by carson-katri** [comment]
v0.0.9 has new optimization settings that can make this possible on lower-end hardware. If you’re getting out of memory errors, try enabling “Sequential CPU Offload”, and maybe set the Attention Slice Size to a manual value of “1”.
