### ISSUE TITLE
Prompts not generating properly.

### ISSUE THREAD

**Issue by K3YJ3N** [carson-katri/dream-textures#26]
Any idea what would be causing this? Every prompt I get the same abstract image.

![09-18-2022-Blender-001724](https://user-images.githubusercontent.com/10353874/190927760-1306d183-4c28-400f-9244-76756e943fea.png)

**Comment by carson-katri** [comment]
Try increasing the steps to 50 or 75.

**Comment by K3YJ3N** [comment]
> Try increasing the steps to 50 or 75.

Same output unfortunately.

**Comment by carson-katri** [comment]
What graphics card do you have

**Comment by K3YJ3N** [comment]
Radeon RX 5700 XT

**Comment by engineer1469** [comment]
i have the same issue. even after a 1000 steps it still looks like random blobs of color.
btw. i get a constant async error

**Comment by carson-katri** [comment]
@engineer1469 do you also have an AMD GPU?

**Comment by carson-katri** [comment]
I believe on NVIDIA 16XX card you need to use full precision, did you have that on?

**Comment by engineer1469** [comment]
yes i have.
i have tested about every setting
i am using less than 130 pixels in each direction because of v-ram limitations. 
could that be the cause of the problem?
