### ISSUE TITLE
mac OS, can't install dependencies -0.0.7

### ISSUE THREAD

**Issue by KeithKarnage** [carson-katri/dream-textures#264]
Thanks for your work on the project.

I'm attempting to install 0.0.7 on an M1 Mac Mini.

The 'Platform' box is set to Apple Silicon, I click install dependencies, and Terminal gives me this response:

pip 22.2.2 from /Applications/Blender.app/Contents/Resources/3.3/python/lib/python3.10/site-packages/pip (python 3.10)
ERROR: Could not open requirements file: [Errno 2] No such file or directory: '/Users/keith/Library/Application Support/Blender/3.3/scripts/addons/dream-textures/stable_diffusion/requirements-mac-MPS-CPU.txt'

Can't find requirements...

Thanks for any help you can provide,
Keith

**Comment by carson-katri** [comment]
Dependencies are included in the 0.0.7 release.

**Comment by KeithKarnage** [comment]
Oops, I accidentally downloaded 0.05, then was switching to 0.07 when I noticed that, but was still trying to install 0.0.5.  Still getting the same error I was originally getting now.  I'll put in a different issue for that, so it's not relegated to comments.
