### ISSUE TITLE
macOS, 0.0.7 Module Not Found Error

### ISSUE THREAD

**Issue by KeithKarnage** [carson-katri/dream-textures#266]
I click to activate the add-on and get an error.  Terminal and a pop up in Blender both say:  "ModuleNotFoundError:  No module named 'dream-texture-0'

**System (please complete the following information):**
- OS
macOS
- GPU
Apple Silicon

- Addon Version
  - Latest

**Additional context**

**Comment by carson-katri** [comment]
Make sure you downloaded the package addon and not the source code. Also if you previously had another version, restart blender after removing it. This will unload the old modules so the new ones can be found

**Comment by KeithKarnage** [comment]
There is a code drop down in the top right corner.  I clicked on that, and Download ZIP.  Is that right?  (AskNK on YT said that would work).  All other modules have been removed, and the computer restarted since then.

**Comment by carson-katri** [comment]
He was wrong 🙂 follow the instructions here: https://github.com/carson-katri/dream-textures/releases/tag/0.0.7

**Comment by KeithKarnage** [comment]
Thanks, this seems to have solved my issues.  After installing the add on, the dependencies were already located, and now I'm downloading the weights.
