### ISSUE TITLE
AUTOMATIC1111 version works on 2GB

### ISSUE THREAD

**Issue by neoOpus** [carson-katri/dream-textures#268]
Hi Carson,

Actually, I was able to make SD work on my machine from here https://github.com/AUTOMATIC1111/stable-diffusion-webui/

With these arguments in webui-user.bat

`set COMMANDLINE_ARGS=--lowvram --precision full --no-half`

So I guess you can make your version work as well by implanting this in the settings; thus more people can enjoy your add-on (mostly laptops)

**Comment by NullSenseStudio** [comment]
I'd like to mention that their lowvram setting appears to use the CPU instead of the GPU.

https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/405c8171d1acbb994084d98770bbcb97d01d9406/modules/processing.py#L391-L392

**Comment by neoOpus** [comment]
> Collaborator

Thank you for the clarification, I thought it will still use GPU but it will be just a bit slower... I hope that someday it will work with low VRAM since, I've seen some Researchers talking about optimizing things to use much less...

**Comment by YAFU** [comment]
Hi.
I have a GPU with 4GB vRAM. I'm using "lowvram" argument and it definitely uses my GPU (Monitored with nvidia-smi on Linux).
I am able to generate images bigger than 512x512 with lowvram argument, which without it I can't go beyond 400x400 at most.

**Comment by JotaRata** [comment]
OMG it's happening, everybody calm down!

**Comment by cornpo** [comment]
One API for krita, blender, inkscape, ... , would be nice.

https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/765

**Comment by Harvester62** [comment]
Is this really a BUG of DT add-on for Blender?

**Comment by neoOpus** [comment]
Guys try Docker Version it uses GPU and works pretty well as is (I didn't test with Dream-Textures yet)

[AbdBarho/stable-diffusion-webui-docker: Easy Docker setup for Stable Diffusion with user-friendly UI (github.com)](https://github.com/AbdBarho/stable-diffusion-webui-docker)

docker-compose.override.yml

```

services:
  auto:
    environment:
      - CLI_ARGS=--allow-code --lowvram --no-half --xformers --opt-split-attention --enable-insecure-extension-access --precision full --api
```

I will find time to do the testing... it is hard with all the crazy stuff going on lately... and comeback with some more tips and results.
