### ISSUE TITLE
Error after inst

### ISSUE THREAD

**Issue by philigranchik** [carson-katri/dream-textures#270]
**Is this a known issue?**
Check the troubleshooting section of the addon before reporting a new issue. Also [search for the error](https://github.com/carson-katri/dream-textures/issues?q=is%3Aissue) first.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
- OS
  - [x] Windows
  - [ ] macOS
  - [ ] Other
- GPU
  - [x] NVIDIA
  - [ ] NVIDIA 16*XX*
  - [ ] Apple Silicon
  - [ ] AMD
- Addon Version
  - Latest

**Additional context**
Hello! I have this problem :(
![image](https://user-images.githubusercontent.com/91761191/194526803-75a3485a-f445-4385-8569-cf4442b30eb7.png)

**Comment by Bobacuk** [comment]
I have the same error
