### ISSUE TITLE
Having problem with allocating memory

### ISSUE THREAD

**Issue by KCH01** [carson-katri/dream-textures#272]
┌───────────────────── Traceback (most recent call last) ─────────────────────┐
│ C:\Users\Administrator\AppData\Roaming\Blender                              │
│ Foundation\Blender\3.3\scripts\addons\dream_textures\generator_process.py:4 │
│ 49 in <module>                                                              │
│                                                                             │
│   446 │   │   │   send_exception(True, f"Unknown intent {intent} sent to pr │
│   447                                                                       │
│   448 if __name__ == "__main__":                                            │
│ > 449 │   main()                                                            │
│                                                                             │
│ C:\Users\Administrator\AppData\Roaming\Blender                              │
│ Foundation\Blender\3.3\scripts\addons\dream_textures\generator_process.py:3 │
│ 47 in main                                                                  │
│                                                                             │
│   344 │   from transformers.utils.hub import TRANSFORMERS_CACHE             │
│   345 │   model_paths = {'bert-base-uncased', 'openai--clip-vit-large-patch │
│   346 │   if any(not os.path.isdir(os.path.join(TRANSFORMERS_CACHE, f'model │
│ > 347 │   │   preload_models()                                              │
│   348 │                                                                     │
│   349 │   generator = None                                                  │
│   350 │   while True:                                                       │
│                                                                             │
│ C:\Users\Administrator\AppData\Roaming\Blender                              │
│ Foundation\Blender\3.3\scripts\addons\dream_textures\generator_process.py:3 │
│ 40 in preload_models                                                        │
│                                                                             │
│   337 │   │   start_preloading("CLIP")                                      │
│   338 │   │   clip_version = 'openai/clip-vit-large-patch14'                │
│   339 │   │   transformers.CLIPTokenizer.from_pretrained(clip_version)      │
│ > 340 │   │   transformers.CLIPTextModel.from_pretrained(clip_version)      │
│   341 │   │                                                                 │
│   342 │   │   tqdm.update = old_update                                      │
│   343                                                                       │
│                                                                             │
│ C:\Users\Administrator\AppData\Roaming\Blender                              │
│ Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\t │
│ ransformers\modeling_utils.py:2024 in from_pretrained                       │
│                                                                             │
│   2021 │   │   │   │   │   model = cls(config, *model_args, **model_kwargs) │
│   2022 │   │   else:                                                        │
│   2023 │   │   │   with no_init_weights(_enable=_fast_init):                │
│ > 2024 │   │   │   │   model = cls(config, *model_args, **model_kwargs)     │
│   2025 │   │                                                                │
│   2026 │   │   if from_tf:                                                  │
│   2027 │   │   │   if resolved_archive_file.endswith(".index"):             │
│                                                                             │
│ C:\Users\Administrator\AppData\Roaming\Blender                              │
│ Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\t │
│ ransformers\models\clip\modeling_clip.py:684 in __init__                    │
│                                                                             │
│    681 │                                                                    │
│    682 │   def __init__(self, config: CLIPTextConfig):                      │
│    683 │   │   super().__init__(config)                                     │
│ >  684 │   │   self.text_model = CLIPTextTransformer(config)                │
│    685 │   │   # Initialize weights and apply final processing              │
│    686 │   │   self.post_init()                                             │
│    687                                                                      │
│                                                                             │
│ C:\Users\Administrator\AppData\Roaming\Blender                              │
│ Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\t │
│ ransformers\models\clip\modeling_clip.py:601 in __init__                    │
│                                                                             │
│    598 │   │   super().__init__()                                           │
│    599 │   │   self.config = config                                         │
│    600 │   │   embed_dim = config.hidden_size                               │
│ >  601 │   │   self.embeddings = CLIPTextEmbeddings(config)                 │
│    602 │   │   self.encoder = CLIPEncoder(config)                           │
│    603 │   │   self.final_layer_norm = nn.LayerNorm(embed_dim)              │
│    604                                                                      │
│                                                                             │
│ C:\Users\Administrator\AppData\Roaming\Blender                              │
│ Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\t │
│ ransformers\models\clip\modeling_clip.py:147 in __init__                    │
│                                                                             │
│    144 │   │   super().__init__()                                           │
│    145 │   │   embed_dim = config.hidden_size                               │
│    146 │   │                                                                │
│ >  147 │   │   self.token_embedding = nn.Embedding(config.vocab_size, embed │
│    148 │   │   self.position_embedding = nn.Embedding(config.max_position_e │
│    149 │   │                                                                │
│    150 │   │   # position_ids (1, len position emb) is contiguous in memory │
│                                                                             │
│ C:\Users\Administrator\AppData\Roaming\Blender                              │
│ Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\t │
│ orch\nn\modules\sparse.py:139 in __init__                                   │
│                                                                             │
│   136 │   │   self.norm_type = norm_type                                    │
│   137 │   │   self.scale_grad_by_freq = scale_grad_by_freq                  │
│   138 │   │   if _weight is None:                                           │
│ > 139 │   │   │   self.weight = Parameter(torch.empty((num_embeddings, embe │
│   140 │   │   │   self.reset_parameters()                                   │
│   141 │   │   else:                                                         │
│   142 │   │   │   assert list(_weight.shape) == [num_embeddings, embedding_ │
└─────────────────────────────────────────────────────────────────────────────┘
RuntimeError: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:81] data.
DefaultCPUAllocator: not enough memory: you tried to allocate 151781376 bytes.
Error: Process closed unexpectedly

- OS
  - [x] Windows
  - [ ] macOS
  - [ ] Other
- GPU
  - [x] NVIDIA
  - [ ] NVIDIA 16*XX*
  - [ ] Apple Silicon
  - [ ] AMD
- Addon Version
  - Latest

I'm using RTX 3050

**Comment by carson-katri** [comment]
Perhaps try restarting your computer to free up some resources.

**Comment by KCH01** [comment]
> Perhaps try restarting your computer to free up some resources.

I had done that, the ram is running at 30% of 16GB but it still don't work

**Comment by MegaGlodon** [comment]
I'm having the same problem : the error message specifies that it cannot allocate 20 mb (?) of Vram because Pytorch reserves 3.40 gb on the VRAM which is 4gb, any way to go around this ? When looking at the ressource manager VRAM instantly fills up when you click generate, when it hits 90% it aborts.

**Comment by MegaGlodon** [comment]
The troubleshooting sheet on the last version suggested to lower the image size if you lacked memory, but even at 64 by 64 it still maxes out memory, any way to tweak Pytorch memory allocation ?

**Comment by LeonelF** [comment]
I am having the same issue.
On Windows with a GTX 1650 4Gb

**Comment by Hohot** [comment]
The same problem here :(  
Any advice? 
![image](https://user-images.githubusercontent.com/5588297/199168825-edbb2c81-8a40-4a74-af8b-0f2c689df852.png)

**Comment by Hohot** [comment]
The same problem here :(
Any advice? 
![image](https://user-images.githubusercontent.com/5588297/199169342-f8e0d3ce-0fd0-434f-9122-ebbb0a77b911.png)
