### ISSUE TITLE
I keep getting this error no matter what

### ISSUE THREAD

**Issue by Just-Ashtin** [carson-katri/dream-textures#28]
Not sure what i did I just followed the steps the best i could

This is the error:
`ERROR: No .egg-info directory found in C:\Users\Ashtin\AppData\Local\Temp\pip-pip-egg-info-9igt2e_l
WARNING: You are using pip version 21.2.4; however, version 22.2.2 is available.
You should consider upgrading via the 'C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\bin\python.EXE -m pip install --upgrade pip' command.`

**Comment by PaintOnBrush** [comment]
open command prompt as admin

run these 

```
cd C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\bin

.\python.exe -m pip install --upgrade pip
```

**Comment by carson-katri** [comment]
Try deleting the folder at `C:\Users\Ashtin\AppData\Local\Temp\pip-pip-egg-info-9igt2e_l` and repeating the process. Seems like something got corrupted.

**Comment by Just-Ashtin** [comment]
I doesnt exists in my temp folder

**Comment by carson-katri** [comment]
Dependency installation is not required since v0.0.6+
