### ISSUE TITLE
Apple Silicon GPUs. SUPER SLOW M1 Pro

### ISSUE THREAD

**Issue by mghoniem** [carson-katri/dream-textures#285]
Apple Silicon GPUs. SUPER SLOW M1 Pro When generating Anything At default settings. 

1. Super super Slow MACBOOKPRO M1
Generating 512 x 512 wood texture 31min 
Mac Book Pro M1
16GB Ram
MacBook Pro (16-inch, 2021)
OS MONETARY 

 

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
- OS
  - [X ] macOS
- GPU

  - [ X] Apple Silicon
- Addon Version
  - Latest

**Additional context**

**Comment by carson-katri** [comment]
Please share your “Activity Monitor” information on Memory while running the generator.

**Comment by carson-katri** [comment]
And also please disable Show Steps onto increase speed significantly.

**Comment by mghoniem** [comment]
> 
<img width="1209" alt="Screen Shot 2022-10-11 at 1 04 12 AM" src="https://user-images.githubusercontent.com/11878255/194965070-eee113f7-8b28-4b8a-9a68-c38eb619332e.png">

**Comment by mghoniem** [comment]
> And also please disable Show Steps onto increase speed significantly.

i tried that,, same exact issue

**Comment by carson-katri** [comment]
Can you show the memory tab? I’d like to see the memory pressure as well

**Comment by carson-katri** [comment]
You have some processes using significant resources, can you restart to stop everything else from executing?

**Comment by carson-katri** [comment]
And do not benchmark with show steps on

**Comment by mghoniem** [comment]
<img width="1443" alt="Screen Shot 2022-10-11 at 1 20 45 AM" src="https://user-images.githubusercontent.com/11878255/194966373-2fd58941-736c-42ab-ab1b-134de2cab66b.png">

**Comment by mghoniem** [comment]
i think its rather GPU issue ? cause the MAC fans wont startup at all during this process .. that take over 20min.. 
but Fans only works while rendering.. i feel its not seeing the GPUs

**Comment by carson-katri** [comment]
You did download the correct version, correct? `dream_textures-darwin-arm64.zip`

**Comment by carson-katri** [comment]
But also please try what I suggested and see if it helps

**Comment by mghoniem** [comment]
> You did download the correct version, correct? `dream_textures-darwin-arm64.zip`

yep thats the one i got.

**Comment by mghoniem** [comment]
even though on the Activity Monitor GPU is 80% or more under Python 3.10 process

**Comment by carson-katri** [comment]
What is memory pressure like though? It is very memory intensive, and you will need to free up as much RAM as possible by closing other applications

**Comment by mghoniem** [comment]
> What is memory pressure like though? It is very memory intensive, and you will need to free up as much RAM as possible by closing other applications
<img width="1385" alt="Screen Shot 2022-10-11 at 1 49 52 AM" src="https://user-images.githubusercontent.com/11878255/194969087-69d0317c-c734-4b6a-8bd1-78971a5012ba.png">
this is after restart and nothing is open. still slow.. like very very slow

**Comment by mghoniem** [comment]
i got to 3% after 8min

**Comment by carson-katri** [comment]
I remembered something about MacBooks: have you turned “High Power Mode” on in the battery settings? This will let the fans run higher and allow for GPU-heavy tasks to throttle less
