### ISSUE TITLE
Since 0.0.6 / 0.0.7 update I am unable to generate texture iMacPro (intel, incompatible architecture)

### ISSUE THREAD

**Issue by sbgraphic** [carson-katri/dream-textures#287]
Hi, since latest 0.0.6 / 0.0.7 update I am unable to generate texture

10 days ago I could generate my one only first texture in 0.0.5 (or was it 0.0.4 ?) in BD3 3.3 on my iMacPro (intel). I've unfortunately deleted this previous installed version (exceptionally no backups at this time). Since updating to 0.0.6 or 0.0.7 I get this error now (Blender 3.3.1).

`Error: OSError("dlopen(/Users/sbgraphic/Library/Application Support/Blender/3.3/scripts/addons/dream_textures/.python_dependencies/torch/lib/libtorch_global_deps.dylib, 0x000A): tried: '/Users/sbgraphic/Library/Application Support/Blender/3.3/scripts/addons/dream_textures/.python_dependencies/torch/lib/libtorch_global_deps.dylib' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64h)))")`

How can I reinstall those correct x86_64 dependencies properly ? manually ?  (I guest I have to clean it too first ?)
Thanks for your help if possible :-)

**Comment by carson-katri** [comment]
You need to follow the instructions for “Other Platforms” in the release notes. It will not utilize your GPU on Intel macOS however, so expect extremely slow speeds.

**Comment by sbgraphic** [comment]
Okay,  I'll try this thank you. I've noticed the slow speed and I better understand why. Sad I could not use my _Radeon Pro Vega 64X_ for this. Anyway another bad call I've made buying this Mac.

**Comment by sbgraphic** [comment]
> You need to follow the instructions for “Other Platforms” in the release notes. It will not utilize your GPU on Intel macOS however, so expect extremely slow speeds.

Just a quick question: When Development Tools are enabled in Blender, under AddOn section "Install Dependencies" and _Platform_ menu, there is no Apple x86_64 option, only Apple Silicon, what should I use for Mac Intel then ? 
Also there is a (!) with Missing script file for 'dream_textures' at the bottom of this window.

**Comment by carson-katri** [comment]
Which did you download in 0.0.5? I would try the apple silicon one first, as it will probably detect your architecture and get the right files. Otherwise, go for Linux (AMD).

**Comment by sbgraphic** [comment]
Well now I just download the latest 0.0.7

**Comment by carson-katri** [comment]
I meant which did you choose that worked for you in the old version so you can use that same option in the new one.

**Comment by sbgraphic** [comment]
Great, I think I recall during the first install of 0.0.5 I used Apple Silicon, I'll try this. Thanks

**Comment by sbgraphic** [comment]
**Thank you, wonderful, Blender is dreaming again !**
I used Apple Silicon as the option for the dependencies. I also check activity monitor and It's using the GPU too about ~ 50% (the iMac's fans goes at nice speed at the last steps). 
It took about ~ 7'30'' min. for a 512x512 seamless texture. How much time should it take normally ? 
Comparing to Dall-e or MidJourney on the web it's slower for sure but it is still impressive to see such result on your own PC ! 
Do you think I should try Linux/AMD dependencies, would it change anything ?

All the best !
Eric

iMacPro (intel) GPU seems to be used fairly
![Activity_Monitor](https://user-images.githubusercontent.com/5297644/194958395-ef8c8212-2005-4477-bc18-362e82ec3e8b.png)

Result (7'30'')
![Brick_wall_512x512_KLMS_25_steps_v2](https://user-images.githubusercontent.com/5297644/194958458-d89d4d2b-916b-4319-ae0e-e43b608c71a8.png)

**Comment by carson-katri** [comment]
Great, stick with those dependencies! On M1 Max it takes roughly 20 seconds (with Show Steps turned off, that will speed it up a lot for you).
