### ISSUE TITLE
filenotfounderror(2, 'no such file or directory')

### ISSUE THREAD

**Issue by gregcont** [carson-katri/dream-textures#289]
The only thing it shows is the following...

**Describe the bug**
filenotfounderror(2, 'no such file or directory') 

**To Reproduce**
1. Click on Generate.
2. Starts Downloading
3. It shows "filenotfounderror(2, 'no such file or directory')"

**System (please complete the following information):**
- OS
  - [x] Windows i7 7700K
  - [ ] macOS
  - [ ] Other
  
- GPU
  - [x] NVIDIA RTX3060 12G
  - [ ] NVIDIA 16*XX*
  - [ ] Apple Silicon
  - [ ] AMD
- Addon Version
  - Latest

![Error](https://user-images.githubusercontent.com/115429570/194934279-f5911ec3-3452-4632-a2d8-9cca47ee6baf.jpg)

**Comment by NullSenseStudio** [comment]
Could you open the system console and show the full error message?

**Comment by TheEhTeam** [comment]
Same error for me as well.
Windows 10
Blender 3.3

Latest windows Dream Texture Install.
Downloading CLIP 0% is the last stage before the error.

![DreamAI Error](https://user-images.githubusercontent.com/111928670/194951861-22e99b94-7634-4387-aa72-d7060d841cc0.jpg)

**Comment by gregcont** [comment]
> Same error for me as well. Windows 10 Blender 3.3
> 
> Latest windows Dream Texture Install. Downloading CLIP 0% is the last stage before the error.
> 
> ![DreamAI Error](https://user-images.githubusercontent.com/111928670/194951861-22e99b94-7634-4387-aa72-d7060d841cc0.jpg)

Yeah, the same for me

**Comment by ApexxCode** [comment]
I am not sure if this helps, but are you missing the "sd-v1-4.ckpt" file which should be renamed to, "model.ckpt"?

It should be located:
`C:\Users\xxxxxx\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\stable_diffusion\models\ldm\stable-diffusion-v1`

**Comment by gregcont** [comment]
This is my problem from the Console


Read prefs: C:\Users\xxxxx\AppData\Roaming\Blender Foundation\Blender\3.0\config\userpref.blend
Traceback (most recent call last):
  File "C:\Users\xxxxx\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\dream_textures\generator_process.py", line 240, in main
    from stable_diffusion.ldm.generate import Generate
  File "C:\Users\xxxxx\AppData\Roaming\Blender 
Foundation\Blender\3.0\scripts\addons\dream_textures\stable_diffusion\ldm\generate.py", line 7, in <module>
    import torch
  File "C:\Users\xxxxx\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\dream_textures\.python_dependencies\torch\__init__.py", line 216, in <module>
    raise ImportError(textwrap.dedent('''
ImportError: Failed to load PyTorch C extensions:
    It appears that PyTorch has loaded the `torch/_C` folder
    of the PyTorch repository rather than the C extensions which
    are expected in the `torch._C` namespace. This can occur when
    using the `install` workflow. e.g.
        $ python setup.py install && python -c "import torch"

    This error can generally be solved using the `develop` workflow
        $ python setup.py develop && python -c "import torch"  # This should succeed
    or by running Python from a different directory.

Error: ImportError('Failed to load PyTorch C extensions:\n    It appears that PyTorch has loaded the `torch/_C` folder\n    of the PyTorch repository rather than the C extensions which\n    are expected in the `torch._C` namespace. This can occur when\n    using the `install` workflow. e.g.\n        $ python setup.py install && python -c "import torch"\n\n    This error can generally be solved using the `develop` workflow\n        $ python setup.py develop && python -c "import torch"  # This should succeed\n    or by running Python from a different directory.')

**Comment by NullSenseStudio** [comment]
That folder gets created when you import the model weights in the addon preferences.

Looks like the generate operator isn't checking for that and prompting to finish setup like it used to.

**Comment by TheEhTeam** [comment]
Read prefs: C:\Users\toada\AppData\Roaming\Blender Foundation\Blender\3.3\config\userpref.blend
Reloading external rigs...
Reloading external metarigs...
cc_blender_tools_updater updater verbose is enabled
cc_blender_tools_updater Updater: Read in JSON settings from file
NOTE: Redirects are currently not supported in Windows or MacOs.
Traceback (most recent call last):
  File "C:\Users\toada\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\generator_process.py", line 373, in main
    generator.load_model()
  File "C:\Users\toada\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\stable_diffusion\ldm\generate.py", line 697, in load_model
    model = self._load_model_from_config(self.config, self.weights)
  File "C:\Users\toada\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\stable_diffusion\ldm\generate.py", line 833, in _load_model_from_config
    with open(weights,'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\toada\\AppData\\Roaming\\Blender Foundation\\Blender\\3.3\\scripts\\addons\\dream_textures\\stable_diffusion/models/ldm/stable-diffusion-v1/model.ckpt'

Error: FileNotFoundError(2, 'No such file or directory')

**Comment by TheEhTeam** [comment]
> That folder gets created when you import the model weights in the addon preferences.
> 
> Looks like the generate operator isn't checking for that and prompting to finish setup like it used to.

You are correct. Downloaded and imported weights and my issue is resolved thank you.

**Comment by gregcont** [comment]
> This is my problem from the Console
> 
> 
> 
> 
> 
> Read prefs: C:\Users\xxxxx\AppData\Roaming\Blender Foundation\Blender\3.0\config\userpref.blend
> 
> Traceback (most recent call last):
> 
>   File "C:\Users\xxxxx\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\dream_textures\generator_process.py", line 240, in main
> 
>     from stable_diffusion.ldm.generate import Generate
> 
>   File "C:\Users\xxxxx\AppData\Roaming\Blender 
> 
> Foundation\Blender\3.0\scripts\addons\dream_textures\stable_diffusion\ldm\generate.py", line 7, in <module>
> 
>     import torch
> 
>   File "C:\Users\xxxxx\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\dream_textures\.python_dependencies\torch\__init__.py", line 216, in <module>
> 
>     raise ImportError(textwrap.dedent('''
> 
> ImportError: Failed to load PyTorch C extensions:
> 
>     It appears that PyTorch has loaded the `torch/_C` folder
> 
>     of the PyTorch repository rather than the C extensions which
> 
>     are expected in the `torch._C` namespace. This can occur when
> 
>     using the `install` workflow. e.g.
> 
>         $ python setup.py install && python -c "import torch"
> 
> 
> 
>     This error can generally be solved using the `develop` workflow
> 
>         $ python setup.py develop && python -c "import torch"  # This should succeed
> 
>     or by running Python from a different directory.
> 
> 
> 
> Error: ImportError('Failed to load PyTorch C extensions:\n    It appears that PyTorch has loaded the `torch/_C` folder\n    of the PyTorch repository rather than the C extensions which\n    are expected in the `torch._C` namespace. This can occur when\n    using the `install` workflow. e.g.\n        $ python setup.py install && python -c "import torch"\n\n    This error can generally be solved using the `develop` workflow\n        $ python setup.py develop && python -c "import torch"  # This should succeed\n    or by running Python from a different directory.')

Do I have to reinstall?

**Comment by NullSenseStudio** [comment]
@gregcont Your issue is unrelated to the one you're posting under. See #184 instead.

**Comment by gregcont** [comment]
@NullSenseStudio  Got it, thanks
