### ISSUE TITLE
In the addon i do not have troubleshooting section

### ISSUE THREAD

**Issue by aanthosh15** [carson-katri/dream-textures#296]
**Is this a known issue?**
Check the troubleshooting section of the addon before reporting a new issue. Also [search for the error](https://github.com/carson-katri/dream-textures/issues?q=is%3Aissue) first.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
- OS
  - [x] Windows
  - [ ] macOS
  - [ ] Other
- GPU
  - [x] NVIDIA
  - [ ] NVIDIA 16*XX*
  - [ ] Apple Silicon
  - [ ] AMD
- Addon Version
  - Latest

**Additional context**

**Comment by NullSenseStudio** [comment]
The troubleshooting section was removed due to its information being outdated and was leading to users misinterpreting it as problems that they didn't actually have.

**Comment by carson-katri** [comment]
Just updated the issue template to remove references to the troubleshooting section.
