### ISSUE TITLE
When clicking Generate it start downloading clip, if the internet is off it goes " error closing unexpectedly "

### ISSUE THREAD

**Issue by aanthosh15** [carson-katri/dream-textures#297]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by carson-katri** [comment]
Please use the issue template in the future so we can collect all of the necessary information. You need internet to when your first run it. So make sure you have a connection
