### ISSUE TITLE
Installation: Torch Dependency Version Conflict

### ISSUE THREAD

**Issue by don1138** [carson-katri/dream-textures#3]
# Add-on, Application and OS versions

Dream Textures 0.0.3
Blender 3.3
Mac OS 10.15.7

# Describe the bug

When installing dependencies, I get an error message that different packages require different specific versions of **Torch**.

**Kornia** requires a later version, while **Torchvision** requires an earlier one.

I changed line 14 of `dream_textures/stable_diffusion/requirements.txt` from `torch==1.12.1` to `torch>=1.12.1`, but same error.

# How to Reproduce

On Mac with same specs, install **Dream Textures**, then in preferences panel click `Install dependencies`.

# Error message

```
ERROR: Cannot install -r /Users/***/Library/Application Support/Blender/3.3/scripts/addons/dream_textures/stable_diffusion/requirements.txt (line 14), -r /Users/***/Library/Application Support/Blender/3.3/scripts/addons/dream_textures/stable_diffusion/requirements.txt (line 6) and torch==1.12.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested torch==1.12.1
    kornia 0.6.0 depends on torch>=1.8.1
    torchvision 0.12.0 depends on torch==1.11.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

# Screenshots

n/a

**Comment by carson-katri** [comment]
Can you try changing the torchvision requirement to 1.13.1 and leaving the torch requirement the same?

**Comment by don1138** [comment]
That did the trick -- Thanks!

**Comment by zuksoon** [comment]
A similar topic so I ask for help here. 
![errorDream](https://user-images.githubusercontent.com/58657263/191569110-ace71392-3e68-4c3f-a352-cd9b7775694d.jpg)

**Comment by carson-katri** [comment]
@zuksoon Look at the windows installation notes in the readme:
> Note for Windows users - If you get an error when installing dependencies that looks similar to the one described https://github.com/carson-katri/dream-textures/issues/13, your dependency file paths might be too long (can't be longer than 256 characters). You can solve it by telling Windows to allow long file paths in the registry:
Open up the Window registry (Start > Run > regedit)
Navigate to HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem
Set LongPathsEnabled to 1

**Comment by zuksoon** [comment]
Thanks, will do it now and update if this fix it :)
