### ISSUE TITLE
Can this work for Mac with Non Silicon 

### ISSUE THREAD

**Issue by enzyme69** [carson-katri/dream-textures#30]
Since my M1 8GB is a bit slow, I was wondering if it would run faster with my older MacBookPro with specs below:

<img width="249" alt="Screenshot 2022-09-19 at 12 42 22 pm" src="https://user-images.githubusercontent.com/3952687/190942067-d814ec0e-38fb-47ef-8ec4-a97e3e9073ae.png">

MacBook Pro
Processor 2.8 GHz Quad-Core
Intel Core i7
Graphics Intel HD Graphics
630 1536 MB
Memory 16 GB 2133 MHz
LPDDR3
Startup Disk Macintosh HD

**Comment by adamthuss** [comment]
Also interested in this one - I'm running a higher end MBP but not running Apple Silicon. Any chance there's an install sequence that would allow for Blender on Mac without Apple Silicon?

Thanks! Plugin looks awesome.

<img width="261" alt="Screen Shot 2022-09-19 at 12 31 01 PM" src="https://user-images.githubusercontent.com/112978878/191100123-ee655968-19b8-49d0-9931-45698d0e87b4.png">

**Comment by carson-katri** [comment]
It might be possible but it won’t be able to use the GPU
