### ISSUE TITLE
Feature Request - Autosave for generated images

### ISSUE THREAD

**Issue by EddieVec** [carson-katri/dream-textures#300]
**Is your feature request related to a problem? Please describe.**
Having the option to save all files out and review them more closely at a later date.

**Describe the solution you'd like**
A check box that enables autosave which reveals a text box for the destination directory, if ticked, once an image is generated it's saved to that path as <seed>.png
(Bonus - An option to enter a name for the image, which can then be iterated over by version, ie. Rabbit001.png, Rabbit002.png)
Please!

**Describe alternatives you've considered**
Hand writing a script to run at the end of a session, simply saving the .blend file and having to move through the images three clicks at a time, or getting good at saving as each time an image is generated. All are clunky.

**Additional context**
N/A

**Comment by sjonsjine** [comment]
Save all files out to destination directory, that's what I was looking for!

**Comment by knekke** [comment]
That would be awesome!
