### ISSUE TITLE
Error finding file for dependencies

### ISSUE THREAD

**Issue by ScottRowley2** [carson-katri/dream-textures#304]
When installing the dependencies on Windows 11 i come across and error, "system cannot find the file specified" - "C:\Users\*user*\AppData\Local\Temp\pip-install-9iz9aqjz\clip_8c992ab2db9f4547902d0d2debfaa7b9
then a warning for PIP version being out of date

Now sure how to reproduce this, all I have done is install the addon in blender as an admin and then click install dependencies.

![image](https://user-images.githubusercontent.com/115724748/195636923-69ef647e-17b7-4880-b9db-1321e82f6567.png)

- OS
  - [x] Windows
  - [ ] macOS
  - [ ] Other
- GPU
  - [x] NVIDIA
  - [ ] NVIDIA 16*XX*
  - [ ] Apple Silicon
  - [ ] AMD
- Addon Version
  - Latest

**Comment by carson-katri** [comment]
You do not need to install dependencies in version 0.0.7.
