### ISSUE TITLE
Failed to load PyTorch c extensions

### ISSUE THREAD

**Issue by ScottRowley2** [carson-katri/dream-textures#305]
Not entirely sure what the issue is, or how to fix it
when running a generation it give the error 'failed to load PyTorch.

![image](https://user-images.githubusercontent.com/115724748/195661673-f213461d-5fe6-4a87-a91c-e646d9f9cf75.png)

- OS
  - [x] Windows
  - [ ] macOS
  - [ ] Other
- GPU
  - [x] NVIDIA
  - [ ] NVIDIA 16*XX*
  - [ ] Apple Silicon
  - [ ] AMD
- Addon Version
  - Latest

**Comment by Angeldawdw** [comment]
Did you find a solution? I have the same

**Comment by ScottRowley2** [comment]
@Angeldawdw no solution yet

**Comment by NullSenseStudio** [comment]
Duplicate of #184
