### ISSUE TITLE
Speed and Progress M1 iMac 8GB

### ISSUE THREAD

**Issue by enzyme69** [carson-katri/dream-textures#307]
Updating my experience with Dream Textures with M1 8GB iMac, not sure if tensorflow GPU is being used. 

So far the fastest is still using DiffusionBee at 3-4 minutes per image generation, at 50 steps?

I am still hoping for speed improvement with Dream Textures, but so far I think it's still a bit slow. Probably at around 10 minutes per image generation as I am watching the progress step by step "Show Steps".

However, would be nice to see log of processing a bit clearer before and after a process generation of image is completed?

Like if I use stable diffusion webUI, at least it's showing the progress in the terminal, maybe prediction on how long it might take?

**Comment by enzyme69** [comment]
Also there might be leaked memory:
```
/Applications/BLENDER_34/Blender.app/Contents/Resources/3.4/python/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
/Applications/BLENDER_34/Blender.app/Contents/Resources/3.4/python/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked shared_memory objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

**Comment by carson-katri** [comment]
Are you using 0.0.7? There is a progress bar showing the progress. Also please do not try to benchmark with show steps enabled, it will slow it down significantly.

**Comment by enzyme69** [comment]
I am using latest 0.0.7, not seeing progress bar on Terminal. 

UPDATE: Oh okey, I can see progress bar in the Blender UI even with "Show Steps" turned off. Okey no problem then.

Just I feel that maybe the time the process will complete / extra log information could be helpful.

**Comment by enzyme69** [comment]
It might just be that "Loading Model" is also taking some times from the processing. 

Feature request:
- Not loading model each time
- Ability to custom path model and replace it on the go

**Comment by carson-katri** [comment]
If you keep precision on “Automatic” it will only have to load the model the first time.

**Comment by enzyme69** [comment]
Yes, it's "Automatic" by default. In my case, the model seems to reload each time I hit generate. But is it because I cancelled a progress previously? Hmm...

**Comment by carson-katri** [comment]
Yes, that would cause it to need a reload

**Comment by enzyme69** [comment]
Is "Half Precision" means faster? I wonder if I could really use 256 x 256, I don't mind smaller just faster.

**Comment by enzyme69** [comment]
Verdict: 4-5 minutes at 25 steps. But this is with model loading for a minute.

**Comment by enzyme69** [comment]
okey now it seems like the model did load once and progress already started.

3-4 minutes is possible, I guess.

The only one thing I "worried" now is the error message popping out:
```
/Applications/BLENDER_34/Blender.app/Contents/Resources/3.4/python/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

```

**Comment by enzyme69** [comment]
Final Speed verdict 4 minutes on iMac M1 8GB. I guess it cannot go any faster. 

It's defaulting to "Texture" by the way and I do get some kind of Material look, which is unsual. Would be nice if we see the whole prompt on the terminal log.

![alpaca_3125103751](https://user-images.githubusercontent.com/3952687/195719951-ec69761d-00be-4f55-a57e-0bde8fea0242.png)

**Comment by carson-katri** [comment]
If you click on the history entry, there is a text field that shows the full prompt for you to copy for use in other tools.

**Comment by carson-katri** [comment]
The main way it could get faster is through updates to PyTorch. Currently they do not support all operations on M1 GPUs, so those unsupported ones run on the CPU, slowing it down.

**Comment by enzyme69** [comment]
Ok thanks for explanation and extra info.

I guess the next feature request list would be:
- batch AI job
- maybe animation?

cheers~

**Comment by carson-katri** [comment]
Check out the render pass for animations: https://github.com/carson-katri/dream-textures/blob/main/docs/RENDER_PASS.md
