### ISSUE TITLE
generting plain green images.

### ISSUE THREAD

**Issue by Hadidaadismake** [carson-katri/dream-textures#308]
1650 gpu
addon version 0.0.7
settings. 
500x500p
25 steps 
half precision. (only option that does anything other than b*tch about vram)
![aedfgaergaerga](https://user-images.githubusercontent.com/114274701/195793357-beca1d5a-e0b0-41ad-8a18-99d785fc8bfc.png)

**Comment by carson-katri** [comment]
The 1650 does not support half precision. This is a hardware limitation. Leave the option as “Automatic” or “Full Precision”.

**Comment by Hadidaadismake** [comment]
@carson-katri Add a disclaimer that the 16 series doesn't work with this then. I wasted 2 fucking weeks on trying to make this shit work. hell. you could have told me first time around. fuck

**Comment by Hadidaadismake** [comment]
dude why did u delete my comment

**Comment by Hadidaadismake** [comment]
if the only option is full perception and it doesn't work then this addon doesn't fucking work

**Comment by Hadidaadismake** [comment]
add a disclaimer that the 16 series card doesn't work with this addon

**Comment by Hadidaadismake** [comment]
@carson-katri

**Comment by carson-katri** [comment]
> add a disclaimer that the 16 series card doesn't work with this addon

I will look into a good way to warn for this 👍

**Comment by Hadidaadismake** [comment]
thank you.
