### ISSUE TITLE
Render Pass: Blender and Windows Crash Due to VRAM Management

### ISSUE THREAD

**Issue by jeffmorice** [carson-katri/dream-textures#312]
**Is this a known issue?**
Searched, but could not find anything related to VRAM management or blue screens.

**Describe the bug**
Render Pass VRAM management causes crashes of Blender and Windows. Rendering multiple frames successively causes dedicated GPU memory usage to balloon, as visible in Task Manager.

**To Reproduce**
1. Open a blend file (one with rigged animation preferred).
2. Follow [instructions](https://github.com/carson-katri/dream-textures/blob/main/docs/RENDER_PASS.md) to enable Render Pass for Dream Textures.
3.  Go to Properties > View Layer Properties tab > Passes > Data and ensure the Z pass is unchecked. Otherwise Dream pass will not take place and render will come out transparent.
4. Go to Properties > Render Properties tab > Performance > Memory > Tile Size and ensure Tile Size is greater than or equal to render resolution (ex: 512). Otherwise render will not be successful and blender will crash.
5. Go to Properties > View Layer Properties tab and Ensure Device is set to GPU Compute.
6. Set frame range to 5 or so frames (more frames may result in a blue screen). My GPU has 8 GB of VRAM. If yours is lower, you may prefer to set the range lower to avoid a blue screen.
7. Open Task Manager. Go to Performance tab and select GPU. See "Dedicated GPU memory usage" graph.
8. Ctrl + F12 to render animation.
9. Go back to Task Manager and watch VRAM balloon. Blender may crash. Windows may encounter a blue screen.

**Expected behavior**
VRAM dump after each frame completed.

**Screenshots**
The first 2 screenshots were captured by following the steps above, resulting in Blender crashing. The 3rd screenshot is from the earlier blue screen.
![DreamVramCrash_BlenderAndTaskManager_PreCrash](https://user-images.githubusercontent.com/43052910/195953972-8572a81c-874c-4475-84ac-4afe2b190165.png)
![DreamVramCrash_TaskManager_PostCrash](https://user-images.githubusercontent.com/43052910/195953973-0d0eb4ba-df2a-418f-b85b-ce1298567e96.png)
![DreamVramCrash_BlueScreen](https://user-images.githubusercontent.com/43052910/195954567-d33b574b-3982-45f4-bbb1-f4457e58bd95.jpg)

**System (please complete the following information):**
- OS
  - [x] Windows
  - [ ] macOS
  - [ ] Other
- GPU
  - [x] NVIDIA GTX 1070 8GB
  - [ ] NVIDIA 16*XX*
  - [ ] Apple Silicon
  - [ ] AMD
- Addon Version
  - 0.0.7

**Additional context**
First attempt resulted in Blender crashing. Having experienced this before, I simply opened the file back up and started rendering where I left off. On the second attempt, I watched VRAM balloon and max out in Task Manager, before receiving a Windows Blue screen. Following restart, I reproduced the issue according to the steps above.

I checked my settings to ensure Persistent Data was not turned on (Go to Properties > Render Properties tab > Performance > Final Render > Persistent Data) and it was unchecked.

Loving the addon so far. Please keep up the great work!

**Comment by carson-katri** [comment]
Thanks for the detailed report. Does this also occur when you use CPU for cycles rendering?

**Comment by jeffmorice** [comment]
Happy to contribute to this awesome project! And thanks for your speedy reply. Great question. I've repeated my test, this time with CPU and with successive single frame renders (F12). I saw the same ballooning VRAM behavior.

With this technique of single frame renders, you can clearly see the bumps in VRAM (see attached screenshot) associated with each render. Some data is being dumped after each frame, but you can also see some data is accumulating or "leaking" between each frame.

Forgive my loose use of terminology as I describe what I'm seeing in this graph. Watching the graph during the render and Dream process, it appears during initial rendering Blender consumes less than 20% of my 8GB of VRAM. Before executing the Dream process, Blender loads the model and VRAM usage increases to between 40% and 50%. I recognize the utility of caching the model in VRAM. I would expect the usage to be reduced back to around 50% or 60% between each frame. By eyeballing the attached graph, it looks like the amount of the memory leak is less than 10% of 8GB per frame or an estimated 8%, equivalent to 0.64 GB.

I did some napkin math based on my current understanding of this addon. My output files are uncompressed and their final size on disk is 772 KB. My strength and steps combo is 0.4 and 25, resulting in 10 steps. Multiplying the final uncompressed image size by 10 doesn't come close to 0.64 GB. So something else is going on.

![DreamVramCrash_BlenderAndTaskManager_SingleFrames_CPU](https://user-images.githubusercontent.com/43052910/196002628-5de9bbee-e766-4d2a-a5f0-2ebb34af964e.png)

I also repeated the test using single frame rendering for GPU. As might be expected, GPU memory fills up much more quickly in around 3 frames, as opposed to around 5 frames with CPU.

![DreamVramCrash_BlenderAndTaskManager_SingleFrames_GPU](https://user-images.githubusercontent.com/43052910/196002632-d054517c-cb0a-42bd-acc0-52c21c4fe4f1.png)

Also, as expected, my dedicated GPU memory usage does return to normal upon quitting Blender in all cases. I hope that's useful.

**Comment by NullSenseStudio** [comment]
I haven't been able to replicate this bug while using CPU rendering.

When using GPU however I notice that Blender is the main one allocating more and more VRAM while the addon's subprocess is still using roughly the same amount as the first run, and killing the subprocess between renders does not help with the issue. So I believe the issue is with the render pass preventing cycles from releasing its VRAM.

First render:
![image](https://user-images.githubusercontent.com/47096043/196005772-f3a26589-9e4b-45b0-8121-f043dbfefea8.png)

Later render:
![image](https://user-images.githubusercontent.com/47096043/196005785-b8755cb1-cbae-448c-9f8c-fd70ca3551f5.png)

**Comment by jeffmorice** [comment]
Hi @NullSenseStudio! I can confirm what you saw in your first and last GPU renders, by looking at Dedicated GPU Memory, under the Details tab.

![image](https://user-images.githubusercontent.com/43052910/196061387-0157bddc-8665-459b-a3c6-cba8e48e6f6e.png)
![image](https://user-images.githubusercontent.com/43052910/196061409-c9f230eb-90ce-465a-8e82-a853d17927c1.png)

I believe the same behavior is occurring with CPU rendering, but at a slower rate. See below:

![image](https://user-images.githubusercontent.com/43052910/196061819-68d916f9-5de7-4fb8-b405-c1ab748c29b1.png)
![image](https://user-images.githubusercontent.com/43052910/196061842-6623e2c5-1871-4f01-a688-c5cd1a68bcad.png)
