### ISSUE TITLE
Init Image numerical strength is inverted

### ISSUE THREAD

**Issue by nyu777** [carson-katri/dream-textures#314]
Init Image numerical intensities are all reversed.

・When Fit to width/heigt is enabled, the size of the generated image is output in the size specified in the "Size" field, and when disabled, the size of the original image is output.

・Lowering the Strength value increases the influence of the original image, while raising the value decreases the influence of the original image.

・When "Fit to width/heigt" is enabled, the influence of the original image on the generated image is reduced.

- OS
Windows
- GPU
NVIDIA　3080
- Addon Version
0.07

**Comment by carson-katri** [comment]
The field should probably be renamed to “Noise Strength” or “Noise Ratio”

**Comment by nyu777** [comment]
Is this a bug? Or is it a specification?

**Comment by carson-katri** [comment]
It’s more a documentation issue than a bug.
