### ISSUE TITLE
Adding asymmetric-tiling

### ISSUE THREAD

**Issue by Ladypoly** [carson-katri/dream-textures#315]
It would be cool If you could implement asymmetric-tiling from here:
https://github.com/tjm35/asymmetric-tiling-sd-webui/

**Comment by carson-katri** [comment]
This looks cool,I may try to implement this for upstream Invoke AI.

**Comment by carson-katri** [comment]
I've opened a PR to InvokeAI to implement this, if that is merged I can get this feature into the addon easily: https://github.com/invoke-ai/InvokeAI/pull/1132
