### ISSUE TITLE
Inpainting brush is offset incorrectly

### ISSUE THREAD

**Issue by enzyme69** [carson-katri/dream-textures#316]
**Is this a known issue?**
Before reporting an error [search for an existing issue](https://github.com/carson-katri/dream-textures/issues?q=is%3Aissue) first.

**Describe the bug**
When using inpaint brush to the image, the brush is dislocated way far like in incorrect position...

**To Reproduce**
Try producing and image and then use inpaint brush tool. The cursor is far above where the mouse is supposed to be.

**Expected behavior**
The position and brush and cursor should be the same?

**Screenshots**

**System (please complete the following information):**
- OS
  - [ ] Windows
  - [x] macOS
  - [ ] Other
- GPU
  - [] NVIDIA
  - [ ] NVIDIA 16*XX*
  - [x ] Apple Silicon
  - [ ] AMD
- Addon Version
  - Latest

**Additional context**

**Comment by enzyme69** [comment]
ALSO: I just realized inpainting here is actually to fix seams in textures? I thought it could be used as "initial image"

**Comment by carson-katri** [comment]
That’s just one idea for a way to use it. You can use it for any inpainting task you’d like.

**Comment by enzyme69** [comment]
Currently testing this "inpaint" and no matter how I erase an area and processing it, it only fills up the seam. 

I have initial image of a forest scene. I did erase some area. And I did specify additional info in the prompt "a giant ogre standing in the forest", and somewhat Dream Texture only fills up the area and leaving me with a forest.

**Comment by enzyme69** [comment]
But that besides the issue in latest Blender 3.4 alpha and how the brush is offset vertically like 300-400 pixels.

<img width="1385" alt="Screenshot 2022-10-16 at 11 42 24 am" src="https://user-images.githubusercontent.com/3952687/196012608-586443cb-b9d2-42c8-9da6-db72fa980870.png">

**Comment by carson-katri** [comment]
You probably want to add some noise in the area to get something new, before using the erase alpha brush.

**Comment by enzyme69** [comment]
Ok roger that... I thought "erase area" will be replaced with new dream.

Uploading Screen Recording 2022-10-16 at 11.43.30 am.mov…

**Comment by enzyme69** [comment]
https://user-images.githubusercontent.com/3952687/196012650-d4acd57e-558a-4876-a168-c52f768874f1.mov
