### ISSUE TITLE
Installing Dependencies stops after successfully preloading CLIP model

### ISSUE THREAD

**Issue by Axel3DM** [carson-katri/dream-textures#32]
Installing dependencies works until after it preloads CLIP model, it just says "...success" and will not progress no matter how long I wait. I can't close the terminal window and if I close blender then the texture doesn't generate after pressing OK in the panel. I've attached a screenshot of the blender terminal at the point where it gets stuck at below.
![Screenshot (6)](https://user-images.githubusercontent.com/113876997/190951690-485ec0dd-206e-4f68-abc7-ab503ea43663.png)

**Comment by gattomanzo** [comment]
same here

**Comment by carson-katri** [comment]
It doesn’t close the console window when it’s done. When it says success, it must have finished the installation.
