### ISSUE TITLE
Is it possible to implement AI image extension by this addon？

### ISSUE THREAD

**Issue by BUGProtectionAssociation** [carson-katri/dream-textures#320]
When someone finds a picture very good, but using tiling will cause the image to be duplicated. So, is it possible to generate new parts based on a part of the image that has already been generated?
![Clip_20221016_220355](https://user-images.githubusercontent.com/65578116/196039980-8f2dd2aa-0ca1-40e9-ab75-b10156620e65.png)

**Comment by carson-katri** [comment]
Seems like you are referring to outpainting? If so, #232 is open to track that.

**Comment by carson-katri** [comment]
Outpainting has been implemented in 0.0.8.
