### ISSUE TITLE
Can't install to Blender: Specify --upgrade to force replacement.

### ISSUE THREAD

**Issue by Ubuntuuuuu** [carson-katri/dream-textures#321]
WARNING: Target directory C:\Users\****\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\attrs-22.1.0.dist-info already exists. **Specify --upgrade to force replacement.**

Is there any way to do that?

**Comment by carson-katri** [comment]
Are you trying to install dependencies? That is not required since version 0.0.6, so once the addon is installed you’re good to go. Also if you’re trying to upgrade the version, make sure you remove the old one from Blender first.

**Comment by Ubuntuuuuu** [comment]
Yes I tried. Thanks a lot, now it works again! I did not noticed that it is in the sidebar nowadays either! Very awesome addon. Thank to You, God Bless!
