### ISSUE TITLE
Mac M1 Max: Generating textures works, but render pass does not

### ISSUE THREAD

**Issue by Even572** [carson-katri/dream-textures#326]
When I try to render an image and use the Dream Textures as a render pass, nothing shows up in the render pass (not black, but blank/null image).
However it works generating a texture inside the image editor. So the process of generating itself seems to work.

Specs/versions: Mac M1 Max, 0.0.7 dream textures, 3.3.0 Blender.

**Comment by carson-katri** [comment]
v0.0.7 has some quirks here. Make sure you don’t have the “Z” pass enabled

**Comment by Even572** [comment]
That worked! Thank you
