### ISSUE TITLE
Blender can't find the zipper 

### ISSUE THREAD

**Issue by Lelovic** [carson-katri/dream-textures#33]
Hello everyone!
I can't install the add-on, blender doesn't detect the zipper, I tried a manual installation but it doesn't work, any ideas?

Thanks everyone! i can't wait to be able to use this add-on for the youtube channel!

**Comment by carson-katri** [comment]
Hi, unfortunately I’m not sure what you mean by the zipper. Can you provide the error message you see?

**Comment by Lelovic** [comment]
Hi! 
there is no error, Blender cannot find the zip that contains the add-on, it is impossible for me to install it

**Comment by Lelovic** [comment]
Exactly! I tried with multiple versions of Blender but nothing, it doesn't want to work .... I also tried to create a custom zip, I also tried with the manual installation, I don't know, I'll try another method!

**Comment by carson-katri** [comment]
Odd, I’ve never seen that before. What platform are you on, and where do you have the zip file saved?

**Comment by Lelovic** [comment]
I'm on windows 10 and I just downloaded the zip and locate it inside my external drive (as always) but it's kinda invisible or something like that by blender. 
Do you think that the problem it's the eternal SSD? Idk

**Comment by carson-katri** [comment]
I’m not sure, but you could try moving it to a different drive and see if it works. This sounds like a Blender bug though.

**Comment by carson-katri** [comment]
Closing this as stale, due to many changes in the latest updates.
