### ISSUE TITLE
ReferenceError: StructRNA of type CyclesRender has been removed

### ISSUE THREAD

**Issue by Anyeos** [carson-katri/dream-textures#330]
**Describe the bug**
```
Exception ignored in: <function CyclesRender.__del__ at 0x7f4f80e92440>
Traceback (most recent call last):
  File "/Compartidos/DisGrafico/Blender/blender-3.3.1/bin/3.3/scripts/addons/cycles/__init__.py", line 54, in __del__
    engine.free(self)
  File "/Compartidos/DisGrafico/Blender/blender-3.3.1/bin/3.3/scripts/addons/cycles/engine.py", line 79, in free
    if hasattr(engine, "session"):
ReferenceError: StructRNA of type CyclesRender has been removed
```

**To Reproduce**
Activate cycles "Dream Textures" feature.
Render something (F12).
Render newly and the error starts to happen.

**System (please complete the following information):**
- OS
  - [ ] Windows
  - [ ] macOS
  - [x] Other
- GPU
  - [x] NVIDIA
  - [ ] NVIDIA 16*XX*
  - [ ] Apple Silicon
  - [ ] AMD
- Addon Version
  - Latest

**Additional context**
With or without this error the cycles Dream Textures feature does not gives output at all (I tested a lot of options without sucess). But when I use the "Render Result" as Init Image on the panel it works when I press "Generate". Of course I don't want to manually render each frame to make a video apply dream textures.

**Note**
I tested to be sure that it is not a cycles itself error. It appears that dream textures deletes StructRNA and Blender Cycles does not expect it to be deleted.

**Comment by carson-katri** [comment]
Make sure you disable the Z pass for this version of the render pass to work.
