### ISSUE TITLE
I'm getting an error ( Error : Process closed unexpectedly ) after preloading 'kornia' requirements 

### ISSUE THREAD

**Issue by lucianmoricz** [carson-katri/dream-textures#331]
I'm getting an error ( Error : Process closed unexpectedly ) after preloading 'kornia' requirements 
I also tried to delete huggingface and torch folders from .cache, but nothing changed.

https://user-images.githubusercontent.com/92894447/196422353-7896699e-2d87-4af6-aa2f-a33ac9e23578.mp4

![image](https://user-images.githubusercontent.com/92894447/196422676-9a12237c-f8e3-44e5-afae-2e787dbbcbdf.png)

- OS
  - [x] Windows
  - [ ] macOS
  - [ ] Other
- GPU
  - [x] NVIDIA RTX 3060
  
- Addon Version
  - Latest

**Comment by carson-katri** [comment]
Please open “Window” > “Toggle System Console” for a more detailed error message.

**Comment by lucianmoricz** [comment]
Here you go!
![image](https://user-images.githubusercontent.com/92894447/196430121-16ec3369-849c-42b0-8b7a-c7f83e43924b.png)

**Comment by carson-katri** [comment]
A user on Discord also faced this issue, but it was odd because the only mentions of it I could find were due to some certificates required in Serbia being badly formed. I believe as a workaround they had a coworker send them the files it tries to download and placed them manually.

You may instead try looking into fixing the CA Root certificates on your machine. It may also be possible for me to disable certificate checks, but I’m not 100% sure.

**Comment by carson-katri** [comment]
I’m not sure if you’re comfortable doing this, but you could try applying these changes to ssl.py in Blender’s installation: https://github.com/python/cpython/pull/91740/files#diff-f6439be9c66350dde4c35dbeea0352c96cc970ba12b0478f6ae36f10725bd8c5

**Comment by lucianmoricz** [comment]
I changed it but and I'm getting the same error
![image](https://user-images.githubusercontent.com/92894447/196439923-0a21efe4-c449-4439-9708-ae8d5748105b.png)

**Comment by devviktoria** [comment]
I had similar issues under Ubuntu 22.04. But I had downloaded the checkpoint_liberty_with_aug.pth file from https://github.com/DagnyT/hardnet/blob/master/pretrained/train_liberty_with_aug/checkpoint_liberty_with_aug.pth and putted into the cache directory it printed in the error message. Restarted Blender started to generate a new image: it downloaded additional stuff and after that I was able to generate images.
