### ISSUE TITLE
Why is it so slow ?

### ISSUE THREAD

**Issue by nicoportorico** [carson-katri/dream-textures#337]
Hi there ,
Great Job on this ... I love your initiative .

Whenever i use the add on , it takes reaaaaally long time before getting the results (up to 15 minutes for seamless 512*512 image).
A friend of mine uses the same add on but it takes less than a minute.

My Specs : Ryzen 7 1700x  , 32Gb Ram 2400Mhz , NVIDIA P2000

Friend Specs : Ryzen 5 3600x , 16Gb Ram 3200Mhz , NVIDIA RTX 2060

Is there any issue on my system or is that difference so significant  ?

I'd love to read from other users as well ! 

Thanks

**Comment by carson-katri** [comment]
The 2060 is significantly faster. You may also want to try running with “Show Steps” enabled.

**Comment by nicoportorico** [comment]
Cool with that but how come task maneger shows no usage of GPU while generating ? 
Unchecking show Steps didn t help :) 
Thanks anyway :)

**Comment by carson-katri** [comment]
I think there is an option in task manager to show CUDA usage specifically, make sure it’s switched to that.
