### ISSUE TITLE
Unable to activate 0.0.7

### ISSUE THREAD

**Issue by GamePIN741** [carson-katri/dream-textures#338]
I don't think this has been seen, mostly because i'm stupid

Ok, so I'm trying to install 0.0.7 and whenever I try and enable the addon, I get this error message
![image](https://user-images.githubusercontent.com/116318593/197085274-c8fd21c1-bb38-40bd-9ad1-0487cdf18b52.png)
so, I didn't actually read all of the directions before I tried to install the new update, so I still had 0.0.5 installed and I don't know how to fix my installation, so if anyone knows what is happening I would love some help. I've tried to use older versions of blender, but no luck. I also want to use the most recent version of blender, and all the alphas i've downloaded are still wrecked (btw im using daily builds for new features, but i've tried normal 3.3 and its still broken
windows 10 
3060ti
![Screenshot 2022-10-20 215202](https://user-images.githubusercontent.com/116318593/197092543-278b1a86-ecc6-4cfe-8f30-b47802cd4c75.png)
![Screenshot 2022-10-20 215236](https://user-images.githubusercontent.com/116318593/197092595-34c9e6c3-3a50-4398-9e3b-2eabf6bd53f7.png)

**Comment by carson-katri** [comment]
When updating, make sure you:
1. Remove the old addon
2. Restart Blender
3. Install the new addon

**Comment by GamePIN741** [comment]
So, I tried that solution, and got the same error message. thanks, always good to try the simple solutions

**Comment by carson-katri** [comment]
Perhaps try unzipping manually, blender may be missing some files (perhaps low on storage space or something). It goes in `C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons`, decompress that nested zip and it’ll create a folder `dream_textures`. Make sure you delete the old folder first too

**Comment by GamePIN741** [comment]
Whooo!! it worked, thanks, never would have found that on my own!
