### ISSUE TITLE
Installing dependencies on linux, blender snap version

### ISSUE THREAD

**Issue by Nudel** [carson-katri/dream-textures#34]
I get the following error when clicking the install dependencies (Linux (AMD)) on ubuntu 20.04, Radeon RX 5500

```
Python: Traceback (most recent call last):
  File "/home/peter/.config/blender/3.3/scripts/addons/dream_textures/operators/install_dependencies.py", line 141, in execute
    install_and_import_requirements(requirements_txt=context.scene.dream_textures_requirements_path)
  File "/home/peter/.config/blender/3.3/scripts/addons/dream_textures/operators/install_dependencies.py", line 115, in install_and_import_requirements
    python_devel_tgz.extractall(path=python_include_dir, members=members(python_devel_tgz))
  File "/snap/blender/2790/3.3/python/lib/python3.10/tarfile.py", line 2040, in extractall
    self.extract(tarinfo, path, set_attrs=not tarinfo.isdir(),
  File "/snap/blender/2790/3.3/python/lib/python3.10/tarfile.py", line 2081, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name),
  File "/snap/blender/2790/3.3/python/lib/python3.10/tarfile.py", line 2154, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/snap/blender/2790/3.3/python/lib/python3.10/tarfile.py", line 2195, in makefile
    with bltn_open(targetpath, "wb") as target:
OSError: [Errno 30] Read-only file system: '/snap/blender/2790/3.3/python/include/python3.10/pystate.h'
```

I've tried the following:

Installing the dependencies like describes in [this issue](https://github.com/carson-katri/dream-textures/issues/6). I needed to comment out "--prefer-binary" in requirements.txt to have it run though. They install fine now with requirements-lin-AMD.txt, but it is not recognized as a completed installation in blender.

I can't change the read only status of pystate.h as it is in a snap folder which is intended to be read only as far as I understand.

Any ideas?

**Comment by carson-katri** [comment]
Unfortunately, I do not have a Linux system to test on. If you install Blender to a folder with write access does it work?

**Comment by Nudel** [comment]
Downloaded blender 3.3 LTS and ran it from a folder in /home.
I now get the following error.
```
Python: Traceback (most recent call last):
  File "/home/peter/.config/blender/3.3/scripts/addons/dream_textures/operators/install_dependencies.py", line 141, in execute
    install_and_import_requirements(requirements_txt=context.scene.dream_textures_requirements_path)
  File "/home/peter/.config/blender/3.3/scripts/addons/dream_textures/operators/install_dependencies.py", line 106, in install_and_import_requirements
    python_devel_tgz = tarfile.open(python_devel_tgz_path)
NameError: name 'tarfile' is not defined
```
Is there something wrong with my python install?

**Comment by Smuzzies** [comment]
Was able to run everything from the pip requirements method. No errors reported, all dependencies downloaded and installed successfully. However, the shader menu does not display the dream tool window. Windows is working fine, but this Linux snapBlender is borked. Also extracted blender into a folder and attempted to run the dependency installation from there but got a message stating there is no pip module, pip is installed via apt. Any SNAP experts out there got ideas?

Thanks in advance.

**Comment by Smuzzies** [comment]
Tried the install on a new Ubuntu 22.04 virtual machine. Used the same method to install via pip requirements. No errors during the dependency installations. Setup model file, successful. However, still no button. Not sure what's going on. I'll continue digging.

![image](https://user-images.githubusercontent.com/110495122/191362845-3b498b4f-f069-4380-aad8-f6d0cdce563f.png)
![image](https://user-images.githubusercontent.com/110495122/191362908-74db7882-88f7-415a-ade5-8106e4fda6df.png)

**Comment by Nudel** [comment]
> Tried the install on a new Ubuntu 22.04 virtual machine. Used the same method to install via pip requirements. No errors during the dependency installations. Setup model file, successful. However, still no button. Not sure what's going on. I'll continue digging.
> 
Do you still have the "install dependencies" button available in the plugin window? In that case I don't think the plugin recognizes the dependencies are installed manually with pip. I dug around and tried to find where the flag for valid installation is set.

The closest I came is "is_install_valid" variable and the validateinstallation class in preferences.py
```
is_install_valid = None

class ValidateInstallation(bpy.types.Operator):
    bl_idname = "stable_diffusion.validate_installation"
    bl_label = "Validate Installation"
    bl_description = ("Tests importing the generator to locate a subset of errors with the installation")
    bl_options = {"REGISTER", "INTERNAL"}
```
I tried to set the variable to true but that didn't change anything, I will look closer at the code and see if I can force it to run without the validation somehow.

**Comment by carson-katri** [comment]
@Nudel The addon does not register the menu item if it cannot import the last necessary module in the requirements file: https://github.com/carson-katri/dream-textures/blob/f182511f8ef44b0dcd1af40bc7786482e27e3635/__init__.py#L69

**Comment by YAFU** [comment]
Hi.
I removed the "--prefer-binary" line from the "requirements.txt" file and then I installed dependencies with:
`python3 -m pip install -r requirements.txt`

In my distro dependencies are installed in user folder "~/.local/lib/python3.8"

Then in the file "__init__.py" I commented lines and leaving it this way:

```
#try:
        # Check if the last dependency is installed.
        #importlib.import_module("transformers")
        #set_dependencies_installed(True)
    #except ModuleNotFoundError:
        # Don't register other panels, operators etc.
        #return
```
From Blender Portable I run blender as follows:
PYTHONPATH=~/.local/lib/python3.8 ./blender --python-use-system-env

So now "Dream Textures" button appears in Shader Editor, but when I select Dream textures -> Dream textures, I get the error:
"Please complete setup in the preferences window."

I assume it is asking me to use the "Install Dependencies" button from addon preferences. But I already have the dependencies installed in "~/.local/lib/python3.8"

**Comment by carson-katri** [comment]
Add back the line: `set_dependencies_installed(True)`.

However, you should know that if the `ModuleNotFoundError` was being tripped, that means an import of the dependencies is not succeeding, so it’s still not seeing your system packages.

**Comment by YAFU** [comment]
Thanks.
I have left the file like this:
try:
        ```
# Check if the last dependency is installed.
        #importlib.import_module("transformers")
        set_dependencies_installed(True)
    except ModuleNotFoundError:
        # Don't register other panels, operators etc.
        return
```
Now I can open the menu from Dream Textures -> Dream textures
I fill the "Subject" field with something, then I click the "Ok" button but I don't get any resulting image, and indeed I get the error from the terminal:
`ModuleNotFoundError: No module named 'torch'`

But torch is installed on my system:
$ pip list | grep -i torch
pytorch-lightning           1.4.2
torch                       1.11.0
torch-fidelity              0.3.0
torchdiffeq                 0.2.3
torchmetrics                0.6.0
torchvision                 0.12.0

**Comment by carson-katri** [comment]
Blender ships with its own Python separate from your system one, so it does not know about dependencies on your global Python install. You could try adding its packages to sys.path in __init__.py, but I’m not sure exactly how this functions:
`sys.path.append([path to system packages])`

**Comment by carson-katri** [comment]
Good find. If this works for you let me know and I can setup instructions for Linux installation.

**Comment by ra100** [comment]
I've tried on linux too.
I have python 3.10 as default, but had to do this first:

opened terminal in `stable_diffusion` folder and run:
```bash
pip3 install --upgrade --force-reinstall --user -r requirements-lin-win-colab-CUDA.txt
```

that installation worked without issues

But then when running got this error
```txt
Opening in existing browser session.
INFO:torch.distributed.nn.jit.instantiator:Created a temporary directory at /tmp/tmp4ac4f_8m
INFO:torch.distributed.nn.jit.instantiator:Writing /tmp/tmp4ac4f_8m/_remote_module_non_scriptable.py
>> Loading model from /home/ra100/.config/blender/3.3/scripts/addons/dream_textures/stable_diffusion/models/ldm/stable-diffusion-v1/model.ckpt
>> Calculating sha256 hash of weights file
>> sha256 = fe4efff1e174c627256e44ec2991ba279b3816e364b49f9be2abc0b3ff3f8556 (10.60s)
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-1' coro=<DreamTexture.dream_texture() done, defined at /home/ra100/.config/blender/3.3/scripts/addons/dream_textures/operators/dream_texture.py:105> exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
  File "/home/ra100/.config/blender/3.3/scripts/addons/dream_textures/operators/dream_texture.py", line 136, in dream_texture
    generator.load_model()
  File "/home/ra100/.config/blender/3.3/scripts/addons/dream_textures/stable_diffusion/ldm/generate.py", line 457, in load_model
    model = self._load_model_from_config(self.config, self.weights)
  File "/home/ra100/.config/blender/3.3/scripts/addons/dream_textures/stable_diffusion/ldm/generate.py", line 578, in _load_model_from_config
    model = instantiate_from_config(c.model)
  File "/home/ra100/.config/blender/3.3/scripts/addons/dream_textures/stable_diffusion/ldm/util.py", line 89, in instantiate_from_config
    return get_obj_from_str(config['target'])(
  File "/home/ra100/.config/blender/3.3/scripts/addons/dream_textures/stable_diffusion/ldm/models/diffusion/ddpm.py", line 657, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File "/home/ra100/.config/blender/3.3/scripts/addons/dream_textures/stable_diffusion/ldm/models/diffusion/ddpm.py", line 768, in instantiate_cond_stage
    model = instantiate_from_config(config)
  File "/home/ra100/.config/blender/3.3/scripts/addons/dream_textures/stable_diffusion/ldm/util.py", line 89, in instantiate_from_config
    return get_obj_from_str(config['target'])(
  File "/home/ra100/.config/blender/3.3/scripts/addons/dream_textures/stable_diffusion/ldm/modules/encoders/modules.py", line 245, in __init__
    self.tokenizer = CLIPTokenizer.from_pretrained(
  File "/home/ra100/.local/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1734, in from_pretrained
    resolved_vocab_files[file_id] = cached_file(
  File "/home/ra100/.local/lib/python3.10/site-packages/transformers/utils/hub.py", line 408, in cached_file
    resolved_file = hf_hub_download(
  File "/home/ra100/.local/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1172, in hf_hub_download
    with open(ref_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ra100/.cache/huggingface/hub/models--openai--clip-vit-large-patch14/refs/main'
```

**Comment by carson-katri** [comment]
@ra100 There’s a script at `dream_textures/stable_diffusion/scripts/preload_models.py` you need to run.

**Comment by ra100** [comment]
Thanks @carson-katri, so this worked for me:

```shell
cd stable_diffusion
pip3 install --user -r requirements-lin-win-colab-CUDA.txt
python3 scripts/preload_models.py
```

I just don't have HW for it (GTX 1080 + 1060), got this crash:
```
INFO:torch.distributed.nn.jit.instantiator:Created a temporary directory at /tmp/tmp2i7dqha3
INFO:torch.distributed.nn.jit.instantiator:Writing /tmp/tmp2i7dqha3/_remote_module_non_scriptable.py
>> Loading model from /home/ra100/.config/blender/3.3/scripts/addons/dream_textures/stable_diffusion/models/ldm/stable-diffusion-v1/model.ckpt
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
>> Using half precision math. Call with --full_precision to use more accurate but VRAM-intensive full precision.
Writing: /tmp/blender.crash.txt
Segmentation fault (core dumped)
```

**Comment by Smuzzies** [comment]
That run was success. Both scripts have processed are not throwing any errors. Yet no dream texture button available. Still missing something. Unsure this will work with a snap install, being it's a read only environment. But we're a step closer.
Output from preload_models.py:
![image](https://user-images.githubusercontent.com/110495122/192029279-ca54763d-4f4d-48d6-bf5d-908d80aa3455.png)

**Comment by ra100** [comment]
@Smuzzies I have actually Blender installed via snap, I just had to install everyting in "site-packages" (`~/.local/lib/python3.10/site-packages/`) not "dist-packages" (`/usr/local/lib/python3.10/dist-packages/ `). At least for me, Blender python is expecting all required modules to be loaded from there.

**Comment by Smuzzies** [comment]
Looks like that's where all the dependencies installed via the requirements file, unless I'm missing a step somewhere. This is very encouraging to hear tho! Exciting tool thanks to Carson!

![image](https://user-images.githubusercontent.com/110495122/192033147-78bc785d-add3-4c7e-b882-1358b7e376e5.png)

**Comment by Smuzzies** [comment]
Using python 3.10.7 on the box. Not sure what blender 3.3 uses, do we all still agree they must the same major/minor?

**Comment by Smuzzies** [comment]
Did try the install button again from the blender addon menu. Complaining about ready only again. How did you get around that?

![image](https://user-images.githubusercontent.com/110495122/192035395-34e2870c-9e8c-4b79-85dd-b0c0ad650bfe.png)

**Comment by Smuzzies** [comment]
Python version 3.10.7
Blender Python version 3.10.2

**Comment by ra100** [comment]
I opened the folder with the extension, 
for you it will be `/home/vender3d/.config/blender/3.3/scripts/addons/dream_textures`
there I went to stable_diffusion folder and run these:
```bash
pip3 install --user -r requirements-lin-win-colab-CUDA.txt
python3 scripts/preload_models.py
```

the `--user` tells pip3 to install requirements to your home/<USER>/.local folder

**Comment by Smuzzies** [comment]
Yup, that's where I ran the commands from. Both 100% successful, no button. Did you use the install button from inside blender at all? or just those two commands via terminal and then the button showed up?

**Comment by ra100** [comment]
When I try the command from Blender, it throws same error as to you. So I've just ran those 2 commands above from terminal.
You can try to edit the `__init__.py` and add around line 68 `importlib.import_module("transformers")` (move it before the `try-catch` block) This way you'll see the error, why it doesn't show the button, when you run blender from terminal.

**Comment by Smuzzies** [comment]
Hmm, interesting. 
![image](https://user-images.githubusercontent.com/110495122/192040714-6345f58e-db62-40d0-81d0-5658f9dff8ae.png)

**Comment by ra100** [comment]
Can you try to run from the `stable_diffusion/src/taming-transformers`
this `python3 setup.py install --prefix ~/.local/`?

**Comment by Smuzzies** [comment]
looks ok i think
![image](https://user-images.githubusercontent.com/110495122/192041585-ff427893-497d-4d9b-b6fa-7336cd229837.png)

**Comment by carson-katri** [comment]
Have you done either of the options mentioned in Blender’s docs here: https://docs.blender.org/api/current/info_tips_and_tricks.html#bundled-python-extensions

**Comment by ra100** [comment]
I didn't try any of those, actually. It could have saved me some time :) trying to install everything to site-packages

**Comment by Smuzzies** [comment]
Kind of scared to try that as I feel like it might hose something outside of blender. I'll look for an undo method before i try that. 
PYTHONPATH=/usr/lib/python3.7 ./blender --python-use-system-env

**Comment by Smuzzies** [comment]
Oddly enough.

PYTHONPATH=/usr/lib/python3.10 /snap/bin/blender --python-use-system-env

Ran directly from terminal, blender opened up, Dream Texture button is there now and it works. You guys are magicians! Thank you so much. Dunno what that equates to as far a fix for snap users. 
![image](https://user-images.githubusercontent.com/110495122/192050004-6b5b60f6-b9b0-4dc2-a413-7b6909245e45.png)

**Comment by Smuzzies** [comment]
Not sure how to make it use that when i just run ./blender from command line. Set ENV variable vi /etc/environment file to no avail. Maybe adding it to ./bashrc?

**Comment by Smuzzies** [comment]
instead of creating the env variable since snap won't let you edit local variables, just gonna add the switch when i call up blender, thanks again everyone, hope someone is able to make a nice snap install version instruction guide LOL

**Comment by ra100** [comment]
I guess I need to find out how to clean whole env so I can try from scratch :D

**Comment by Smuzzies** [comment]
Something else that's odd:

If I run this: PYTHONPATH=/usr/lib/python3.10 /snap/bin/blender --python-use-system-env
Blender UI opens and the addon is good, everything works.
If I append further instructions such as -b -P -f switches for a headless render, it throws and error which I've concluded means the addon is not working.

If you come up with a console render command in which the addon works, I'd love to see it.
![image](https://user-images.githubusercontent.com/110495122/192115826-a4b4695e-0bed-4ee8-9a8b-8b2f26a71683.png)

**Comment by Smuzzies** [comment]
Just tried creating a startup script in /home/user/.config/blender/3.3/scripts/startup:

import sys
sys.path.append('usr/lib/python3.10')
def register():
      print("Added python env to path")

If I run the snap version from terminal >blender the UI opens and terminal displays the print command so I know its reading the startup script but dream texture button missing.

Just throwing this out there, dunno if that would even work. Trying everything! =)

**Comment by Smuzzies** [comment]
I can render blend and python file from GUI fine, here's output from headless command.

![image](https://user-images.githubusercontent.com/110495122/192118738-11fbaf7c-34d6-4aee-a8fd-8688f1103368.png)
