### ISSUE TITLE
AMD support thru onnx?

### ISSUE THREAD

**Issue by Ecl1pseGST** [carson-katri/dream-textures#340]
**Is your feature request related to a problem? Please describe.**
Not really a problem, just that us AMD GPU owners are stuck using CPU. 
**Describe the solution you'd like**
AMD GPU compatibility for this tool
**Describe alternatives you've considered**
I have a fork of SD that runs on my AMD using onnx, its not Nvidia fast but it's much faster than using my humble 3300x. Could this be implemented here? The Blender integration is super handy, and being able to see the steps is also very cool. 
**Additional context**
Nothing else, appreciate your time, and thank you for such an amazing tool.

**Comment by Groock** [comment]
I second this, and would love to help if I could, but its quite beyond my programming levels currently, also this tool is incredible and will be running it a lot for my PhD art practice research so thanks to all involved

**Comment by PeterNjeim** [comment]
I think this would be better: https://github.com/carson-katri/dream-textures/issues/504
