### ISSUE TITLE
Plugin kicks my PC off due to overvoltage protection

### ISSUE THREAD

**Issue by MrGTAmodsgerman** [carson-katri/dream-textures#345]
**Is this a known issue?**
Well, i know overvoltage from other AI's outhere where it was depending on the model and file amount i used

**Describe the bug**
I tried generating my first texture. It was about 98% finished and then my PC was shutdown completely. And i was unable to start it again without switchting off/on my power strip, which is obviously the overvoltage protection from my power supply.

**To Reproduce**
Use the setup that i have or simular with 600 W PSU and try to generate a texture.
Use standard 512px setting and type "dark wood panels" as prompt

**Expected behavior**
That the plugin works with regulated general electricity usage. A sort of limiter or regulation or mentioning of minimum requirements when it comes to the power supply

**Screenshots**
Paste in here a picture of a turned of pc

**System**
- OS
  - Windows 8.1 64 bit

- CPU
  - AMD Ryzen 7 1800X Eight Core Processor
 
- GPU
  - Aorus GTX 1080 Ti Xtreme Edition
  RAM
  - 32GB of RAM
 
 - Power 
  - be Quiet! Straight Power 10 Powersupply 600W

- Addon Version
  - Latest

**Comment by RazorWolvendom** [comment]
if youre rendering with your GPU, try to use MSI afterburner to adjust the voltage and frequency of your components

**Comment by MrGTAmodsgerman** [comment]
> if youre rendering with your GPU, try to use MSI afterburner to adjust the voltage and frequency of your components or aswell with the windows settings of the Energy schedule

How can i change what i render with?
