### ISSUE TITLE
MacOS - Architecture support - x86_64 - libtorch_global_deps.dylib

### ISSUE THREAD

**Issue by cs0rfecs0rfe** [carson-katri/dream-textures#346]
**Is this a known issue?**

No - this seems to be a first ;-)

**Describe the bug**
When I hit 'generate', the following error message appears:

Error: OSError("dlopen(/Users/if/Library/Application Support/Blender/3.3/scripts/addons/dream_textures/.python_dependencies/torch/lib/libtorch_global_deps.dylib, 0x000A): tried: '/Users/if/Library/Application Support/Blender/3.3/scripts/addons/dream_textures/.python_dependencies/torch/lib/libtorch_global_deps.dylib' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64h)))")

**To Reproduce**
Simply clicking on the 'generate' button causes this to happen.

**Expected behavior**
NOrmal operation

**System (please complete the following information):**
- OS
  - [ ] Windows
  - [x] macOS (Monterey 12.6) running on a 2020 13" Macbook Pro
  - [ ] Other
- GPU
  Intel Iris Plus graphics 1536Mb

- Addon Version
  0.0.7

**Additional context**
I'm guessing that the packaged torch dylibs are for an arm architecture rather than the X86_64 but that's getting to the limits of my knowledge of the internal workings of python/macOS.

**Comment by carson-katri** [comment]
Only Apple Silicon macs are supported at this time.
