### ISSUE TITLE
Error: ModuleNotFoundError("No module named 'clipseg_models'")

### ISSUE THREAD

**Issue by ManuLinares** [carson-katri/dream-textures#354]
**Describe the bug**
I *git pull* latest commits, and updated python modules with pip: and now it gives error

I updated pip modules with this command inside plugin root folder "~/.config/blender/3.3/scripts/addons/dream-textures"
`pip install --upgrade --target=./.python_dependencies/ -r stable_diffusion/requirements.txt`

```
Traceback (most recent call last):
  File "/home/user/.config/blender/3.3/scripts/addons/dream-textures/generator_process/__init__.py", line 305, in main
    from ldm.invoke import txt2mask
  File "/home/user/.config/blender/3.3/scripts/addons/dream-textures/stable_diffusion/ldm/invoke/txt2mask.py", line 32, in <module>
    from clipseg_models.clipseg import CLIPDensePredT
ModuleNotFoundError: No module named 'clipseg_models'

Error: ModuleNotFoundError("No module named 'clipseg_models'")

```

**System:**
- OS
  - [x] Other (Linux Arch)
- GPU
  - [x] NVIDIA
- Addon Version
  - Latest

**Comment by carson-katri** [comment]
There were some changes with clipseg, can you try deleting the folder `stable_diffusion/clipseg` then running `python -m pip install -e git+https://github.com/invoke-ai/clipseg.git@models-rename#egg=clipseg --target ../.python_dependencies` from inside `stable_diffusion`?

**Comment by ManuLinares** [comment]
Thanks, so adding a "-e " to the beginning of the last line in `stable_diffusion(requirements.txt` did it

I'll leave complete step by step installation instructions here for Linux Arch.

```
# Arch Linux Installation.
# 'pacman -S blender'

mkdir -p ~/.config/blender/3.3/scripts/addons
cd ~/.config/blender/3.3/scripts/addons

git clone https://github.com/carson-katri/dream-textures
cd dream-textures
git submodule update --init --recursive

cd stable_diffusion

#Add "-e " to the beginning of "clipseg"
sed -i 's/git+https:\/\/github.com\/invoke-ai\/clipseg/-e git+https:\/\/github.com\/invoke-ai\/clipseg/' requirements.txt

pip install --target=../.python_dependencies -r requirements.txt

#Open Blender, go to menu: "Edit -> Preferences" -> "Addons" -> Search for "Paint: Dream Textures" ->
# * "Setup Model Weight" -> Download and import Models as Detailed in the "Addon Setup" there.
# * Done!
```

**Comment by NullSenseStudio** [comment]
This is no longer an issue in main or releases/0.0.8 branch.
