### ISSUE TITLE
Missing libtorch_global_deps.so

### ISSUE THREAD

**Issue by Amenia1999** [carson-katri/dream-textures#355]
**Is this a known issue?**
Before reporting an error [search for an existing issue](https://github.com/carson-katri/dream-textures/issues?q=is%3Aissue) first.

**Describe the bug**
Missing File
**Screenshots**
[https://imgur.com/zuVnii6.png]

**System (please complete the following information):**
- OS
  - [ ] Windows
  - [ ] macOS
  - [X] Other (Linux)
- GPU
  - [x] NVIDIA
  - [ ] NVIDIA 16*XX*
  - [ ] Apple Silicon
  - [ ] AMD
- Addon Version
  - Latest

**Additional context**
Using Arch LInux

**Comment by Smuzzies** [comment]
Did you find a fix for perhaps?

**Comment by FrankNat996** [comment]
Same problem with Ubuntu 22.04.1 LTS

**Comment by NullSenseStudio** [comment]
This is most likely due to improper installation. This bug can be reproduced by running the windows release on a linux system.

What steps did you take to install?
