### ISSUE TITLE
Duplicate subjects with 'character' tag

### ISSUE THREAD

**Issue by TimNick151297** [carson-katri/dream-textures#357]
Hello! 
I noticed that often the image shows two bodies/faces instead of one. Is there a way to fix this/get a workaround? Negative prompt does not seem to do the trick.

**Comment by Dekker3D** [comment]
This is common when generating images larger than 512x512. I see it happen regularly on resolutions around 768 and basically always around 1024. This is a result of the model being trained at 512x512.
