### ISSUE TITLE
RunwayML Inpainting Model Support

### ISSUE THREAD

**Issue by carson-katri** [carson-katri/dream-textures#358]
**Is your feature request related to a problem? Please describe.**
RunwayML released a [model for inpainting](https://huggingface.co/runwayml/stable-diffusion-v1-5#training). InvokeAI has added support for this model in https://github.com/invoke-ai/InvokeAI/pull/1243. It should be usable when a "Source Image" is selected.

**Describe the solution you'd like**
Inpainting models will have a separate directory in the `weights` folder. They can then be selected when the backend is `LOCAL` and `use_init_img` is enabled.

**Describe alternatives you've considered**
The model could be selected like any other model in the `model` dropdown. The issue with this, is that the model requires different configuration, and detecting if a model is for inpainting could be problematic.

**Comment by NullSenseStudio** [comment]
supported in #405
