### ISSUE TITLE
error when trying to install dependencies

### ISSUE THREAD

**Issue by Aadi100409** [carson-katri/dream-textures#362]
### Description

when i click 'install dependencies' i get this error:
Command '['C:\\Program Files\\Blender Foundation\\Blender 3.3\\3.3\\python\\bin\\python.EXE', '-W', 'ignore::DeprecationWarning', '-c', '\nimport runpy\nimport sys\nsys.path = [\'C:\\\\Users\\\\HP\\\\AppData\\\\Local\\\\Temp\\\\tmpy3rhjn_g\\\\setuptools-58.1.0-py3-none-any.whl\', \'C:\\\\Users\\\\HP\\\\AppData\\\\Local\\\\Temp\\\\tmpy3rhjn_g\\\\pip-21.2.4-py3-none-any.whl\'] + sys.path\nsys.argv[1:] = [\'install\', \'--no-cache-dir\', \'--no-index\', \'--find-links\', \'C:\\\\Users\\\\HP\\\\AppData\\\\Local\\\\Temp\\\\tmpy3rhjn_g\', \'setuptools\', \'pip\']\nrunpy.run_module("pip", run_name="__main__", alter_sys=True)\n']' returned non-zero exit status 3221225794.

### Steps to Reproduce

1. enable the version 0.0.5 addon (0.0.7 does not work)
2. click install dependencies
3. sometimes it will install halfway and then close with the error

### Expected Behavior

the dependencies would install normally

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by carson-katri** [comment]
I will not be supporting old versions of the addon. Please update to the latest version, which no longer requires dependencies to be installed.
