### ISSUE TITLE
Theres no butten 

### ISSUE THREAD

**Issue by ajarcon** [carson-katri/dream-textures#365]
### Description

After installing everything the sidebar doesn't show the butten

### Steps to Reproduce

Installing the mac version and deleting it and reinstall the windows 32bit version

### Expected Behavior

show the butten

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by carson-katri** [comment]
The UI is now in the sidebar of the image editor and shader editor. press ‘N’ in one of those spaces to open it.

**Comment by ajarcon** [comment]
its not there

**Comment by ajarcon** [comment]
all i can see is view tool and item no dream textures

**Comment by carson-katri** [comment]
I will need an error message or something to fix this. Did you make sure to enable the addon in preferences? Also check Window > Toggle System Console for error logs.

**Comment by ajarcon** [comment]
i have enabled it and the console logs only say fake_module: addon missing

**Comment by ajarcon** [comment]
ah i found it
