### ISSUE TITLE
Spontaneous crash upon attempting to plug in/edit normal values/roughness values

### ISSUE THREAD

**Issue by Gwendoesstuff** [carson-katri/dream-textures#37]
The image plugs into the procedural shader just fine and there are no issues during the generation, but upon attempting to edit/plug in any normal/roughness values while in rendered mode the program will spontaneously crash, these values can be edited in material preview and then viewed in rendered mode.
![blender crash log](https://user-images.githubusercontent.com/113808257/191139245-daa70917-75c1-461d-98f9-b32d840d0e99.png)

CPU: Amd Ryzen 5 5600x 6-core
GPU: Nvidia Geforce rtx 3050 8gb vram

Below is a blend file in which the issue is encountered.
https://mega.nz/file/mJZlAbwI#PdESWIChYugVFn0Vi58jNy8RP691F7N2HsDxo2kInh0

**Comment by carson-katri** [comment]
Please share the contents of `C:\Users\20pot\AppData\Local\Temp\blender.crash.txt`
