### ISSUE TITLE
Generate half image ???

### ISSUE THREAD

**Issue by Ngoc68** [carson-katri/dream-textures#371]
### Description

Generate half image

### Steps to Reproduce

I try to generate but just half of process
![image](https://user-images.githubusercontent.com/117069710/198958700-7efe9e52-32eb-49ca-9cc6-b0e67f83452e.png)

### Expected Behavior

 how to fix this

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by enJey009** [comment]
Its normal for 64x64, ive tried, the same result
