### ISSUE TITLE
File Batch is incompatible with DreamStudio Online

### ISSUE THREAD

**Issue by enzyme69** [carson-katri/dream-textures#378]
### Description

<_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception iterating responses: multiple text prompts"
	debug_error_string = "UNKNOWN:Error received from peer ipv4:104.18.21.212:443 {created_time:"2022-11-02T16:47:39.683909+11:00", grpc_status:2, grpc_message:"Exception iterating responses: multiple text prompts"}"
>

### Steps to Reproduce

1. Try text batch multiple text
2. Send job to Dream Studio
3. Failed..

### Expected Behavior

I wish it works.

### Addon Version

macOS (Intel)

### GPU

Other

**Comment by enzyme69** [comment]
Not just batch apparently it does not work at all, simply just frozen when I am sending to compositor nodes, into Dream Studio.

**Comment by carson-katri** [comment]
Seems like DreamStudio does not support prompt batches, I will need to either disable this or manually send the prompts to the backend one by one.

**Comment by enzyme69** [comment]
Okey, noted. Maybe one by one batch would be ideal.

**Comment by NullSenseStudio** [comment]
fixed in #485
