### ISSUE TITLE
Updated to 0.0.8 but blender still says update available

### ISSUE THREAD

**Issue by lxne** [carson-katri/dream-textures#379]
### Description

I am on a macbook pro M1 max running macOS Ventura and Blender 3.3.1.
After updating from a previous dream-textures version to 0.0.8 blender still says 'update available'.
<img width="1102" alt="Bildschirm­foto 2022-11-02 um 18 52 37" src="https://user-images.githubusercontent.com/13134654/199565327-81b964b7-baad-46a9-996f-2d6b18f207a4.png">

I even removed it and reinstalled it. Still the same.

### Steps to Reproduce

See above.

### Expected Behavior

Do not show 'Update available…'

### Addon Version

macOS (Apple Silicon)

### GPU

Apple Silicon

**Comment by carson-katri** [comment]
You have the correct version, there was a bug in the update checker code that wasn’t caught until it was released. I ran a new build this morning and am getting the fixed versions uploaded.

**Comment by lxne** [comment]
Thank you for the fast response.
Should I leave the issue open?

Am Mi., 2. Nov. 2022 um 18:58 Uhr schrieb Carson Katri <
***@***.***>:

**Comment by carson-katri** [comment]
Sure, I’ll close it once everything is uploaded.

**Comment by lxne** [comment]
Thanks a lot.
This thing is insanely awesome.


Am Mi., 2. Nov. 2022 um 19:03 Uhr schrieb Carson Katri <
***@***.***>:

**Comment by carson-katri** [comment]
Release artifacts have been updated to fix this issue.
