### ISSUE TITLE
"update files" vs "all files"

### ISSUE THREAD

**Issue by AlienXtream** [carson-katri/dream-textures#382]
separate downloads for the "update files" and "all files" would be nice. basically for smaller patches and bug fixes only having to download the changed files instead of the whole thing. more relevent for limited bandwidth or slow connections. even an integrated auto updater tool that would auto fetch the updated files that are needed. not really a high priority suggestion but would be a nice convenience if it does not make things too complicated for you

**Comment by ajarcon** [comment]
I also want this for the next version pls add it made me redownload everything

**Comment by niudage** [comment]
good
