### ISSUE TITLE
Can not generate after update

### ISSUE THREAD

**Issue by christersonw** [carson-katri/dream-textures#383]
### Description

Getting this error message on Macbook Pro with M1 chip. After having installed the 0.0.8 version of the plugin. Did not have an issue with 0.0.7 prior. Using Blender 3.3.1

Python: Traceback (most recent call last):
  File "/Users/xxxx/Library/Application Support/Blender/3.3/scripts/addons/dream_textures/operators/dream_texture.py", line 41, in invoke
    return self.execute(context)
  File "/Users/xxxx/Library/Application Support/Blender/3.3/scripts/addons/dream_textures/operators/dream_texture.py", line 71, in execute
    node_tree = context.material.node_tree if hasattr(context, 'material') else None
AttributeError: 'NoneType' object has no attribute 'node_tree'

### Steps to Reproduce

Install plugin and follow instructions in the addon section of blender.

Try and generate any image using any prompt

### Expected Behavior

Expected that image would generate upon pressing "Generate"

### Addon Version

macOS (Apple Silicon)

### GPU

Apple Silicon

**Comment by carson-katri** [comment]
Can you try creating a material on any object in the scene?

**Comment by christersonw** [comment]
That indeed did the trick. Doing the classic "remove everything from new project" was at fault here.
