### ISSUE TITLE
Suggestion: Tiled Rendering

### ISSUE THREAD

**Issue by RazorWolvendom** [carson-katri/dream-textures#386]
### would it be possible if blender would be able to: 
generating a promt putting together smaller tiles to a bigger total image / Rendering it in tiles to save more Vram due to the max capacity of each Device.

just like the same way how Cinebench visualizes your cores in tiles renders each fragment of the total image in the process.

so people would be able to generate bigger final resolutions which most people cant generate at "once" and at a to low resolution the prompt would just turn into nonsense like at 64x64 with weird coloring and shapes / unreadable-text.

the way to prevent this is like to generate in background as "mask" of what it should "turn into" and then depending of how much tiles / divides is set as modifier in the UI then it generates each Tile / Divions each after another and then showing the final result as Rendered Viewport and therefore you could go for more specific resolutions like 16:9, 4:3 and 9:16 since there would be just more layers on the bottom of the same "tile size" of the grid (4x 128x128 Horizontal and 3x 128x128 Vertical) etc

<img width="300" alt="ScreenShot_20221105181651" src="https://user-images.githubusercontent.com/44827474/200132822-06230aac-a7b2-4aa4-bb98-c5af85f13ee5.png">

**Comment by playerla** [comment]
Hi,
Question is which prompt for which tiles ? Tiles (compute parallelization) model seems no to fit text-to-image. Maybe some out-painting and seamless constraints could help here ?
There are ai upscaling models that look promising (Yet I haven't tested)
