### ISSUE TITLE
Windows AttributeError("'NoneType' object has no attribute 'modules'")

### ISSUE THREAD

**Issue by macglencoe** [carson-katri/dream-textures#388]
### Description

Installed 0.0.8 as normal
Opened blender, imported model sd-v1-4.ckpt
Entered a prompt and clicked generate, and it did the whole loading routine as usual. It got stuck on "Loading CLIP Segmentation" for a good bit, but eventually went on.
After the status shows "Starting" it immediately throws this error:
![image](https://user-images.githubusercontent.com/101204247/200141890-d07ee322-e703-404c-a86c-c8de9d9a9955.png)

It works when using DreamStudio, but it is slower than when I used 0.0.7
I saw there's another issue similar to this, but it's Ubuntu, which I am not using. ~I also am not getting the full traceback message, only the error name.~
UPDATE: I found the full error message sorry I'm not very familiar with blender's interface
![image](https://user-images.githubusercontent.com/101204247/200142354-7bb3e543-a870-4923-9d7c-fa414de01f38.png)

### Steps to Reproduce

Install 0.0.8 from .zip archive
Import model sd-v1-4.ckpt
Type prompt and click generate

### Expected Behavior

Generation should begin

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by McKlinton2** [comment]
I got the exact same problem. Blender 3.3.0 (Windows)

**Comment by carson-katri** [comment]
This happens when the model fails to load. Can you try changing this line to `sys.stdout = sys.stderr` then restart Blender and check the logs again? Then you’ll get a more detailed log of exactly what happened during model loading.
https://github.com/carson-katri/dream-textures/blob/6e849766274ec29c01e5864516246d89a5ee2306/generator_process/__init__.py#L140

**Comment by carson-katri** [comment]
You may also want to check if the checksum matches for the checkpoint file. If you open `C:\Users\youruser\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\weights\stable-diffusion-v1.4\sd-v1-4.sha256`, check that contents are `fe4efff1e174c627256e44ec2991ba279b3816e364b49f9be2abc0b3ff3f8556`. It's possible that the checkpoint download was corrupted.

**Comment by makoki21** [comment]
> This happens when the model fails to load. Can you try changing this line to `sys.stdout = sys.stderr` then restart Blender and check the logs again? Then you’ll get a more detailed log of exactly what happened during model loading.
> 
> https://github.com/carson-katri/dream-textures/blob/6e849766274ec29c01e5864516246d89a5ee2306/generator_process/__init__.py#L140

Hello, I have the same bug. I tried to do this but no results, the same message appeared. And I checked the file sd-v1-4.sha256 and it's correct

**Comment by NullSenseStudio** [comment]
There should be more information before the error message after you changed that line. Could you post the whole console output?

**Comment by makoki21** [comment]
> There should be more information before the error message after you changed that line. Could you post the whole console output?

Yes, here you have
![error](https://user-images.githubusercontent.com/117671962/200433348-35baf3e0-620f-4def-9fb1-74753d145518.png)

**Comment by makoki21** [comment]
> There should be more information before the error message after you changed that line. Could you post the whole console output?

I have made the modification of _init_.py directly in the .zip file before unzipping. In order to install _init_.py with the modification already made
![2022-11-08](https://user-images.githubusercontent.com/117671962/200434281-356da332-87d6-4398-a578-a5e944b74340.png)

**Comment by carson-katri** [comment]
@makoki21 Open Window > Toggle System Console for the entire output.

**Comment by McKlinton2** [comment]
My issue with this plugin was probably the memory usage. I might had another stable diffusion instance running when I tried the addon on Blender. Now it works just fine after reboot and not starting anything else than Blender.

**Comment by carson-katri** [comment]
@makoki21 Looks like your computer ran out of VRAM when trying to load the model. I'd try closing some other programs and restarting to see if it can get enough.
