### ISSUE TITLE
custom weights directory

### ISSUE THREAD

**Issue by BoosterCore** [carson-katri/dream-textures#393]
Is it possible to set the weights directory to a custom path, such as sharing the same directory with webui, so as to avoid bursting the system disk where Blender is located.

**Comment by BoosterCore** [comment]
Thank you very much，I edit the “absolute_path.py” file to get it done.

**Comment by BoosterCore** [comment]
I'm very sorry, this method fails after restarting the system, and the error "AttributeError("'NoneType' object has no attribute 'modules'")" is displayed. Are there any other path-related settings in the document that need to be modified?

**Comment by carson-katri** [comment]
Editing the absolute path implementation could break other things. This guide looks ok, although I’ve never used symlinks on Windows myself: https://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/amp/

**Comment by BoosterCore** [comment]
Thanks, I'll go and learn

**Comment by BoosterCore** [comment]
> Editing the absolute path implementation could break other things. This guide looks ok, although I’ve never used symlinks on Windows myself: https://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/amp/

Cool！Finally worked！Thanks again！

**Comment by carson-katri** [comment]
Awesome, glad you got it setup!

**Comment by carson-katri** [comment]
Closing this one as another similar issue is already open. #63

**Comment by gerroon** [comment]
> You could create a symlink to the checkpoint file in the weights folder.

Where are the weights located in the addon's folders?
