### ISSUE TITLE
Docker?

### ISSUE THREAD

**Issue by neoOpus** [carson-katri/dream-textures#397]
Hi,

Is it possible to have a slimmed down version that uses Automatic1111 ported to Docker (that's the only way I can use my laptop GPU with 2GB of VRAM)... which uses CPU as well

https://github.com/AbdBarho/stable-diffusion-webui-docker

I think this will allow more people to have access to this plugin without necessarily having High-End uber expensive GPUs

**Comment by carson-katri** [comment]
#405 integrates diffusers, which can consume less VRAM with some configuration or run on CPU only.
