### ISSUE TITLE
Not working on Mac M1, OSError (0x000A)

### ISSUE THREAD

**Issue by nechaevdeveloper** [carson-katri/dream-textures#398]
### Description

I installed the correct version of the addon (dream_textures-macos-arm.zip), then installed v1-5-pruned-emaonly.ckpt. 

Next, I click the generate button. 
I am getting an error:
![ssss](https://user-images.githubusercontent.com/86629028/202352907-fbfa2a6c-1b79-4528-aa39-42df589657ba.jpg)

System (please complete the following information):
OS
- macOS
GPU
- Apple Silicon (M1 Max)
Addon Version
- Latest 0.0.8

### Steps to Reproduce

Click the "generate" button

### Expected Behavior

Getting error OSError (0x000A)

### Addon Version

macOS (Apple Silicon)

### GPU

Apple Silicon

**Comment by carson-katri** [comment]
Can you try running the command mentioned for macOS at the top of the README: https://github.com/carson-katri/dream-textures#installation

**Comment by carson-katri** [comment]
Make sure you are using an apple silicon version of Blender as well.

**Comment by nechaevdeveloper** [comment]
Thank you. The problem was in the blender, I downloaded it from Steam, but it should have been from the official site. Problem solved.
