### ISSUE TITLE
Getting Error during install on Apple Silicon

### ISSUE THREAD

**Issue by alexajwhite** [carson-katri/dream-textures#4]
Error is: Command '['/Applications/Blender.app/Contents/Resources/3.0/python/bin/python3.9', '-m', 'pip', 'install', '-r', '/Users/alexajwhite/Library/Application Support/Blender/3.0/scripts/addons/dream_textures/stable_diffusion/requirements.txt']' returned non-zero exit status 1.

**Comment by carson-katri** [comment]
You may have the sample problem as #3. Can you try editing `/Users/***/Library/Application Support/Blender/3.3/scripts/addons/dream_textures/stable_diffusion/requirements.txt` to change the line `torchvision==0.12.0` to `torchvision==0.13.1`? Then run it again.

**Comment by alexajwhite** [comment]
Still seem to be getting the same error after changing

**Comment by carson-katri** [comment]
Launch Blender from the terminal so you can see the full error message:
1. Open Terminal
2. Run `/Applications/Blender.app/Contents/MacOS/Blender`
The path may be slightly off, but basically you need to run the Blender executable inside the .app

**Comment by alexajwhite** [comment]
Its successfully installed after running blender through terminal which is strange, thanks for the help though.
