### ISSUE TITLE
Apple M1 Pro - Time to generate is exponentially longer after first generation

### ISSUE THREAD

**Issue by winterwarrior3** [carson-katri/dream-textures#40]
Running Blender 3.3 and latest release of Monterey.

The generation of the first texture in a fresh start of Blender takes about 47 seconds running on a base 14inch M1 Pro MacBook Pro. 

After the first generation, every attempt following that takes way longer at 583 seconds. Same settings for each generation so I'm not sure why it takes longer.

**Comment by TroySeins** [comment]
Blender 3.3.1 on macOS 12.5, M1 Ultra 128Gb.

Texture mode, tillable, 512, 1st 30s., 2nd 28s., 3rd - Blender crashes. Sometimes at the second, sometimes at the 4th.
2048x2048 crashes sadly, 1536x1536 works for one image, but takes very long time. That's so great nevertheless.

**Comment by moebis** [comment]
I having a different issue on the M1 Ultra. First texture generation was "bricks" and it worked fine, took a while at first just using all of the defaults. Then I switched the sampler to DDIM and it started generating much faster then crashed. Loaded blender again, tried another sampler, crashed. Went back to the default KLMS, now it crashes every time. I only had success on the very first generation. How do I reset this?

**Comment by carson-katri** [comment]
@moebis That is odd. I would try restarting your computer if you haven’t already.

**Comment by moebis** [comment]
not sure if this helps, or I should try running blender from terminal for more details. It was working again, then after 3 or 4 prompts it started crashing. I'll try a restart too: https://pastebin.com/SyexCt8e

**Comment by moebis** [comment]
@carson-katri caught this in the terminal:

```
>> Using slower but more accurate full-precision math (--full_precision)
>> Model loaded in 5.77s
>> Setting Sampler to k_lms
/Users/moebis/Library/Application Support/Blender/3.3/scripts/addons/dream_textures/stable_diffusion/ldm/modules/embedding_manager.py:155: UserWarning: The operator 'aten::nonzero' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/mps/MPSFallback.mm:11.)
  placeholder_idx = torch.where(
Generating:   0%|                                         | 0/1 [00:00<?, ?it/sWriting: /var/folders/r0/19s1tlsn31jb7npr_050xh100000gn/T/blender.crash.txt4it/s]
zsh: segmentation fault  /Applications/Blender.app/Contents/MacOS/Blender
moebis@Carls-Mac-Studio ~ % /Applications/Blender.app/Contents/Resources/3.3/python/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
moebis@Carls-Mac-Studio ~ %
```

**Comment by moebis** [comment]
@carson-katri simply amazing update. It works flawlessly now on the M1 Ultra, and it's so much faster! I love that you can access it from tool menu. Thank you. Where can I tip/donate/support this project?

**Comment by carson-katri** [comment]
You can become a GitHub sponsor if you’d like, there’s a button at the top of this page.

also, would you care to share your speeds on the ultra with default settings? I’m curious how big the difference is between my M1 Max and the ultra.
