### ISSUE TITLE
ImportError: cannot import name 'Log' from 'distutils.log'

### ISSUE THREAD

**Issue by wtfreely** [carson-katri/dream-textures#404]
### Description

Running this on Linux, managed to get everything set up and seemingly working fine, but I get the following error:

`ImportError: cannot import name 'Log' from 'distutils.log'`

A quick google shows it might be related to [a recent change in the pypa tools?](https://github.com/pypa/setuptools/issues/3693)

### Steps to Reproduce

Install per the "contributor" steps, as per Linux installation instructions.
Install dependencies and models.
Click "generate" and get error.

### Expected Behavior

Generate sans error.

### Addon Version

Other (Built from source)

### GPU

NVIDIA

**Comment by carson-katri** [comment]
Hmm, that's unfortunate. Can you please share the full error log so I can see what code is importing distutils?

**Comment by NullSenseStudio** [comment]
You may just have to reinstall dependencies, setuptools just released version 65.6.1 which re-added the Log class for this sort of issue.
