### ISSUE TITLE
504　Gateway Time-out

### ISSUE THREAD

**Issue by nyu777** [carson-katri/dream-textures#406]
### Description

I get an error in this image when I start the generation.

Addon ver 0.0.8

![image](https://user-images.githubusercontent.com/114099714/204207039-5cf885b9-b841-4704-acbc-09c1f3cb2cbc.png)

### Steps to Reproduce

I downloaded sd-v1.4 yesterday by clicking on "Downlod weights from huggingface" in the DT prefarence. When I generated an image with that model, I got a 504Gateway timeout error.

And now when I reinstall the add-on and try to download sd-v1.4 again, when I access the "Downlod weights from huggingface" link, the site does not open and I get "504 Gateway Time-out".
![SnapCrab_NoName_2022-11-28_15-2-35_No-00](https://user-images.githubusercontent.com/114099714/204207339-da1d9fd7-d2a5-489f-a48a-8199fb3f8ec0.png)

What should I do?

### Expected Behavior

I was able to generate it using sd-v1.4 that I had previously downloaded. But with sd-v1.4 that I downloaded today, I could not generate it.

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by NullSenseStudio** [comment]
Looks like the huggingface site was having some [temporary issues](https://status.huggingface.co/). You don't have reinstall the addon for that. Just try generating again with the weights you already have.
