### ISSUE TITLE
Too much RAM usage

### ISSUE THREAD

**Issue by pixol20** [carson-katri/dream-textures#407]
### Description

When I try to generate even a 16x16 texture, the blender takes up all the RAM and the computer freezes. I have 8Gb DDR3 RAM

### Steps to Reproduce

Just try to generate image

### Expected Behavior

Blender was not expected to take up that much RAM

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by carson-katri** [comment]
Please specify what graphics card you have. Stable diffusion requires at least 4GB of VRAM, and more if your card doesn’t support half precision math.

**Comment by pixol20** [comment]
RTX 3050(i know its weird to use rtx with ddr3 ram)

**Comment by carson-katri** [comment]
Have you tried restarting and closing other programs to make more RAM/VRAM available to Stable Diffusion? It needs to be able to load the model into memory, which is a few GB. Make sure you got the pruned/EMA-only file which is lighter weight for inference.

**Comment by pixol20** [comment]
So I need 4 gb of free RAM

**Comment by pixol20** [comment]
Even after I cleared enough RAM, blender just takes that memory for a while after which it loads the CPU very heavily while not using the GPU at all

**Comment by pixol20** [comment]
Even after I cleared enough RAM, blender just takes that memory for a while after which it loads the CPU very heavily while not using the GPU at all

**Comment by pixol20** [comment]
Even after I cleared enough RAM, blender just takes that memory for a while after which it loads the CPU very heavily while not using the GPU at all

**Comment by carson-katri** [comment]
If monitoring from task manager, you have to switch the GPU stat to show CUDA usage afaik.

**Comment by pixol20** [comment]
how to do it?

**Comment by carson-katri** [comment]
There’s a drop-down above the GPU usage graph. By default I think it’s set to “3D”
