### ISSUE TITLE
Not able to set Seed above 2147483647 or below -2147483647

### ISSUE THREAD

**Issue by theflopmeister** [carson-katri/dream-textures#41]
I have not been able to manually set the seed above 2147483647 or below -2147483647. The random seeds are usually outside this range.

**Comment by jordigcs** [comment]
That's the maximum range for a signed 32-bit integer. The 'IntProperty' class Blender uses is most likely using a 32-bit int under the hood. When this plugin is ran, it's actually the Stable Diffusion package that generates the random seed. Not `dream-textures`
https://github.com/carson-katri/dream-textures/blob/f182511f8ef44b0dcd1af40bc7786482e27e3635/operators/dream_texture.py#L209-L243

There's nothing that can be done to fix this, AFAIK.

**Comment by carson-katri** [comment]
I can move the seed generation into dream textures with these bounds.
