### ISSUE TITLE
Vertex group tagging

### ISSUE THREAD

**Issue by GracilePaddington** [carson-katri/dream-textures#421]
**Is your feature request related to a problem? Please describe.**
There is no ostensible problem, the plugin works as intended. Great work you guys! 

**Describe the solution you'd like**
I would like the information about particular objects in a single mesh to have their own keywords associated with them. E.g. I can select all objects that are meant to be "metal" as a vertex group named "Metal  (add on further keywords)" 

**Describe alternatives you've considered**
I think that this could be achieved with different material groups that create submeshes within the model. 

**Additional context**
None needed I believe. Thank you guys for your hard work!

**Comment by carson-katri** [comment]
If I understand correctly, this is similar to what I’ve started working on in #414. Separate prompts for each object in the scene for more control over the generated textures.

**Comment by GracilePaddington** [comment]
> 

Thank you Carson, I'll be more diligent in reading the Git. Would be nice to have it on a single-object level if possible. You guys rule!

**Comment by carson-katri** [comment]
Exactly, so every object prompt needs to be contained in the main prompt, and it weights the tokens differently for each pixel depending on what object is there.
