### ISSUE TITLE
The Dream tab in the sidebar shows up in the image editor, but not Edit mode

### ISSUE THREAD

**Issue by Effervescent73** [carson-katri/dream-textures#423]
### Description

Just like the title says The Dream tab in the sidebar shows up in the image editor, but not Edit mode

### Steps to Reproduce

1. Install Dream Textures
2. Don't find dream tab

### Expected Behavior

The dream tab should've been there

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by OnlyKnowALittle** [comment]
Check that you're version of the add-on is "0.9" or "0.8". I kept downloading 0.8 from the under "Choose Your Installation" even though it seems it should be the new release.

You need to go to the very bottom of 0.9 and under Contributors->Assetts->Dream-Textures-Windows-Cuda . Then install and under 'Find Models' search for 'stable-diffusion-2-depth' . 

![Here](https://user-images.githubusercontent.com/31841351/208000302-91ef7c54-9be9-4d72-aeb2-d938470259df.jpg)
