### ISSUE TITLE
"The Selected Pipeline Does not support depth to image"

### ISSUE THREAD

**Issue by ChaseFlorom** [carson-katri/dream-textures#425]
### Description

I'm wondering if I've done something wrong. I'm getting the error: "The Selected Pipeline Does not support depth to image"

### Steps to Reproduce

I'm on Windows version that uses the online dreambooth models.

### Expected Behavior

It would work for depth-2-img as planned.

### Addon Version

Windows (DreamStudio-only)

### GPU

AMD (unsupported for local generation)

**Comment by carson-katri** [comment]
DreamStudio does not support depth to image yet.

**Comment by ChaseFlorom** [comment]
Dang, so as an AMD user am I not able to use that concept art model?

**Comment by carson-katri** [comment]
They currently only provide text to image, image to image, and inpainting.

**Comment by ChaseFlorom** [comment]
Bummer! Guess I'll wait for AMD to be supported or Dreambooth to support depth-2-img.

**Comment by enzyme69** [comment]
Also just additional info that might be related:
First time Dream Texture user might be confused with few different mode offered.

1. You can "render" the AI dreams in 3D thanks to the "depth" feature, so you setup the 3D view layout, your 3D objects, make sure to be as close as square, then you run the "depth" AI dreams, with depth ckpt model that you already downloaded.

2. You can also use the non depth feature, if you use Image Editor.

3. And plus you have the Composition Dream feature, that can be used for AI dream after render.
