### ISSUE TITLE
0.0.9, Inpainting doesn't appear to be working

### ISSUE THREAD

**Issue by nikolatesla20** [carson-katri/dream-textures#427]
### Description

Dream Textures 0.0.9 with Blender 3.4

I follow the inpainting documentation:

The quickest way to inpaint is with the Mark Inpaint Area brush.

    Use the Mark Inpaint Area brush to remove the edges of the image
    Enter a prompt for what should fill the erased area
    Enable Source Image, select the Open Image source and the Inpaint action
    Choose the Alpha Channel mask source
    Click Generate

So I draw a hole in my image with the inpaint brush and then followed the instructions. When I click "generate" it doesn't do anything and I see no new images in the inpainted area.

![image](https://user-images.githubusercontent.com/3721469/208027024-68ca9e26-91da-4d01-8a37-b53129f04064.png)

console: 
![image](https://user-images.githubusercontent.com/3721469/208027327-29278890-c971-408e-8ded-14eb184d7675.png)

### Steps to Reproduce

Use the Mark Inpaint Area brush to remove the edges of the image
    Enter a prompt for what should fill the erased area
    Enable Source Image, select the Open Image source and the Inpaint action
    Choose the Alpha Channel mask source
    Click Generate

### Expected Behavior

Inpaint should generate new content in the masked area

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by nikolatesla20** [comment]
Ok all, I'm a moron, I forgot to choose the inpainting model.

I know it's a user problem, I wonder if there would be a way to pop a message to a user if they haven't chosen that model and they try to inpaint it will tell them what's wrong..

**Comment by Arcayer** [comment]
This seems to also be a problem that applies to image to image, specifically when using the stable diffusion 2-1 model (Probably, using any model in the 2+ series?) Image to image works fine with the 1.5 model.
