### ISSUE TITLE
No Dream Textures Menu in Shader Editor

### ISSUE THREAD

**Issue by noc2art** [carson-katri/dream-textures#43]
![image](https://user-images.githubusercontent.com/32395664/191403655-17ffc405-edb3-48bb-a0cd-0c5c3dc4b675.png)

I installed the addon successfully but where is the menu?

**Comment by carson-katri** [comment]
The top right of the image and shader editors.

**Comment by AlienXtream** [comment]
i dont have the button anywhere.

**Comment by carson-katri** [comment]
It has moved to the side panel in v0.0.6. Press N to open it on the Image and Shader editors.
