### ISSUE TITLE
<title>

### ISSUE THREAD

**Issue by mityakimovskii** [carson-katri/dream-textures#433]
### Description

Hi all!
in object mode "Starting" not finishing
in image mode this error

<img width="1389" alt="ssss" src="https://user-images.githubusercontent.com/120757163/208199136-28b70b2e-0a16-4c52-a621-d0b60509657b.png">

### Steps to Reproduce

installed the latest version. Everything is done according to the instructions.

### Expected Behavior

generation process

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by enzyme69** [comment]
Random guess: maybe you have funky character in the prompt?
