### ISSUE TITLE
Depth Not Working - Stops Quickly After Starting, diffusion_pytorch_model.bin not found

### ISSUE THREAD

**Issue by JasonHoku** [carson-katri/dream-textures#434]
### Description

I may have messed up the original installation by not running as administrator. 

I had to retrieve the 'diffusion_pytorch_model.bin not found' error from the console and didn't receive any error message in Blender.

Could use with an improved error catch, message or suggestion to the user here possibly.

```
Traceback (most recent call last):
  File "C:\Users\JasonHoku\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\dream_textures\generator_process\actor.py", line 98, in run_callbacks
    exception_callback(self, exception)
  File "C:\Users\JasonHoku\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\dream_textures\operators\project.py", line 171, in on_exception
    raise exception
OSError: Error no file named diffusion_pytorch_model.bin found in directory C:\Users\JasonHoku/.cache\huggingface\diffusers\models--stabilityai--stable-diffusion-2-depth\snapshots\3d8508e740daa5aadca5af4e4cd978490b0f8110.
```

### Steps to Reproduce

Follow Setup Instructions (Maybe didn't run as admin)
Blender --> Run Depth

### Expected Behavior

Error instead prompt user towards a fix.

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by Atair1** [comment]
for me the problem was that i only downloaded 2.1 image generation, made some tests and afterwards tried to download depth - it messed something up..
maybe try removing the addon and delete the .cache/huggingface folder
when reinstalling make sure to download both models 2.1 and depth before running anything the first time.

**Comment by JasonHoku** [comment]
I believe this was caused by not having the proper -base model also installed with the depth model.
