### ISSUE TITLE
Not able to make anything other than 512x512 and can't upscale

### ISSUE THREAD

**Issue by Elattyak** [carson-katri/dream-textures#436]
I have a decent computer (ryzen 7 5800x and RTX 3070ti), but for some reason, I can't use the ai upscaler or make anything bigger than 512 x 512. My PC should be capable, but it gets forever stuck on "Starting..." and I'm definitely waiting long enough (512 x 512 take about 10 seconds I've been waiting for 1024 x 1024 for 10+ minutes) Does anyone have a fix? my console has no errors so it's not like something is explicitly broken.

**Comment by Lissanro** [comment]
The documentation says:

`> Upscaling uses the model `stabilityai/stable-diffusion-4x-upscaler`. This model will automatically be downloaded when the operator is first run.`

It is very unlikely to download in just ten minutes. Also, you may need to apply https://github.com/carson-katri/dream-textures/pull/410 patch. For me, upscaling did not work at all without it.

With 8GB card, I can generate 1024x1024 textures and upscale to 4K.
