### ISSUE TITLE
Unable to download Stable Diffusion in addon settings in version 0.0.9

### ISSUE THREAD

**Issue by somerando111** [carson-katri/dream-textures#440]
### Description

After installing the addon, following the steps to download the recommended version of Stable Diffusion by clicking on the button does not work.  At first a download progress bar will appear, but no loading will happen.  after that the preferences menu in the addon settings disappears for a split second before reappearing, almost too fast to notice.  other than that nothing happens.  it does not load as expected.  

The same thing happens when trying to add a model from the search menu below that in the addon settings.  clicking on the download icon results in a quick flash in the menu and then nothing happens.

### Steps to Reproduce

install the addon as normal,
select "Download Stable Diffusion v2.1 (recommended)
nothing happens

here is a video of what happens:
https://user-images.githubusercontent.com/120836632/208265447-8a2cb52b-fa0b-4127-b5d1-bf772d568c03.mp4

### Expected Behavior

install the addon as normal,
select "Download Stable Diffusion v2.1 (recommended)
Stable Diffusion begins to download

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by SmowHD** [comment]
I am having the same issue
Win10 CUDA
RTX 3080

**Comment by BennettWerner** [comment]
Same issue here, Windows 10, Blender 3.2.2, CUDA

**Comment by SmowHD** [comment]
when updating to blender 3.4.0 you can start the doenload through the "find models" search bar

**Comment by ircrp** [comment]
> when updating to blender 3.4.0 you can start the download through the "find models" search bar

Did this work for you ? For me any model I download from Find Models does not appear to be selectable from Dream Texture's Addons select box. Made sure to restart Blender & start up as Admin.

**Comment by sherifdaizer** [comment]
Same problem from last blender too!!

**Comment by Dablette** [comment]
I have same issue with that. Windows 10 blender 3.4 with RTX 3060ti

**Comment by sherifdaizer** [comment]
Windows 11 blender 3.4 with RTX 3080ti

**Comment by SmowHD** [comment]
> > when updating to blender 3.4.0 you can start the download through the "find models" search bar
> 
> Did this work for you ? For me any model I download from Find Models does not appear to be selectable from Dream Texture's Model select box.

Yes it did. Additionally I had the issue that my C drive where the AI models are saved was getting low on storage so i freed up some space and updated Blender. Then it worked

**Comment by BennettWerner** [comment]
> 

downloaded blender 3.4 issue resolved

**Comment by sherifdaizer** [comment]
> 

But I have last version yesterday!

**Comment by Zincr0** [comment]
Tested used blender 3.3 with main branch, it not only doesn't download the models, the button to "import checkpoint file" also does nothing, it doesn't even log any error on the console.

**Comment by Zincr0** [comment]
Looks like the addon is using the wrong python interpreter, probably the system one instead of the blender one, so lets install the dependencies manually:

`blender-3.4.0-linux-x64/3.4/python/bin$ ./python3.10 -m ensurepip`

`blender-3.4.0-linux-x64$ ./pip3 install -r  /disk3/blender-config/3.4/scripts/addons/dream-textures/requirements/win-linux-cuda.txt `

and now lets enable huggingface diffusers

`blender-3.4.0-linux-x64/3.4/python/bin$ ./huggingface-cli login`

`blender-3.4.0-linux-x64/3.4/python/bin$ ./python3.10`

`>>> from diffusers import StableDiffusionPipeline`
`>>> pipe = StableDiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-2")`

Then inside the plugin got an 

`FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.cache/huggingface/diffusers/models--CompVis--stable-diffusion-v1-4/refs/main'`

Now Looks like the addon is looking always for a "main" ref but i got installed only the "fp16" ref, a bug in "generator_process/actions/huggingface_hub.py" on "function def _map_model(file)" line 65.
Since i'm not using the 1.4 i just deleted the folder '/home/user/.cache/huggingface/diffusers/models--CompVis--stable-diffusion-v1-4'

Then got "Unsupported model" in the addon with the "stabilityai/stable-diffusion-2" on the N panel.

So, back to the console to

`blender-3.4.0-linux-x64/3.4/python/bin$ ./python3.10`

`>>> from diffusers import StableDiffusionPipeline`
`>>> pipe = StableDiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-2-depth")`

And finally I was able to select the model and run the addon. If only it generate something that isn't garbage... maybe  256*256 is just too low...

**Comment by sherifdaizer** [comment]
> Looks like the addon is using the wrong python interpreter, probably the system one instead of the blender one, so lets install the dependencies manually:
> 
> `blender-3.4.0-linux-x64/3.4/python/bin$ ./python3.10 -m ensurepip`
> 
> `blender-3.4.0-linux-x64$ ./pip3 install -r /disk3/blender-config/3.4/scripts/addons/dream-textures/requirements/win-linux-cuda.txt `
> 
> and now lets enable huggingface diffusers
> 
> `blender-3.4.0-linux-x64/3.4/python/bin$ ./huggingface-cli login`
> 
> `blender-3.4.0-linux-x64/3.4/python/bin$ ./python3.10`
> 
> `>>> from diffusers import StableDiffusionPipeline` `>>> pipe = StableDiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-2")`
> 
> Then inside the plugin got an
> 
> `FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.cache/huggingface/diffusers/models--CompVis--stable-diffusion-v1-4/refs/main'`
> 
> Now Looks like the addon is looking always for a "main" ref but i got installed only the "fp16" ref, a bug in "generator_process/actions/huggingface_hub.py" on "function def _map_model(file)" line 65. Since i'm not using the 1.4 i just deleted the folder '/home/user/.cache/huggingface/diffusers/models--CompVis--stable-diffusion-v1-4'
> 
> Then got "Unsupported model" in the addon with the "stabilityai/stable-diffusion-2" on the N panel.
> 
> So, back to the console to
> 
> `blender-3.4.0-linux-x64/3.4/python/bin$ ./python3.10`
> 
> `>>> from diffusers import StableDiffusionPipeline` `>>> pipe = StableDiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-2-depth")`
> 
> And finally I was able to select the model and run the addon. If only it generate something that isn't garbage... maybe 256*256 is just too low...
> 
> Edit: maybe the log message `Keyword arguments {'depth_estimator': ['transformers', 'DPTForDepthEstimation']} are not expected by GeneratorPipeline and will be ignored.` is related?
> 
> Edit 2: 256x256 was indeed too low.

That's cool Bro. but I'm n't programmer to understand how or where to writ this scripts!
But thank you so much!

**Comment by carson-katri** [comment]
This can happen when you previously had Dream Textures v0.0.5 or earlier where the dependencies were installed into Blender's site-packages.

You can fix this by removing the following folders:
1. `C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\site-packages\wandb`
2. `C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\site-packages\k_diffusion`

Another solution is to remove everything in `C:\Program Files\Blender Foundation\Blender 3.4` and re-install Blender.

**Comment by yych42** [comment]
> This can happen when you previously had Dream Textures v0.0.5 or earlier where the dependencies were installed into Blender's site-packages.
> 
> You can fix this by removing the following folders:
> 
> 1. `C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\site-packages\wandb`
> 2. `C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\site-packages\k_diffusion`
> 
> Another solution is to remove everything in `C:\Program Files\Blender Foundation\Blender 3.4` and re-install Blender.

I've never installed earlier version on my M1 Mac. The Blender 3.4 installation is pretty fresh (just a few days old). Would you still recommend trying to reinstall?

**Comment by sherifdaizer** [comment]
> > This can happen when you previously had Dream Textures v0.0.5 or earlier where the dependencies were installed into Blender's site-packages.
> > You can fix this by removing the following folders:
> > 
> > 1. `C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\site-packages\wandb`
> > 2. `C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\site-packages\k_diffusion`
> > 
> > Another solution is to remove everything in `C:\Program Files\Blender Foundation\Blender 3.4` and re-install Blender.
> 
> I've never installed earlier version on my M1 Mac. The Blender 3.4 installation is pretty fresh (just a few days old). Would you still recommend trying to reinstall?

O.K 
Thanks a lot.
I will try!

**Comment by alperton** [comment]
on blender 3.4 still having the issue, I downloaded Stable diffusion from hugging face but is there a way I can place this manually in C drive? thank you.

**Comment by illieart** [comment]
Same problem on windows 10 blender 3.3

**Comment by k-a-s-o-u** [comment]
> Looks like the addon is using the wrong python interpreter, probably the system one instead of the blender one, so lets install the dependencies manually:
> 
> `blender-3.4.0-linux-x64/3.4/python/bin$ ./python3.10 -m ensurepip`
> 
> `blender-3.4.0-linux-x64$ ./pip3 install -r /disk3/blender-config/3.4/scripts/addons/dream-textures/requirements/win-linux-cuda.txt `
> 
> and now lets enable huggingface diffusers
> 
> `blender-3.4.0-linux-x64/3.4/python/bin$ ./huggingface-cli login`
> 
> `blender-3.4.0-linux-x64/3.4/python/bin$ ./python3.10`
> 
> `>>> from diffusers import StableDiffusionPipeline` `>>> pipe = StableDiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-2")`
> 
> Then inside the plugin got an
> 
> `FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.cache/huggingface/diffusers/models--CompVis--stable-diffusion-v1-4/refs/main'`
> 
> Now Looks like the addon is looking always for a "main" ref but i got installed only the "fp16" ref, a bug in "generator_process/actions/huggingface_hub.py" on "function def _map_model(file)" line 65. Since i'm not using the 1.4 i just deleted the folder '/home/user/.cache/huggingface/diffusers/models--CompVis--stable-diffusion-v1-4'
> 
> Then got "Unsupported model" in the addon with the "stabilityai/stable-diffusion-2" on the N panel.
> 
> So, back to the console to
> 
> `blender-3.4.0-linux-x64/3.4/python/bin$ ./python3.10`
> 
> `>>> from diffusers import StableDiffusionPipeline` `>>> pipe = StableDiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-2-depth")`
> 
> And finally I was able to select the model and run the addon. If only it generate something that isn't garbage... maybe 256*256 is just too low...
> 
> Edit: maybe the log message `Keyword arguments {'depth_estimator': ['transformers', 'DPTForDepthEstimation']} are not expected by GeneratorPipeline and will be ignored.` is related?
> 
> Edit 2: 256x256 was indeed too low.

Thank you for your information!
I had same issue on Windows10 Blender 3.4.0 of this
> `FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.cache/huggingface/diffusers/models--CompVis--stable-diffusion-v1-4/refs/main'`
So I deleted this folder,too. '/home/user/.cache/huggingface/diffusers/models--CompVis--stable-diffusion-v1-4'
But since deleted this folder I got the error message "Unsupported model" in the addon with the "stabilityai/stable-diffusion-2" on the N panel.
Even though I cleaned install Blender to delete 'C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.4'
I assume I need to input this for define pipline.
`>>> from diffusers import StableDiffusionPipeline` `>>> pipe = StableDiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-2")`
I can use python on Windows but don't know on which folder I should run python and input these code.
Could someone can help?

**Comment by carson-katri** [comment]
@k-a-s-o-u You need the `stable-diffusion-2-depth` model to use the projection feature.

**Comment by k-a-s-o-u** [comment]
> @k-a-s-o-u You need the `stable-diffusion-2-depth` model to use the projection feature.

that worked perfectly! I just followed your Setup document to search stabilityai/stable-diffusion-2-1-base but -2- depth worked!
Thank you so much for your quick support!
