### ISSUE TITLE
feature request: connect to automatic11111's server instead of starting its own 

### ISSUE THREAD

**Issue by Ulf3000** [carson-katri/dream-textures#447]
even though i have 12GB vram its stretched thin between my blender eevee scenes, photoshop,browser and stable diffusion and sometimes you gotta close a program or it crashes when vram is filled up , which is not ideal... 

many interfaces including krita and photoshop plugin connect to automatic111111 server , so it would be nice if dream textures could do it too instead of starting its own server and grabbing even more vram.

**Comment by BrahRah** [comment]
Yes that would def. better that would also allow me to use my own dreambooth model files.

**Comment by Vainilla07** [comment]
one possibility would be: Using https://ngrok.com/ to build tonnel to Collab VM and paste the link generated on blender like DreamStudio key 

because in my case i have a AMD GPU and i can't use dream textures or stable difusion in local TT

**Comment by abvgdeabvgde2** [comment]
Please add option to connect to a1111 running on Colab

**Comment by UndeRus** [comment]
Not stale
