### ISSUE TITLE
More text input lines / text block linking

### ISSUE THREAD

**Issue by Atair1** [carson-katri/dream-textures#455]
As the text input is only one line, it gets quite tedious to edit it. I usually copy paste from a text editor window.
I would suggest two changes:
1. allow dynamic adding / removing of input fields that get concatenated. 
2. allow to directly link text bocks instead of input fields

**Comment by carson-katri** [comment]
You can do this with the "File Batch" prompt option. Select a text datablock from the "Text Editor" space and it will use each line as a separate prompt.
