### ISSUE TITLE
Image Cant be generated on a 1080 by 1080 size

### ISSUE THREAD

**Issue by BumbuSateMedan** [carson-katri/dream-textures#465]
### Description

![image](https://user-images.githubusercontent.com/112267801/208946385-ce9c55fd-8fbd-472d-bac1-e88fdd0d7dc7.png)
Seems like something with the looping in line 98 and RuntimeError: The size of tensor a (5) must match the size of tensor b (4) at non-singleton dimension 1 i dont under stand what that means

### Steps to Reproduce

1. Open BLENDER 3.4
2. Go to Image Editor press 'n'
3. change sie to 1080 1080 
4. give the prompt as the screenshot
![image](https://user-images.githubusercontent.com/112267801/208947070-00e6ad08-334b-49ef-93eb-7dff3dfa1f5f.png)

![image](https://user-images.githubusercontent.com/112267801/208947233-ffdba9c1-48ea-4242-aa71-5ee48f20d43f.png)

### Expected Behavior

Error

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by carson-katri** [comment]
You can’t use a depth model for normal image generation. If you want to use the depth model in the image editor, enable “Source Image” and select the “Depth” or “Depth and Color” image type.

**Comment by BumbuSateMedan** [comment]
what does sorce image do is it like img2img ?

**Comment by BumbuSateMedan** [comment]
> You can’t use a depth model for normal image generation. If you want to use the depth model in the image editor, enable “Source Image” and select the “Depth” or “Depth and Color” image type.

Should i open the image ? and what does Source Image do ? is it like img2img or something else
![image](https://user-images.githubusercontent.com/112267801/209148224-5cddcbc0-1f80-4746-a978-9091573c56ff.png)

**Comment by BumbuSateMedan** [comment]
Oh so i cant use the dream texture like the DALLE one ? well if that's it than i think this issue is Closed @carson-katri
