### ISSUE TITLE
Generating images seems to take up a lot of storage space. Is there any way I can remove previous generations and free of some space?

### ISSUE THREAD

**Issue by Pickleaxe** [carson-katri/dream-textures#468]

**Comment by JasonHoku** [comment]
What I've been doing is removing old and un-used materials from the object's material list, leaving only ones that I want to keep on the object, then navigating to the Outliner Menu, Clicking Show Orphaned Data and then Clicking Purge and Accept which deletes all unused and non-saved items from the blend file.
![image](https://user-images.githubusercontent.com/6715569/209414760-ec3745c2-a062-47ca-b87d-1e8d4bae2124.png)
