### ISSUE TITLE
Dream Textures cannot download a model on Mac (M1)

### ISSUE THREAD

**Issue by rehypothecation** [carson-katri/dream-textures#472]
### Description

Like the title says, the add-on cannot download the diffusion model or search for models on M1 Macs. The download bar is stuck at 0%. Searching does nothing.

<img width="670" alt="Screenshot 2022-12-23 at 9 28 18 PM" src="https://user-images.githubusercontent.com/72181637/209418261-e1429e7e-00b5-4d7a-b952-a3a33b755945.png">

### Steps to Reproduce

1. Install.
2. Click download model.

### Expected Behavior

Downloads model.

### Addon Version

macOS (Apple Silicon)

### GPU

Apple Silicon

**Comment by yych42** [comment]
This is related to #440
