### ISSUE TITLE
0.09 Windows CUDA local installs model, does not appear in Blender.

### ISSUE THREAD

**Issue by InfoTheGamer** [carson-katri/dream-textures#474]
### Description

The addon and all dependencies are installed, and installing the model appears to work because the file size of blender in %appdata% increases. However the model does not show up as downloaded in the addon  window nor in the "N" menu with the dropdown showing no model downloaded.

### Steps to Reproduce

1. Restart blender
2. Open a default file, look in Dream Textures addon window and pop-up menu
3. Model is not installed, go to reinstall the model with the addon
4. Model does not show up in popup menu even after "reinstalling" model.

### Expected Behavior

Expected to have a model installed after addon installation, no model appears.

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by andybak** [comment]
Same here.

**Comment by DrEinbrein** [comment]
You need to free up some storage space
You can do this by emptying your trash bin and search for "delete temporary files" in your windows search bar.
It will show you useless files on your computer. Your previously installed, unused models for example.
Fixed it for me
