### ISSUE TITLE
Problem loading config.ocio (and my fix for linux)

### ISSUE THREAD

**Issue by TutajITeraz** [carson-katri/dream-textures#476]
### Description

On my linux machine, Composite Node for AI rendering was unable to load color management profile config.ocio

It was trying to load it from the path that does not exist in linux os.

I needed to change the code:
```
bpy.utils.resource_path('LOCAL')
```

to:
```
bpy.utils.resource_path('SYSTEM')
```

in two places of the plugin, and now it works.

### Steps to Reproduce

Connect composite node
press f12 to render

### Expected Behavior

ai render should show up

### Addon Version

Other (Built from source)

### GPU

NVIDIA

**Comment by carson-katri** [comment]
Feel free to make a PR to add this fix for Linux.
