### ISSUE TITLE
Compositing Dream Textures renders the same frame over and over again (animation and image).

### ISSUE THREAD

**Issue by TutajITeraz** [carson-katri/dream-textures#483]
### Description

When I'm using Compositing Node with Dream Textures enabled, it remembers the first frame i've tried to render, and then it ignores all the changes to the static scene or animation and renders the same frame over and over again with different variants.

I have to release generator to get the modified scene dreamed.

### Steps to Reproduce

1. Create simple scene with 2 objects and animate them
2. Turn on Dream Textures in Rendering Tab, and connect Dream Textures to Composite in Compositing tab.
3. Render image once (F12)
4. Render animation

### Expected Behavior

Generated animation frames should correspond to the original animation frames, but they are not.

### Addon Version

Other (Built from source)

### GPU

NVIDIA

**Comment by NullSenseStudio** [comment]
I can't seem to reproduce this issue. Are you still experiencing it, and if so does the issue still occur if you disable the dream texture render pass?

**Comment by TutajITeraz** [comment]
@NullSenseStudio  Yes. I can reproduce it both on Linux and Windows version (fresh install). Version 0.0.9
I have recorded 3 minute video showing simple setup and the problem:
https://youtu.be/crP5GRJ8NUs

**Comment by TutajITeraz** [comment]
@NullSenseStudio  are you able to reproduce it now, or should I provide more information?

**Comment by NullSenseStudio** [comment]
I see it now. I've only been using depth and seems it only occurs when using color.

**Comment by TutajITeraz** [comment]
Thank you @NullSenseStudio ! 
I have removed the line and it works beautifully! It is so great plugin!
I have already recorded a video tutorial about it https://youtu.be/4C_3HCKn10A
But with that option working, i will be able to do so much more!
