### ISSUE TITLE
Running Dream Textures on CPU

### ISSUE THREAD

**Issue by NoJustAnother** [carson-katri/dream-textures#487]
Is there a way to run Dream Textures on CPU?
i.e. without GPU?

I know that would be awfully slow, but that does not matter

**Comment by carson-katri** [comment]
Yeah under Advanced you can enable “CPU Only”

**Comment by NullSenseStudio** [comment]
Noting that this is not possible with the DreamStudio version since it's only cloud rendering. If you're on Windows with an AMD GPU you can use the CUDA/NVIDIA version, but always in CPU only mode.
