### ISSUE TITLE
Can't install weights/import ckpt file on Linux

### ISSUE THREAD

**Issue by 64Yoshi64** [carson-katri/dream-textures#488]
### Description

After I installed the dependencies in the addon setting (after enabling developer extras) I tried to Download the standard weight model through the add on settings. After that failed, I tried to install a model manually however, after I try to import the checkpoint file, it returns this error:
cannot import name 'CompVisVDenoiser' from 'k_diffusion.external' (/usr/lib/python3.10/site-packages/k_diffusion/external.py)

In the console I also saw that after I'd try to Download the model it spits out this:
bpy.ops.dream_textures.install_model(model="stabilityai/stable-diffusion-2-1")

And I thought "maybe it's just not showing the download", but in the task manager I can see, that blender doesn't download anything...

Also, if this helps, here's the kernel
Kernel: 6.1.1-arch1-1 

(And I'm also using Blender 3.4.1)

### Steps to Reproduce

1. enable developer extras
2. Go to the add on settings
3. Try to download a model/ Try to import a checkpoint file

### Expected Behavior

Download the weight

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by NathanSalapat** [comment]
I am experiencing the same issue.

**Comment by NullSenseStudio** [comment]
That k_diffusion module isn't part of the addon. If you don't know of anything that is using it could you uninstall it?

**Comment by NullSenseStudio** [comment]
Do you mean that you were unable to delete the folder, or that after it was deleted that the same error occurred?

**Comment by 64Yoshi64** [comment]
> That k_diffusion module isn't part of the addon. If you don't know of anything that is using it could you uninstall it?

So, I just tried to delete the files, but it didn't change anything. Or do I have to somehow (don't know how it'd be done, since I don't know how to use pip) remove it using pip?

**Comment by jurassicjordan** [comment]
I'm experiencing this issue only with V2 related models
