### ISSUE TITLE
Error: File "setup.py" or "setup.cfg not found

### ISSUE THREAD

**Issue by nytmaer** [carson-katri/dream-textures#49]
Hello.  

I'm trying to install the dependencies for Dream Textures, but when I go I get the following error 
![Error Message](https://user-images.githubusercontent.com/42222838/191568757-9dad1cf4-0022-4ecd-b9a4-489929e65aff.jpg)

What am I missing?

**Comment by carson-katri** [comment]
This is a duplicate of #47
