### ISSUE TITLE
Project dream texture generate not working and create empty texture(Pink image)

### ISSUE THREAD

**Issue by CryptoSoltan** [carson-katri/dream-textures#493]
1- ive installed the 0.0.9 version 
2- downloaded the depth model
select faces and clicked on project dream texture
without loading or doing anything (PC) it suddenly shows an empty texture material
![image](https://user-images.githubusercontent.com/89420883/210152940-47d51255-70e5-4811-9b34-a12c575a74f7.png)

**Comment by kenster4000** [comment]
same issue here.

**Comment by carson-katri** [comment]
Check Window > Toggle System Console for an error message. And in the future, please use the issue form.
