### ISSUE TITLE
Nothing happens when I select Init Image

### ISSUE THREAD

**Issue by nyu777** [carson-katri/dream-textures#50]
When I click on the file icon in Init Image and select an image from my own file, the Dream Textures settings window closes. When I click on Dream Textures again and try to set it up, the selected image is gone and setting is back to the original state. The version of Blender used is 3.3LTS.
![22](https://user-images.githubusercontent.com/114099714/191569435-f6209e45-5b63-4f19-b00f-d6215d44a817.gif)

**Comment by carson-katri** [comment]
The UI changes in #39 should fix this. For now, click the drop-down next to open and select the file.

**Comment by nyu777** [comment]
Sorry I am not familiar with Github. How can I adapt that update to my Blender?

**Comment by carson-katri** [comment]
It will be easiest to just wait until I can package the next release.

**Comment by nyu777** [comment]
I've done a lot of work and successfully set up a new UI! But looking forward to the next release!
