### ISSUE TITLE
Depth model not showing up in model list

### ISSUE THREAD

**Issue by Slopz** [carson-katri/dream-textures#500]
### Description

Downloaded the depth model using the search feature within the addon, but it doesn't show up in the model list. 

[Clicking on the download button after the model has already been downloaded](http://link.nbbn.cloud/PFPl6)

[Model shows up in local files](http://link.nbbn.cloud/FB9KT)

[Model doesn't show up in model selection](http://link.nbbn.cloud/fCySt)

I've tried deleting the folder of the model locally and redownloading it again, but I got the same result. 

### Steps to Reproduce

1. Search for depth model via the search feature within the addon
2. Click to download it

### Expected Behavior

The model should show up under the models list

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by carson-katri** [comment]
Try deleting the x4 upscaler folder.

**Comment by Slopz** [comment]
> Try deleting the x4 upscaler folder.

That did it! Why is the upscaler causing the issue?

**Comment by carson-katri** [comment]
It is fixed in #479, it only downloaded the fp16 branch when you tried using the upscaler and the model list errors when reading models with no main branch.

**Comment by Slopz** [comment]
Got it. Thanks.
