### ISSUE TITLE
On Linux, unable to download weights (no error output)

### ISSUE THREAD

**Issue by PredellaN** [carson-katri/dream-textures#503]
### Description
Using any weights download feature of the addon does not work: the addon screen flashes for a millisecond, then returns to its previous state. System monitor shows no download is in process.
No error appears in the python output, only one info line is displayed: `bpy.ops.dream_textures.install_model(model="stabilityai/stable-diffusion-2-1")`
This happens both when searching for a model and then clicking on the download button, and when clicking on the larger 2-1 model download button.
Importing v2-1_512-ema-pruned.ckpt manually with the import checkpoint button works, and images generate correctly.

Same issue happens also using branch dream-textures-linux-fixes

### Steps to Reproduce
- Clone the 0.0.9 addon from git
- install the addon in blender 3.4.1
- go in the addon folder
- run "pip3 install -r ./requirements/win-linux-cuda.txt  --target .python_dependencies --upgrade"
- open dream textures in blender's addon menu
- click on any button to download a model
- nothing happens, no error, no download.

### Addon Version
 0.0.9, cloned from git, installed in blender, dependencies then installed with "pip3 install -r ./requirements/win-linux-cuda.txt  --target .python_dependencies --upgrade" (which installed without errors)

### System
Pop_os 22.04, 
NVIDIA RTX A4500

**Comment by PredellaN** [comment]
With today's "build", installing the following models manually (downloading with git clone from huggingface the models and placing them in `.var/app/org.blender.Blender/cache/huggingface/diffusers/` ) works and renders correctly:

stable-diffusion-2-depth-diffusers
stable-diffusion-x4-upscaler
v2-1_512-ema-pruned
v2-1_768-ema-pruned

Downloading them using the download buttons in the addon doesn't work, maybe there's some issue with how filepaths/urls are formed when downloading? is there a way i can check which paths are in use?

**Comment by barshag** [comment]
If I bring model  not from huggingface, where should I put it? (I don't have this directory on my pc)

**Comment by PredellaN** [comment]
> If I bring model not from huggingface, where should I put it? (I don't have this directory on my pc)

In this case i have installed blender through flatpak, if you downloaded the binary (assuming you're on Linux), i suspect you'll find this directory in one of the following:

~/.cache/blender
~/.config/blender
~/.blender

If you can't find it, I'll download the binary blender and check myself tomorrow

**Comment by NullSenseStudio** [comment]
There was a somewhat recent change in diffusers that breaks model downloading. I've suggested a fix for it in #479. If you don't want to wait for that to be completed and merged you can change this line https://github.com/carson-katri/dream-textures/blob/main/generator_process/actions/huggingface_hub.py#L117 to `from diffusers.utils.hub_utils import http_user_agent`

**Comment by PredellaN** [comment]
Thank you! Appears to work correctly now. I'll need to check on how to get a more detailed debug output, i'm not that familiar with python in blender but it would look like this kind of issue should produce a message

**Comment by barshag** [comment]
This is indeed a workaround to install the plugin!
*Unfortunately, it's still not working.*

When I went inside the dream-texture menu I got the following error:
"unsupported pipeline not support depth to image", even if I choose stable
diffusion 512-v.2-0, and put the model  of v2 in:
```'~/.cache/huggingface/diffusers```
