### ISSUE TITLE
Stable Diffusion 2.1 for Blender 3.4.1 Renders a Black Image and black texture for Depth

### ISSUE THREAD

**Issue by avishaked** [carson-katri/dream-textures#505]
### Description

While Rendering an Image in Blender 3.4.1 with Dream Texture Addon - Stable-Diffusion-2-1, and Stable-Diffusion-2-Depth, the result is a black image, or black texture for depth rendering.

### Steps to Reproduce

![render image-1](https://user-images.githubusercontent.com/63899055/211150086-1fd6c027-98dd-4301-a46f-9270552e9f09.jpg)

### Expected Behavior

Getting a Forest Image.

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by avishaked** [comment]
Thanks for the quick answer.
Unfortunately, disabling the “Half Precision” didn't help, and the
generation got stuck in "Requesting redraw..."
More than that, all objects remain black and I can't find the way to return
back to the original color texture.
Regards
Avi

**Comment by avishaked** [comment]
Hi,
Is there any solution for this BUG?
Regards
Avi

**Comment by carson-katri** [comment]
If it says “requesting redraw” just click anything in the 3d view. If that doesn’t work, I’ll need to see an error message from Window > Toggle System Console to know what the issues is.

**Comment by avishaked** [comment]
Read prefs: C:\Users\avisr\AppData\Roaming\Blender Foundation\Blender\3.4\config\userpref.blend
  0%|                                                                                           | 0/25 [00:01<?, ?it/s]
Exception in thread Thread-3 (_send_thread):
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\avisr\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actor.py", line 299, in _send_thread
    response = self._response_queue.get()
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\multiprocessing\queues.py", line 122, in get
    return _ForkingPickler.loads(res)
ModuleNotFoundError: No module named 'torch'

**Comment by NullSenseStudio** [comment]
Unfortunately when that error occurs the real error information couldn't be properly transferred. In most cases however it'll be that you've run out of VRAM.

**Comment by avishaked** [comment]
Hi,
I don't think that I'm running out of VRAM. I monitored the memory while
running Dream Texture with Stable Diffusion 2.1 in blender and it takes
only 9 Gig from 32 Gig.

[image: image.png]
Regards
Avi

**Comment by avishaked** [comment]
The bug is still there.
Closing the issue is ok if the bug will be fixed, not because it was inactive for 7 days.
Regards 
Avi

**Comment by serhiro89** [comment]
After installing Dreamtexture, Stable Diffusion 2.1 for Blender 3.5 following the instructions to download the recommended version by clicking the button does not work

**Comment by avishaked** [comment]
Hi,
After installinglast version of Dreamtexture, Stable Diffusion 2.1 for
Blender 3.5.1, I am still getting the same "black texture while running
Stable Diffusion 2.1 in Depth mode.
I'm getting an error regarding memory size even when I'm running just one
face of a cube to get an AI texture.
Regards
Avi
