### ISSUE TITLE
Error when import checkpoint file

### ISSUE THREAD

**Issue by yukasung** [carson-katri/dream-textures#506]
### Description

I got this error when I try to import Checkpoint File.
![Screenshot 2023-01-07 235448](https://user-images.githubusercontent.com/7720293/211161833-b6a1420d-00c1-4b0d-9a0d-8d17190787f9.png)

### Steps to Reproduce

import Checkpoint File

### Expected Behavior

Please help me resolve this issue.

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by NullSenseStudio** [comment]
This is caused by an issue with the upscaler downloading the fp16 branch. You'll have to find the upscaler model in the addon preferences, open its folder, and delete it.

**Comment by cornpo** [comment]
I have this same problem. It will return results from huggingface, but not download or import the models.

But it's usable in a way. It seems to be picking up on the models installed in `~/.cache/huggingface/diffusers/`

However, cloning the depth model (with git lfs) into `~/.cache/huggingface/diffusers/` gives the following error on use. `The size of tensor a (5) must match the size of tensor b (4) at non-singleton dimension 1` The full large files are present. Blender starts without error. I tried `https://github.com/carson-katri/dream-textures/pull/479` but it didn't help. This error only occurs with `stabilityai/stable-diffusion-2-depth` that was cloned manually by me with git lfs.

Amazing work, regardless.

**Comment by barshag** [comment]
Same error here -Ubuntu.

Tried 3 things:
1) moving the model to ``` ~/.cache/huggingface/diffusers$```,
2)giving my hugging face token, and
3)Delete the ``upscale.py`` and ``pyc``.

But still can't see any model on the list :(

**Comment by cornpo** [comment]
I did manage to import models thru the addon, but not 2.0/2.1 models. The huggingface query results still won't download.

@barshag Did you try import for a 1.4/1.5 model. Or did you manually copy the model into ~/.cache/huggingface/diffusers/

**Comment by barshag** [comment]
Tried 2.1 model and 1.5 from the select-box

in addition I manually copy to that Directory, but still didn't work out. :(

**Comment by barshag** [comment]
Any suggestions what I can do?  should I give it specific name?

**Comment by cornpo** [comment]
Try the import button, but pay special attention to the top right corner of
the dialog that opens. There in the top right corner of the file>open
dialog it will have three options for model types.

That worked for me. What isn't working is the huggingface search. The
2.0/2.1 models don't work for me because of tensor size mismatch.

**Comment by barshag** [comment]
Can't find the import button - I'v got only import prompt

Can you send some printscreen?

(Now I don't have import in the preference nor in the toolbox)



If there is any path to put the file or any other walkaroundthat will be
great - I really want to play with this extension :)

**Comment by cornpo** [comment]
Just used the huggingface search to download a model. My end is fixed.

**Comment by Ainaemaet** [comment]
If the solution was to use a workaround (downloading the model rather than having import work properly) than the issue isn't fixed. 
I can't get import to work either and I've tried dozens of checkpoints.
