### ISSUE TITLE
Generating Something cause old generated texture to become Empty/black

### ISSUE THREAD

**Issue by Elisto** [carson-katri/dream-textures#509]
### Description

Going back and forth between material may cause previously generated texture as blank/black. and any new generated material will be blank/black. 

**Note :  that's not happening every time **

![This](https://user-images.githubusercontent.com/13967541/211224557-1a1cd95e-f1ad-4ef2-8f40-6fd133e84bc1.png)

![this2](https://user-images.githubusercontent.com/13967541/211224564-1ecbbbce-7367-4438-84d3-40f57aa1039a.png)

### Steps to Reproduce

1. Generating a bunch of texture
2. Change the current selected material 
3. Generated new texture

### Expected Behavior

Generating new texture.

### Addon Version

Other (Built from source)

### GPU

NVIDIA

**Comment by carson-katri** [comment]
This should be resolved by #495
