### ISSUE TITLE
Error: Cannot find command `git`

### ISSUE THREAD

**Issue by nytmaer** [carson-katri/dream-textures#51]
Getting a different error now.  

![Error Message 2](https://user-images.githubusercontent.com/42222838/191579000-0b3ff0a2-090c-44f2-80b6-9ac336b52658.jpg)

**Comment by carson-katri** [comment]
Make sure you install git first.

**Comment by nytmaer** [comment]
Seems to be working now.  Thank you.  Sorry, still new to a lot of this, but appreciate the quick responses.
