### ISSUE TITLE
How does texture projection work under the hood?

### ISSUE THREAD

**Issue by mj-hue** [carson-katri/dream-textures#510]
Hi, thanks for releasing this great project! 

In the README, you briefly mention that you use the depth2img model to generate textures, could you please provide a bit more details on this? For example, if the mechanism is to render the depth images from different viewpoints and convert them to RGB images, how do you handle the overlapping region?

**Comment by carson-katri** [comment]
Currently it only projects from a single view. You can see the operator here: https://github.com/carson-katri/dream-textures/blob/main/operators/project.py

And the stable diffusion pipeline here: https://github.com/carson-katri/dream-textures/blob/main/generator_process/actions/depth_to_image.py

**Comment by mj-hue** [comment]
Thank you for the prompt reply.
Sorry but I don't quite understand the blender scripting. If the texture is obtained from the every single view seperately, when we move the viewport, wouldn't we get a totally different image from the diffusion model? But in the demo, it seems changing the viewport will not change the textures that have already been generated in previous viewports.

**Comment by carson-katri** [comment]
It generates new UVs that match the projected angle. Then it makes a new material using the generated image and that UV map. So the texture is frozen onto the mesh from that perspective.
