### ISSUE TITLE
Upscaling fails installation

### ISSUE THREAD

**Issue by vilemduha** [carson-katri/dream-textures#511]
### Description

1. Installed dt on windows 10 - 
2. generated texture, 
3. tried to upscale it
got following output.

`100%|██████████████████████████████████████████████████████████████████████████████████| 25/25 [00:13<00:00,  1.89it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 25/25 [00:13<00:00,  1.82it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 100/100 [00:54<00:00,  1.82it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 100/100 [01:07<00:00,  1.48it/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████| 485/485 [00:00<00:00, 241kB/s]
C:\Users\vilem\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\.python_dependencies\huggingface_hub\file_download.py:127: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\vilem\.cache\huggingface\diffusers. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Downloading: 100%|█████████████████████████████████████████████████████████████████████| 300/300 [00:00<00:00, 149kB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████| 348/348 [00:00<00:00, 114kB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████| 634/634 [00:00<00:00, 316kB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████| 681M/681M [01:23<00:00, 8.14MB/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 525k/525k [00:00<00:00, 1.06MB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 460/460 [00:00<00:00, 228kB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 825/825 [00:00<00:00, 275kB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.06M/1.06M [00:00<00:00, 1.69MB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 977/977 [00:00<00:00, 321kB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 982/982 [00:00<00:00, 492kB/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 947M/947M [01:35<00:00, 9.90MB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 558/558 [00:00<00:00, 186kB/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 111M/111M [00:09<00:00, 11.6MB/s]
Fetching 14 files: 100%|███████████████████████████████████████████████████████████████| 14/14 [03:20<00:00, 14.35s/it]████████████████████████████████████████████████████████▍ | 110M/111M [00:09<00:00, 11.7MB/s]
Exception: Traceback (most recent call last):
  File "C:\Users\vilem\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actor.py", line 273, in _receive
    for res in iter(response):
  File "C:\Users\vilem\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actions\upscale.py", line 52, in upscale
    low_res_image = Image.fromarray(image)
  File "C:\Users\vilem\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\.python_dependencies\PIL\Image.py", line 2982, in fromarray
    arr = obj.__array_interface__
AttributeError: 'str' object has no attribute '__array_interface__'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\vilem\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actor.py", line 111, in run_callbacks
    done_callback(self)
  File "C:\Users\vilem\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\operators\upscale.py", line 114, in image_done
    tile: ImageUpscaleResult = future.result()
  File "C:\Users\vilem\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actor.py", line 58, in result
    raise self._exception
AttributeError: 'str' object has no attribute '__array_interface__'`

### Steps to Reproduce

1. Installed dt on windows 10 - 
2. generated texture, 
3. tried to upscale it

Probably cause - the machine didn't have 'developer mode' on?

### Expected Behavior

it should work ;)

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by carson-katri** [comment]
This was resolved in #410 but is not present in any release yet.
