### ISSUE TITLE
My suggestions

### ISSUE THREAD

**Issue by faxcorp** [carson-katri/dream-textures#514]
- Input custom image as depth map
- See depth map before submitting to generate
- Image names as prompt, not just numbers

Thank you for consideration

**Comment by carson-katri** [comment]
You can do the first one already. Use “Source Image” set to “Modify” and choose the “Depth” input option.

**Comment by faxcorp** [comment]
Is it possible to "stable diffuzify" an object from multiple angles and make a tri-planar like texture of the object? lets say object name is "soda_can", can i press a button and generate 6 textures like box projection with the prompt "soda can" ? maybe a geometry node or something?

**Comment by GottfriedHofmann** [comment]
>     * Image names as prompt, not just numbers

Seems like this feature is in the works already: https://github.com/carson-katri/dream-textures/pull/499

**Comment by Dekker3D** [comment]
> Is it possible to "stable diffuzify" an object from multiple angles and make a tri-planar like texture of the object? lets say object name is "soda_can", can i press a button and generate 6 textures like box projection with the prompt "soda can" ? maybe a geometry node for this plugin to do a tool myself?

#446 deals with this.

**Comment by NNNenov** [comment]
> You can do the first one already. Use “Source Image” set to “Modify” and choose the “Depth” input option.

Hello, Im new to the plugin and I'd like to debug my depth map, it seems the camera needs to be very close to the geometry to generate good results, it would be nice if there was a way to define the depth range you want to use. First I wanted to try with a custom depth map, but I am not sure where can I find the "source image" option that you refer to?
