### ISSUE TITLE
Downloading stable diffusion 2.1 in dream textures does not work along with all other models

### ISSUE THREAD

**Issue by illieart** [carson-katri/dream-textures#516]
### Description

It starts for a millisecond then stops automatically, that's all that happens and provides no explanation. Please help me

### Steps to Reproduce

1. Install Dream textures 
2. Enable Paint: Dream Textures
3. Click on "Download Stable Diffusion v2.1 (Recommended)

### Expected Behavior

The expected Behaviour should be: Downloading Stable Diffusion 2.1

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by jurassicjordan** [comment]
I am also having this problem trying to install "stabilityai/stable-diffusion-2-depth" I click download it instantly stops.

**Comment by carson-katri** [comment]
This can happen when you previously had Dream Textures v0.0.5 or earlier where the dependencies were installed into Blender's site-packages.

You can fix this by removing the following folders:
1. `C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\site-packages\wandb`
2. `C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\site-packages\k_diffusion`

Another solution is to remove everything in `C:\Program Files\Blender Foundation\Blender 3.4` and re-install Blender.

**Comment by myk68** [comment]
I have blender loaded from steam. These files dont seem to appear in that folder but i am getting the same issue.
Anywhere else I should look?

**Comment by JasonHoku** [comment]
> I have blender loaded from steam. These files dont seem to appear in that folder but i am getting the same issue. Anywhere else I should look?

For me, dream textures installs to %appdata% like so: `C:\Users\JasonHoku\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures`

**Comment by myk68** [comment]
cheers for the reply jasonhoku
sadly not. That just breaks the install and I have to reinstall DT, then back to not downloading the model.
Im loading up direct Blender, no steam, to see if that works

**Comment by JasonHoku** [comment]
> cheers for the reply jasonhoku sadly not. That just breaks the install and I have to reinstall DT, then back to not downloading the model. Im loading up direct Blender, no steam, to see if that works

I also ended up running Blender as Admin for the DT install and I downgraded Blender out of alpha to 3.4 to get it working.

Maybe try those things, making sure you have ~20GB (at the very least) free on C:/ (or have changed your huggingface/model folder locations and going over the (dt setup docs)[https://github.com/carson-katri/dream-textures/blob/main/docs/SETUP.md] again.

Might be worth trying a PC reboot to clear any hanging processes or cached files too.

**Comment by myk68** [comment]
Hi, so the separate install made no difference, Blender already had DT installed so it was using a collective config somewhere.
I checked the system console and it gave me a huggingface folder not there.  So i did a search and found the folder full of 12gb+ files for SD.  
Deleted this then removed the Blenders. then the install worked as it should on a new install of blender and DT.
hope this helps if anyone has this issue.
