### ISSUE TITLE
More info in relation to checkpoint management and Linux setup please

### ISSUE THREAD

**Issue by jurassicjordan** [carson-katri/dream-textures#520]
**Is your feature request related to a problem? Please describe.**
OK this addon is amazing, but there's seriously a problem with the lack of documentation and clear instructions for certain platforms. I can understand why you don't include a release specifically for linux, but you don't even list the instructions clearly for linux. nowhere in the "contributing" instructions does it say I have to restart blender before attempting to use the addon. Along with that, there is barely any info when it comes to managing ckpt files. you expect me to know what the differences between the types of V2 files there are, you expect me to just KNOW that you have to set the model type when importing a checkpoint. why is this info nowhere in the readme? Do I need a V2 model in addition to the depth aware model? No info about that either. I realize there is a model installation tool built into the addon to install models from huggingface's database, but currently at this moment, it is failing to work for me. I have no other option. Clearly both Epsilon and Prediction model versions are not even close to the type that depth-aware is. So how the heck am I supposed to get the correct model? 
**Describe the solution you'd like**
I would like if you could please have more documentation, have a clear and concise set of heavily detailed instructions for installing on linux. Oh and please don't list it as "contributing". Yes many linux users are proud developers, but not all of them, I'm just a 3D artist trying to avoid spending a thousand dollars every 2 years on a new mac. All I ask is some simple but in-detail instructions for installing on linux, under the heading of "linux installation instructions", not "contributing". I'm not even asking for a dedicated linux release, just information. 
In addition please have more info in relation to managing ckpt models in the addon's preferences, please put somewhere in the readme, anywhere! "When selecting a checkpoint, be sure to check the version type on the import window, V1 coresponds with SD V1.0-1.4, V2-Epsilon corresponds with blabla and V2-Predictive corresponds to blabla." A button to remove checkpoints from the list would also be nice.
**Describe alternatives you've considered**
An official linux release would be very nice, but it is not something I am demanding. Since that would understandably be alot more work just to have two simultaneous releases for every new version. Please don't interpret this as a demand for a linux release, I just want information.

**Additional context**
Also pls fix whatevers going on with the huggingface model downloader...like its not working and im sure theres plenty of bug reports about it, I just thought I'd mention it. thank you.

**Comment by carson-katri** [comment]
The instructions for importing a checkpoint are here: https://github.com/carson-katri/dream-textures/blob/main/docs/SETUP.md#importing-checkpoints

As for more detailed manual setup instructions, I’ll take a look.

**Comment by JasonHoku** [comment]
It may be helpful to mention you can rename pytorch_diffusion.bin files to .ckpt files and maybe also offer info on moving the folder to other drives with the use of a symlink. (Network drives may require UMD path formatting on Windows).

Converting and merging models (as well as the many other SD tools) with https://github.com/AUTOMATIC1111/stable-diffusion-webui could be useful for some as well.

**Comment by PredellaN** [comment]
The issue with Linux is that so far I have had very different experiences between versions and installing the addon, but with the last 0.0.9 version and my new machine (Pop OS 22.04 + RTX A4500 mobile) it seems pretty straightforward:

- Clone the repo OR download a zip from the addon homepage: Clone > Download .zip
- Install the .zip file as blender addon
- Install the dependencies, either with the method described in "Contributing" or using command `pip3 install -r ./requirements/win-linux-cuda.txt --target .python_dependencies --upgrade` from the folder where the addon is installed (as in my case it's supposed to be Linux + CUDA)

That's it, after this I can install models and use all of the features (generation, upscaling, depth, gen with 768 model, etc.) the download issue is not present anymore after the recent fix
