### ISSUE TITLE
Please do not unpack checkpoint files.

### ISSUE THREAD

**Issue by Yakumounr** [carson-katri/dream-textures#529]
Dream Textures unpacks downloaded and imported checkpoints into `%userprofile%\.cache\huggingface\diffusers`
This is a quite wasteful for disk space which is especially unfortunate on SSD, I even have some 2GB checkpoints that expand to 5.1GB.

Unless it is a requirement for some functionality for Dream Textures to do this unlike other Stable Diffusion based systems, it should simply copy the imported files unchanged.

As an even further improved extra it would be incredibly useful if the option to import in-place was offered, storing and using a link to the current location of the file instead of duplicating it at all.

**Comment by carson-katri** [comment]
This is required as dream textures does not read checkpoint files, it uses diffusers format.
