### ISSUE TITLE
Local models

### ISSUE THREAD

**Issue by guzuligo** [carson-katri/dream-textures#531]
Instead of using 🤗's API, I'd like to use local models. Is there a way, or does that have to be developed?

**Comment by carson-katri** [comment]
The addon does generate locally, using the diffusers package (created by Hugging Face). DreamStudio is the only cloud option preset.

**Comment by carson-katri** [comment]
If you’re referring to using a diffusers-format model you trained locally, you can place the folder in `C:\Users\YOURUSER\.cache\huggingface\diffusers`

**Comment by guzuligo** [comment]
I posted it there but it doesn't seem I can choose it .🫤

**Comment by carson-katri** [comment]
Are there any errors in Window > Toggle System Console?

**Comment by guzuligo** [comment]
I just have a ckpt. How can I construct a json for it?

**Comment by carson-katri** [comment]
Oh, then you need to use the “Import Checkpoint” button in the preferences :)

Here’s the instructions for that: https://github.com/carson-katri/dream-textures/blob/main/docs/SETUP.md#importing-checkpoints

The model would need to be in diffusers format if you wanted to just place it there.

**Comment by guzuligo** [comment]
No import button =/
![image](https://user-images.githubusercontent.com/4189008/213871710-f3191f5a-d4d5-4bb8-adf3-ed69c71376da.png)

**Comment by carson-katri** [comment]
Seems you have downloaded a DreamStudio-only version of the addon. You need to get one that supports local generation, such as the CUDA version: https://github.com/carson-katri/dream-textures/releases/tag/0.0.9
