### ISSUE TITLE
Dream texture FILTER node for compositor. 

### ISSUE THREAD

**Issue by solyaevwork** [carson-katri/dream-textures#532]
It would be great to implement dream texture exactly as a filter node in the compositor pipeline. 
(yes, I know there is a pass for cycles now, but it doesn't do much)

This will allow you to separate the Depth and color maps and create animation variants without correcting the 3D scene.

Also, if the filter nodes can be run one after the other, it will allow you to create a cascade processing of multiple Prompts with different settings.

(separate channels of depth and color into the node would be great)

**Comment by carson-katri** [comment]
This is unfortunately not possible in Blender’s Python API.
