### ISSUE TITLE
Separate model file folder

### ISSUE THREAD

**Issue by Leteen** [carson-katri/dream-textures#534]
Hi, I've been trying to get the addon to work with some other models that I have on another SSD and I can't get it to work.

I've tried changing the WEIGHTS_PATH but that results in "AttributeError: 'NoneType' object has no attribute 'modules'" when running...

Any solutions to this? I need to use this addons with the models on a separate folder

**Comment by carson-katri** [comment]
The addon does not use the `.ckpt` file format, so you must import the checkpoint file through the addon UI to convert it.

You can change where the converted models (and downloaded ones) are installed by changing the system environment variable `HF_HOME` to a different path.
