### ISSUE TITLE
Image Not Drawing

### ISSUE THREAD

**Issue by YourDLCMaster** [carson-katri/dream-textures#535]
### Description

I don't know if this issue exists so I'll open one for now. Also, I have a 16 series NVIDIA card so that may be a problem.

I have installed dream textures (CUDA version for Windows, I have an NVIDIA card) and Stable Diffusion 2 Depth alongside it via the addon settings. In Edit Mode, if I select all faces of an object and attempt to run Dream Texture Projection, my GPU usage spikes to near 100% and it counts all 25 steps, but no noise (let alone a texture) appears on the selected object. In the Image Editor, it simply says "Starting...", spikes my GPU and slows down my computer for a second and then finishes with no result, only an output in the History. I've tried this multiple times and restarted both Blender and my computer multiple times to no avail, and stabilityai/stable-diffusion-2-depth is the only model I have access to even after entering my token. I do not have access to cloud rendering with DreamStudio. I am also using version 0.0.9 (latest as of writing) and Blender version 3.4.1.

Here are some example screenshots.
![image_2023-01-23_171949690](https://user-images.githubusercontent.com/98079688/214193494-c35bc710-7135-46ca-bc69-812b8e95b277.png)
![image_2023-01-23_172019510](https://user-images.githubusercontent.com/98079688/214193542-20c90c55-0547-488b-87a6-9f25527f07f5.png)
![image_2023-01-23_172053967](https://user-images.githubusercontent.com/98079688/214193598-c1409742-6346-474f-89e5-ee1f8b4af3bc.png)
![image_2023-01-23_172124171](https://user-images.githubusercontent.com/98079688/214193651-efaaec98-8a10-4222-b31e-d2f00cd252f3.png)

### Steps to Reproduce

1. Install Dream Textures (Windows CUDA) version 0.0.9 on Blender 3.4.1
2. Install Stable Diffusion 2 Depth from the provided model list in the Add-ons Preferences submenu, as well as install the required checkpoint file and add key if neccesary.
3. Open Edit Mode in the 3D Viewport and open the Dream Texture Projection menu (N)
4. Set the Pipeline to Stable Diffusion, the model to stabilityai/stable-diffusion-2-depth, and the Prompt type to Texture
5. Set the subject to be whatever (seamless or not) and the Width/Height to whatever
6. Under Advanced, set Random Seed on and the Steps to 25
7. Select all faces of the selected object (A) and click "Project Dream Texture".

### Expected Behavior

There should be noise appearing as per usual on the object, but no noise or image appears. The object remains with the same color and texture.

### Addon Version

Windows (CUDA)

### GPU

NVIDIA 16 Series

**Comment by JasonHoku** [comment]
Hey @YourDLCMaster, try checking Blender's system console in the top left under the "Window" dropdown next to "File" and "Edit" for any error messages. Then [search in the issues list](https://github.com/carson-katri/dream-textures/issues?q=is%3Aissue) with your error message.

![image](https://user-images.githubusercontent.com/6715569/214434929-cca7a1c4-2bf4-4983-a47c-ff2dba05e7e6.png)


It's probably one of a couple things so that system console error message should tell what's going on.

**Comment by YourDLCMaster** [comment]
I just ran it with the console open, it finished with
`Read prefs: C:\Users\<user>\AppData\Roaming\Blender Foundation\Blender\3.4\config\userpref.blend                         The config attributes {'depth_estimator': ['transformers', 'DPTForDepthEstimation']} were passed to GeneratorPipeline, but are not expected and will be ignored. Please verify your model_index.json configuration file.                        Keyword arguments {'depth_estimator': ['transformers', 'DPTForDepthEstimation']} are not expected by GeneratorPipeline and will be ignored.                                                                                                     You have disabled the safety checker for <class 'dream_textures.generator_process.actions.depth_to_image.depth_to_image.<locals>.GeneratorPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254 .                                                            0%|                                                                                           | 0/25 [01:10<?, ?it/s]  `
The Project Dream Texture button counted up 25 steps, but the console remained at 0% progress. Running it again just starts over again at the "The config attributes" line right under the empty progress bar.
`The config attributes {'depth_estimator': ['transformers', 'DPTForDepthEstimation']} were passed to GeneratorPipeline, but are not expected and will be ignored. Please verify your model_index.json configuration file.                        Keyword arguments {'depth_estimator': ['transformers', 'DPTForDepthEstimation']} are not expected by GeneratorPipeline and will be ignored.`
I don't know if there's a problem with the proclaimed model_index.json file or if I should be concerned about the keyword arguments note, or if everything's fine.

**Comment by potesd** [comment]
I'm having the exact same problem on multiple computers. It seems to me that the most recent git update broke some things. 

I just get 

" 0%|                                                                                           | 0/30 [01:19<?, ?it/s]" 

constantly in the system console, while Dream Textures shows that it's generating steps.

**Comment by CongHoang1** [comment]
same problem with me ( im not good english btw)
