### ISSUE TITLE
Installed and dowloaded models, error message when I press 'Generate'

### ISSUE THREAD

**Issue by Daandeleon** [carson-katri/dream-textures#536]
### Description

v0.0.9, Blender 3.4.1 - I get the following error after pressing Generate:

Python: Traceback (most recent call last):
  File "C:\Users\Daniël\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\operators\dream_texture.py", line 58, in execute
    generated_args = scene.dream_textures_prompt.generate_args()
  File "C:\Users\Daniël\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\property_groups\dream_prompt.py", line 230, in generate_args
    args = { key: getattr(self, key) for key in DreamPrompt.__annotations__ }
  File "C:\Users\Daniël\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\property_groups\dream_prompt.py", line 230, in <dictcomp>
    args = { key: getattr(self, key) for key in DreamPrompt.__annotations__ }
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcc in position 1: invalid continuation byte

Anybody have any clue why this is happening?

### Steps to Reproduce

1. Install Dream Textures
2. Download stabilityai models (2-1, 2-1-base, 2-1-depth)
3. enter prompt into dream
4. press generate

### Expected Behavior

Generate a texture

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by JasonHoku** [comment]
I bet this is because 'Daniël' has a non utf-8 letter and it's trying to decode the path with that letter in it

**Comment by Daandeleon** [comment]
> I bet this is because 'Daniël' has a non utf-8 letter and it's trying to decode the path with that letter in it

It's giving different decoding errors (0fx0, 0xcc) and postitions (1, 3) so I don't think thats it?

**Comment by JasonHoku** [comment]
That is rather interesting.

Do you know what commit hash or version of the DT GitHub repo you are on?

Some additional research shows that decoding of utf-8 is handles automatically on py3 but not on <= py2. Maybe your system doesn't have the right version of python installed. Can you check the version of Blender's Python in the Blender scripting tab? It would be shown like so in that tab (if not you may need to enable blender developer ui settings) : 
![image](https://user-images.githubusercontent.com/6715569/214714794-42ded184-e1b6-4286-af52-c4942821ae73.png)

And also what method of Blender installation did you use?

**Comment by NullSenseStudio** [comment]
Every time I've seen this error occur it's on an account with special characters in the name. Try moving the huggingface folder at `%homepath%/.cache/huggingface` to not be in your user folder and set the `HF_HOME` system environment variable to its new location.
