### ISSUE TITLE
Stuck at Starting.... (ModuleNotFoundError: No module named 'torch')

### ISSUE THREAD

**Issue by Voxeliorn** [carson-katri/dream-textures#538]
### Description

![image](https://user-images.githubusercontent.com/86244069/214593592-30f1e7aa-d87f-4240-9f77-5bd18924592f.png)

basically my pc freezes then the addon is stuck at _Starting..._

maybe because i have 2 gpu's in my latop
iGpu: Intel XE
dGpu: Nvidia MX330 (i know its trash but i think it _should_ atleast work?)
Heres some Stats for the nivida GPU
![image](https://user-images.githubusercontent.com/86244069/214594571-3ff1eb98-cf02-4be0-85f7-3b5b5bbe2d96.png)
I thought 5.9 GB > 4 GB (needed)  so i thought it would work wonders

### Steps to Reproduce

1. install the CUDA addon.
2. accidently install the base but then also install the depth models.
3. open the dream tab and select the depth model.
4. put anything in the prompt.
5. you will see a pink texture after your pc laggs and it will say "Starting..." 
6. discover about blenders system console after looking at this issue page
7. you will see ModuleNotFoundError: No module named 'torch'

### Expected Behavior

It saying "Starting..." for a few seconds then generating something
(also sorry if this is a dumb issue because i am dumb)

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by potesd** [comment]
Same here, but only with the Depth Model, which doesn't make any sense. 

"Exception in thread Thread-4 (_send_thread):
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\dpote\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actor.py", line 299, in _send_thread
    response = self._response_queue.get()
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\multiprocessing\queues.py", line 122, in get
    return _ForkingPickler.loads(res)
ModuleNotFoundError: No module named 'torch'"

**Comment by JasonHoku** [comment]
Generally `No module named 'torch'` means your ram has ran out of memory while attempting to run the generation as discussed in: https://github.com/carson-katri/dream-textures/issues/184, https://github.com/carson-katri/dream-textures/issues/505, https://github.com/carson-katri/dream-textures/issues/437

You might find luck with assigning 8GB-16GB+ of virtual memory.

You may want to test with 128px or 256px generations or use the DreamStudio version for a cloud rendering solution.

**Comment by carson-katri** [comment]
It's probable that PyTorch will only use the dedicated memory it shows there, so 2GB which would not be possible with the current optimizations available.

**Comment by Voxeliorn** [comment]
> It's probable that PyTorch will only use the dedicated memory it shows there, so 2GB which would not be possible with the current optimizations available.

okay :)
