### ISSUE TITLE
Button not showing (in upper right corner), script reload error

### ISSUE THREAD

**Issue by cornpo** [carson-katri/dream-textures#54]
Hello,

Platform; Manjaro, AMD/ROCm 6800xt, functional in stable-diffusion-webui Blenders 3.3 & 3.4 from blender.org's binaries.

Steps to reproduce; On similar machine, Install dream_textures.zip. After using Blender's python -mpip to install dependencies. Press F3 System > Reload Scripts. What follows is the error.

```
  File "/home/corn/Downloads/blender-3.4.0-alpha+master.6f15141f2731-linux.x86_64-release/3.4/scripts/addons/io_scene_gltf2/blender/com/gltf2_blender_ui.py", line 24, in poll
    return space.type == "NODE_EDITOR" \
AttributeError: 'NoneType' object has no attribute 'type'
Exception in module unregister(): '/home/corn/.config/blender/3.4/scripts/addons/dream_textures/__init__.py'
Traceback (most recent call last):
  File "/home/corn/Downloads/blender-3.4.0-alpha+master.6f15141f2731-linux.x86_64-release/3.4/scripts/modules/addon_utils.py", line 421, in disable
    mod.unregister()
  File "/home/corn/.config/blender/3.4/scripts/addons/dream_textures/__init__.py", line 102, in unregister
    panel.unregister()
  File "/home/corn/.config/blender/3.4/scripts/addons/dream_textures/ui/panel.py", line 110, in unregister
    unregister_class(cls)
RuntimeError: unregister_class(...):, missing bl_rna attribute from 'RNAMeta' instance (may not be registered)
Reloading: <module 'bl_operators' from '/home/corn/Downloads/blender-3.4.0-alpha+master.6f15141f2731-linux.x86_64-release/3.4/scripts/startup/bl_operators/__init__.py'>
Reloading: <module 'bl_ui' from '/home/corn/Downloads/blender-3.4.0-alpha+master.6f15141f2731-linux.x86_64-release/3.4/scripts/startup/bl_ui/__init__.py'>
Reloading: <module 'keyingsets_builtins' from '/home/corn/Downloads/blender-3.4.0-alpha+master.6f15141f2731-linux.x86_64-release/3.4/scripts/startup/keyingsets_builtins.py'>
Reloading: <module 'nodeitems_builtins' from '/home/corn/Downloads/blender-3.4.0-alpha+master.6f15141f2731-linux.x86_64-release/3.4/scripts/startup/nodeitems_builtins.py'>
gc.collect() -> 1580
```

I haven't tried executing stable-diffusion, from dream, with Blender's python. I do have torch and the entire requirements-lin-AMD.txt installed fine.

Unrelated to title, when you press the install dependencies button in dream_textures you get...

```
pip 22.2.2 from /home/corn/.local/lib/python3.10/site-packages/pip (python 3.10)
/home/corn/Downloads/blender-3.4.0-alpha+master.6f15141f2731-linux.x86_64-release/3.4/python/bin/python3.10: No module named pip
```
Here's the output of >>>help("modules")

`Cryptodome          builtins            json5               server
Cython              bz2                 jsonmerge           setproctitle
DateTime            cProfile            jsonschema          setup
IPython             cachetools          jupyter             setuptools
PIL                 caffe2              jupyter_client      shelve
__future__          calendar            jupyter_core        shlex
_abc                certifi             jupyterlab_widgets  shortuuid
_aix_support        cgi                 k_diffusion         shutil
_ast                cgitb               keyword             signal
_asyncio            chardet             kiwisolver          site
_bisect             charset_normalizer  kornia              six
_blake2             chunk               libextern_draco     skimage
_bootsubprocess     cleanfid            libfuturize         sklearn
_bz2                click               libpasteurize       smmap
_codecs             clip                linecache           smtpd
_codecs_cn          cmath               llvmlite            smtplib
_codecs_hk          cmd                 lmdb                sndhdr
_codecs_iso2022     code                locale              sniffio
_codecs_jp          codecs              logging             socket
_codecs_kr          codeop              lpips               socketio
_codecs_tw          collections         lzma                socketserver
_collections        colorsys            mailbox             spwd
_collections_abc    commonmark          mailcap             sqlite3
_compat_pickle      compileall          main                sre_compile
_compression        concurrent          markdown            sre_constants
_contextvars        configparser        markupsafe          sre_parse
_crypt              contextlib          marshal             srt
_csv                contextvars         math                srt_tools
_ctypes             contourpy           matplotlib          ssl
_ctypes_test        copy                matplotlib_inline   stack_data
_curses             copyreg             mimetypes           stat
_curses_panel       crypt               mmap                statistics
_datetime           csv                 modulefinder        streamlit
_decimal            ctypes              multidict           string
_distutils_hack     curses              multiprocessing     stringprep
_elementtree        cv2                 nest_asyncio        struct
_functools          cycler              netrc               subprocess
_hashlib            cython              networkx            sunau
_heapq              dataclasses         nis                 symtable
_imp                datetime            nntplib             sys
_io                 dateutil            ntpath              sysconfig
_json               dbm                 nturl2path          syslog
_locale             debugpy             numba               tabnanny
_lsprof             decimal             numbers             taming
_lzma               decorator           numpy               tarfile
_markupbase         dependency_injector oauthlib            telnetlib
_md5                deprecate           omegaconf           tempfile
_multibytecodec     difflib             opcode              tensorboard
_multiprocessing    dis                 operator            tensorboard_data_server
_opcode             distlib             optparse            tensorboard_plugin_wit
_operator           distutils           os                  termios
_osx_support        dns                 ossaudiodev         test_tube
_pickle             dockerpycreds       packaging           textwrap
_posixshmem         doctest             pandas              this
_posixsubprocess    einops              parso               threading
_py_abc             email               past                threadpoolctl
_pydecimal          encodings           pathlib             tifffile
_pyio               engineio            pathtools           time
_pyrsistent_version ensurepip           pdb                 timeit
_queue              entrypoints         pexpect             tlz
_random             enum                pickle              token
_sha1               errno               pickleshare         tokenize
_sha256             eventlet            pickletools         tokenizers
_sha3               examples            pip                 toml
_sha512             executing           pipes               toolz
_signal             facexlib            pkg_resources       torch
_sitebuiltins       faulthandler        pkgutil             torch_fidelity
_socket             fcntl               platform            torchdiffeq
_sqlite3            filecmp             platformdirs        torchgen
_sre                fileinput           plistlib            torchmetrics
_ssl                filelock            poplib              torchvision
_stat               filterpy            posix               tornado
_statistics         flask               posixpath           tqdm
_string             flask_cors          pprint              trace
_strptime           flask_socketio      profile             traceback
_struct             fnmatch             promise             tracemalloc
_symtable           fontTools           prompt_toolkit      traitlets
_sysconfigdata__linux_x86_64-linux-gnu fractions           pstats              transformers
_testbuffer         frozenlist          psutil              tty
_testcapi           fsspec              pty                 types
_testimportmultiple ftfy                ptyprocess          typing
_testinternalcapi   ftplib              pudb                typing_extensions
_testmultiphase     functools           pure_eval           tzdata
_thread             future              pvectorc            tzlocal
_threading_local    gc                  pwd                 unicodedata
_tracemalloc        genericpath         py_compile          unittest
_warnings           getopt              pyarrow             urllib
_weakref            getpass             pyasn1              urllib3
_weakrefset         gettext             pyasn1_modules      urwid
_xxsubinterpreters  gfpgan              pyclbr              uu
_xxtestfuzz         git                 pydantic            uuid
_yaml               gitdb               pydeck              uvicorn
_zoneinfo           glob                pydevd_plugins      validators
abc                 google_auth_oauthlib pydoc               venv
absl                graphlib            pydoc_data          virtualenv
accelerate          greenlet            pyexpat             wandb
addict              grp                 pygments            warnings
aifc                grpc                pylab               watchdog
aiohttp             gzip                pympler             wave
aiosignal           h11                 pyparsing           wcwidth
albumentations      hashlib             pyrsistent          weakref
altair              heapq               pytorch_lightning   webbrowser
antigravity         hmac                pytz                werkzeug
antlr4              html                pytz_deprecation_shim wheel
anyio               http                pywt                widgetsnbextension
argparse            huggingface_hub     qudida              wsgiref
array               idna                queue               xdrlib
ast                 imageio             quopri              xml
asttokens           imageio_ffmpeg      random              xmlrpc
async_timeout       imaplib             re                  xmltodict
asynchat            imghdr              regex               xxlimited
asyncio             imp                 reprlib             xxlimited_35
asyncore            importlib           requests            xxsubtype
atexit              importlib_metadata  requests_oauthlib   yaml
attr                inspect             resize_right        yapf
attrs               integrations        resource            yapftests
audioop             io                  rich                yarl
backcall            ipaddress           rlcompleter         zipapp
base64              ipykernel           rsa                 zipfile
basicsr             ipykernel_launcher  runpy               zipimport
bdb                 ipywidgets          sched               zipp
bidict              itertools           scipy               zlib
binascii            itsdangerous        secrets             zmq
binhex              jedi                select              zoneinfo
bisect              jinja2              selectors           zstandard
blinker             joblib              semver              
blobfile            json                sentry_sdk `

I've tried this in 3.3 too. Same result, have to install depends manually, and never see the button. About to try again with 3.3

**Comment by cornpo** [comment]
Short update;

I installed blender with pacman. When I ran it non-sudo I get a permission error.

`Modules Installed (dream_textures) from '/home/corn/Downloads/dream_textures.zip' into '/home/corn/.config/blender/3.2/scripts/addons'
pip 22.2.2 from /home/corn/.local/lib/python3.10/site-packages/pip (python 3.10)
Traceback (most recent call last):
  File "/home/corn/.config/blender/3.2/scripts/addons/dream_textures/operators/install_dependencies.py", line 141, in execute
    install_and_import_requirements(requirements_txt=context.scene.dream_textures_requirements_path)
  File "/home/corn/.config/blender/3.2/scripts/addons/dream_textures/operators/install_dependencies.py", line 115, in install_and_import_requirements
    python_devel_tgz.extractall(path=python_include_dir, members=members(python_devel_tgz))
  File "/usr/lib/python3.10/tarfile.py", line 2059, in extractall
    self.extract(tarinfo, path, set_attrs=not tarinfo.isdir(),
  File "/usr/lib/python3.10/tarfile.py", line 2100, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name),
  File "/usr/lib/python3.10/tarfile.py", line 2173, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/usr/lib/python3.10/tarfile.py", line 2214, in makefile
    with bltn_open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: '/usr/include/python3.10/pystate.h'
Error: Python: Traceback (most recent call last):
  File "/home/corn/.config/blender/3.2/scripts/addons/dream_textures/operators/install_dependencies.py", line 141, in execute
    install_and_import_requirements(requirements_txt=context.scene.dream_textures_requirements_path)
  File "/home/corn/.config/blender/3.2/scripts/addons/dream_textures/operators/install_dependencies.py", line 115, in install_and_import_requirements
    python_devel_tgz.extractall(path=python_include_dir, members=members(python_devel_tgz))
  File "/usr/lib/python3.10/tarfile.py", line 2059, in extractall
    self.extract(tarinfo, path, set_attrs=not tarinfo.isdir(),
  File "/usr/lib/python3.10/tarfile.py", line 2100, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name),
  File "/usr/lib/python3.10/tarfile.py", line 2173, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/usr/lib/python3.10/tarfile.py", line 2214, in makefile
    with bltn_open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: '/usr/include/python3.10/pystate.h'
`

Gave up and ran it sudo, clicked install dependencies button. It's currently running from requirements-lin-AMD.txt. Which, thanks for noticing us poor ROCm havers.

**Comment by carson-katri** [comment]
So it is working correctly now?

**Comment by cornpo** [comment]
No. It did install enough to produce the Ui item in the upper right corner of shader editor. Segfault on attempting to use it.

**Comment by cornpo** [comment]
It's working in 0.7 repeatably
