### ISSUE TITLE
Project Dream Texture error - Unable to load weights

### ISSUE THREAD

**Issue by johnmblaz** [carson-katri/dream-textures#540]
OSError: Unable to load weights from pytorch checkpoint file for 'C:\Users\artof/.cache\huggingface\diffusers\models--stabilityai--stable-diffusion-2-depth\snapshots\d41a0687231847e8bd55f43fb1f576afaeefef19\text_encoder\pytorch_model.bin' at 'C:\Users\artof/.cache\huggingface\diffusers\models--stabilityai--stable-diffusion-2-depth\snapshots\d41a0687231847e8bd55f43fb1f576afaeefef19\text_encoder\pytorch_model.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

**Comment by carson-katri** [comment]
The model download failed. You should delete the folder at `C:\Users\artof\.cache\huggingface\diffusers\models--stabilityai--stable-diffusion-2-depth` and redownload the model through the UI.
