### ISSUE TITLE
Unable to install Windows CUDA version in Blender 3.4 with NVIDIA GeForce RTX 3080

### ISSUE THREAD

**Issue by SBK-3232** [carson-katri/dream-textures#541]
### Description

Hi, I am able to install the Windows CUDA version of Dream Textures in Blender 3.3 (although I'm having other issues, including texture projection hanging with a "requesting redraw" error, which I'll raise separately). In Blender 3.4 however, Dream Textures does not appear in my add-ons menu after installing the .zip file. (I do get a message saying "modules installed" at the bottom right of the Blender GUI, and don't see any errors.)

The DreamStudio version does install but I want to render locally and use the depth features. Any suggestions? Thanks so much!

### Steps to Reproduce

Install Windows CUDA .zip file in Blender add-ons in v 3.4

### Expected Behavior

Add-on should appear in add-ons menu after installation

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by carson-katri** [comment]
This sounds like a bug with Blender, not Dream Textures. You can try copying the folder manually:

1. Delete the dream textures folder here `C: \Users\YOUR_USER\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures`
2. Manually unzip the add-on folder to that same path. After doing that there should be a file `__init__.py` in `C: \Users\YOUR_USER\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\__init__.py`

Then restart Blender and see if the problem persists.

**Comment by carson-katri** [comment]
FYI, the addon will no longer freeze on “Requesting Redraw” since #495. This is not released yet but already fixed.

**Comment by SBK-3232** [comment]
Thanks so much for the quick response @carson-katri ! Unfortunately that didn't get it working. After manually copying the folder and restarting Blender, I can see Dream Textures in the add-on menu, but underneath it is an error saying "missing script files", and it's missing in the N-panel. This is with Blender 3.4.1 FYI. 

Glad to know that issue is fixed, thank you for the update!

**Comment by carson-katri** [comment]
You could try redownloading the addon from GitHub in case some files got lost. Also make sure you have enough storage space available for it.

**Comment by SBK-3232** [comment]
No luck with a clean download and install of both Dream Textures and Blender. The Blender system window does say Modules installed but the add on still isn't appearing. No worries, thanks for your quick responses. If nobody else is seeing this issue with Blender 3.4.1 then maybe something is going wrong with my particular system. I'll check back to try again with a later release in a few weeks, thanks!
