### ISSUE TITLE
search box not showing on MacOS V12.2 <title>

### ISSUE THREAD

**Issue by keo17** [carson-katri/dream-textures#545]
### Description

When I enabled the dream texture it does't show the Hugging face search box so I can dowloand the stable diffusion v1.4. I only see the Token Key. Is the Dream Texture 0.0.9 too old? 
I'm on MacOS V12.2 Intel!
My Macbook don't have GPU!
I'm on Blender 3.3

Image
![Skärmavbild 2023-01-31 kl  19 12 55](https://user-images.githubusercontent.com/53412198/215847391-2714466c-cdeb-49dc-8f92-ca53b2d299ba.jpg)

### Steps to Reproduce

1. Open Blender 3.3
2. Go to Edit>preferences>Install
3. Install Dream Texture 0.0.9
4. Boom Not showing the search box!

### Expected Behavior

To show The Hugging face search box so I can dowloand the stable diffusion v1.4

### Addon Version

Windows (CUDA)

### GPU

Intel

**Comment by NullSenseStudio** [comment]
Models cannot be downloaded on an Intel MacOS system since only cloud generation through DreamStudio is supported.
