### ISSUE TITLE
Removed addon but unrecovered used storage space

### ISSUE THREAD

**Issue by Maker261** [carson-katri/dream-textures#547]
the moment I noticed that the addon wasn't generating the textures, I knew that my gpu was not capable of using it so I decided to remove the addon.

Tho upon doing so I noticed that the amount of space used was not freed. So now my SSD has over 10GB of used storage space and idk where the addon has put all those files in when I downloaded them.

Even checked the file size on the master Blender Foundation folder and the size is completely normal.

**Comment by carson-katri** [comment]
The models you download are stored in `C:\Users\YOUR_USER\.cache\huggingface\diffusers`

**Comment by Maker261** [comment]
ah thank goodness....
Thanks alot :D
