### ISSUE TITLE
Texture naming

### ISSUE THREAD

**Issue by Andrewmad** [carson-katri/dream-textures#550]
It would be cool if the generated textures were called not faceless numbers, but something like 

Prompt_seamlessType_samplerName_seed_nextNumber. 

Thus, looking at the texture file (your own or sent/downloaded), you can easily generate a similar texture by simply looking at the name and filling in the necessary parameters. 

Regarding the naming of other types of generated files, I haven't thought about it yet, but it would also be nice to have something similar there.

**Comment by carson-katri** [comment]
Naming was updated in #499
