### ISSUE TITLE
UPBGE Support

### ISSUE THREAD

**Issue by geekgirljoy** [carson-katri/dream-textures#558]
**Is your feature request related to a problem? Please describe.**
It would be match made of dreams for Dream Textures to support UPBGE [https://upbge.org/](https://upbge.org/) and the Multi-view Projection that seems slated for v0.0.10 is exciting... but when I try to install Dream Textures v0.0.9 into UBGE (based on Blender) I receive the following error:

```
Preferences saved
bpy.context.space_data.system_bookmarks_active = 1
bpy.context.space_data.system_bookmarks_active = 3
Modules Installed (dream_textures) from 'C:\\Users\\Joy\\Downloads\\dream_textures-win32-cuda.zip' into 'C:\\Users\\Joy\\AppData\\Roaming\\UPBGE\\Blender\\3.0\\scripts\\addons'
Modules Installed (dream_textures) from 'C:\\Users\\Joy\\Downloads\\dream_textures-windows-cuda_v0.0.9\\dream_textures-windows-cuda.zip' into 'C:\\Users\\Joy\\AppData\\Roaming\\UPBGE\\Blender\\3.0\\scripts\\addons'
Traceback (most recent call last):
  File "C:\Users\Joy\Desktop\UPBGE-0.30-windows-x86_64\3.0\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Joy\AppData\Roaming\UPBGE\Blender\3.0\scripts\addons\dream_textures\__init__.py", line 39, in <module>
    from .render_pass import register_render_pass, unregister_render_pass, pass_inputs
  File "C:\Users\Joy\AppData\Roaming\UPBGE\Blender\3.0\scripts\addons\dream_textures\render_pass.py", line 90
    match scene.dream_textures_render_properties_pass_inputs:
          ^
SyntaxError: invalid syntax
```
 
**Describe the solution you'd like**
Ideally, Dream textures could support UPBGE.

**Describe alternatives you've considered**
The alternative consists of modeling in Blender and then importing into UPBGE.

**Additional context**
At this time I am uncertain if UPBGE is too divergent from Blender to be compatible with Dream Textures or of it could be as simple adding a version to the compatibility list.

**Comment by geekgirljoy** [comment]
> That error can happen when the addon is used in versions of Blender that are too old. Looks like you're using UPBGE 0.30 which is based on Blender 3.0. You could try using UPBGE 0.35 alpha to get around this specific issue.

Yes, thank you NullSenseStudio. :-) Installing the UPBGE development build enabled me to get Dream Textures v0.0.9 installed, however when I install the stable diffusion model by clicking the "Download Stable Diffusion v2.1 (Recommended) ", the model seems to be downloaded but the checkpoint file never becomes available in the list of installed ckpt's and  the same is true of any of the checkpoint files I attempt to install from the list in the preferences menu.

![image](https://user-images.githubusercontent.com/16138522/217955453-f9de88b9-9d12-4817-bb90-7757cf6e2c2f.png)

**Comment by NullSenseStudio** [comment]
Are there any new errors that appear in the console?

**Comment by geekgirljoy** [comment]
Strangely, no, console:

```
PYTHON INTERACTIVE CONSOLE 3.10.9 (main, Dec  8 2022, 14:09:03) [MSC v.1928 64 bit (AMD64)]

Builtin Modules:       bpy, bpy.data, bpy.ops, bpy.props, bpy.types, bpy.context, bpy.utils, bgl, gpu, blf, mathutils
Convenience Imports:   from mathutils import *; from math import *
Convenience Variables: C = bpy.context, D = bpy.data

>>> bpy.ops.dream_textures.install_model(model="stabilityai/stable-diffusion-2-1")
{'FINISHED'}

>>> bpy.ops.dream_textures.install_model(model="stabilityai/stable-diffusion-2-inpainting")
{'FINISHED'}

>>> bpy.ops.dream_textures.install_model(model="stabilityai/stable-diffusion-x4-upscaler")
{'FINISHED'}

>>> 
```
