### ISSUE TITLE
"Downloading BRET tokenizer" is closed unexpectedly

### ISSUE THREAD

**Issue by Mohammad9760** [carson-katri/dream-textures#559]
### Description

hi! I installed the add-on and imported the hugging-face model and gave it the .pth weight file but when I try to generate it tries to download BRET tokenizer and fails.
![Screenshot 2023-02-08 092611](https://user-images.githubusercontent.com/79392031/217446842-21e34821-6f1a-4abd-b8f4-599aeae7b83d.jpg)

### Steps to Reproduce

1. install the addon according to the instructions
2. give a prompt and click generate

### Expected Behavior

generate image

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by carson-katri** [comment]
Please install the latest version, v0.0.9.
