### ISSUE TITLE
DreamTextures doesn't work in Blender 3.4, cannot import models neither

### ISSUE THREAD

**Issue by tetsuoo-online** [carson-katri/dream-textures#560]
### Description

I downloaded around 10GB in total for this, now I have no more space on the system disk (938MB) because it all goes to users/AppData/.cache folder and I found no way to put it somewhere else - I'm not sure hardlinks would be a good idea. Nothing works so far.
I already have about 200GB of checkpoint models on another disk, why are we now stuck to download on HuggingFace only, did I miss something ? Can we import without having to fill up the system disk more, please ? Like use an external folder for instance.
If I try to hit Generate nothing happens at all, even after downloading all the stuff (SD v1.4 SD 2-depth, and tons of other Python things).
if I try to import a model I get Python error :

Error(s) in loading state_dict for UNet2DConditionModel:
	Missing key(s) in state_dict: "up_blocks.0.upsamplers.0.conv.weight", "up_blocks.0.upsamplers.0.conv.bias", "up_blocks.1.upsamplers.0.conv.weight", "up_blocks.1.upsamplers.0.conv.bias", "up_blocks.2.upsamplers.0.conv.weight", "up_blocks.2.upsamplers.0.conv.bias". 
	Unexpected key(s) in state_dict: "up_blocks.0.attentions.2.conv.bias", "up_blocks.0.attentions.2.conv.weight". 

I don't know, should I go back to first version ? It was a pain to rename every model to 'model.ckpt' and all very limited but at least it worked.
Extra infos, I have RTX 3060/12GB so I shouldn't have any VRAM issue, I'm usually using Automatic1111

### Steps to Reproduce

Go to Addons
Import Checkpoint file
Choose a CKPT or SAFETENSORS file

### Expected Behavior

Import checkpoint

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by carson-katri** [comment]
You need to make sure to select the correct model type when importing from checkpoint, as described here: https://github.com/carson-katri/dream-textures/blob/main/docs/SETUP.md#importing-checkpoints

We do not use the checkpoint format so there is no way to use those files you have directly. They must be imported/converted.

**Comment by tetsuoo-online** [comment]
Alright this kind of s... but can't be helped I guess, thanks for the quick answer as always.
Now maybe I didn't explain correctly but I did download the SD1.4 and SD 2-depth using the "dream-texture" way, so what else do I need to make generation work at all please ? Right now it's not doing anything

**Comment by ThinkWithPbody** [comment]
Same problem here. Inside the .cache\huggingface\diffusers folder I have the base, depth, inpainting, and upscaler models all downloaded, but none of them got picked up by 0.0.9 except "models--stabilityai--stable-diffusion-2-1". Deleting and downloading them again doesn't help. Would appreciate any help on this.
