### ISSUE TITLE
ControlNet support for texture projection

### ISSUE THREAD

**Issue by Dekker3D** [carson-katri/dream-textures#565]
**Is your feature request related to a problem? Please describe.**
Currently, texture projection only works with the depth2img model, which is limited stylistically and doesn't have many finetunes, and it has an offset to the bottom-right to align to the nearest internal-pixel-border (so, roughly 8 pixels or so?).

**Describe the solution you'd like**
ControlNets allow any Stable Diffusion model to have a depth input. The Automatic1111 extension at https://github.com/Mikubill/sd-webui-controlnet could serve as a reference implementation, it already has txt2img and img2img working. This depth input is at full resolution, rather than the internal (heavily downscaled) resolution. I have tested it, and it aligns much better.

**Comment by carson-katri** [comment]
I’d like to explore this, here is a relevant issue in diffusers on a ControlNet pipeline: https://github.com/huggingface/diffusers/issues/2331

**Comment by AugmentedRealityCat** [comment]
Here is a workflow example that might inspire you for upcoming versions of Dream-Texture: it generates all around UV texture map in a single shot using ControlNet image segmentation based on unwrapped UV mapping. It's made using Cinema4d but it could be done with any 3d app. 
https://github.com/Mikubill/sd-webui-controlnet/discussions/204

I am a big fan of Dream-Texture by the way - I love it so much that it forced me to learn how to use blender ! Thanks for sharing this amazing tool with all of us, your generosity is deeply appreciated.
