### ISSUE TITLE
Mulitple Textures (Roughness, Normals, etc.)

### ISSUE THREAD

**Issue by Saruwein** [carson-katri/dream-textures#569]
Hi, there should be a button to generate a roughness texture, normal map and perhaps a smoothness texture for Unity from any given output after rendering the initial texture. 
That would be a serious time saver in the long run, very cool forgame Jams!

**Comment by Dekker3D** [comment]
https://github.com/HugoTini/DeepBump can already do normal/height maps, which is nice. Roughness/smoothness though... we'd have to find some pre-trained AI for that too, if we wanted that. Or just train a Stable Diffusion finetune, I guess. But that seems outside the scope of this add-on.
