### ISSUE TITLE
Support for other Stable Diffusion Backends

### ISSUE THREAD

**Issue by Lostdragon5** [carson-katri/dream-textures#572]
I've noticed that this implementation of Stable Diffusion eats through my VRAM like crazy (which I don't have much to spare), even at lower resolutions, while other's do not (such as Automatic1111's webui). I can't exactly tell you why or how it does, but it makes running locally impossible for me unless running exclusively on the CPU, which I don't think I need to explain why that isn't ideal.

Something I would love to see is a way to connect to other Stable Diffusion backends, such as Automatic1111's webui, or even other could services like https://stablehorde.net like I've seen some other addons do (such as the AI Render addon). I don't know what sort of limitations this would pose, but it would be a huge plus since A111 has much more optimization options to help it run on weaker hardware like mine without restricting users to whatever models dream studio is using.

Regardless if this becomes a thing or not, thanks for your time and consideration~

**Comment by Ainaemaet** [comment]
Why is this not a thing? This plugin is by a large margin, imo, the best available for blender (thank you @carson-katri) but the one thing some of the others have over it is the ability to use Automatic1111.
Please 🙏🥺👉👈make this something we can do! :)

**Comment by carson-katri** [comment]
This is definitely a popular request. While this isn’t my top priority at the moment, I’d gladly accept contributions to add this.

It may also be beneficial to refactor the internals a bit so that separate addons can add backends to Dream Textures. So anyone could make a repo that adds a new backend.
