### ISSUE TITLE
Scheduler.DPM_SOLVER_MULTISTEP cannot be used with DreamStudio.

### ISSUE THREAD

**Issue by lymanzhao** [carson-katri/dream-textures#577]
### Description

Scheduler.DPM_SOLVER_MULTISTEP cannot be used with DreamStudio.

### Steps to Reproduce

An error occurred while generating. Check the issues tab on GitHub to see if this has been reported before:

ValueError('Scheduler.DPM_SOLVER_MULTISTEP cannot be used with DreamStudio.')

Apple M2 Ventura 13.2.1 (22D68)

### Expected Behavior

click “Generate”

### Addon Version

macOS (Apple Silicon, DreamStudio-only)

### GPU

Apple Silicon

**Comment by 1322138614** [comment]
me too

**Comment by PimHuisman** [comment]
I have the same problem.

**Comment by NullSenseStudio** [comment]
Select a different scheduler under the advanced section.

**Comment by leovfxuk** [comment]
I have this issue. Tried every other scheduler option and none worked

**Comment by NullSenseStudio** [comment]
It'll work for LMS Discrete, DDIM, DDPM, Euler Discrete, and Euler Ancestral Discrete. The rest will encounter this error.
https://github.com/carson-katri/dream-textures/blob/057d78035bf22d6222058b1693757b24d7105e16/generator_process/actions/prompt_to_image.py#L127-L141
