### ISSUE TITLE
Runtime Error on generate texture DT 0.1.0

### ISSUE THREAD

**Issue by MBoidot** [carson-katri/dream-textures#579]
### Description

The process to generate the error is described in the list of steps and settings below.

My configuration is : 
Windows 11
Blender 3.4.1
GPU : NVIDIA GeForge GTX1660 Ti
Dreamtexture : 0.1.0 (downloaded today, the latest release dream_textures-windows-cuda)

### Steps to Reproduce

1. Go to dreamtexture tab in the shader editor
2. Choose model stabilityai/stable-diffusion-2-1
3. Prompt : custom
4. Subject : (anything, but here is my example) bark
5. other settings default
6. Iterations 1
7. When I click on generate, after a while I got the following error message : 
RuntimeError('CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreata('handle)`')

![image](https://user-images.githubusercontent.com/36082177/221045379-05461055-b116-40ba-8383-a62706536e32.png)

### Expected Behavior

To generate a texture

### Addon Version

Windows (CUDA)

### GPU

NVIDIA 16 Series

**Comment by NullSenseStudio** [comment]
IIRC this may occur when running out of VRAM. Try using different memory optimizations under the advanced section.
