### ISSUE TITLE
Is "Depth" really working? - unwanted projection offset issue

### ISSUE THREAD

**Issue by enzyme69** [carson-katri/dream-textures#581]
### Description

I've used the depth feature few months ago, but compared to today, something weird going on, I cannot seem to get anything looking right.

I am using the "Bake" feature. But with whatever setting, I kept only getting this kind of pattern.

![Screenshot 2023-03-01 at 7 38 04 am](https://user-images.githubusercontent.com/3952687/221974187-f2315077-8b23-47ac-8fd3-72173eb9018e.png)

### Steps to Reproduce

1. Select basic geometry
2. Edit Mode, Select All Face
3. Generate synth art for depth using depth model
4. Result: strange

### Expected Behavior

I kind of wish it gives something that's more like "depth". I also tried ortographic, but none works.

This is version 0.1

I have installed and redownload depth model so many times but same.

### Addon Version

macOS (Apple Silicon)

### GPU

Apple Silicon

**Comment by kalkishnu** [comment]
I am experiencing the same results on linux with nvidia gpu.

**Comment by enzyme69** [comment]
I have a feeling there is like a weird "offset" going on. I am using Blender 3.5 beta. Even when selecting face of Suzanne from certain angle, I can't get it right.

**Comment by enzyme69** [comment]
![Screenshot 2023-03-01 at 8 13 34 am](https://user-images.githubusercontent.com/3952687/221981520-1bbd203c-ba0f-4358-9e72-fb3e9a61d4eb.png)

Testing on 3.4, the select has no offset in here, but the projection is still way way off.

**Comment by enzyme69** [comment]
As I am suspecting, the issue is with "offset" when projecting. It's weird. 

![Screenshot 2023-03-01 at 8 17 06 am](https://user-images.githubusercontent.com/3952687/221982125-21515495-8d0e-427c-82db-da184f5b85c4.png)

**Comment by carson-katri** [comment]
Can you share the image it generated, as well as your UV Map settings? Also, is this reproducible with “Bake” unselected?

**Comment by carson-katri** [comment]
There will always be a small offset because the internal depth representation stable diffusion uses is smaller than the image it generates. Adding support for a depth control net may improve this in the future.

**Comment by Atair1** [comment]
but it worked perfectly (in comparison) on windows (cuda) - compared to the mac version(s)

**Comment by enzyme69** [comment]
it was working perfectly before, the offset was not like this. at this moment the "Depth" does not work for me.

**Comment by enzyme69** [comment]
![Screenshot 2023-03-07 at 10 06 15 am](https://user-images.githubusercontent.com/3952687/223276907-fa6a7f31-c788-41c2-b286-8bda73cc7a55.png)

I think I might have that issue before with 3.5, but 3.4 seems to work (?). I still need to do a couple of testing. I might have specified "size" 512 x 512 and the projection was incorrect (?)

"Bake" does not seem to work correctly.

I will do a video on this.

**Comment by enzyme69** [comment]
Found out what might be the "culprit". The UV Maps selected was not projected, and so it gives a wrong preview.

And in 3.5 alpha or 3.6 alpha earlier, macOS, the face select was offset (even when selecting face using mouse precisely).

![Screenshot 2023-03-07 at 10 15 54 am](https://user-images.githubusercontent.com/3952687/223278364-30bbad6e-9257-4f88-9825-e09119973d42.png)
![Screenshot 2023-03-07 at 10 16 00 am](https://user-images.githubusercontent.com/3952687/223278383-4d5072bf-bef6-41ca-9b08-d95a88fe1707.png)

Ok I can close this I guess. Thanks!

**Comment by enzyme69** [comment]
![Screenshot 2023-04-14 at 12 35 16 am](https://user-images.githubusercontent.com/3952687/231793848-276b0b30-7e01-4ca2-a85b-4a69735063df.png)

Works fine with Blender 3.4.1. So I wonder what's the bug with 3.5?

**Comment by enzyme69** [comment]
![Screenshot 2023-04-14 at 9 04 03 am](https://user-images.githubusercontent.com/3952687/231901546-4d926188-c034-41ee-858b-91db5850044d.png)

And suddenly this also happens in some occasions. Exploding UV. Not sure why.

**Comment by grabthar** [comment]
Also happen on windows / main branch
I think it's because the view does not update at the right time.
For repro steps:
-select bake
-select UVMap
-use a constant seed
-select the geometry
-click generate (wrong projection result)
-click generate again (correct result)(don't move in the viewport)
