### ISSUE TITLE
No module found (Stability_sdk)

### ISSUE THREAD

**Issue by yumkah** [carson-katri/dream-textures#591]
Blender 3.4 can't find module stability sdk
![image](https://user-images.githubusercontent.com/116777296/223607885-7ef9cc78-3f87-48e2-8b95-959af99d2926.png)

**Comment by NullSenseStudio** [comment]
What kind of system is this running on?

**Comment by yumkah** [comment]
Do you mean the operating system, its on linux

**Comment by NullSenseStudio** [comment]
Most likely your dependencies aren't installed.
