### ISSUE TITLE
Blank image after generating with half precision on 7900XTX

### ISSUE THREAD

**Issue by mdl0316** [carson-katri/dream-textures#595]
### Description

Using the default settings to generate an image on 7900XTX it doesn't display the final image. If I uncheck Half Precision and generate it will display the final image. 
I don't see this problem using the CUDA solution on Nvidia GPUs but do see it on the AMD DirectML install. 

![half-precision-on-finished](https://user-images.githubusercontent.com/127449099/224164455-9233caa7-0485-4b01-979c-b9dd8944d2c7.jpg)
![half-precision-on-generating](https://user-images.githubusercontent.com/127449099/224164456-120f90e5-c398-40c6-81fe-95697259f4b7.jpg)
![half-precision-off](https://user-images.githubusercontent.com/127449099/224164458-3033ab07-8044-49bf-bc10-b45ed9a1b259.jpg)

### Steps to Reproduce

on a system with radeon gpu 7900XTX, install blender 3.4.1
install dream textures for AMD add-on
type prompt and click Generate
watch image start to generate then go white when displaying the final image
To workaround the issue, uncheck Half Precision and generate again

### Expected Behavior

Final image is displayed 

### Addon Version

Other (Built from source)

### GPU

AMD (unsupported for local generation)

**Comment by NullSenseStudio** [comment]
I believe this might be caused by a bug in group norm that's more likely to occur in the VAE than the u-net. Potentially can be fixed by just upcasting that specific function or have a way to lock full precision in the VAE alone.
