### ISSUE TITLE
Save model files to different location

### ISSUE THREAD

**Issue by Ainaemaet** [carson-katri/dream-textures#598]
For many people using a dedicated _smaller_ SSD for their system drive is common. The fact this plugin saves downloaded models to system directory .cash is an issue, as a lot of model files are quite large. 
Is there an option to change the directory (or a workaround), and if not can we please have that ability added so we can save the model files wherever we want?

Thank you and keep up the great work.

**Comment by carson-katri** [comment]
See #534 for information on changing the cache directory location.
