### ISSUE TITLE
I can't install dependencies on Linux

### ISSUE THREAD

**Issue by YAFU** [carson-katri/dream-textures#6]
Hi.
With v0.0.3 from Releases files when I hit the "Install dependencies" button in the addon , I get the following message:
`Command '['/media/TEMP/Blender_Releases/blender-2.83.0-linux64/blender', '-m', 'pip', 'install', '-r', '/home/nulluser/.config/blender/2.83/scripts/addons/dream_textures/stable_diffusion/requirements.txt']' returned non-zero exit status 1.`

With github "main" version I get:
`Command '['/media/TEMP/Blender_Releases/blender-2.83.0-linux64/blender', '-m', 'pip', 'install', '-r', '/home/nulluser/.config/blender/2.83/scripts/addons/dream-textures-main/stable_diffusion/requirements-mac.txt']' returned non-zero exit status 1.`

Similar error, and apparently it is also trying to load Mac dependencies instead of Linux dependencies.

Using KDE Neon distro (based in Ubuntu 20.04)

Could you tell me the command to manually install the dependencies on Linux in the meantime?

Thanks.

**Comment by industArk** [comment]
It looks like the `Command` tries to call this installation on blender app instead on python. It should work if you just type in your terminal:
`python3 -m pip install -r path/to/requirements.txt'

**Comment by satscape** [comment]
Having the same issue, couldn't find requirements.txt, so I tried 
`python3 -m pip install -r requirements-win-torch-1-11-0.txt`
`ERROR: file:///home/scott/.config/blender/3.4/scripts/addons/dream_textures (from -r requirements-win-torch-1-11-0.txt (line 33)) does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.`
Also tried running ~/.config/blender/3.4/scripts/addons/dream_textures/operators/install_dependencies.py in a terminal and that crashes the operating system. I guess running blender as root might work, but it's not a good idea to do that.

**Comment by carson-katri** [comment]
@satscape You should run the pip command from inside the `dream_textures/stable_diffusion` folder.

**Comment by YAFU** [comment]
Hi.
I am testing latest git main version (0.0.5) downloaded with:
`git clone --recurse-submodules https://github.com/carson-katri/dream-textures.git`

Then apparently the "install dependencies" button worked fine (be patient, it has to download a couple of GB of data and then install it. Even Blender's addon window can seem frozen during the process).
Then I have restarted Blender, and "Validate installation" and validation was successful.
Now you will find the addon in the Blender Shader Editor, but not in the Tabs of the N panel, instead you will see a "Dream Textures" button at the end of the Header bar in the Shader Editor.

**Comment by cfoster1228** [comment]
I have had the same issues as @industArk, and removing or commenting out the last line of the requirments text file solved my problem. The install validates just fine, but I am still not sure if it is working yet. I think i may have 3 missing dependancies as a result of that, but chasing them down based on colsole errors isnt a problem.

**Comment by YAFU** [comment]
On linux you can install Blender from repositories or download official Blender from the Blender website. Downloaded version from Blender web site is a Portable Version.
I can confirm that the python addon dependencies are being installed in the Blender Portable Version folder. This is not good because when you update the version of Portable Blender you just delete the old Blender version folder.
Dependencies should be installed on the Linux system preferably. Or alternatively, they will be installed in the Blender "User" folder in "$HOME/.config/blender/3.3/" for example:
https://docs.blender.org/manual/en/latest/advanced/blender_directory_layout.html

It would also be nice if the install script could check if the dependencies are already installed on the system, so that every time you try to install the addon you don't need to download the dependencies again every time.

Thanks for this promising addon, I'll keep trying to make it work.

De todos modos, gracias por este prometedor addon, voy a seguir intentando instalarlo.

**Comment by cfoster1228** [comment]
When blended updates and runs for the first time, it gives you the option
to migrate your older stuff over, which just copies it to the new version
folder. I think this should pull in those requirements when it does.

And if it doesn't, you just reinstall the addon?

**Comment by YAFU** [comment]
> When blended updates and runs for the first time, it gives you the option to migrate your older stuff over, which just copies it to the new version folder.

I've been using Blender for many years and I've never seen an addon installing things in the Blender installation folder or in the Portable Blender folder. Addons always save things in the "User" folder in "$HOME/.config/blender/X.X". Migrating to new version from stuff in "$HOME/.config/blender/X.X" always worked for me. But with things stored in the Portable folder I'm not sure if the migration works, because as I said before I've never seen other addons saving things there.

> And if it doesn't, you just reinstall the addon?
Probably if you have a good internet connection it's not a problem, but if you don't have a good connection it can be a bit of a pain to download dependencies each time.

**Comment by YAFU** [comment]
Just say that with latest Git main:
`git clone --recurse-submodules https://github.com/carson-katri/dream-textures.git`
I can install the dependencies correctly from the addon in Blender, that is by installing dependencies in the Blender folder and not in the system.
Now the Dream Textures properties are located in the N panel in the Shader Editor.

You may want to close this entry as resolved.
Thanks.

**Comment by dynamodan** [comment]
I still get `/usr/share/blender340/3.4/python/bin/python3.10: No module named pip`

You should not have to run anything as root.  This seems like basic problems with the way the addon installs and validates.

**Comment by dynamodan** [comment]
The problem is that the addon's installation script is looking for pip in blender's site packages.  I installed pip there and it took away the "No module named pip" error.

This seems incorrect.  This could be a problem with blender itself or with the addon.  At any rate it seems like python should be looking in the system's or the user's site packages folder for pip, not in blender's.  Maybe the standalone blender includes pip?  Maybe it's an environment variable issue?  Dunno.

**Comment by cfoster1228** [comment]
So pip is prepackaged in the python that blender ships with. Basically that
line of the installer just needs to change to call pip from within blender
correctly. I have done that in the past for some projects but can't recall
how I did it before. Trying to look it up turned up some people in older
versions using something like:

import subprocess (and sys and os for the filepaths probably)
subprocess.call([args, go, here])
