### ISSUE TITLE
it say selected pipeline does not support depth tasks.

### ISSUE THREAD

**Issue by Teaa12t** [carson-katri/dream-textures#600]
![image](https://user-images.githubusercontent.com/107637307/224481115-d3ca28ca-5713-4952-baf6-676d31b7d466.png)

whether i change it to another pipeline, it still shows. I cannot gen the image to project on cube.

what should i do?

**Comment by carson-katri** [comment]
You need a version of the addon that supports local generation. DreamStudio does not support this feature.
