### ISSUE TITLE
KeyError: 'bpy_prop_collection[key]: key "Principled BSDF" not found'

### ISSUE THREAD

**Issue by huhai463127310** [carson-katri/dream-textures#601]
### Description

an error dialog appeared after press “Project Dream Texture ” button. The error message is:

```
Python: Traceback (most recent call last):
  File "C:\Users\huhai\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\operators\project.py", line 330, in execute
    material.node_tree.links.new(image_texture_node.outputs[0], material.node_tree.nodes['Principled BSDF'].inputs[0])
KeyError: 'bpy_prop_collection[key]: key "Principled BSDF" not found'

```

<img width="1920" alt="Snipaste_2023-03-13_01-50-33" src="https://user-images.githubusercontent.com/1825820/224562905-33302aab-fbf9-4157-b4fe-97b1a01cbee7.png">

### Steps to Reproduce

**Blender Version**:3.4
**Windows Version**: Win 11
**Blender Addon**: dream_textures-windows-cuda(download at 2023/03/11 from [https://github.com/carson-katri/dream-textures/releases/download/0.1.0/dream_textures-windows-cuda.7z](https://github.com/carson-katri/dream-textures/releases/download/0.1.0/dream_textures-windows-cuda.7z))

1. use Blender default scene.
2. select the box.
3. enter edit mode.
4. select model: stabilityai--stable-diffusion-2-depth
5. promot:box 
6. select input:depth
7. press “Project Dream Texture ” button

### Expected Behavior

The box texture will be generated.

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by lzghades** [comment]
i have same error, my version is macos, do you have fixed the error?

**Comment by huhai463127310** [comment]
> 

No. I haven't.

**Comment by longshiine** [comment]
I think this issue is because, your "Language" setting. I changed my language from korean to english, then it works

**Comment by huhai463127310** [comment]
@carson-katri It's a bug when Blender interface Language is not English.

**Comment by BeiTown** [comment]
Python: Traceback (most recent call last):
  File "C:\Users\name\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\dream_textures\operators\project.py", line 307, in execute
    material.node_tree.links.new(image_texture_node.outputs[0], material.node_tree.nodes['Principled BSDF'].inputs[0])
KeyError: 'bpy_prop_collection[key]: key "Principled BSDF" not found'

This error is due to a node named "Principled BSDF" not being found in the specified material. This may be because the structure of the material has changed or there may not be a node with that name.

You can fix that in the project.py file:

replaced code:

material.node_tree.links.new(image_texture_node.outputs[0], material.node_tree.nodes['BSDF PRINCIPLED'].inputs[0])

to:

principled_node = None
        for node in material.node_tree.nodes:

            if node.type == 'BSDF_PRINCIPLED':
                principled_node = node
                break

        if principled_node:
            material.node_tree.links.new(image_texture_node.outputs[0], principled_node.inputs[0])
        else:
            self.report({'ERROR'}, "No Principled BSDF node found in the material.")
            return {'CANCELLED'}

**Comment by rushbggg** [comment]
> I think this issue is because, your "Language" setting. I changed my language from korean to english, then it works

that works!
