### ISSUE TITLE
The link to setup.md in inpainting/outpainting tutorial doesn't work

### ISSUE THREAD

**Issue by andreygetmanov** [carson-katri/dream-textures#602]
### Description

In the beginning, in "For both inpainting and outpainting you must use a model fine-tuned for inpainting, such as stabilityai/stable-diffusion-2-inpainting. Follow the instructions to [download a model](https://github.com/carson-katri/dream-textures/blob/main/docs/setup.md#download-a-model)."

The link should be to `SETUP.md`, not `setup.md`

### Steps to Reproduce

1. Go to the inpainting [guide](https://github.com/carson-katri/dream-textures/blob/main/docs/INPAINT_OUTPAINT.md)
2. Press "Follow the instructions to download a model' in the very beginning

### Expected Behavior

The link should be `https://github.com/carson-katri/dream-textures/blob/main/docs/SETUP.md#download-a-model`

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by playerla** [comment]
Other refs with bad case : https://github.com/carson-katri/dream-textures/search?q=setup.md
