### ISSUE TITLE
AV flags blobs as Wacatac trojan

### ISSUE THREAD

**Issue by TimNick151297** [carson-katri/dream-textures#603]
As stated in the title, my AV flags the blobs as a trojan. This issue did not occur with the previous release (0.0.9).

**Comment by carson-katri** [comment]
This is certainly possible this a false positive. However, you’re always free to install things manually as described here: https://github.com/carson-katri/dream-textures/blob/main/docs/DEVELOPMENT_ENVIRONMENT.md
