### ISSUE TITLE
API for Additional Backends

### ISSUE THREAD

**Issue by carson-katri** [carson-katri/dream-textures#604]
Many users have a preferred web or cloud-based interface for running Stable Diffusion besides the 🤗 diffusers based implementation Dream Textures ships with. Dream Textures currently supports swapping out the backend to support both diffusers and DreamStudio, but new backends must be maintained here. This proposes a new architecture that would allow other addons to add backends to Dream Textures.

## Detailed Design
Each backend would be represented as its own Blender addon. This addon would only need to implement a limited set of functionality to provide a backend for Dream Textures.

### Backend Registration
In an addon's `register` function, it should register a backend class with blender.

```python
def register():
    bpy.utils.register_class(Automatic1111)
```

Dream Textures can then look up all registered backends from the `bpy.types` module.

### Backend Interface
Backends would themselves be `bpy.types.PropertyGroup` subclasses. This would allow them to declare any additional properties or optimizations they support on their class.

A backend would implement methods like the following:

```python
def list_models(self) -> list[Model]: ...
```
Returns the list of models installed for this backend.

Model import/downloading would be handled by each individual backend's addon in its own preferences window.

```python
def supported_features(self) -> set[SupportedFeature]: ...
```
Can be used to enable certain aspects of the main interface.

Possible values could be:
* `SEAMLESS`
* `NEGATIVE_PROMPT`
* `CONTROL_NET`

```python
def draw_prompt(self, layout, context): ...
def draw_speed_optimizations(self, layout, context): ...
def draw_memory_optimizations(self, layout, context): ...
def draw_extra(self, layout, context): ...
```
The backend should draw its own properties in one of these sections.

```python
def prompt_to_image(self, dream_prompt, on_response, on_complete, on_exception): ...
def image_to_image(self, dream_prompt, on_response, on_complete, on_exception): ...
def depth_to_image(self, dream_prompt, on_response, on_complete, on_exception): ...
def inpaint(self, dream_prompt, on_response, on_complete, on_exception): ...
def outpaint(self, dream_prompt, on_response, on_complete, on_exception): ...
def control_net(self, dream_prompt, on_response, on_complete, on_exception): ...
```
If any of these methods are declared, it is assumed that the task is supported by the backend. Otherwise, it will be reported to the user that the backend cannot be used for that task.

### Dream Textures API
To make imports simple for backend addons, a separate `api` folder could contain all public classes necessary for creating backends.

```python
from dream_textures.api import Model, SupportedFeature, DreamPrompt
```

This module could also contain a better public API for calling Dream Textures from scripts running via Blender's background mode.

## Alternatives Considered
The most popular backends could be added natively to Dream Textures. However, supporting every backend users may want would be impossible to keep up to date within this single repo with only a few contributors.

**Comment by carson-katri** [comment]
I would also be interested in removing DreamStudio support from the core Dream Textures addon since the release of StabilityAI's own Blender addon: https://platform.stability.ai/docs/integrations/blender/

If someone is still interested in DreamStudio support in Dream Textures, despite the limited feature set, a separate backend addon could be created.

**Comment by Alyndiar** [comment]
Please go ahead with this idea! Having AUTO1111 as a backend would be phenomenal!
