### ISSUE TITLE
no file named diffusion_pytorch_model - incorrect model type selected for depth tasks

### ISSUE THREAD

**Issue by ishanpal13** [carson-katri/dream-textures#609]
### Description

the Dream tab says - Incorrect model type selected for depth tasks. And when I click on downloading the recommended model, it gets stuck at 40% and doesn't do anything. 

### Steps to Reproduce

Everytime I download the software and install it

### Expected Behavior

I expect it to work..

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by andrejbestuzhev** [comment]
Here's solution: https://github.com/carson-katri/dream-textures/issues/611
Your models are in c:/users/username/.cache/huggingface. Just delete it and redownload.

**Comment by ishanpal13** [comment]
@andrejbestuzhev I tried that multiple times it keeps installing them in that location.

**Comment by andrejbestuzhev** [comment]
Had the same issue and after few tries the download completed.  And i got another error :D https://github.com/carson-katri/dream-textures/issues/612

It seems this issue is about hugginface or blender, not about dream textures
