### ISSUE TITLE
Could not install packages due to an OSError

### ISSUE THREAD

**Issue by Johnnyboiiiiiiiii** [carson-katri/dream-textures#61]
Hi all, I'm sure this is something on my end, but I can't figure out what. I have a Windows system, I opened the application with admin privileges, and my account is the only admin account on my computer. Installing the addon worked fine, and downloading the packages from within the addon worked fine, but it has a fatal error every time it attempts to install. Here's my error message:
`Installing collected packages: opencv-python, numba, lmdb, jsonschema, jinja2, gitpython, future, ftfy, filterpy, filelock, entrypoints, docker-pycreds, decorator, commonmark, click, antlr4-python3-runtime, addict, watchdog, wandb, validators, urwid, tzlocal, tornado, torchdiffeq, tokenizers, semver, rich, resize-right, pytorch-lightning, pympler, pydeck, pyarrow, opencv-python-headless, omegaconf, kornia, jsonmerge, importlib-metadata, imgaug, huggingface-hub, facexlib, einops, clip, clean-fid, blinker, basicsr, altair, accelerate, transformers, torch-fidelity, test-tube, taming-transformers-rom1504, streamlit, stable-diffusion, pudb, pip, k-diffusion, imageio-ffmpeg, gfpgan, albumentations`
`ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Program Files\\Blender Foundation\\Blender 3.3\\3.3\\python\\Lib\\site-packages\\cv2\\cv2.pyd'
Consider using the` `--user` `option or check the permissions.`
This is a fresh install of Windows, so I haven't edited any registry files yet, except for when I edited a registry file to add the blender installation to PATH.  I also made myself the owner of all the files in my Blender Foundation folder, and gave full access to all processes in the security tab of the properties panel, all to no avail. Any help would be greatly appreciated. Thank you!

**Comment by JotaRata** [comment]
You either need to run blender as admin, or change the default windows path length limit

**Comment by Johnnyboiiiiiiiii** [comment]
> You either need to run blender as admin, or change the default windows path length limit

As I said above, I already did both of these things, repeatedly, to no avail.

> ... I opened the application with admin privileges... I edited a registry file to add the blender installation to PATH

**Comment by analball** [comment]
same here 
`ERROR: Could not install packages due to an OSError: [WinError 5] Отказано в доступе: 'G:\\Program Files\\Blender Foundation\\Blender 3.1\\3.1\\python\\Lib\\site-packages\\cv2\\cv2.pyd'
Consider using the `--user` option or check the permissions.`
run as admin path 1

**Comment by carson-katri** [comment]
v0.0.6 and higher do not require dependencies to be installed.
