### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by lamducnguyen14** [carson-katri/dream-textures#615]
### Description

hi i just download DT for window cuda, unzip the 7zip and install it to blender.
but when i hit the checkbox for the addon, this error pop-up
![image](https://user-images.githubusercontent.com/61793610/227750054-b88821f3-8dda-43ec-9071-fcf7d15cadd6.png)

### Steps to Reproduce

1. Install the addon
2. Hit the checkbox
3. Woala

### Expected Behavior

The addon shouldbe checked like normal i guess

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by carson-katri** [comment]
You need Blender 3.1 or higher to run Dream Textures.

**Comment by lamducnguyen14** [comment]
thanks <3 its work
