### ISSUE TITLE
wheres the models folder

### ISSUE THREAD

**Issue by Ulf3000** [carson-katri/dream-textures#618]
i cant download models through the UI/Blender.. but i have them all downloaded already anyways. where do i need to copy them , the folder seems to not being creating before fiorst model is downloaded . 

thanx

**Comment by LukeV1** [comment]
Start Blender with admin rights. Then model download inside of blender should be working.

Anyways, the path to the models is `C:\Users\%USERNAME%\.cache\huggingface\diffusers`. 
But I guess just copying files there will not work.
