### ISSUE TITLE
Dream Textures can't process the image

### ISSUE THREAD

**Issue by yurnero7** [carson-katri/dream-textures#62]
hello, i have a problem after installing the add-ons, after i follow the intruction and try to input brick keyword they dont do processing to generate the image ?
i try on blender ver. 3.2.1

maybe someone can help this issues!

![image](https://user-images.githubusercontent.com/66900486/191690408-d1e4b5a9-3412-4037-ac31-6e23a7e6ff23.png)
![image](https://user-images.githubusercontent.com/66900486/191691553-91b78f9d-d0dc-4eea-b43b-a0b326f22105.png)

**Comment by merecesarchviz** [comment]
the same here, after do it the texture dont shows in blender!

**Comment by Gasased** [comment]
Same. Blender 3.3.0 stable, gtx1660ti(6GB)+ryzen1600x+24GB RAM
After pressing generate button in the blender nothing happens, but VRAM becomes full and stays like this until the blender is closed

**Comment by engineer1469** [comment]
You have to create a object and texture before you can generate an image

**Comment by Gasased** [comment]
> 

Maybe I misunderstand you, but nope, it still doesn't work.
