### ISSUE TITLE
<title>OSError.Error no file named diffusion_pytorch_model.bin

### ISSUE THREAD

**Issue by Areesn** [carson-katri/dream-textures#622]
### Description

An error occurred while generating. Check the issues tab on GitHub to see if this has been reported before:

OSError('Error no file named diffusion_pytorch_model.bin found in directory C:\\Users\\XXXXX/.cache\\huggingface\\diffusers\\models--stabilityai--stable-diffusion-2-depth\\snapshots\\6330e936a1cc2da7fe149bfba83462003f5e71c7.')

### Steps to Reproduce

run 'dream texture'.This error occurs

### Expected Behavior

It seems that this file is missing. How do I download it

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by SoloDevelooper** [comment]
Can we get somebody to figure this out? im having this issue and i cant find any solutions

**Comment by carson-katri** [comment]
This can be fixed by deleting the model and redownloading it.

**Comment by LEAFCHINA** [comment]
I have also encountered this problem and I don't know how to solve it

**Comment by Pires77** [comment]
"This can be fixed by deleting the model and redownloading it." Does not work.
