### ISSUE TITLE
How to use on Nvidia GPU with 2GB VRAM?

### ISSUE THREAD

**Issue by Mohammad9760** [carson-katri/dream-textures#629]
### Description

I installed the latest version of the addon yesterday and I downloaded the stable-diffusion-2-1-base and when I press the Generate button in the addons menu in the Image Editor it freezes for a while then says out of CUDA  memory. here's the error:
`An error occurred while generating. Check the issues tab on GitHub to see if this has been reported before:

RuntimeError("OutOfMemoryError('CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 2.00 GiB total capacity; 1.70 GiB already allocated; 0 bytes free; 1.75 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF')")
`

so can I or can I not use this with only 2GB of VRAM?

### Steps to Reproduce

1. install the addon
2. press the generate button

### Expected Behavior

generate an image

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by Mohammad9760** [comment]
also where does the downloaded stable diffusion models go? I tried disabling then enabling the addon and the models are gone and it tells me to 'download' again :(

**Comment by carson-katri** [comment]
You probably won’t be able to use it on 2GB.

models are at `\Users\youruser\.cache\huggingface`

**Comment by Mohammad9760** [comment]
okay thanks for answering :(
