### ISSUE TITLE
module not found error

### ISSUE THREAD

**Issue by haydenlovestnt** [carson-katri/dream-textures#634]
### Description

when I try to generate an image this error pops up 
![image](https://user-images.githubusercontent.com/130925134/232330202-eca44498-dfd4-4a42-9a00-d84383724d12.png)

### Steps to Reproduce

i put in a random word and then the error pops up

### Expected Behavior

i thought it would generate it, but it didn't even generate

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by carson-katri** [comment]
Did you download a prebuilt release, or the source code?
