### ISSUE TITLE
AMD pytorch version wrong (fixed)

### ISSUE THREAD

**Issue by cornpo** [carson-katri/dream-textures#635]
### Description

Since the Pytorch 2.0 release. Pytorch 2.0 is installed for AMD leaving the GPU non-functional.

The fix. Changed linux-rocm.txt where `torch>=1.13` to `torch==1.13.1`

The line (`--extra-index-url https://download.pytorch.org/whl/rocm5.2/`) stays the same.

This doesn't use pip to install. Rather, it's changed in linux-rocm.txt.

Thanks -CR

### Steps to Reproduce

Install as normal for Linux AMD development from git clone of main.

### Expected Behavior

ROCm engages GPU, rather than CPU.

### Addon Version

Other (Built from source)

### GPU

AMD (unsupported for local generation)

**Comment by carson-katri** [comment]
Their install page seems to indicate that 2.0 can be install for ROCm with a different index URL: https://pytorch.org/get-started/locally/
It would be better to use 2.0 so you can use the new builtin SDPA ops for better performance.
If that works for you, could you open a PR to change the requirements file?

**Comment by cornpo** [comment]
Installed 2.0 manually with Blender's Python. It is faster. In the current *main state it grabs Torch CUDA, Triton, etc.

PR in the morning. Thanks.
