### ISSUE TITLE
White picture - sometimes yellow and green

### ISSUE THREAD

**Issue by Pejda** [carson-katri/dream-textures#637]
### Description

Hi,
In like 70% of cases picture is generating but at the last step (sometimes even in like half of steps) it just turn all image blank white color. Next 30% its just horrible green/yellow picture. Tried different settings. Using "stable-diffusion-2-1" There are no error messages shown in console. GPU Vega64

![image](https://user-images.githubusercontent.com/13038691/232526430-cefa0301-8d87-4f5c-b86a-6f6122f8fd77.png)

![image](https://user-images.githubusercontent.com/13038691/232526097-48ca93ac-e665-48d9-ab45-226b4f2fe5ac.png)

### Steps to Reproduce

1. install DirectML version
2. fill in settings (tried even changing some of it)
3. push "Generate" button
![image](https://user-images.githubusercontent.com/13038691/232528034-21e7ed1c-6ab9-4e65-812d-d79e0ba7292a.png)

### Expected Behavior

Generate image

### Addon Version

Other (Built from source)

### GPU

AMD (unsupported for local generation)

**Comment by carson-katri** [comment]
This is a common issue with DirectML when using half precision. Disabling half precision will resolve this issue.
