### ISSUE TITLE
Render engine - Modifiers not being used by controlnet on render time

### ISSUE THREAD

**Issue by marianbastiUNRN** [carson-katri/dream-textures#644]
### Description

It seems that the modifier stack is being ignored when rendering using ControlNet depth pass.

Blender version: 3.5 Stable 1be25cfff18b
OS: Windows 10 64bit
System: AMD Ryzen 9 5900X, Nvidia RTX3090

### Steps to Reproduce

1. Setup the render engine, and create basic node setup that uses ControlNet (namely depth).
2. Add a mesh and any modifier that should have an evident effect on the mesh
3. Hit render

### Expected Behavior

Modifier should be visible on the render result

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by marianbastiUNRN** [comment]
Hmm, further testing with the rig modifier reveals that the problem occurs with depth and also normal controlnet. Openpose works just fine.

**Comment by aulerius** [comment]
+1.
Can confirm this from my own experience with depth ControlNet.
