### ISSUE TITLE
FileNotFoundError(2, 'No such file or directory')

### ISSUE THREAD

**Issue by Nockeat** [carson-katri/dream-textures#647]
### Description

Can't Project Dream Textrue

### Steps to Reproduce

<img width="390" alt="2023-04-25 18 34 46" src="https://user-images.githubusercontent.com/92221548/234251476-d35baa4a-ea14-4b4e-9ae8-e5e220a32bbe.png">

### Expected Behavior

Dream Correctly

### Addon Version

macOS (Apple Silicon)

### GPU

Apple Silicon

**Comment by Kaesops** [comment]
Same thing happened to me but on windows

**Comment by danielbill** [comment]
yeah  me too

**Comment by Hunanbean** [comment]
Same. then when i looked at the console..
`The system cannot find the path specified: 'C:\\Users\\Username/.cache\\huggingface\\diffusers\\refs'`

**Comment by danielbill** [comment]
> Same. then when i looked at the console.. `The system cannot find the path specified: 'C:\\Users\\Username/.cache\\huggingface\\diffusers\\refs'`

where to cfg the path ?

**Comment by carson-katri** [comment]
The original report was for macOS. Please run Blender from the terminal to get a full log:

1. Open the app “Terminal”
2. Enter the command `/Applications/Blender.app/Contents/MacOS/Blender` and press enter
3. Try to generate an image

The full log will appear in Terminal.

**Comment by GrantelbartonCetamine** [comment]
Dont Work for me . Need help

**Comment by melwinsss** [comment]
any one got solution for windows

**Comment by alemanimani** [comment]
same issue here, I've tried various models, checking the roaming data file, I'm out of ideas

An error occurred while generating. Check the issues tab on GitHub to see if this has been reported before:

FileNotFoundError(2, 'The system cannot find the path specified')

**Comment by alemanimani** [comment]
Update: I downloaded controlnet models from the addon search bar and the original error is gone, but replaced with a runtime error where "mat1 and mat2 shapes cannot be multiplied"

**Comment by alemanimani** [comment]
Update: I went to /users/.cache/huggingface and deleted the models in that folder and close reopened blender to download the appropriate models again. This seemed to fix the problem temporarily before it returned. To fix it again I repeated the steps above. 
For controlnet to operate correctly you will need to download the canni or depth ctrlnet models through the search bar in your blender addon>dreamtexture window (you can do this manually but it's less confusing this way)

**Comment by Kieaer** [comment]
Same ``The system cannot find the path specified: 'C:\\Users\\Username/.cache\\huggingface\\diffusers\\refs'`` error
Actually there is no diffusers folder, only hub folder.

**Comment by AlexNolasco** [comment]
> For controlnet to operate correctly you will need to download the canni or depth ctrlnet model

Came across the same error "mat1 and mat2 shapes cannot be multiplied". I proceeded as follows
 
1.- Removed /users/.cache/huggingface 
2.- Installed stabilityai/stable-diffusion-2-1
3.- Installed thibaud/controlnet-sd-21-depth-diffusers

Now trying to get a nice image 🙄

**Comment by saturdayxiii** [comment]
Any progress?  I had the FileNotFound error, installed whatever the most popular controlnet was, now I have the mat1 and 2 error.  I'm using blender from portableapps.com for Windows so I'm not finding a .cache/huggingface anywhere to delete.

**Comment by carson-katri** [comment]
You need to use a ControlNet model that works with the base model. So a Stable Diffusion 2.1 base model needs a 2.1 compatible ControlNet for example.

**Comment by saturdayxiii** [comment]
Wonderful, it's working now.  Thank you for that detail.
