### ISSUE TITLE
Support for Furusu ControlNet Model

### ISSUE THREAD

**Issue by saphtea** [carson-katri/dream-textures#649]
Hey! Just curious if there's anyway to load Furusu's 2.1 controlnet's safetensors at this moment. Linked here https://civitai.com/models/17292/controlnet-furusus-sd21-models . Thank you!

**Comment by carson-katri** [comment]
Those models are not in diffusers format, so you would need to convert them yourself with the scripts Hugging Face provides.

But you could also just use these models: https://huggingface.co/thibaud/controlnet-sd21-depth-diffusers

You can search for them in the addon preferences and download them. Thibaud has published a bunch of 2.1 ControlNet models.
