### ISSUE TITLE
Blender crushes on open

### ISSUE THREAD

**Issue by Vitaliy452** [carson-katri/dream-textures#65]
When I launch blender, window appears for about 1 second and closes. I can't open blender.
Errors from console:
[https://disk.yandex.ru/i/Vs9AwSUPcY-rWQ](url)

**Comment by carson-katri** [comment]
This may have to do with your username containing special characters

**Comment by whthawk** [comment]
Okay, how do I clean or uninstall this outside of blender?  I ran the new file, started to install it and now it appears to hang just after success on preloading CLIP model.  Any ideas?  Is it trying to download something hitting a wall or a queue somewhere?
