### ISSUE TITLE
4x compute slowdown

### ISSUE THREAD

**Issue by LukeV1** [carson-katri/dream-textures#652]
### Description

The new v0.20 build is almost four times slower when generating images on my Nvidia GTX980 Ti (6GB VRAM).
That's quite surprising to me, since according to the release notes, speed improvements have been made. At least for me it's the other way around.

Also, I noticed that rendering image with v0.20 slows down the whole PC, even Windows gets pretty sluggish. With the previous version there was no noticeable lag at all.

**v0.20 image generation time, 1st run**
![grafik](https://user-images.githubusercontent.com/8466561/235091822-fcf4fc2e-ee34-4b03-b830-b725293caefe.png)
**v0.20 image generation time, 2nd run**
![grafik](https://user-images.githubusercontent.com/8466561/235093321-52eba533-daec-443e-b58b-93301c104113.png)

**v0.10 image generation time, 1st run**
![grafik](https://user-images.githubusercontent.com/8466561/235091953-ceb5ed3b-e134-41e8-b66a-1cd25da0b7c4.png)
**v0.10 image generation time, 2nd run**
![grafik](https://user-images.githubusercontent.com/8466561/235092459-f607d9b6-184d-4010-b16d-f901e97fd37c.png)

### Steps to Reproduce

1. generate an image with all set to default (SD 2.1 model) in version v0.10
2. generate an image with all set to default (same SD2.1 model) in version v0.20
3. compare results displayed in the blender console

### Expected Behavior

According to the release notes the new verison v0.20 should be faster, not way slower.

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by carson-katri** [comment]
Try disabling SDP attention in the optimization settings. It’s possible it has a negative effect on some cards.

**Comment by LukeV1** [comment]
Disabling SDP attention brought the generation time back to its former speed:
**v0.20 image generation time, 2nd run**
![grafik](https://user-images.githubusercontent.com/8466561/235296981-a321483f-1a85-446b-9da7-576fefd0a029.png)

so I guess I just have the wrong card to benefit from the optimizations, right?

**Comment by LukeV1** [comment]
Well, after checking the changelog, I'm pretty sure the speed improvements aren't working for my card:

As I understand it, xformers was added to speed things up. 
According to here [Xformers - AUTOMATIC1111](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Xformers) this works only for `Pascal, Turing, Ampere, Lovelace or Hopper cards`. My GTX980 Ti is the last one with a Maxwell core..

**Comment by LukeV1** [comment]
I am closing this as it is not a bug but a feature - that is missing for my card type..

**Comment by carson-katri** [comment]
We didn’t add xformers, but SDP attention is built-in to PyTorch 2 and possibly has those same drawbacks you identified.
