### ISSUE TITLE
Upscalling in render engine nodes

### ISSUE THREAD

**Issue by aulerius** [carson-katri/dream-textures#657]
**Is your feature request related to a problem? Please describe.**
Upscale functionality is missing in render engine. It is not possible (afaik) to run upscaller on animation render.

**Describe the solution you'd like**
A node to host and control upscalling models, to be used together with other nodes (for instance upscalling a low res generated image in one go)

**Describe alternatives you've considered**
Using upscaller as batch process on rendered images outside of blender

**Additional context**
Is such implementation realistic in terms of performance and memory consumption? When it would be running together with other nodes such as diffusion nodes.

**Comment by GottfriedHofmann** [comment]
I would suggest using [controlnet tile](https://github.com/lllyasviel/ControlNet-v1-1-nightly#controlnet-11-tile) for this.
