### ISSUE TITLE
Prompt weighting via nodes

### ISSUE THREAD

**Issue by aulerius** [carson-katri/dream-textures#663]
Prompt weighting enhances the control of diffusion output significantly. Implementing it into the render engine would allow seamless experience of animating the weights, or linking it to drivers. It would open up workflows of blending between different prompts for creative intent.

To my eyes, ideally you'd be able to have a multi-input socket for one or many strings (prompts) that each come with their own weight, just like with control nets. They could be dynamically normalized to fit within 0-1 when added up under the hood.

_example mock-up:_
![image](https://github.com/carson-katri/dream-textures/assets/51526300/a5cee886-e461-46a6-81a0-464a2412e333)

It has been suggested to use ["Compel" library](https://github.com/damian0815/compel) and their syntax for implementing prompt weighting directly in the strings. I assume it would be possible to adapt that to node-based implementation as well?

**Comment by carson-katri** [comment]
I’d like to implement both, so weighting can be done from the image editor/viewport with compel, and the render engine can use nodes (or the compel syntax if the user wants something quicker to setup).

**Comment by aulerius** [comment]
Small additional note. Could the nodes in render engine follow the blender's UI indication of multi-input sockets?
They appear slightly taller to indicate that.
![image](https://github.com/carson-katri/dream-textures/assets/51526300/867421f4-d85d-4b02-a250-23952f04b693)

**Comment by carson-katri** [comment]
Unfortunately it doesn't seem possible to get that UI with custom nodes.
