### ISSUE TITLE
Upscaling of images with dark areas creates tiles with unrelated graphics

### ISSUE THREAD

**Issue by PredellaN** [carson-katri/dream-textures#665]
### Description

Upscaling of images with very dark areas (low contrast between bright pixels and dark pixels) creates tiles with unrelated graphics.

### Steps to Reproduce

Pop_os 22.04 (Linux),
NVIDIA RTX A4500 (16GB)

- Install the v0.2.0 addon
- Install stable-diffusion-x4-upscaler
- Load the attached image
![a golden palace in an immense cave with quar  (17040480)](https://github.com/carson-katri/dream-textures/assets/75480205/4c76654d-ecff-49cf-8a5b-e82ce36ab153)
- Use the following settings:
"a golden palace in an immense cave with quartz crystals that look like stars" 
![Screenshot from 2023-05-12 14-40-51](https://github.com/carson-katri/dream-textures/assets/75480205/eb6aea42-46f4-4b19-a754-7f6bb31e84a3)
(same result happens with tiles sized 128px)

- Get the following result:

![a golden palace in an immense cave with quar  (17040480) 001](https://github.com/carson-katri/dream-textures/assets/75480205/d1442256-8f6d-46cd-8644-3418f62e4d70)

### Expected Behavior

Would upscale the dark sections of the image in a similar way to the higher contrast parts of the image.

### Addon Version

Other (Built from source)

### GPU

NVIDIA

**Comment by enzyme69** [comment]
I wonder if upscaler better to use "Tile Resample" method?

**Comment by PredellaN** [comment]
In my experience tile resample has the tendency to over-do it with changing the original image, but it might be me applying it in a suboptimal way

**Comment by Zee-Germans** [comment]
I have the exact problem. And I agree: it only happens in the dark parts of the images. Is there already a solution for this bug?
