### ISSUE TITLE
🚩AI Text To 3D addon mixed SD really easy to set up scenes

### ISSUE THREAD

**Issue by eliecer696** [carson-katri/dream-textures#670]
![image](https://github.com/carson-katri/dream-textures/assets/4975856/e4e223e8-fdd0-4a42-9361-2935402628b3)
am just shearing something i did with Dream Textures and this other blender addon that makes 3d models from text prompts inside blender it + Dream textures is just the fastest workflow ever this were i got it from https://devbud.gumroad.com/l/Shap-e

**Comment by carson-katri** [comment]
Thanks for sharing. This would be better suited as a discussion post. Issues are for bug reports or feature requests.

**Comment by eliecer696** [comment]
> Thanks for sharing. This would be better suited as a discussion post. Issues are for bug reports or feature requests.

sorry about that
