### ISSUE TITLE
An error occurred while generating. Check the issues tab on GitHub to see if this has been reported before:

### ISSUE THREAD

**Issue by adityapandeyz** [carson-katri/dream-textures#671]
An error occurred while generating. Check the issues tab on GitHub to see if this has been reported before:

OSError('Error no file named diffusion_pytorch_model.bin found in directory C:\\Users\\adity\\.cache\\huggingface\\hub\\models--stabilityai--stable-diffusion-2-depth\\snapshots\\6330e936a1cc2da7fe149bfba83462003f5e71c7\\unet.')

**Comment by carson-katri** [comment]
Duplicate of #622

**Comment by shiyuze112** [comment]
Hello, got it solved？
