### ISSUE TITLE
Models not downloading

### ISSUE THREAD

**Issue by AtanoKSi** [carson-katri/dream-textures#674]
I installed dream textures on blender 3, and when I click install stable diffusion it says downloading but nothing happens in the end
Same for base and depth, or any you try
Why is this happening?
Thanks in advance

**Comment by NullSenseStudio** [comment]
Can you share console logs?

**Comment by niyunsheng** [comment]
I'm having the same issue. How to download the models manually and import them to this plugin ?

**Comment by RazorWolvendom** [comment]
> Can you share console logs?

![ScreenShot_20230723202800](https://github.com/carson-katri/dream-textures/assets/44827474/a19529d4-6a84-48ea-a392-03c54ce94afd)
