### ISSUE TITLE
Error projecting texture

### ISSUE THREAD

**Issue by michaeltintiuc** [carson-katri/dream-textures#677]
### Description

I'm getting the following error when trying to project any texture on a simple cube:
>An error occurred while generating. Check the issues tab on GitHub to see if this has been reported before:
>TypeError("StableDiffusionInpaintPipeline.check_inputs() missing 1 required positional argument: 'callback_steps'")

I'm running it on Linux and installed the python dependencies both manually and via the Blender UI when troubleshooting. 
Using `stabilityai/stable-diffusion-2-depth`

Basic texture generation works fine btw.

### Steps to Reproduce

Click `Project  Dream Texture`

### Expected Behavior

No errors

### Addon Version

Other (Built from source)

### GPU

NVIDIA

**Comment by ivakam** [comment]
I'm having the same issue on EndeavourOS, Nvidia.

**Comment by carson-katri** [comment]
You may want to try downgrading diffusers, perhaps to v0.16.1? By default it will pull the latest from `main`, and they may have made some internal changes that haven't been accounted for here yet.

**Comment by dragonwarrior** [comment]
> You may want to try downgrading diffusers, perhaps to v0.16.1? By default it will pull the latest from `main`, and they may have made some internal changes that haven't been accounted for here yet.

this works for me.

**Comment by ganim3d** [comment]
for me too
win 10 blender 3.4 thanks !

**Comment by 64blit** [comment]
Great! How do you downgrade?

**Comment by LightDashing** [comment]
Same problem, but somehow I doesn't even had diffusers lib, installing it doesn't fixed anything. I'm running pop os 22.04, nvidia, blender 3.6, installed dependencies manually.
