### ISSUE TITLE
ModuleNotFoundError: No module named 'dream_textures.prompt_engineering'

### ISSUE THREAD

**Issue by sanroot3** [carson-katri/dream-textures#682]
### Description

Traceback (most recent call last):
  File "C:\Users\Administrator\_Work\_Instant App\Blender_Launcher\Blender\stable\blender-3.5.1+stable.e1ccd9d4a1d3\3.5\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\dream_textures\__init__.py", line 40, in <module>
    from .prompt_engineering import *
ModuleNotFoundError: No module named 'dream_textures.prompt_engineering'

### Steps to Reproduce

英伟达显卡
[适用于 Windows (CUDA) 的 Dream Textures](https://github.com/carson-katri/dream-textures/releases/download/0.2.0/dream_textures-windows-cuda.7z) - 使用 NVIDIA CUDA 进行本地和云渲染
由于 GitHub 上的文件大小限制，附加 ZIP 文件包含在 7-Zip 存档中。
安装[7-Zip](https://www.7-zip.org/)，右键单击下载的dream_textures-windows-cuda.7z存档，选择“7-Zip”>“在此处解压”以获取文件dream_textures-windows-cuda.zip。
在 Blender 首选项中打开“附加组件”>“安装...”，然后选择文件dream_textures-windows-cuda.zip。

### Expected Behavior

1

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by PoeticDeath** [comment]
Re-extracting from the .zip into the C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\dream_textures\ directory seems to fix the issue for now.
