### ISSUE TITLE
RuntimeError('The size of tensor a (9) must match the size of tensor b (4) at non-singleton dimension 1')

### ISSUE THREAD

**Issue by ajarcon** [carson-katri/dream-textures#683]
### Description

An error occurred while generating. Check the issues tab on GitHub to see if this has been reported before:

https://github.com/carson-katri/dream-textures/assets/9829
![Blender 6_17_2023 10_55_49 AM](https://github.com/carson-katri/dream-textures/assets/98292515/e63e8fe1-9e4d-4564-a4bd-2883d293d174)
2515/d26a3b44-f374-4187-898c-ba1a224f9fdf

RuntimeError('The size of tensor a (9) must match the size of tensor b (4) at non-singleton dimension 1')
 when i try to use out painting 

### Steps to Reproduce

texture paint click on dream textures chose outpainting and click generate 

### Expected Behavior

idk start or something but it says error and ask to check if the issue is on github but it was not

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by Anderdragoon** [comment]
link a source image first

**Comment by ajarcon** [comment]
i umm reinstalled windows on my computer bc it was unstable and stuff can u just tell me how to use it
