### ISSUE TITLE
can't install on Blender 3.6 on Ubuntu? 

### ISSUE THREAD

**Issue by tuberatanka** [carson-katri/dream-textures#689]
### Description

Blender 3.6
Ubuntu 20.04
Installing zip file results in "You're likely downloaded source instead of release by accident" error, and it can't be continued
No release option in downloads

### Steps to Reproduce

1. Download zip file from github
2. install it onto Blender
3. run the install

### Expected Behavior

the addon should be installed, but it gets stuck

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by Tenchrio** [comment]
If you read the install instructions on the release page, you will see that the instructions for the Linux version is to manually install it. The zip will not work. These instructions [can be found here](https://github.com/carson-katri/dream-textures/blob/main/docs/DEVELOPMENT_ENVIRONMENT.md).
