### ISSUE TITLE
CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by fillemazendacus** [carson-katri/dream-textures#690]
### Description

What would that mean?

[RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.]

Part 1:
This error is completely new to me, and I haven't encountered it before. There haven't been any hardware changes. Initially, I thought it might be related to memory, so I made more space available on the C-drive for temporary files, and I even redirected some system temporary files to another disk. About a month ago, it was able to generate new images continuously at the same resolution, but now I encounter this error with the first image I try to process, even when I reduce the resolution.

I also attempted to install version 0.2.0 of DT (currently, the error is coming from version 0.1.0), but it didn't help. Then I installed the latest version of Blender (3.6.0), but the problem persisted. I tried to remove the model and reinstall it, but it seems there are some issues with installing the new model (in this case, openjourney_V4) correctly in 0.2.0, and when I try to generate it, it can't find the "diffusers" path. So, I reinstalled version 0.1.0, which installed the model correctly so it can be found later, but the error still occurs. This error happens with other models as well.

Part 2:
These problems occur when I load the source image using the "File" option. An interesting observation is that when I load the image with "File" and then switch to "Open Image" (so that the loaded file becomes an open image), it seems to work as usual. However, I have only tested it for one day, so it is possible that it simply hasn't reached the specific error yet.

Do you have any clues or suggestions?

### Steps to Reproduce

1. Staring to generate
2. After a certain amount of time, the rendering process of the mosaic stops and an error occurs.

### Expected Behavior

It should generate new image as usually before.

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by carson-katri** [comment]
Thank you for the detailed report. However, I cannot provide support for v0.1.0. Could you please describe the issue you get running the latest version and the steps to reproduce it?
