### ISSUE TITLE
Blender shows a solid color instead of texture

### ISSUE THREAD

**Issue by illieart** [carson-katri/dream-textures#695]
### Description

As you can see in the screenshot- the image that the addon generated looks great, and the automatic projection also looks quite impressive, judging by the way it's stretched in the UV editor panel on the left.
However, in the viewport, and in renders, all of the photos that are generated by dream textures appear as a solid color even though there's nothing wrong with the image nor with the projection. I tried switching the source photo to an imported one and the issue disappeared. Switched back to the dream textures one and it returned. That issue makes absolutely 0 sense. It's like blender personally blocks images that are generated by the addon.

![This makes no sense](https://github.com/carson-katri/dream-textures/assets/113828729/1ba97d32-3398-44cf-a42c-82928df81f67)

### Steps to Reproduce

1. Prepare the Object for projection
2. Click "Generate"

### Expected Behavior

I expect to see the nice texture that the addon generated and projected on the target object.

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by NullSenseStudio** [comment]
Are you using Blender 3.5? This sounds like the bug in that version where it modifies the wrong UV map. https://github.com/carson-katri/dream-textures/issues/642
