### ISSUE TITLE
KeyError: 'bpy_prop_collection[key]: key "Principled BSDF" not found'

### ISSUE THREAD

**Issue by 0xkl** [carson-katri/dream-textures#705]
### Description

Python: Traceback (most recent call last):
  File "F:\blender app\blender_script\addons\dream_textures\operators\project.py", line 307, in execute
    material.node_tree.links.new(image_texture_node.outputs[0], material.node_tree.nodes['Principled BSDF'].inputs[0])
KeyError: 'bpy_prop_collection[key]: key "Principled BSDF" not found'

### Steps to Reproduce

I don't know why it has this problem.

### Expected Behavior

run 

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by 0xkl** [comment]
I have found a solution: just change the language to English to avoid this error.

But another error occurred:

An error occurred while generating. Check the issues tab on GitHub to see if this has been reported before:
OSError('Error no file named diffusion_pytorch_model.bin found in directory C:\\Users\\Administrator\\.cache\\huggingface\\hub\\models--runwayml--stable-diffusion-v1-5\\snapshots\\ded79e214aa69e42c24d3f5ac14b76d568679cc2\\vae.')

**Comment by 0xkl** [comment]
This issue has also been resolved:
It's because the VAE file was not fully downloaded, just download stable differentiation v1-5 again

**Comment by GottfriedHofmann** [comment]
> I have found a solution: just change the language to English to avoid this error.

It is very likely that the changing names of the nodes when using another language than English are causing this. Out of curiosity - which language did you have your UI in when the error occured?

**Comment by shiyuze112** [comment]
An error occurred while generating. Check the issues tab on GitHub to see if this has been reported before:

RuntimeError("OutOfMemoryError('CUDA out of memory. Tried to allocate 30.00 MiB (GPU 0; 2.00 GiB total capacity; 1.67 GiB already allocated; 0 bytes free; 1.72 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF')")
