### ISSUE TITLE
Duplicate of #622 - FIX NOT WORKING (OSError('Error no file named diffusion_pytorch_model.bin found...)

### ISSUE THREAD

**Issue by phattydee** [carson-katri/dream-textures#708]
### Description

An error occurred while generating. Check the issues tab on GitHub to see if this has been reported before:

OSError('Error no file named diffusion_pytorch_model.bin found in directory C:\\Users\\patri\\.cache\\huggingface\\hub\\models--stabilityai--stable-diffusion-2-depth\\snapshots\\6330e936a1cc2da7fe149bfba83462003f5e71c7\\vae.')

I tries deleting the model and redownloading as in #622 but problem persists.

### Steps to Reproduce

clicked Dream Texture. got the above error.

i deleted the stable-diffusion-2-depth model and restarted.

It downloaded the model again and still gives the same error.

### Expected Behavior

Expected to see the stable diffusion do it's magic thing.

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by shiyuze112** [comment]
An error occurred while generating. Check the issues tab on GitHub to see if this has been reported before:

ValueError('Scheduler.DPM_SOLVER_MULTISTEP cannot be used with DreamStudio.')

**Comment by shiyuze112** [comment]
I've run into this issue as well, can anyone fix it and can you provide an answer

**Comment by Pires77** [comment]
Any fix?

**Comment by Pires77** [comment]
> I've run into this issue as well, can anyone fix it and can you provide an answer

Did you found something?

**Comment by flyinggoatman** [comment]
Any fix found yet?

**Comment by shiyuze112** [comment]
> 找到任何修复了吗？

I tried to fix the issue after overwriting my previous model file with a small memory file in a model file downloaded by the lower version plugin in another version of blender

**Comment by shiyuze112** [comment]
> 有什么解决办法吗？

Download and keep the model file generated by the earlier version, and then overwrite the model file with the error

**Comment by Antszkol** [comment]
any fix?
