### ISSUE TITLE
gfpgan error

### ISSUE THREAD

**Issue by ProcopioPi** [carson-katri/dream-textures#71]
ERROR: Could not find a version that satisfies the requirement basicsr>=1.4.2 (from gfpgan) (from versions: 1.3.1, 1.3.2, 1.3.3, 1.3.3.1, 1.3.3.3, 1.3.3.4, 1.3.3.5, 1.3.3.6, 1.3.3.7, 1.3.3.8, 1.3.3.9, 1.3.3.10, 1.3.3.11, 1.3.4.0, 1.3.4.1, 1.3.4.2, 1.3.4.3, 1.3.4.4, 1.3.4.6, 1.3.4.7, 1.3.4.8, 1.3.4.9, 1.3.5, 1.4.0, 1.4.1, 1.4.2)
ERROR: No matching distribution found for basicsr>=1.4.2

**Comment by mty39** [comment]
Same here :(
Blender 3.3.0, Win 10, pip 22.2.2
PLEASE HELP

**Comment by mty39** [comment]
> ERROR: Could not find a version that satisfies the requirement basicsr>=1.4.2 (from gfpgan) (from versions: 1.3.1, 1.3.2, 1.3.3, 1.3.3.1, 1.3.3.3, 1.3.3.4, 1.3.3.5, 1.3.3.6, 1.3.3.7, 1.3.3.8, 1.3.3.9, 1.3.3.10, 1.3.3.11, 1.3.4.0, 1.3.4.1, 1.3.4.2, 1.3.4.3, 1.3.4.4, 1.3.4.6, 1.3.4.7, 1.3.4.8, 1.3.4.9, 1.3.5, 1.4.0, 1.4.1, 1.4.2) ERROR: No matching distribution found for basicsr>=1.4.2

works fot me:

Open up the Window registry (Start > Run > regedit)
Navigate to HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem
Set LongPathsEnabled to 1
