### ISSUE TITLE
potential Mac OS issue

### ISSUE THREAD

**Issue by Hoe2020** [carson-katri/dream-textures#715]
### Description

When attempting to installs stabilityai/stable-diffusion-2-1-base after installing the add-on the download never begins.

### Steps to Reproduce

1. Open Blender
2.  Download the dream textures version for Mac OS 
3.  Install the addon successfully 
4. Attempt to install the model.
5.  It gets stuck at 0%

### Expected Behavior

I expected the ai model to install. 
But the download never begins.
![image](https://github.com/carson-katri/dream-textures/assets/144179460/233ea1c8-e41f-40c5-a8c2-9e5d53cddfde)

### Addon Version

macOS (Apple Silicon)

### GPU

Apple Silicon

**Comment by enzyme69** [comment]
Try deleting this folder and try downloading again until it is complete:
/Users/YOURNAME/.cache/huggingface/diffusers

I had similar issue of this addon unable to complete the download because I accidentally closed Blender while it's downloading.
