### ISSUE TITLE
Want to make depth texture projection using SDXL and SDXL refiner with ControlNet Depth, but getting error

### ISSUE THREAD

**Issue by enzyme69** [carson-katri/dream-textures#724]
### Description

An error occurred while generating. Check the issues tab on GitHub to see if this has been reported before:

RuntimeError('linear(): input and weight.T shapes cannot be multiplied (77x2048 and 768x320)')

### Steps to Reproduce

setup texture projection as usual. I use depth controlnet. does not work.

### Expected Behavior

Supposedly just work when depth specified.

### Addon Version

macOS (Apple Silicon)

### GPU

Apple Silicon

**Comment by carson-katri** [comment]
Which base model and depth ControlNet model are you using?
