### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by shiyuze112** [carson-katri/dream-textures#727]
### Description

An error occurred while generating. Check the issues tab on GitHub to see if this has been reported before:

FileNotFoundError(2, '系统找不到指定的路径。')

### Steps to Reproduce

bpy.ops.shade.dream_texture()

An error occurred while generating. Check the issues tab on GitHub to see if this has been reported before:

FileNotFoundError(2, '系统找不到指定的路径。')

### Expected Behavior

How to fix it

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by carson-katri** [comment]
Can you try redownloading the model in Blender's preferences? This may resolve the issue automatically.

**Comment by GottfriedHofmann** [comment]
I did have a similar issue with stabilityai/stable-diffusion-2-1 and re-downloading it in the preferences fixed it, thanks!

**Comment by shiyuze112** [comment]
An error occurred while generating. Check the issues tab on GitHub to see if this has been reported before:

OSError('Error no file named diffusion_pytorch_model.bin found in directory C:\Users\adity\.cache\huggingface\hub\models--stabilityai--stable-diffusion-2-depth\snapshots\6330e936a1cc2da7fe149bfba83462003f5e71c7\unet.')


I tried to delete the model and download it again, but it still gets an error, is there a solution?

**Comment by shiyuze112** [comment]
> 引用
An error occurred while generating. Check the issues tab on GitHub to see if this has been reported before:

OSError('Error no file named diffusion_pytorch_model.bin found in directory C:\Users\adity.cache\huggingface\hub\models--stabilityai--stable-diffusion-2-depth\snapshots\6330e936a1cc2da7fe149bfba83462003f5e71c7\unet.')

I tried to delete the model and download it again, but it still gets an error, is there a solution?

**Comment by shiyuze112** [comment]
> Can you try redownloading the model in Blender's preferences? This may resolve the issue automatically.

An error occurred while generating. Check the issues tab on GitHub to see if this has been reported before:

OSError('Error no file named diffusion_pytorch_model.bin found in directory C:\Users\adity.cache\huggingface\hub\models--stabilityai--stable-diffusion-2-depth\snapshots\6330e936a1cc2da7fe149bfba83462003f5e71c7\unet.')

I tried to delete the model and download it again, but it still gets an error, is there a solution?

**Comment by GottfriedHofmann** [comment]
That seems to be a different error unfortunately.

**Comment by shiyuze112** [comment]
> 不幸的是，这似乎是一个不同的错误。

Yes, I have solved the previous problem, but a new one has appeared

**Comment by Pires77** [comment]
Same here.
