### ISSUE TITLE
ZIP Installation without errors, but the addon is not installed

### ISSUE THREAD

**Issue by Belluxx** [carson-katri/dream-textures#728]
### Description

I get the following log: `Modules Installed () from 'Users/user/Downloads/dream_textures-macos-arm.zip' into '/Users/user/Library/Application Support/Blender/3.6/scripts/addons'`

If i go to `/Users/user/Library/Application Support/Blender/3.6/scripts/addons/Users/carsonkatri/Documents/Art/Add-ons/Custom/Blender/dream_textures/` i see all the flies and directories that are needed for the addon and the directory weight is **1.3GB**

What i tried:
* De-quarantine python dependencies (from the correct directory): `xattr -r -d com.apple.quarantine .python_dependencies`
* Manually extract and move ZIP contents to the blender directory

Info:
* Blender: 3.6.5
* dream-textures: 0.3.0
* MacOS: 13.6
* SoC: M1 Base

### Steps to Reproduce

1. Click on `Edit`
2. Click on `Preferences`
3. Go to `Add-ons` tab
4. Click `Install`
5. Choose the ZIP
6. Wait for installation
7. Get the `Modules Installed () from ...` log (note the empty bracket content)
8. Search for the module in the list
9. Nothing found

### Expected Behavior

The addon is added to the list of available addons so that i can enable it

### Addon Version

macOS (Apple Silicon)

### GPU

Apple Silicon

**Comment by enzyme69** [comment]
On Mac, if you check the folder, you see Carson might have forgotten to simplify the folder tree structure. Just found "dream texture" folder and recompress it yourself. Then install the addon. It should work.

**Comment by Belluxx** [comment]
@enzyme69 Thanks, that was the issue, now it's working perfectly.
I'll leave the issue open since this may be useful for others before the zip gets fixed

**Comment by carson-katri** [comment]
Good catch, the release has been fixed.
