### ISSUE TITLE
Minimum/Recommended PC specs?

### ISSUE THREAD

**Issue by JotaRata** [carson-katri/dream-textures#73]
What are the recommended GPUs and RAM amount to run this add-on properly?

**Comment by NullSenseStudio** [comment]
It should be able to run on as little as 4GB of VRAM, and I think 10GB of VRAM is normally recommended for running on full precision. I personally have an 8GB card and have generated up to 1024x1024 images with full precision disabled.

**Comment by sorcerice** [comment]
I'm using a 1660 super with 6gb vram and it doesn't generate anything. I think 8GB is the minimum requirement. Also it could be a problem with 1600 generation cards. (tried it with full precision at 16x16)
