### ISSUE TITLE
Image File Naming Bug

### ISSUE THREAD

**Issue by enzyme69** [carson-katri/dream-textures#734]
### Description

Image file naming for generated is not right

### Steps to Reproduce

Generate image using image editor as usual. Provide list of batch of text to generate image. Use a very long prompt. Make batch again and again, sometimes the name is using the old one.

### Expected Behavior

The naming should match prompt regardless how long the prompt is.

### Addon Version

macOS (Apple Silicon)

### GPU

Apple Silicon

**Comment by enzyme69** [comment]
Below is prompt VS what file naming I got, the one after many text. It's still using ULTRAMAN instead of DINO

<img width="1248" alt="Screenshot 2023-11-08 at 8 23 35 am" src="https://github.com/carson-katri/dream-textures/assets/3952687/7d60201c-1731-4129-8a86-d83c13b4d98d">
<img width="544" alt="Screenshot 2023-11-08 at 8 23 42 am" src="https://github.com/carson-katri/dream-textures/assets/3952687/dc93f837-53f2-4d31-aeb9-a32b5dc69df6">

**Comment by carson-katri** [comment]
Blender has a length limit of 64 on image datablock names, so we need to truncate it.
