### ISSUE TITLE
GPU Server Feature

### ISSUE THREAD

**Issue by MincoMK** [carson-katri/dream-textures#742]
Please make remote server (self-hosted) GPU image generation.

**Comment by wizard3376** [comment]
It will be very cool

**Comment by fantasyRqg** [comment]
I luckily got something working on remote server. I'm still working on test and modify, hope to add some logic to hold the inference pipeline without load it ervery time.

![Screenshot 2024-01-11 at 22 15 36](https://github.com/carson-katri/dream-textures/assets/3463310/d4adda0d-0efb-4d58-8370-1f4ae0961911)
