### ISSUE TITLE
Project Dream Texture button greyed out

### ISSUE THREAD

**Issue by saminatorkash** [carson-katri/dream-textures#747]
### Description

Using a Mac pro M2 8gb 256 variant. 
using Blender 4.0.
Installed Dream Textures addon.
downloaded the models.

getting the error in console as soon as I open the dream menu upon hovering on any options in the menu.

**WARN (bpy.rna): source/blender/python/intern/bpy_rna.cc:1349 pyrna_enum_to_py: current value '1' matches no enum in 'DreamPrompt', '', 'backend'**

Traceback (most recent call last):
  File "/Users/saminator/Library/Application Support/Blender/4.0/scripts/addons/dream_textures/ui/panels/dream_texture.py", line 361, in draw
    backend.validate(prompt.generate_args(context))
  File "/Users/saminator/Library/Application Support/Blender/4.0/scripts/addons/dream_textures/property_groups/dream_prompt.py", line 268, in generate_args
    model=next(model for model in self.get_backend().list_models(context) if model is not None and model.id == self.model),
StopIteration

Also the system runs out of memory when generating image from prompt in the image editor.

### Steps to Reproduce

1. Install the addon.
2. download the models.
3. write the prompt.
4. select the defaults.
5. hit produce button. it will give a traceback error.
6. Restart Blender.
7. the button will be greyed out.

### Expected Behavior

The button working as intended.

### Addon Version

macOS (Apple Silicon)

### GPU

Apple Silicon

**Comment by ShadowAimai** [comment]
I am getting this error as well in Blender 4, PC, RTX 3060. I tried reinstalling but got the same issue.

**Comment by saminatorkash** [comment]
> I am getting this error as well in Blender 4, PC, RTX 3060. I tried reinstalling but got the same issue.

Same here..reinstalled it but nothing happened.

**Comment by NullSenseStudio** [comment]
Blender 4.0 is not supported yet. You can use anything between 3.1-3.6 in the meantime.
