### ISSUE TITLE
Error installing dependencies

### ISSUE THREAD

**Issue by mostafa5tommy** [carson-katri/dream-textures#75]
![Screenshot 2022-09-22 223514](https://user-images.githubusercontent.com/114188939/191846635-c7453006-4f6d-44ed-8bc2-3a483d0f9d23.png)

here problem i had while i try to install 
i follow all the instruction even i changed the long path letter to 1 and i still have same issue
also downloaded the main zip file not the source code

**Comment by carson-katri** [comment]
Look in the system console not Blender’s console to see what error message it says.

**Comment by mostafa5tommy** [comment]
![S2](https://user-images.githubusercontent.com/114188939/191848886-dc8effa6-979f-4de9-a0bf-6d7ce5ea670c.png)

**Comment by carson-katri** [comment]
Did you install git to your system?

**Comment by mostafa5tommy** [comment]
i don't know what git is in first place !

**Comment by carson-katri** [comment]
It is used to install some dependencies, and should show as the first step in the preferences windows. You can get it at https://git-scm.org

**Comment by mostafa5tommy** [comment]
is that fine :
![S3](https://user-images.githubusercontent.com/114188939/191857291-f85ad29a-b0e1-4540-b000-c053f310292d.png)

**Comment by NeonThoth** [comment]
im having a simlar issue any updates on how to fix it??

**Comment by iamforgettable** [comment]
Upgrading pip got my past this step but I get stuck on the next...

> blender-3.3.0-linux-x64/3.3/python/bin/python3.10 -m pip install --upgrade pip

**Comment by Vaxy-27** [comment]
Had the original problem but upgrading from 3.0 > 3.3 fixed that. Now I'm getting the same PATH warnings for over 23 scripts and have no idea what PATH I have to change, mine is installed in the same place.

**Comment by carson-katri** [comment]
Nothing looks wrong in that screenshot to me. They’re just warnings not errors, so I don’t think anything went wrong.

**Comment by Vaxy-27** [comment]
So after a proper look at the main page I noticed my GPU needs CUDA, my RX 6800 doesn't have that... The video I watched didn't mention this and I missed it on the **<>code** section, might want to move **Compatibility** to the top.

**Comment by mostafa5tommy** [comment]
Thanks to [carson-katri] after i install Git and install dependencies it work fine this time and after i move on on rest of steps 
you helped me a lot and now everything work just fine 
just it take more time when i change the resolution from 512 to 1080 like it don't take the effect 
but as long i work with 512 everything work fine 
i would like to mention my graphic card not RTX
