### ISSUE TITLE
AI Model Doesn't Install on Macbook M1 (Issue #715?)

### ISSUE THREAD

**Issue by FuzzyTheFirst** [carson-katri/dream-textures#751]
### Description

I am unable to use Dream Textures as trying to install any model through Blender/DreamTextures ad-don causes nothing to happen. I am unable to search for other models because nothing shows up, and clicking the "Install Stable Diffusion 2.1" button just leaves it at 0%. I am unable to do anything further and have to re-install the ad-don if I want access to those 2 buttons again.

If it matters, I'm using blender through Steam.

### Steps to Reproduce

1. Go to Preferences, Add-ons
2. Install Dream Textures via the .zip file
3. Enable the ad-don
4. Search for "stable" within the search bar within the add-on (nothing shows up for me)
5. Press the button that should install stable diffusion 2.1 (It stays at 0% and doesn't change for me)
<img width="479" alt="Screenshot 2023-11-21 at 8 34 33 PM" src="https://github.com/carson-katri/dream-textures/assets/97268304/2ee1b908-7528-49ae-8fa0-4be4b360616e">

### Expected Behavior

1. Options should show up when searching "stable"
2. Stable Diffusion 2.1 should actually download when the button is pressed

### Addon Version

macOS (Apple Silicon)

### GPU

Apple Silicon

**Comment by wizard3376** [comment]
I have Windows 10 but have exactly the same problem
