### ISSUE TITLE
Path too long

### ISSUE THREAD

**Issue by amazingoomoo** [carson-katri/dream-textures#752]
### Description

Trying to unzip the downloaded file into C:\Users\MY USERNAME\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons and I get this error:
![image](https://github.com/carson-katri/dream-textures/assets/43025827/26d4d1f0-3845-44c1-82c8-870bcc8598bd)
My username is only four letters long. Could the file be renamed to something shorter than **convert_trajectory_transformer_original_pytorch_checkpoint_to_pytorch.cpython-310.pyc**? Thanks.

### Steps to Reproduce

Just try to extract the file.

### Expected Behavior

The file would have a shorter name to avoid giving this error. My username is only four characters long. I don't understand how other people aren't having this issue?

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by JakeMcCann** [comment]
I had this same problem on Windows 11, despite having long path names enabled.

It worked when I extracted the file into a folder further up the path tree; I extracted it to my desktop, for example.

I've read that extracting with 7Zip doesn't have this problem, which could be another option to try.

**Comment by JakeMcCann** [comment]
I got around this by extracting it to my desktop first (i.e. further up the path tree), then copying the folder from there into the Blender scripts folder.
