### ISSUE TITLE
error when clicking generate

### ISSUE THREAD

**Issue by TearsRfuel** [carson-katri/dream-textures#762]
### Description

Python: Traceback (most recent call last):
  File "C:\Users\Me\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\dream_textures\engine\annotations\depth.py", line 32, in _execute
    shader = gpu.shader.from_builtin('3D_UNIFORM_COLOR')
ValueError: expected a string in ('FLAT_COLOR', 'IMAGE', 'IMAGE_COLOR', 'SMOOTH_COLOR', 'UNIFORM_COLOR', 'POLYLINE_FLAT_COLOR', 'POLYLINE_SMOOTH_COLOR', 'POLYLINE_UNIFORM_COLOR'), got '3D_UNIFORM_COLOR'

### Steps to Reproduce

click on generate image

### Expected Behavior

an image to generate

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by Greaterist** [comment]
'3D_UNIFORM_COLOR' was removed in blender 4. Downgrade to 3.6
