### ISSUE TITLE
Error in Blender 4.0 MacOS Apple Silicon

### ISSUE THREAD

**Issue by hemanth-x** [carson-katri/dream-textures#766]
### Description

Python: Traceback (most recent call last):
  File "/Users/hemanthsubbiah/Library/Application Support/Blender/4.0/scripts/addons/dream_textures/engine/annotations/depth.py", line 32, in _execute
    shader = gpu.shader.from_builtin('3D_UNIFORM_COLOR')
ValueError: expected a string in ('FLAT_COLOR', 'IMAGE', 'IMAGE_COLOR', 'SMOOTH_COLOR', 'UNIFORM_COLOR', 'POLYLINE_FLAT_COLOR', 'POLYLINE_SMOOTH_COLOR', 'POLYLINE_UNIFORM_COLOR'), got '3D_UNIFORM_COLOR'

### Steps to Reproduce

1. Install stable-diffusion-2-depth
2. Create a cube -> Edit mode -> Subdivide the mesh couple of times -> Press 'a' to select all faces -> Run "Project dream texture" with configuration as shown in image.
<img width="468" alt="Screenshot 2023-12-29 at 8 59 51 AM" src="https://github.com/carson-katri/dream-textures/assets/11975695/cc5cd4bf-e075-4979-b2af-8b3826f12785">

### Expected Behavior

Works as expected in Blender 3.5x versions, but not working in Blender 4.0. Used same machine. The texture generation model works as expected in Blender 4.0 though. Only the depth model is having issue.

### Addon Version

macOS (Apple Silicon)

### GPU

Apple Silicon

**Comment by blastframe** [comment]
I'm also having this issue with Blender 4.0 on MacOS Apple Silicon, but the Texture Generation model isn't working for me either.
![Screenshot 2023-12-30 at 10 02 33 AM](https://github.com/carson-katri/dream-textures/assets/3729547/29fef9b2-fe52-4f83-bb9a-0649cc4e2072)
![Screenshot 2023-12-30 at 10 08 17 AM](https://github.com/carson-katri/dream-textures/assets/3729547/156d67fe-f450-41df-a5ff-40f0453a5ecf)

**Comment by renggli** [comment]
Using the [command-line-rendering](https://github.com/carson-katri/dream-textures/tree/command-line-rendering)  branch solves the problem for me.

**Comment by CyWP** [comment]
I simply changed this line of code in engine/annotations/depth.py, works fine now!
Mind you I had the same issue in Windows with an AMD Ryzen 9 and an Nvidia Rtx3060Ti, Blender 4.0.3
![image](https://github.com/carson-katri/dream-textures/assets/77861524/7709c190-1661-4d18-8843-cd632a43741f)
