### ISSUE TITLE
Generating with a linked Checkpoint/safetensor file or folder will fail if the addon can't connect to the internet

### ISSUE THREAD

**Issue by Tertion** [carson-katri/dream-textures#771]
### Description

Note  : this is possible that this is the same problem encountered by the person that reported issue#750 (https://github.com/carson-katri/dream-textures/issues/750)

It appear that generation using a linked .pkg/.safetensor file require the addon to connect to an external service/server to founction. Note : this behavior is not present if using an HugginFace model downloaded directly from the addon's preferences. [[THis was tested using the DT node render engine]]

### Steps to Reproduce

1. Make it not possible for the addon to connect to the internet (ex: turn off your wifi, close the port(s) used by blender, unproperly setup a DNS or a network-wide add blocking system like a Pie-Hole...)

2- Try to generate an image using a model that is a linked checkpoint/safetensor file

Result :

The generation will fail and the following error message will appear : 
ConnectionError(MaxRetryError('HTTPSConnectionPool(host=\'raw.githubusercontent.com\', port=443): Max retries exceeded with url: /CompVis/stable-diffusion/main/configs/stable-diffusion/v1-inference.yaml (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FC841FB8B0>: Failed to resolve \'raw.githubusercontent.com\' ([Errno 11001] getaddrinfo failed)"))'))

### Expected Behavior

The addon should be able to generate locally and offline.

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by carson-katri** [comment]
To add a model without an internet connection you need to select the model configuration in the sidebar when importing it.

Press N to reveal the sidebar in the file selector window. Then choose the correct model configuration from the dropdown.

**Comment by Tertion** [comment]
> To add a model without an internet connection you need to select the model configuration in the sidebar when importing it.
> 
> Press N to reveal the sidebar in the file selector window. Then choose the correct model configuration from the dropdown.

I think you misunderstood.
 The problem is that you cannot USE a model you added this way without an internet connection.
