### ISSUE TITLE
cant use model on amd gpu

### ISSUE THREAD

**Issue by FINNisherGH** [carson-katri/dream-textures#785]
### Description

i downloaded the amd version of the dream textures addon, and after installing it nothing came up for the first couple of times, im using blender 3.6. eventually the addon appeared as in the screenshot, but it wont let me select a model, it didnt ask for one either when installing the plugin. i got a model.ckpt in my download folder but impossible to select it as an option.
![136z18746178](https://github.com/carson-katri/dream-textures/assets/54814086/f33badf7-59ec-483b-8763-51952d9e01f4)

### Steps to Reproduce

use amd graphics card, in my case rx570 with 8gb vram
install amd version of the dream textures add on

### Expected Behavior

i would expect the plugin to ask for either the llm or run right away

### Addon Version

Other (Built from source)

### GPU

AMD (unsupported for local generation)

**Comment by cornpo** [comment]
Use the plugin interface under Blender Edit->Preferences->Dream Textures to download the suggested model.

Copying that model where it needs to go by hand is a challenge.

**Comment by FINNisherGH** [comment]
> >Dream Textures to download the suggested model.

The thing is that nothing shows up when it comes to asking for a model in the Preferences tab after installing the addon.
