### ISSUE TITLE
Dream Texture doesn't download any library and search doesn't work

### ISSUE THREAD

**Issue by gioxyer** [carson-katri/dream-textures#787]
### Description

Refer to #786, I fixed the problem with cuda version but when downloading any library or search, it stuck at 0% and I couldn't search any models
![image](https://github.com/carson-katri/dream-textures/assets/161426313/c724502b-3184-4c1b-9711-85fc851c451f)

### Steps to Reproduce

From enable AddOn download recommend stability diffusion v2.1
Search any models

### Expected Behavior

From enable AddOn download recommend stability diffusion v2.1 and it will download
Search any models and it will work

### Addon Version

Windows (CUDA)

### GPU

Other

**Comment by LordVortexCake** [comment]
I too am having this problem, installed the zip and now on the dependencies are frozen on 0%

**Comment by gioxyer** [comment]
Do you have the last version too, right?

**Comment by gioxyer** [comment]
I think the AddOn require an update, considering that python library change even from Blender 4.0 to Blender 4.1 and some improvements in Mesh since Blender 3.6

**Comment by tommywright** [comment]
Same issue

**Comment by helishmopter** [comment]
same, win11, cuda version, blender 4.1.0

**Comment by tommywright** [comment]
On Discord they guy says it doesn't work with newer versions of Blender. I'm not sure he's still working on it.

**Comment by carson-katri** [comment]
The next release of Dream Textures will support Blender 4.x. You can try out the prerelease builds here: https://github.com/carson-katri/dream-textures/actions/runs/9331190844

**Comment by tommywright** [comment]
OH nice! I thought the last version of Blender it supported was like 3.5 which is why I thought the project might be dead.

**Comment by helishmopter** [comment]
Thanks @carson-katri! The prerelease works for image generation in the img editor, but I get the following error when I try to Project Dream Texture onto faces in edit mode:

An error occurred while generating. Check the issues tab on GitHub to see if this has been reported before:

TypeError("StableDiffusionInpaintPipeline.check_inputs() missing 3 required positional arguments: 'strength', 'callback_steps', and 'output_type'")

Is there anything that can be done to fix this error? Did I miss anything in setup? Thank you

WIN11 cuda, Blender 4.1.0

**Comment by gioxyer** [comment]
Thank you so much

**Comment by gabor-smith** [comment]
> Thanks @carson-katri! The prerelease works for image generation in the img editor, but I get the following error when I try to Project Dream Texture onto faces in edit mode:
> 
> An error occurred while generating. Check the issues tab on GitHub to see if this has been reported before:
> 
> TypeError("StableDiffusionInpaintPipeline.check_inputs() missing 3 required positional arguments: 'strength', 'callback_steps', and 'output_type'")
> 
> Is there anything that can be done to fix this error? Did I miss anything in setup? Thank you
> 
> WIN11 cuda, Blender 4.1.0

Same issue here

Windows 10, Blender 4.1.0, Directml

**Comment by carson-katri** [comment]
There are new builds available that should hopefully resolve these issues: https://github.com/carson-katri/dream-textures/actions/runs/9343245628

**Comment by helishmopter** [comment]
> There are new builds available that should hopefully resolve these issues: https://github.com/carson-katri/dream-textures/actions/runs/9343245628

Amazing, it works! Thanks so much!

**Comment by misosoup1990** [comment]
> There are new builds available that should hopefully resolve these issues: https://github.com/carson-katri/dream-textures/actions/runs/9343245628

The server on GitHub is very bad, doesn't support resume on IDM.
To download a 3GB (large) file, if it gets interrupted in the middle you have to start over again.

I'm having trouble downloading because the GitHub server will close itself if it takes too long, while the download process hasn't finished yet.

You should divide it into several small file parts so that users can download it without fail.

**Comment by misosoup1990** [comment]
![Untitled-1](https://github.com/carson-katri/dream-textures/assets/171687466/810934d6-cb84-4ee3-bfff-69b676682c68)

It happens again !
2.7GB/2.9GB download process and failed!

DO YOU WANT TO DOWNLOAD THIS FILE FROM THE BEGINNING ?
NOOOOOOOOOOO!!!!!!

**Comment by 42320611** [comment]
Only in the latest version of the use of the failure, ,other releases will be the same situation ?

**Comment by 42320611** [comment]
An error occurred while generating. Check the issues tab on GitHub to see if this has been reported before:

TypeError("StableDiffusionInpaintPipeline.check_inputs() missing 3 required positional arguments: 'strength', 'callback_steps', and 'output_type'")   Is there anything that can be done to fix this error? Did I miss anything in setup? Thank you

**Comment by aaaaaaaaargh** [comment]
I solved this by downgrading and pinning  `huggingface_hub` to version 0.22.0. The reason for me was that they recently changed their API and therefore certain types such as ModelFilter don't exist anymore.
