### ISSUE TITLE
Blender 3.3 Installation Failure

### ISSUE THREAD

**Issue by whthawk** [carson-katri/dream-textures#79]
Hello,

First, thank you for this amazing work!  I am attempting to install this but have run into issues.  A couple I have fixed like the pip version issue and the run ad administrator requirement I missed.  However, I am getting this at I attempt to install the prereqs:

  Preparing metadata (setup.py) ... done
Obtaining file:///C:/Users/Jeff/AppData/Roaming/Blender%20Foundation/Blender/3.3/scripts/addons/dream-textures-main/stable_diffusion (from -r C:\Users\Jeff\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream-textures-main\requirements-win-torch-1-11-0.txt (line 33))
ERROR: file:///C:/Users/Jeff/AppData/Roaming/Blender%20Foundation/Blender/3.3/scripts/addons/dream-textures-main/stable_diffusion (from -r C:\Users\Jeff\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream-textures-main\requirements-win-torch-1-11-0.txt (line 33)) does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

Not sure what it is asking for.  Line 33 is just an entry "-e ." w/o the quotes.  Line above is tourchvision alone.  Can you share where I might be going wrong?  Thank you.

**Comment by NullSenseStudio** [comment]
"-e ." is to install the current working directory (the stable_diffusion directory within the addon) so the python environment will be able to use it as a module.

It looks like you downloaded the main branch as a zip so the stable_diffusion directory is completely empty. You'll either have to download stable_diffusion and place it in that directory or [download the addon from the releases which includes that.](https://github.com/carson-katri/dream-textures/releases)
