### ISSUE TITLE
No issues installing addon or error messages but images wont generate in the shader

### ISSUE THREAD

**Issue by advladim** [carson-katri/dream-textures#8]
addon installed perfectly with no issues or errors on Blender versions of 3.3, 3.2.2, 3.1.2. The shader will not generate an image output in the shader. It would take a moment after hitting ok and not create a texture.

**Comment by carson-katri** [comment]
What do the console logs say: “Window” > “Toggle System Console”? Is there any error log there?

**Comment by advladim** [comment]
This is the result in the console in Blender 3.3.0, maybe you can see something I don't

[SystemConsole.txt](https://github.com/carson-katri/dream-textures/files/9556801/SystemConsole.txt)

**Comment by carson-katri** [comment]
It looks like the automatic downloads of the secondary models got corrupted or failed somehow. I would simply suggest repeating the process with a fresh install of Blender 3.3, and see if it works then.

**Comment by advladim** [comment]
Still having the same problem even with a fresh install of 3.3 but here's the system console whilst installing the dependencies and model:

[SystemConsole During installation.txt](https://github.com/carson-katri/dream-textures/files/9557450/SystemConsole.During.installation.txt)
