### ISSUE TITLE
Can't load tokenizer for 'openai/clip-vit-large-patch14 on Linux

### ISSUE THREAD

**Issue by NathanSalapat** [carson-katri/dream-textures#80]
I'm running 0.0.5 on Linux Mint 20.2 with 64GB of ram, and a GeForce GTX 1060 6GB I get the following error when I try to generate an image. The addon reports correct installation when checking from the preferences window.

`>> Loading model from /home/nathans21/.config/blender/3.2/scripts/addons/dream_textures/stable_diffusion/models/ldm/stable-diffusion-v1/model.ckpt
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<DreamTexture.dream_texture() done, defined at /home/nathans21/.config/blender/3.2/scripts/addons/dream_textures/operators/dream_texture.py:105> exception=OSError("Can't load tokenizer for 'openai/clip-vit-large-patch14'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'openai/clip-vit-large-patch14' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.")>
Traceback (most recent call last):
  File "/home/nathans21/.config/blender/3.2/scripts/addons/dream_textures/operators/dream_texture.py", line 136, in dream_texture
    generator.load_model()
  File "/home/nathans21/.config/blender/3.2/scripts/addons/dream_textures/stable_diffusion/ldm/generate.py", line 457, in load_model
    model = self._load_model_from_config(self.config, self.weights)
  File "/home/nathans21/.config/blender/3.2/scripts/addons/dream_textures/stable_diffusion/ldm/generate.py", line 578, in _load_model_from_config
    model = instantiate_from_config(c.model)
  File "/home/nathans21/.config/blender/3.2/scripts/addons/dream_texturesl/stable_diffusion/ldm/util.py", line 89, in instantiate_from_config
    return get_obj_from_str(config['target'])(
  File "/home/nathans21/.config/blender/3.2/scripts/addons/dream_texturesl/stable_diffusion/ldm/models/diffusion/ddpm.py", line 657, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File "/home/nathans21/.config/blender/3.2/scripts/addons/dream_texturesl/stable_diffusion/ldm/models/diffusion/ddpm.py", line 768, in instantiate_cond_stage
    model = instantiate_from_config(config)
  File "/home/nathans21/.config/blender/3.2/scripts/addons/dream_texturesl/stable_diffusion/ldm/util.py", line 89, in instantiate_from_config
    return get_obj_from_str(config['target'])(
  File "/home/nathans21/.config/blender/3.2/scripts/addons/dream_texturesl/stable_diffusion/ldm/modules/encoders/modules.py", line 245, in __init__
    self.tokenizer = CLIPTokenizer.from_pretrained(
  File "/home/nathans21/blender-3.2.2/3.2/python/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1768, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'openai/clip-vit-large-patch14'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'openai/clip-vit-large-patch14' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.
/home/nathans21/.config/blender/3.2/scripts/addons/dream_textures/async_loop.py:62: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
`

**Comment by vuaieo** [comment]
hi i just wanted report same problem exactly that i get in the terminal on endeavour os (arch linux) oin blender 3.4
tryed to install on 3.3 lts but it says no pip module..

**Comment by vuaieo** [comment]
sry i dont understand what you mean with script running there and how to do and what script even can you help ?

**Comment by NathanSalapat** [comment]
Trying to run that python script gives this result.
`python3 preload_models.py 
Traceback (most recent call last):
  File "preload_models.py", line 6, in <module>
    from transformers import CLIPTokenizer, CLIPTextModel
ModuleNotFoundError: No module named 'transformers'
`
Which makes sense because none of the Blender modules are available. Trying to see if I can run the script within Blender, and will update once I figure that out.

**Comment by NathanSalapat** [comment]
That worked! Thanks
@vuaieo In Blender if you go to the Scripting tab you can open a python file, browse to `dream_textures/stable_diffusion/scripts/preload_models.py` and run the script. It will hang for a while as it downloads around 1.5GB of data. Once that finishes you should hopefully be able to generate a texture.

**Comment by vuaieo** [comment]
well thanks super much guys @NathanSalapat @carson-katri  i followed what you said and it worked that it downloaded stuff but problem now is if i try to generate something then my pc freezes, the led light on front of pc case flashes all the time and fans goes up but mouse freezes and keyboard freezes and nothing cant do . i waited for few minutes but nothing happened, can you explain how long should be waited to generate it? on the video it was few second T_T well i got 16gb ram with ryzen 5700G and RTX 3080 ti if that helps.. what can i do ?

**Comment by NathanSalapat** [comment]
Try opening the system monitor an GPU monitors before trying to generate an image. It's possible that you are just maxing out all your system resources. You could also try a lower resolution image, or fewer samples, just to see if it's actually working. On my system I can't go above 512x512 as I run out of vRam.

**Comment by vuaieo** [comment]
yea i tryed but couldnt. well i tryed 64 x 64 and it still same freezing T__T

**Comment by NathanSalapat** [comment]
If you launch blender with a terminal do you get any output when clicking the generate button?

**Comment by vuaieo** [comment]
OMG its working now !! i wanted make picutre but i today checked the addon preference and clicked on validate and restarted and then it suddenly works THANKS SUPER MUCH : )
