### ISSUE TITLE
when generating nothing happens, reinstalling depencies wont fix it

### ISSUE THREAD

**Issue by miaumori** [carson-katri/dream-textures#85]
might be similar to it https://github.com/carson-katri/dream-textures/issues/35, but i also doubt if my depencies installed succesfully, because when i was installing them for the first time i had multiple loadings finished succesfully, but one of them (1.59GB one i believe) was loading slower than 1kb/s and then it had just skipped i think... then:

it says depencies installed sucessfuly, but when i hit install them again i get this:
[depencies.txt](https://github.com/carson-katri/dream-textures/files/9633856/depencies.txt)

then when i try to generate image nothing happens, and the console says this:

[generating.txt](https://github.com/carson-katri/dream-textures/files/9633874/generating.txt)

i have gtx 1660 6gb

**Comment by JustSlothMate** [comment]
Personally I'd try reinstalling depencies or the whole thing from scratch. Make sure that you're running Blender as admin when installing the add on also. The first time I tried to install depencies I had some errors when the downloads started and it just crashed in the end, I started it again from square one and it works fine for me now at 512x512 with a GTX1060 6GB.

**Comment by miaumori** [comment]
> Personally I'd try reinstalling depencies or the whole thing from scratch. Make sure that you're running Blender as admin when installing the add on also. The first time I tried to install depencies I had some errors when the downloads started and it just crashed in the end, I started it again from square one and it works fine for me now at 512x512 with a GTX1060 6GB.

i writed that i tried reinstalling them by click install button once more and what it says when i try to
or there is other way to reisntall them? even if i delete addon it looks like it keep tem

**Comment by JustSlothMate** [comment]
> > Personally I'd try reinstalling depencies or the whole thing from scratch. Make sure that you're running Blender as admin when installing the add on also. The first time I tried to install depencies I had some errors when the downloads started and it just crashed in the end, I started it again from square one and it works fine for me now at 512x512 with a GTX1060 6GB.
> 
> i writed that i tried reinstalling them by click install button once more and what it says when i try to or there is other way to reisntall them? even if i delete addon it looks like it keep tem

Did you disable the add on, Open the drop down box and select "Remove" for the add on itself or just the depencies?
Sorry I don't really have a clue I'm just trying to suggest something that might help. Also make sure that you downloaded the add on through the "Releases" tab as just downloading the ZIP as you usually would might not have all the correct data

**Comment by miaumori** [comment]
> 

yes i tried the remove button in the addon button

**Comment by miaumori** [comment]
fixed it by deleting C:\Users\user\.cache\huggingface folder, and after it succesfully reinstalled depencies. that make it work!

**Comment by alexandis** [comment]
So do I get it right the current bug is "closed", because there's version 0.0.6 is coming where the given issue gonna be resolved? ;)

**Comment by miaumori** [comment]
> So do I get it right the current bug is "closed", because there's version 0.0.6 coming where the given issue gonna be resolved? ;)

i closed that one because i already foud solution to exact my issue, the error was because my depencies wasnt isntalled correctly and i was not be able to reisntall them with addon menu so i had to unisntall them by deleting folder manually and install them again

**Comment by alexandis** [comment]
> > So do I get it right the current bug is "closed", because there's version 0.0.6 coming where the given issue gonna be resolved? ;)
> 
> i closed that one because i already foud solution to exact my issue, the error was because my depencies wasnt isntalled correctly and i was not be able to reisntall them with addon menu so i had to unisntall them by deleting folder manually and install them again

Oops, sorry. Just navigated to the linked issue which is yours. But our error is different and seems like no solution yet.
