### ISSUE TITLE
Trouble installing Dependencies

### ISSUE THREAD

**Issue by dariomoriconi** [carson-katri/dream-textures#86]
I've tried every solution found online.. still getting the following error:

<img width="567" alt="Schermata 2022-09-23 alle 15 42 27" src="https://user-images.githubusercontent.com/114239174/191973826-1e29fd1f-399b-459d-8e76-83386a6a6471.png">

**Comment by ExercitusMortem** [comment]
I had a similar error but I had downloaded the wrong file. Make sure to get it from here
https://github.com/carson-katri/dream-textures/releases/tag/0.0.5

**Comment by dariomoriconi** [comment]
I finally solved reinstalling Blender.
