### ISSUE TITLE
Files above 512x512 don't work

### ISSUE THREAD

**Issue by JustSlothMate** [carson-katri/dream-textures#88]
Whenever I try to change the resolution size above the default size (512x512) it loads for a couple seconds but then does nothing. Changing the resolution back down the 512x512 generates a picture. I've probably installed something wrong  but I have no idea what or where to start to fix this.

**Comment by carson-katri** [comment]
You probably do not have enough VRAM for larger images.

**Comment by JustSlothMate** [comment]
Oh Probably, I only have 6Gb VRAM unfortunately
