### ISSUE TITLE
There is no current event loop

### ISSUE THREAD

**Issue by drag0nD** [carson-katri/dream-textures#9]
when i try generating anything it freeze for 2 seconds then nothing happens this is the log
https://pastelink.net/j9kp9jxc

**Comment by gavin-collier** [comment]
I am also having this problem.
[](https://pastebin.com/kYewsDVL)

I am running on the latest version of blender on Windows 11 if that helps.

**Comment by HowTheHellDoIdoThis** [comment]
i have the same issue, except for me instead of freezing for two seconds each attempt it just stops responding for a while on the first attempt and then every subsequent attempt immediately spits the same thing in the system console

**Comment by gregnr** [comment]
@drag0nD @gavin-collier @HowTheHellDoIdoThis 

Do you guys get any other errors at the end of the operation besides `DeprecationWarning: There is no current event loop`?

`DeprecationWarning: There is no current event loop` is just a deprecation warning and shouldn't actually be the real error here (though it is obnoxious how many times it prints that).

For me, I was able to reproduce something similar to this by trying to generate a texture larger than my GPU could support (in my case anything over 1024x1024). I got:
`RuntimeError: CUDA out of memory ...` at the bottom below all the `DeprecationWarning: There is no current event loop` warnings.

**Comment by gavin-collier** [comment]
> 

Yep: File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\site-packages\torch\nn\functional.py", line 2486, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'

Full Error File Here:
https://pastebin.com/kYewsDVL

**Comment by HowTheHellDoIdoThis** [comment]
https://pastebin.com/3JPhndMx

it said here that the max vram it used was 2.21, and i have 6gb of vram according to the bottom panel thing of blender

**Comment by BioMechAlex** [comment]
I was having the same problem. Turning on "Precision Mode" got it working.

**Comment by drag0nD** [comment]
> I was having the same problem. Turning on "Precision Mode" got it working.

@BioMechAlex how do I turn it on? sorry if its dumb question

**Comment by HowTheHellDoIdoThis** [comment]
its under the advanced configuration bit, for me it just makes it crash

**Comment by BioMechAlex** [comment]
Yes its a little check box. For me it gets results maybe 1 in 10 times, every other time it results in a crash after maxing out my VRAM (6GB).
At this point I either get the No Loop error without precision mode, or occasional results but more often than not a crash to desktop with it on.

**Comment by carson-katri** [comment]
You can reduce the image size to prevent VRAM issues. Unfortunately, the 16— cards do not support mixed precision math as far as I know, so they need to use the more VRAM intensive full precision mode. I will enable this by default on these cards in the future, like it is for M1

**Comment by HowTheHellDoIdoThis** [comment]
i tried to generate a 10x10 image with full precision and it still does nothing
full log:
https://pastebin.com/h1RhrTY8

**Comment by Parsnip** [comment]
How big of a texture should you be able to generate with an 8gig card? Like an RTX 3070 for example. Or is it even possible to guesstimate? Does the VRAM need change depending on if you generate from just the prompt vs if you have a init image as a base.

**Comment by engineer1469** [comment]
my max with a 6Gb 1660-ti with precision mode turned on is 125x125
