### ISSUE TITLE
No current event loop

### ISSUE THREAD

**Issue by gwynhyffar** [carson-katri/dream-textures#91]
I've tried installing a couple of times and each time the verification works fine, with no installation errors.  When I try to run the add-on, nothing happens that I can see.  I looked at the console and and getting the following error:

AssertionError: Padding value causes wrapping around more than once.
C:\Users\Gwynh\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\async_loop.py:62: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()

That current event loop occurs several time through the process.  Any ideas?

**Comment by NeonThoth** [comment]
\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\async_loop.py:62: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
  
  im having the same loop error now no image can be generated even though I've reinstalled blender a few times now

**Comment by furbski** [comment]
Same issue here. Lots of these deprecation warnings and this runtime error:
`RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'`

Maybe this part of the console output is relevant?:
`>> Using half precision math. Call with --full_precision to use more accurate but VRAM-intensive full precision.`

I had some installation issues that were fixed by manually adding antlr4 and jsonmerge to C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages. Not sure if that's related.

[Here's blender's output](https://github.com/carson-katri/dream-textures/files/9638638/consoleOutput.txt)

**Comment by AaryamanCodes** [comment]
Same issue here

**Comment by rmurrish** [comment]
I'm having this issue, after it tries and fails to pull a file from the internet.

`Downloading: "https://github.com/DagnyT/hardnet/raw/master/pretrained/train_liberty_with_aug/checkpoint_liberty_with_aug.pth" to /home/redacted/.cache/torch/hub/checkpoints/checkpoint_liberty_with_aug.pth                                                                                                                                                                                   
Task exception was never retrieved                                                                                                                                                           
future: <Task finished name='Task-1' coro=<DreamTexture.dream_texture() done, defined at /home/redacted/.config/blender/3.3/scripts/addons/dream_textures/operators/dream_texture.py:105> exceptio
n=URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)'))> `

What is the `checkpoint_liberty_with_aug.pth` file, and is there any alternative way to install it? Putting it into that location manually results in other errors.

**Comment by Atezian** [comment]
I have the same problem. The generated console log from blender is 6000 lines long. 
It is mostly this line:
```C:\Users\Atezian\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\async_loop.py:62: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()```

**Comment by JC-Sutter** [comment]
When I click "OK" in the DreamTextures. Blender just freeze for some seconds and I get this error in the console. But I have an CUDA GPU. I have Nividia GeForce GTX 1060

.....................

C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\torch\cuda_init_.py:82: UserWarning: CUDA initialization: CUDA driver initialization failed, you might not have a CUDA gpu. (Triggered internally at ..\c10\cuda\CUDAFunctions.cpp:112.)
return torch._C._cuda_getDeviceCount() > 0

Loading model from C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\stable_diffusion/models/ldm/stable-diffusion-v1/model.ckpt
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Using half precision math. Call with --full_precision to use more accurate but VRAM-intensive full precision.
Model loaded in 10.67s
Setting Sampler to k_lms
C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\async_loop.py:62: DeprecationWarning: There is no current event loop
loop = asyncio.get_event_loop()
....

**Comment by jmgwilson** [comment]
I am getting the loop error every time I try to generate an image.  Everything installs with no issues.  It just fails to create an image. I have removed Blender entirely including Appdata files and installed fresh from blender site, 3.3.0.

Graphics Card: ATI AMD Radeon RX 6800 XT
Windows 10

C:\Users\username\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\async_loop.py:62: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()

**Comment by wolfmanyoda** [comment]
I am also having this "no current event loop" error. There is also a scalar type error shown below.
Windows 10, Nvidia GTX 1660


RuntimeError: expected scalar type Half but found Float
C:\Users\*****\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\async_loop.py:62: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()

>> Could not generate image.
>> Usage stats:C:\Users\*****\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\async_loop.py:62: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()

>>   0 image(s) generated in 0.87sC:\Users\*****\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\async_loop.py:62: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()

>>   Max VRAM used for this generation: 2.21G.C:\Users\*****\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\async_loop.py:62: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
 Current VRAM utilization: 2.21GC:\Users\*****\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\async_loop.py:62: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()

>>   Max VRAM used since script start:  2.21GC:\Users\*****\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\async_loop.py:62: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()

C:\Users\*****\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\async_loop.py:62: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
C:\Users\*****\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\async_loop.py:62: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()

**Comment by carson-katri** [comment]
`async_loop.py` has been replaced in [version 0.0.6](https://github.com/carson-katri/dream-textures/releases/tag/0.0.6)
