### ISSUE TITLE
Init Image inaccessible if previously Inpainting

### ISSUE THREAD

**Issue by SpicyMelonYT** [carson-katri/dream-textures#94]
The init image option is missing and it was there when I started but after one use, it disappeared and never showed up. I have restarted blender and my computer a few times though out the week but it never came back. Suggestions?

**Comment by SpicyMelonYT** [comment]
Here is an image showing the missing option

![image](https://user-images.githubusercontent.com/80491863/192076250-46e71ac4-9d6c-487b-8a06-24f52fef0bd3.png)

**Comment by carson-katri** [comment]
Can you check the console?
Also, there’s a known issue where if you previously enabled inpainting, but then closed an image with alpha the option will become inaccessible. So you could try opening an image with alpha then disabling inpainting and it will reappear.

**Comment by SpicyMelonYT** [comment]
> 

Oh that fixed it thank you. I feel like that should be changed somehow. But yeah awesome help!

**Comment by carson-katri** [comment]
I’ll leave this open until it’s fixed.

**Comment by SpicyMelonYT** [comment]
> Can you check the console? Also, there’s a known issue where if you previously enabled inpainting, but then closed an image with alpha the option will become inaccessible. So you could try opening an image with alpha then disabling inpainting and it will reappear.

So one more question? I now am using it and I am changing the strength value but it doesn't seem like each result is inspired by the init image. Am I thinking wrong here? Does it now influence the final image

**Comment by carson-katri** [comment]
It should if you have an image selected. If it seems way off, please file a new issue for that and attach screenshots.

**Comment by SpicyMelonYT** [comment]
will do

**Comment by carson-katri** [comment]
This should be resolved by #132
