### ISSUE TITLE
As fast as Diffusion Bee?

### ISSUE THREAD

**Issue by enzyme69** [carson-katri/dream-textures#95]
For unknown reason, "Diffusion Bee" able to generate image 512 x 512 at just under 4 minutes on my slow M1 iMac, I wonder if Dream Textures can perform in such speed? Is it because of different model used?

Gupta Twitter post:
https://twitter.com/divamgupta/status/1571234504320208897?s=21&t=xcBNqxff8hXCgrye-JH0Tg

http://diffusionbee.com

Thanks!

**Comment by carson-katri** [comment]
Have you tried with “Show Steps” turned off? On M1 Max this takes about 20 seconds for me.

**Comment by enzyme69** [comment]
On M1 8GB, it takes 15 minutes on me and error always shows up like this:
```
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
>> Using slower but more accurate full-precision math (--full_precision)
>> Model loaded in 95.85s
>> Setting Sampler to k_lms
/Users/jimmygunawan/Library/Application Support/Blender/3.4/scripts/addons/dream_textures/stable_diffusion/ldm/modules/embedding_manager.py:155: UserWarning: The operator 'aten::nonzero' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/mps/MPSFallback.mm:11.)
  placeholder_idx = torch.where(
Generating:   0%|                                         | 0/1 [00:00<?, ?it/s]
  0%|                                                    | 0/25 [00:00<?, ?it/s]


```

**Comment by carson-katri** [comment]
You may also want to try DDIM sampler, which could run a bit faster.

**Comment by enzyme69** [comment]
Ok roger that, will try, at 25 samples sampe prompt, default settings: generated in 1355.95s 
![2954919608](https://user-images.githubusercontent.com/3952687/192078768-7df01cec-3fc6-4e87-a00b-86117833877a.png)

I will try DDIM and see how fast.

**Comment by enzyme69** [comment]
I tested DDIM, no actual speed increase, for 25 samples, ended up 30 minutes ish.
