### ISSUE TITLE
Init Image not influencing result

### ISSUE THREAD

**Issue by SpicyMelonYT** [carson-katri/dream-textures#99]
I am using the init image option but it seems to not influence the result at all. The strength parameter doesn't seem to affect it.

Here is an init image: 
![image](https://user-images.githubusercontent.com/80491863/192076771-375bf3c1-f769-435f-b880-10027b8a934d.png)

Here is Dream Texture Parameters: 
![image](https://user-images.githubusercontent.com/80491863/192076896-4d22d08a-b195-4333-9444-624598416774.png)

Here is result: 
![image](https://user-images.githubusercontent.com/80491863/192076832-1d290d21-effb-4461-8aea-424f5b858bf9.png)

I would expect that putting strength to 0.9999 would make the final image almost identical but even doing that doesn't seem to work. Also putting strength to 1 exactly, causes it to never run

**Comment by carson-katri** [comment]
Thanks for the samples!
It looks like the image is not selected. Try using the drop-down next to “open” to select it after opening. The next version fixes the image not being selected on open.

**Comment by SpicyMelonYT** [comment]
Oh i see, I had suspected something was wrong like that but I didn't test it. I should have tested more. Thank you! Also this is so freaking awesome. I had bought midjourney a while back but this definitely is better. Maybe not artistically but definitely creatively. And I love blender so yeah!

**Comment by SpicyMelonYT** [comment]
Very cool: 
![image](https://user-images.githubusercontent.com/80491863/192076998-5fb35df9-4c2b-4e8f-84f0-ddffaa715071.png)

**Comment by SpicyMelonYT** [comment]
Oh also it seems like the strength value works in the opposite way to what I thought. The lower the value, the more the init image influences the result. That is good cause I was beginning to think the AI would never spit out very identical images to the init image which is desirable.

**Comment by ktronfabi** [comment]
Hello! I love the tool that you created! super handy and it works super fast!

I was having issues with the "init image", it was not using the image i was loading and **disabling the "fit to width/height" checkbox** worked for me
